# -*- coding: utf-8 -*-
"""New and revised user-facing app-settings strings for 1.21.0."""

APP = {
    "Keyboard Cleaner…": {
        "hu": "Billentyűzettisztító…", "es": "Limpiador de teclado…", "fr": "Nettoyeur de clavier…", "de": "Tastaturreiniger…", "zh-Hans": "键盘清洁器…",
        "it": "Pulitore della tastiera…", "ja": "キーボードクリーナー…", "ko": "키보드 클리너…", "ru": "Очистка клавиатуры…", "pt-BR": "Limpador de teclado…", "tr": "Klavye Temizleyici…", "pl": "Czyszczenie klawiatury…", "uk": "Очищення клавіатури…", "zh-Hant": "鍵盤清潔工具…",
    },
    "Public Wi-Fi…": {
        "hu": "Nyilvános Wi-Fi…", "es": "Wi-Fi público…", "fr": "Wi-Fi public…", "de": "Öffentliches WLAN…", "zh-Hans": "公共 Wi-Fi…",
        "it": "Wi-Fi pubblico…", "ja": "公共 Wi-Fi…", "ko": "공용 Wi-Fi…", "ru": "Общедоступный Wi-Fi…", "pt-BR": "Wi-Fi público…", "tr": "Herkese Açık Wi-Fi…", "pl": "Publiczne Wi-Fi…", "uk": "Загальнодоступний Wi-Fi…", "zh-Hant": "公共 Wi-Fi…",
    },
    "Method": {
        "hu": "Módszer", "es": "Método", "fr": "Méthode", "de": "Methode", "zh-Hans": "方法",
        "it": "Metodo", "ja": "方法", "ko": "방법", "ru": "Метод", "pt-BR": "Método", "tr": "Yöntem", "pl": "Metoda", "uk": "Метод", "zh-Hant": "方法",
    },
    "Refresh": {
        "hu": "Frissítés", "es": "Actualizar", "fr": "Actualiser", "de": "Aktualisieren", "zh-Hans": "刷新",
        "it": "Aggiorna", "ja": "更新", "ko": "새로 고침", "ru": "Обновить", "pt-BR": "Atualizar", "tr": "Yenile", "pl": "Odśwież", "uk": "Оновити", "zh-Hant": "重新整理",
    },
    "A small system service for the switches that need administrator rights: closed-display mode below, Keyboard Cleaner, the thermal fan boost, AWDL pausing in Gaming & Streaming, and flushing DNS from the Public Wi-Fi assistant. Without it, macOS asks for your password once per app run (and fan boost stays off entirely: fan control can't prompt). With it, everything is instant and silent: macOS asks once, when you approve the helper under Login Items, and the approval survives restarts and app updates. Updates never need a reinstall, the service replaces itself with the app. It can only flip those specific switches, everything it changes is restored if Keepresso quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list. The status shown here is the real one.": {
        "hu": "Egy kis rendszerszolgáltatás a rendszergazdai jogosultságot igénylő kapcsolókhoz: az alábbi csukott fedél módhoz, a Billentyűzettisztítóhoz, a hővédelmi ventilátorfokozáshoz, az AWDL szüneteltetéséhez a Játék és streamelésben, valamint a DNS ürítéséhez a Nyilvános Wi-Fi segédben. Nélküle a macOS alkalmazásindításonként egyszer kéri a jelszavát, és a ventilátorfokozás teljesen kikapcsolva marad, mert a ventilátorvezérlés nem kérhet jelszót. Vele minden azonnali és csendes: a macOS egyszer kér jelszót, amikor jóváhagyja a segédet a Bejelentkezési elemeknél, és a jóváhagyás újraindítások és alkalmazásfrissítések után is megmarad. A frissítésekhez soha nem kell újratelepítés, a szolgáltatás az alkalmazással együtt lecseréli magát. Csak ezeket a kapcsolókat állíthatja, minden módosítását visszaállítja, ha a Keepresso kilép vagy összeomlik, és itt bármikor eltávolíthatja. A keepresso parancssori eszközt is felveszi a PATH változóba, a Homebrew-telepítésekben ez már megvan. Eltávolítás után a Rendszerbeállítások még mutathat elavult Bejelentkezési elemek sort, amíg a macOS nem frissíti a listát. Az itt látható állapot a tényleges állapot.",
        "es": "Un pequeño servicio del sistema para los interruptores que requieren permisos de administrador: el modo con pantalla cerrada de abajo, el Limpiador de teclado, el refuerzo térmico de los ventiladores, la pausa de AWDL en Juegos y streaming y el vaciado de DNS desde el asistente de Wi-Fi público. Sin él, macOS te pide la contraseña una vez por cada ejecución de la app, y el refuerzo de ventiladores permanece completamente desactivado porque el control de ventiladores no puede pedirla. Con él, todo es instantáneo y silencioso: macOS la pide una vez, cuando autorizas el asistente en Ítems de inicio, y la autorización persiste tras reinicios y actualizaciones de la app. Las actualizaciones nunca requieren reinstalación, el servicio se reemplaza a sí mismo con la app. Solo puede cambiar esos interruptores concretos, todo lo que modifica se restaura si Keepresso se cierra o falla, y puedes eliminarlo aquí cuando quieras. También añade la herramienta de línea de comandos keepresso a tu PATH, las instalaciones de Homebrew ya la tienen. Tras eliminarlo, Ajustes del Sistema puede seguir mostrando una fila obsoleta de Ítems de inicio hasta que macOS actualice la lista. El estado mostrado aquí es el real.",
        "fr": "Un petit service système pour les interrupteurs qui nécessitent des droits d’administrateur : le mode écran fermé ci-dessous, le nettoyeur de clavier, l’accélération thermique des ventilateurs, la mise en pause d’AWDL dans Jeu et streaming, et le vidage DNS depuis l’assistant Wi-Fi public. Sans lui, macOS demande votre mot de passe une fois par lancement de l’app, et l’accélération des ventilateurs reste entièrement désactivée, car leur contrôle ne peut pas demander de mot de passe. Avec lui, tout est immédiat et silencieux : macOS le demande une fois, lorsque vous approuvez l’assistant dans Ouverture au démarrage, et cette approbation survit aux redémarrages et aux mises à jour de l’app. Les mises à jour ne nécessitent jamais de réinstallation, le service se remplace avec l’app. Il ne peut basculer que ces interrupteurs précis, tout ce qu’il modifie est restauré si Keepresso quitte ou plante, et vous pouvez le supprimer ici à tout moment. Il ajoute aussi l’outil en ligne de commande keepresso à votre PATH, les installations Homebrew l’ont déjà. Après sa suppression, Réglages Système peut continuer d’afficher une ligne Ouverture au démarrage obsolète jusqu’à ce que macOS actualise sa liste. L’état affiché ici est le véritable état.",
        "de": "Ein kleiner Systemdienst für die Schalter, die Administratorrechte benötigen: den Modus bei geschlossenem Display unten, den Tastaturreiniger, den thermischen Lüfter-Boost, das Pausieren von AWDL unter Gaming und Streaming sowie das Leeren des DNS-Caches im Assistenten für öffentliches WLAN. Ohne ihn fragt macOS einmal pro App-Ausführung nach deinem Passwort, und der Lüfter-Boost bleibt vollständig aus, weil die Lüftersteuerung nicht nach einem Passwort fragen kann. Mit ihm funktioniert alles sofort und ohne Rückfrage: macOS fragt einmal, wenn du den Hilfsdienst unter Anmeldeobjekte erlaubst, und die Genehmigung bleibt über Neustarts und App-Updates erhalten. Updates brauchen nie eine Neuinstallation, der Dienst ersetzt sich zusammen mit der App selbst. Er kann nur diese bestimmten Schalter umlegen, alle Änderungen werden wiederhergestellt, wenn Keepresso beendet wird oder abstürzt, und du kannst ihn hier jederzeit entfernen. Er fügt außerdem das Befehlszeilenwerkzeug keepresso zu deinem PATH hinzu, bei Homebrew-Installationen ist es bereits vorhanden. Nach dem Entfernen kann Systemeinstellungen noch einen veralteten Eintrag unter Anmeldeobjekte zeigen, bis macOS seine Liste aktualisiert. Der hier angezeigte Status ist der tatsächliche.",
        "zh-Hans": "这是一个小型系统服务，用于需要管理员权限的开关：下方的合盖模式、键盘清洁器、散热风扇加速、游戏与串流中的 AWDL 暂停，以及公共 Wi-Fi 助手中的 DNS 刷新。没有它，macOS 会在每次运行 App 时要求你输入一次密码，而且风扇加速会完全保持关闭，因为风扇控制无法弹出密码请求。有了它，一切都会立即且安静地完成：当你在登录项中批准该助理时，macOS 只会询问一次，且批准在重启和 App 更新后仍然有效。更新从不需要重新安装，服务会随 App 自行替换。它只能切换这些特定开关，如果 Keepresso 退出或崩溃，它所做的所有更改都会恢复，而且你随时可以在此将其移除。它还会将 keepresso 命令行工具加入你的 PATH，Homebrew 安装已经具备此项。移除后，系统设置可能仍会显示过时的登录项行，直到 macOS 刷新列表。这里显示的状态才是真实状态。",
        "it": "Un piccolo servizio di sistema per gli interruttori che richiedono diritti di amministratore: la modalità a schermo chiuso qui sotto, il Pulitore della tastiera, l’aumento termico delle ventole, la pausa di AWDL in Gaming e streaming e lo svuotamento DNS dall’assistente Wi-Fi pubblico. Senza di esso, macOS chiede la password una volta per ogni esecuzione dell’app e l’aumento delle ventole resta del tutto disattivato, perché il controllo delle ventole non può richiederla. Con esso, tutto è immediato e silenzioso: macOS la chiede una sola volta, quando autorizzi l’assistente in Elementi di login, e l’autorizzazione resta valida dopo riavvii e aggiornamenti dell’app. Gli aggiornamenti non richiedono mai una reinstallazione, il servizio si sostituisce insieme all’app. Può solo attivare quegli interruttori specifici, tutto ciò che modifica viene ripristinato se Keepresso si chiude o va in crash, e puoi rimuoverlo qui in qualsiasi momento. Aggiunge inoltre lo strumento da riga di comando keepresso al tuo PATH, le installazioni Homebrew lo hanno già. Dopo la rimozione, Impostazioni di Sistema può continuare a mostrare una riga obsoleta in Elementi di login finché macOS non aggiorna l’elenco. Lo stato mostrato qui è quello reale.",
        "ja": "管理者権限が必要なスイッチのための小さなシステムサービスです。下のクラムシェルモード、キーボードクリーナー、熱によるファン増速、ゲームとストリーミングでの AWDL の一時停止、公共 Wi-Fi アシスタントからの DNS フラッシュに使われます。これがない場合、macOS はアプリの起動ごとに一度パスワードを求めます。また、ファン制御はパスワードを求められないため、ファン増速は完全にオフのままです。これがあれば、すべて即座に静かに動作します。ログイン項目でヘルパーを許可すると macOS が一度だけ確認し、その許可は再起動やアプリ更新後も維持されます。更新時に再インストールは不要で、サービスはアプリとともに自動的に置き換わります。この特定のスイッチだけを切り替えられ、Keepresso の終了やクラッシュ時には変更がすべて復元されます。ここからいつでも削除できます。さらに keepresso コマンドラインツールを PATH に追加します。Homebrew でのインストールにはすでに含まれています。削除後も、macOS がリストを更新するまでシステム設定に古いログイン項目の行が表示されることがあります。ここに表示される状態が実際の状態です。",
        "ko": "관리자 권한이 필요한 스위치를 위한 작은 시스템 서비스입니다. 아래의 디스플레이 닫힘 모드, 키보드 클리너, 열 관리 팬 부스트, 게임 및 스트리밍의 AWDL 일시 정지, 공용 Wi-Fi 도우미의 DNS 플러시에 사용됩니다. 이것이 없으면 macOS가 앱을 실행할 때마다 한 번 암호를 요청하며, 팬 제어는 암호를 요청할 수 없으므로 팬 부스트는 완전히 꺼진 상태로 유지됩니다. 이것이 있으면 모든 것이 즉시 조용히 작동합니다. 로그인 항목에서 도우미를 승인할 때 macOS가 한 번만 묻고, 승인은 재시동과 앱 업데이트 후에도 유지됩니다. 업데이트에 재설치는 필요 없으며 서비스가 앱과 함께 스스로 교체됩니다. 이 특정 스위치만 바꿀 수 있고 Keepresso가 종료되거나 충돌하면 바꾼 모든 항목이 복원되며, 여기서 언제든 제거할 수 있습니다. keepresso 명령줄 도구도 PATH에 추가합니다. Homebrew 설치에는 이미 포함되어 있습니다. 제거 후 macOS가 목록을 새로 고칠 때까지 시스템 설정에 오래된 로그인 항목 행이 남아 있을 수 있습니다. 여기에 표시되는 상태가 실제 상태입니다.",
        "ru": "Небольшая системная служба для переключателей, которым нужны права администратора: режима закрытого дисплея ниже, очистки клавиатуры, термоускорения вентиляторов, приостановки AWDL в разделе «Игры и стриминг» и очистки DNS из помощника общедоступного Wi-Fi. Без неё macOS запрашивает пароль один раз при каждом запуске приложения, а ускорение вентиляторов остаётся полностью выключенным, поскольку управление вентиляторами не может запросить пароль. С ней всё работает сразу и без лишних запросов: macOS спрашивает один раз, когда вы разрешаете помощника в объектах входа, и это разрешение сохраняется после перезапусков и обновлений приложения. Обновления никогда не требуют переустановки, служба заменяет себя вместе с приложением. Она может переключать только эти конкретные функции, все её изменения восстанавливаются, если Keepresso завершится или аварийно закроется, и вы можете удалить её здесь в любое время. Она также добавляет инструмент командной строки keepresso в PATH, в установках Homebrew он уже есть. После удаления Системные настройки могут продолжать показывать устаревшую строку объектов входа, пока macOS не обновит список. Показанный здесь статус является фактическим.",
        "pt-BR": "Um pequeno serviço do sistema para os controles que precisam de direitos de administrador: o modo com a tela fechada abaixo, o Limpador de teclado, o reforço térmico das ventoinhas, a pausa de AWDL em Jogos e streaming e a limpeza de DNS pelo assistente de Wi-Fi público. Sem ele, o macOS pede sua senha uma vez por execução do app, e o reforço das ventoinhas permanece totalmente desativado porque o controle delas não pode pedir senha. Com ele, tudo é imediato e silencioso: o macOS pergunta uma vez, quando você aprova o assistente em Itens de Login, e a aprovação sobrevive a reinicializações e atualizações do app. As atualizações nunca exigem reinstalação, o serviço se substitui junto com o app. Ele só pode alternar esses controles específicos, tudo que ele altera é restaurado se o Keepresso encerrar ou falhar, e você pode removê-lo aqui a qualquer momento. Ele também adiciona a ferramenta de linha de comando keepresso ao seu PATH, instalações do Homebrew já a incluem. Após removê-lo, os Ajustes do Sistema podem continuar mostrando uma linha obsoleta de Itens de Login até que o macOS atualize a lista. O estado mostrado aqui é o real.",
        "tr": "Yönetici hakları gerektiren anahtarlar için küçük bir sistem hizmeti: aşağıdaki kapalı ekran modu, Klavye Temizleyici, termal fan hızlandırma, Oyun ve Yayın bölümündeki AWDL duraklatma ve Herkese Açık Wi-Fi yardımcısındaki DNS temizleme. Bu olmadan macOS uygulamanın her çalıştırılmasında bir kez parolanızı ister ve fan denetimi parola isteyemediği için fan hızlandırma tamamen kapalı kalır. Bununla her şey anında ve sessizce çalışır: macOS, yardımcının Oturum Açma Öğeleri altında onaylanması sırasında bir kez sorar ve onay yeniden başlatmalar ile uygulama güncellemelerinden sonra da korunur. Güncellemeler hiçbir zaman yeniden kurulum gerektirmez, hizmet uygulamayla birlikte kendini değiştirir. Yalnızca bu belirli anahtarları değiştirebilir, Keepresso kapanır veya çökerse yaptığı her değişiklik geri alınır ve istediğiniz zaman buradan kaldırabilirsiniz. Ayrıca keepresso komut satırı aracını PATH'inize ekler, Homebrew kurulumlarında bu zaten vardır. Kaldırıldıktan sonra, macOS listeyi yenileyene kadar Sistem Ayarları eski bir Oturum Açma Öğeleri satırı göstermeye devam edebilir. Burada gösterilen durum gerçek durumdur.",
        "pl": "Mała usługa systemowa dla przełączników wymagających uprawnień administratora: trybu zamkniętej pokrywy poniżej, czyszczenia klawiatury, termicznego zwiększania obrotów wentylatorów, wstrzymywania AWDL w Graj i przesyłaj strumieniowo oraz czyszczenia DNS przez asystenta publicznego Wi‑Fi. Bez niej macOS prosi o hasło raz na każde uruchomienie aplikacji, a zwiększanie obrotów wentylatorów pozostaje całkowicie wyłączone, ponieważ sterowanie wentylatorami nie może o nie zapytać. Dzięki niej wszystko działa od razu i bezgłośnie: macOS pyta raz, gdy zatwierdzasz pomocnika w Elementach logowania, a zatwierdzenie pozostaje po ponownych uruchomieniach i aktualizacjach aplikacji. Aktualizacje nigdy nie wymagają ponownej instalacji, usługa zastępuje się wraz z aplikacją. Może przełączać tylko te konkretne przełączniki, wszystkie wprowadzone zmiany są przywracane, jeśli Keepresso zakończy działanie lub ulegnie awarii, a usługę możesz tu usunąć w dowolnym momencie. Dodaje też narzędzie wiersza poleceń keepresso do PATH, instalacje Homebrew już je mają. Po usunięciu Ustawienia systemowe mogą nadal pokazywać nieaktualny wiersz Elementów logowania, dopóki macOS nie odświeży listy. Pokazany tutaj stan jest rzeczywisty.",
        "uk": "Невелика системна служба для перемикачів, яким потрібні права адміністратора: режиму закритої кришки нижче, очищення клавіатури, термічного прискорення вентиляторів, призупинення AWDL у розділі «Ігри та стримінг» і очищення DNS у помічнику загальнодоступного Wi‑Fi. Без неї macOS запитує пароль один раз для кожного запуску застосунку, а прискорення вентиляторів повністю вимкнене, бо керування вентиляторами не може запитати пароль. З нею все працює миттєво й безшумно: macOS запитає один раз, коли ви схвалите помічника в об’єктах входу, а схвалення зберігається після перезавантажень і оновлень застосунку. Оновлення ніколи не потребують перевстановлення, служба замінює себе разом із застосунком. Вона може перемикати лише ці конкретні перемикачі, усі її зміни відновлюються, якщо Keepresso завершує роботу або аварійно закривається, і ви можете видалити її тут будь-коли. Вона також додає інструмент командного рядка keepresso до PATH, установки Homebrew уже його мають. Після видалення Системні параметри можуть і далі показувати застарілий рядок об’єктів входу, доки macOS не оновить список. Показаний тут стан є фактичним.",
        "zh-Hant": "這是一個小型系統服務，用於需要管理員權限的開關：下方的闔蓋模式、鍵盤清潔工具、散熱風扇加速、遊戲與串流中的 AWDL 暫停，以及公共 Wi-Fi 助理中的 DNS 清除。沒有它，macOS 會在每次執行 App 時要求輸入一次密碼，而且風扇加速會完全保持關閉，因為風扇控制無法要求輸入密碼。有了它，一切都會立即且安靜地完成：當您在登入項目中核准此輔助程式時，macOS 只會詢問一次，且該核准在重新啟動與 App 更新後仍會保留。更新從不需要重新安裝，服務會隨 App 自行替換。它只能切換這些特定開關，如果 Keepresso 結束或當機，它所做的所有變更都會還原，而且您隨時可在此移除它。它也會將 keepresso 命令列工具加入您的 PATH，Homebrew 安裝已經具備此工具。移除後，系統設定可能仍會顯示過時的登入項目列，直到 macOS 重新整理清單。此處顯示的狀態才是真實狀態。",
    },
    "Power / cursor warp": {
        "hu": "Energia / kurzorugrás", "es": "Energía / salto del cursor", "fr": "Alimentation / déplacement du curseur", "de": "Energie / Cursorversatz", "zh-Hans": "电源 / 光标偏移",
        "it": "Alimentazione / spostamento del cursore", "ja": "電源 / カーソル移動", "ko": "전원 / 커서 이동", "ru": "Питание / смещение курсора", "pt-BR": "Energia / deslocamento do cursor", "tr": "Güç / imleç kaydırma", "pl": "Zasilanie / przesunięcie kursora", "uk": "Живлення / зміщення курсора", "zh-Hant": "電源 / 游標位移",
    },
    "F15 key every 60 s": {
        "hu": "F15 billentyű 60 másodpercenként", "es": "Tecla F15 cada 60 s", "fr": "Touche F15 toutes les 60 s", "de": "F15-Taste alle 60 s", "zh-Hans": "每 60 秒按一次 F15 键",
        "it": "Tasto F15 ogni 60 s", "ja": "60 秒ごとに F15 キー", "ko": "60초마다 F15 키", "ru": "Клавиша F15 каждые 60 с", "pt-BR": "Tecla F15 a cada 60 s", "tr": "Her 60 sn’de F15 tuşu", "pl": "Klawisz F15 co 60 s", "uk": "Клавіша F15 кожні 60 с", "zh-Hant": "每 60 秒按一次 F15 鍵",
    },
    "Shift every 60 s": {
        "hu": "Shift 60 másodpercenként", "es": "Mayús cada 60 s", "fr": "Maj toutes les 60 s", "de": "Umschalttaste alle 60 s", "zh-Hans": "每 60 秒按一次 Shift",
        "it": "Maiusc ogni 60 s", "ja": "60 秒ごとに Shift", "ko": "60초마다 Shift", "ru": "Shift каждые 60 с", "pt-BR": "Shift a cada 60 s", "tr": "Her 60 sn’de Shift", "pl": "Shift co 60 s", "uk": "Shift кожні 60 с", "zh-Hant": "每 60 秒按一次 Shift",
    },
    "Specified key": {
        "hu": "Megadott billentyű", "es": "Tecla especificada", "fr": "Touche choisie", "de": "Festgelegte Taste", "zh-Hans": "指定按键",
        "it": "Tasto specificato", "ja": "指定キー", "ko": "지정한 키", "ru": "Выбранная клавиша", "pt-BR": "Tecla especificada", "tr": "Belirtilen tuş", "pl": "Wybrany klawisz", "uk": "Вказана клавіша", "zh-Hant": "指定按鍵",
    },
    "Mouse move": {
        "hu": "Egérmozgatás", "es": "Movimiento del ratón", "fr": "Mouvement de la souris", "de": "Mausbewegung", "zh-Hans": "鼠标移动",
        "it": "Movimento del mouse", "ja": "マウス移動", "ko": "마우스 이동", "ru": "Движение мыши", "pt-BR": "Movimento do mouse", "tr": "Fare hareketi", "pl": "Ruch myszy", "uk": "Рух миші", "zh-Hant": "滑鼠移動",
    },
    "Key": {
        "hu": "Billentyű", "es": "Tecla", "fr": "Touche", "de": "Taste", "zh-Hans": "按键",
        "it": "Tasto", "ja": "キー", "ko": "키", "ru": "Клавиша", "pt-BR": "Tecla", "tr": "Tuş", "pl": "Klawisz", "uk": "Клавіша", "zh-Hant": "按鍵",
    },
    "Key %d": {
        "hu": "%d. billentyű", "es": "Tecla %d", "fr": "Touche %d", "de": "Taste %d", "zh-Hans": "按键 %d",
        "it": "Tasto %d", "ja": "キー %d", "ko": "키 %d", "ru": "Клавиша %d", "pt-BR": "Tecla %d", "tr": "Tuş %d", "pl": "Klawisz %d", "uk": "Клавіша %d", "zh-Hant": "按鍵 %d",
    },
    "Needs Accessibility for this method.": {
        "hu": "Ehhez a módszerhez Kisegítő lehetőségek engedély kell.", "es": "Este método requiere Accesibilidad.", "fr": "Cette méthode nécessite l’accès à Accessibilité.", "de": "Für diese Methode wird Bedienungshilfen-Zugriff benötigt.", "zh-Hans": "此方法需要辅助功能权限。",
        "it": "Questo metodo richiede l’accesso ad Accessibilità.", "ja": "この方法にはアクセシビリティの許可が必要です。", "ko": "이 방법에는 손쉬운 사용 권한이 필요합니다.", "ru": "Для этого метода нужен доступ к универсальному доступу.", "pt-BR": "Este método precisa de acesso à Acessibilidade.", "tr": "Bu yöntem için Erişilebilirlik izni gerekir.", "pl": "Ta metoda wymaga dostępu do funkcji Dostępność.", "uk": "Для цього методу потрібен доступ до універсального доступу.", "zh-Hant": "此方法需要輔助使用權限。",
    },
    "Keeping the Mac awake stops it sleeping, but that does not keep you active in other software. Meeting and chat apps, remote desktop and VDI, cloud gaming, and many other tools still apply their own idle timeout: they mark you away, disconnect, or end the session. This reports activity so you stay present. The default method needs no extra permission. Some software only notices a real key or mouse, so you can pick F15, Shift, a specified key, or a posted mouse move. Those need Accessibility, requested only when you choose them, never at launch. F15 is the usual pick (most keyboards lack it, so nothing is typed). Shift is invisible. A specified key or mouse move covers software that only watches those. A letter or number will type into the front app. It only steps in once you've been idle a few seconds, so it never types or nudges while you're using the Mac. Off by default.": {
        "hu": "A Mac ébren tartása megakadályozza az alvást, de más szoftverekben nem tart aktívként. Az értekezlet- és csevegőalkalmazások, a távoli asztal és VDI, a felhőalapú játékok és sok más eszköz továbbra is saját tétlenségi időkorlátot alkalmaz: távollévőnek jelölnek, bontják a kapcsolatot vagy befejezik a munkamenetet. Ez tevékenységet jelez, hogy jelen maradjon. Az alapértelmezett módszerhez nem kell további engedély. Egyes szoftverek csak valódi billentyűt vagy egeret észlelnek, ezért választhat F15-öt, Shiftet, megadott billentyűt vagy küldött egérmozgást. Ezekhez Kisegítő lehetőségek engedély kell, amelyet csak kiválasztáskor kérünk, soha nem indításkor. Az F15 a szokásos választás, mert a legtöbb billentyűzeten nincs ilyen, így semmi nem íródik be. A Shift láthatatlan. A megadott billentyű vagy egérmozgás lefedi az ezeket figyelő szoftvereket. Betű vagy szám a legelöl lévő alkalmazásba íródik. Csak néhány másodperc tétlenség után lép működésbe, ezért soha nem gépel vagy mozdítja meg az egeret, amíg használja a Macet. Alapértelmezés szerint ki van kapcsolva.",
        "es": "Mantener el Mac despierto evita que se suspenda, pero no te mantiene activo en otro software. Las apps de reuniones y chat, el escritorio remoto y VDI, los juegos en la nube y muchas otras herramientas siguen aplicando su propio tiempo de espera por inactividad: te marcan como ausente, te desconectan o terminan la sesión. Esto informa actividad para que sigas presente. El método predeterminado no necesita permisos adicionales. Algunos programas solo detectan una tecla o un ratón reales, así que puedes elegir F15, Mayús, una tecla especificada o un movimiento de ratón publicado. Esos requieren Accesibilidad, que solo se solicita al elegirlos, nunca al iniciar. F15 es la opción habitual, porque la mayoría de teclados no la tienen y no se escribe nada. Mayús es invisible. Una tecla especificada o un movimiento de ratón cubren el software que solo observa esos elementos. Una letra o un número se escribirá en la app frontal. Solo interviene después de unos segundos de inactividad, así que nunca escribe ni mueve el ratón mientras usas el Mac. Desactivado por defecto.",
        "fr": "Garder le Mac éveillé l’empêche de dormir, mais ne vous garde pas actif dans les autres logiciels. Les apps de réunion et de discussion, le bureau à distance et VDI, le cloud gaming et bien d’autres outils appliquent encore leur propre délai d’inactivité : ils vous marquent absent, vous déconnectent ou terminent la session. Cette option signale une activité afin que vous restiez présent. La méthode par défaut ne demande aucune autorisation supplémentaire. Certains logiciels ne détectent qu’une vraie touche ou souris, vous pouvez donc choisir F15, Maj, une touche choisie ou un mouvement de souris envoyé. Ces méthodes nécessitent Accessibilité, demandée uniquement lorsque vous les choisissez, jamais au lancement. F15 est le choix courant, car la plupart des claviers ne l’ont pas et rien n’est saisi. Maj est invisible. Une touche choisie ou un mouvement de souris couvre les logiciels qui ne surveillent que cela. Une lettre ou un chiffre sera saisi dans l’app au premier plan. L’option n’intervient qu’après quelques secondes d’inactivité, donc elle ne saisit rien et ne déplace pas la souris pendant que vous utilisez le Mac. Désactivée par défaut.",
        "de": "Den Mac wach zu halten verhindert den Ruhezustand, hält dich aber nicht in anderer Software aktiv. Meeting- und Chat-Apps, Remote-Desktop und VDI, Cloud-Gaming und viele andere Tools verwenden weiterhin ihren eigenen Leerlauf-Timeout: Sie markieren dich als abwesend, trennen die Verbindung oder beenden die Sitzung. Diese Option meldet Aktivität, damit du präsent bleibst. Die Standardmethode benötigt keine zusätzliche Berechtigung. Manche Software erkennt nur eine echte Taste oder Maus, daher kannst du F15, Umschalttaste, eine festgelegte Taste oder eine gesendete Mausbewegung wählen. Dafür wird Bedienungshilfen-Zugriff benötigt, der nur beim Auswählen abgefragt wird, nie beim Start. F15 ist die übliche Wahl, da die meisten Tastaturen diese Taste nicht haben und daher nichts eingegeben wird. Die Umschalttaste ist unsichtbar. Eine festgelegte Taste oder Mausbewegung deckt Software ab, die nur darauf achtet. Ein Buchstabe oder eine Zahl wird in die vorderste App eingegeben. Die Option greift erst nach einigen Sekunden Leerlauf ein und tippt oder bewegt nichts, während du den Mac benutzt. Standardmäßig aus.",
        "zh-Hans": "让 Mac 保持唤醒可以阻止它睡眠，但不会让你在其他软件中保持活跃。会议和聊天 App、远程桌面和 VDI、云游戏以及许多其他工具仍会采用自己的空闲超时策略：它们会将你标记为离开、断开连接或结束会话。此功能会报告活动，让你保持在线。默认方法不需要额外权限。有些软件只会注意到真实的按键或鼠标，因此你可以选择 F15、Shift、指定按键或发送的鼠标移动。这些方法需要辅助功能权限，只会在你选择时请求，绝不会在启动时请求。F15 是常见选择，因为大多数键盘没有它，所以不会输入任何内容。Shift 不会显示。指定按键或鼠标移动可适用于只观察这些输入的软件。字母或数字会输入到前台 App。它只会在你空闲几秒后介入，因此在你使用 Mac 时绝不会输入或移动鼠标。默认关闭。",
        "it": "Mantenere il Mac sveglio ne impedisce la sospensione, ma non ti mantiene attivo negli altri software. Le app di riunioni e chat, il desktop remoto e VDI, il cloud gaming e molti altri strumenti continuano ad applicare il proprio timeout di inattività: ti segnano come assente, ti disconnettono o terminano la sessione. Questa opzione segnala attività per mantenerti presente. Il metodo predefinito non richiede permessi aggiuntivi. Alcuni software rilevano solo una tastiera o un mouse reali, quindi puoi scegliere F15, Maiusc, un tasto specificato o un movimento del mouse inviato. Questi richiedono Accessibilità, richiesta solo quando li scegli e mai all’avvio. F15 è la scelta comune, perché la maggior parte delle tastiere non lo ha e non viene digitato nulla. Maiusc è invisibile. Un tasto specificato o un movimento del mouse copre i software che osservano solo questi elementi. Una lettera o un numero verrà digitato nell’app in primo piano. Interviene solo dopo qualche secondo di inattività, quindi non digita né muove il mouse mentre usi il Mac. Disattivato per impostazione predefinita.",
        "ja": "Mac をスリープさせないようにしても、ほかのソフトウェアでアクティブな状態を維持するわけではありません。会議やチャットの App、リモートデスクトップと VDI、クラウドゲームなど多くのツールは独自のアイドルタイムアウトを適用し続け、離席としてマークしたり、接続を切断したり、セッションを終了したりします。この機能はアクティビティを通知して在席状態を保ちます。既定の方法に追加の許可は必要ありません。一部のソフトウェアは実際のキー入力やマウスしか認識しないため、F15、Shift、指定キー、送信されたマウス移動を選べます。これらにはアクセシビリティの許可が必要ですが、起動時ではなく選択時にだけ求められます。F15 は一般的な選択です。多くのキーボードにはなく、何も入力されないためです。Shift は見えません。指定キーまたはマウス移動は、それらだけを監視するソフトウェアに対応します。文字または数字は前面の App に入力されます。数秒間アイドル状態になってからだけ動作するため、Mac の使用中に文字を入力したりマウスを動かしたりすることはありません。デフォルトではオフです。",
        "ko": "Mac을 깨어 있게 유지하면 잠들지는 않지만 다른 소프트웨어에서 활성 상태가 유지되지는 않습니다. 회의 및 채팅 앱, 원격 데스크톱과 VDI, 클라우드 게임, 기타 여러 도구는 자체 유휴 시간 제한을 계속 적용합니다. 사용자를 자리 비움으로 표시하거나 연결을 끊거나 세션을 종료할 수 있습니다. 이 기능은 활동을 보고하여 현재 상태를 유지합니다. 기본 방법에는 추가 권한이 필요하지 않습니다. 일부 소프트웨어는 실제 키나 마우스만 감지하므로 F15, Shift, 지정한 키 또는 전송된 마우스 이동을 선택할 수 있습니다. 이 방법들에는 손쉬운 사용 권한이 필요하며, 실행 시가 아니라 선택할 때만 요청됩니다. F15는 대부분의 키보드에 없어 아무것도 입력되지 않으므로 일반적인 선택입니다. Shift는 보이지 않습니다. 지정한 키나 마우스 이동은 그것만 감시하는 소프트웨어에 대응합니다. 문자나 숫자는 전면 앱에 입력됩니다. 몇 초 동안 유휴 상태일 때만 개입하므로 Mac을 사용하는 동안 입력하거나 마우스를 움직이지 않습니다. 기본적으로 꺼져 있습니다.",
        "ru": "Поддержание активности Mac не даёт ему уснуть, но не сохраняет вашу активность в другом ПО. Приложения для встреч и чатов, удалённый рабочий стол и VDI, облачные игры и многие другие инструменты всё равно применяют собственный тайм-аут бездействия: они могут отметить вас как отсутствующего, отключить или завершить сеанс. Эта функция сообщает об активности, чтобы вы оставались в статусе присутствия. Метод по умолчанию не требует дополнительных разрешений. Некоторые программы замечают только реальную клавишу или мышь, поэтому можно выбрать F15, Shift, указанную клавишу или отправленное движение мыши. Для них нужен универсальный доступ, который запрашивается только при выборе, а не при запуске. F15 является обычным выбором, поскольку на большинстве клавиатур её нет и ничего не вводится. Shift незаметна. Указанная клавиша или движение мыши подходят для программ, которые следят только за ними. Буква или цифра будет введена в приложение на переднем плане. Функция срабатывает только после нескольких секунд бездействия, поэтому не печатает и не двигает мышь, пока вы пользуетесь Mac. По умолчанию выключена.",
        "pt-BR": "Manter o Mac acordado impede que ele durma, mas não mantém você ativo em outros softwares. Apps de reunião e chat, desktop remoto e VDI, jogos na nuvem e muitas outras ferramentas ainda aplicam seu próprio tempo limite de inatividade: elas podem marcar você como ausente, desconectar ou encerrar a sessão. Esta opção informa atividade para que você permaneça presente. O método padrão não precisa de permissão extra. Alguns programas só percebem uma tecla ou mouse reais, então você pode escolher F15, Shift, uma tecla especificada ou um movimento de mouse enviado. Esses métodos exigem Acessibilidade, solicitada apenas quando você os escolhe, nunca na inicialização. F15 é a escolha usual porque a maioria dos teclados não a tem e nada é digitado. Shift é invisível. Uma tecla especificada ou movimento do mouse cobre programas que observam apenas isso. Uma letra ou número será digitado no app em primeiro plano. A opção só intervém depois de alguns segundos de inatividade, portanto nunca digita nem move o mouse enquanto você usa o Mac. Desativada por padrão.",
        "tr": "Mac'i uyanık tutmak uykuya geçmesini önler, ancak sizi diğer yazılımlarda etkin tutmaz. Toplantı ve sohbet uygulamaları, uzak masaüstü ve VDI, bulut oyunları ve birçok başka araç kendi boşta kalma zaman aşımını uygulamaya devam eder: sizi uzakta olarak işaretleyebilir, bağlantıyı kesebilir veya oturumu sonlandırabilir. Bu özellik, mevcut kalmanız için etkinlik bildirir. Varsayılan yöntem ek izin gerektirmez. Bazı yazılımlar yalnızca gerçek bir tuşu veya fareyi fark eder, bu nedenle F15, Shift, belirtilen tuş ya da gönderilen fare hareketini seçebilirsiniz. Bunlar, yalnızca seçtiğinizde istenen Erişilebilirlik izni gerektirir, uygulama açılışında asla istenmez. F15 yaygın seçimdir, çünkü çoğu klavyede yoktur ve hiçbir şey yazılmaz. Shift görünmezdir. Belirtilen bir tuş veya fare hareketi, yalnızca bunları izleyen yazılımları kapsar. Bir harf veya sayı öndeki uygulamaya yazılır. Yalnızca birkaç saniye boşta kaldıktan sonra devreye girer, bu nedenle Mac'i kullanırken asla yazmaz veya fareyi oynatmaz. Varsayılan olarak kapalıdır.",
        "pl": "Utrzymywanie Maca w stanie czuwania zapobiega jego uśpieniu, ale nie utrzymuje Twojej aktywności w innym oprogramowaniu. Aplikacje do spotkań i czatu, pulpit zdalny i VDI, gry w chmurze i wiele innych narzędzi nadal stosują własny limit bezczynności: mogą oznaczyć Cię jako nieobecnego, rozłączyć lub zakończyć sesję. Ta opcja zgłasza aktywność, aby zachować status obecności. Metoda domyślna nie wymaga dodatkowego zezwolenia. Niektóre programy wykrywają tylko prawdziwy klawisz lub mysz, dlatego możesz wybrać F15, Shift, wybrany klawisz albo wysłany ruch myszy. Wymagają one dostępu do funkcji Dostępność, o który prosimy tylko po ich wybraniu, nigdy przy uruchomieniu. F15 to częsty wybór, ponieważ większość klawiatur go nie ma i nic nie zostanie wpisane. Shift jest niewidoczny. Wybrany klawisz lub ruch myszy obsługuje oprogramowanie obserwujące tylko te sygnały. Litera lub cyfra zostanie wpisana do aplikacji na pierwszym planie. Opcja działa dopiero po kilku sekundach bezczynności, więc nie wpisuje niczego ani nie porusza myszą podczas używania Maca. Domyślnie wyłączona.",
        "uk": "Утримання Mac без сну не дає йому заснути, але не підтримує вашу активність в іншому програмному забезпеченні. Застосунки для зустрічей і чатів, віддалений робочий стіл і VDI, хмарні ігри та багато інших інструментів і далі застосовують власний час очікування бездіяльності: вони можуть позначити вас як відсутнього, від’єднати або завершити сеанс. Ця функція повідомляє про активність, щоб ви залишалися присутніми. Стандартний метод не потребує додаткового дозволу. Деякі програми помічають лише справжню клавішу або мишу, тому можна вибрати F15, Shift, вказану клавішу або надісланий рух миші. Для них потрібен універсальний доступ, який запитується лише під час вибору, а не запуску. F15 є звичним вибором, бо на більшості клавіатур її немає і нічого не вводиться. Shift непомітна. Вказана клавіша або рух миші підходять для програм, які стежать лише за ними. Літера або цифра буде введена в застосунок на передньому плані. Функція втручається лише після кількох секунд бездіяльності, тому не вводить текст і не рухає мишу, коли ви користуєтеся Mac. Типово вимкнена.",
        "zh-Hant": "讓 Mac 保持喚醒能防止它睡眠，但不會讓您在其他軟體中保持活動狀態。會議和聊天 App、遠端桌面和 VDI、雲端遊戲以及許多其他工具仍會套用自己的閒置逾時：它們可能將您標記為離開、中斷連線或結束工作階段。此功能會回報活動，讓您保持在線。預設方法不需要額外權限。有些軟體只會注意到真實的按鍵或滑鼠，因此您可以選擇 F15、Shift、指定按鍵或送出的滑鼠移動。這些方法需要輔助使用權限，只會在您選擇時要求，絕不會在啟動時要求。F15 是常見選擇，因為大多數鍵盤沒有它，所以不會輸入任何內容。Shift 不會顯示。指定按鍵或滑鼠移動可適用於只觀察這些輸入的軟體。字母或數字會輸入到前景 App。它只會在您閒置幾秒後介入，因此在您使用 Mac 時絕不會輸入或移動滑鼠。預設為關閉。",
    },
    "Reports activity so you stay present in apps that have their own idle timeout.": {
        "hu": "Tevékenységet jelez, hogy jelen maradjon a saját tétlenségi időkorláttal rendelkező alkalmazásokban.", "es": "Informa actividad para que sigas presente en apps con su propio tiempo de espera por inactividad.", "fr": "Signale une activité pour que vous restiez présent dans les apps ayant leur propre délai d’inactivité.", "de": "Meldet Aktivität, damit du in Apps mit eigenem Leerlauf-Timeout präsent bleibst.", "zh-Hans": "报告活动，让你在有自己空闲超时策略的 App 中保持在线。",
        "it": "Segnala attività per mantenerti presente nelle app con un proprio timeout di inattività.", "ja": "独自のアイドルタイムアウトを持つ App で在席状態を保つためにアクティビティを通知します。", "ko": "자체 유휴 시간 제한이 있는 앱에서 현재 상태를 유지하도록 활동을 보고합니다.", "ru": "Сообщает об активности, чтобы вы оставались в статусе присутствия в приложениях с собственным тайм-аутом бездействия.", "pt-BR": "Informa atividade para que você permaneça presente em apps com seu próprio tempo limite de inatividade.", "tr": "Kendi boşta kalma zaman aşımı olan uygulamalarda mevcut kalmanız için etkinlik bildirir.", "pl": "Zgłasza aktywność, aby zachować status obecności w aplikacjach z własnym limitem bezczynności.", "uk": "Повідомляє про активність, щоб ви залишалися присутніми в застосунках із власним часом очікування бездіяльності.", "zh-Hant": "回報活動，讓您在有自己閒置逾時的 App 中保持在線。",
    },
    "Prompt-free. Some apps ignore this and need a key or mouse method.": {
        "hu": "Jelszókérés nélkül. Egyes alkalmazások ezt figyelmen kívül hagyják, és billentyűs vagy egeres módszert igényelnek.", "es": "Sin solicitudes. Algunas apps lo ignoran y necesitan un método de tecla o ratón.", "fr": "Sans demande d’autorisation. Certaines apps l’ignorent et nécessitent une méthode par touche ou souris.", "de": "Ohne Rückfrage. Manche Apps ignorieren dies und benötigen eine Tasten- oder Mausmethode.", "zh-Hans": "无需弹出权限请求。有些 App 会忽略此方法，需要使用按键或鼠标方法。",
        "it": "Senza richieste. Alcune app lo ignorano e richiedono un metodo con tasto o mouse.", "ja": "確認は不要です。一部の App はこれを無視するため、キーまたはマウスの方法が必要です。", "ko": "권한 요청이 없습니다. 일부 앱은 이를 무시하므로 키 또는 마우스 방법이 필요합니다.", "ru": "Без запросов. Некоторые приложения игнорируют этот метод, и им нужен метод с клавишей или мышью.", "pt-BR": "Sem solicitações. Alguns apps ignoram isso e precisam de um método de tecla ou mouse.", "tr": "İzin istemez. Bazı uygulamalar bunu yok sayar ve tuş ya da fare yöntemi gerekir.", "pl": "Bez pytań o uprawnienia. Niektóre aplikacje to ignorują i wymagają metody z klawiszem lub myszą.", "uk": "Без запитів. Деякі застосунки ігнорують цей метод і потребують методу з клавішею або мишею.", "zh-Hant": "不會跳出權限要求。有些 App 會忽略此方法，需要使用按鍵或滑鼠方法。",
    },
    "Posts F15 every 60 s. A common pick for software that watches the keyboard.": {
        "hu": "60 másodpercenként F15-öt küld. Gyakori választás a billentyűzetet figyelő szoftverekhez.", "es": "Envía F15 cada 60 s. Una opción habitual para software que vigila el teclado.", "fr": "Envoie F15 toutes les 60 s. Un choix courant pour les logiciels qui surveillent le clavier.", "de": "Sendet alle 60 s F15. Eine häufige Wahl für Software, die die Tastatur überwacht.", "zh-Hans": "每 60 秒发送一次 F15。适合监测键盘的软件的常见选择。",
        "it": "Invia F15 ogni 60 s. Una scelta comune per i software che controllano la tastiera.", "ja": "60 秒ごとに F15 を送信します。キーボードを監視するソフトウェアでよく使われます。", "ko": "60초마다 F15를 보냅니다. 키보드를 감시하는 소프트웨어에 흔히 쓰입니다.", "ru": "Отправляет F15 каждые 60 с. Обычный выбор для ПО, отслеживающего клавиатуру.", "pt-BR": "Envia F15 a cada 60 s. Uma escolha comum para softwares que observam o teclado.", "tr": "Her 60 sn’de F15 gönderir. Klavyeyi izleyen yazılımlar için yaygın bir seçimdir.", "pl": "Wysyła F15 co 60 s. Częsty wybór dla oprogramowania obserwującego klawiaturę.", "uk": "Надсилає F15 кожні 60 с. Звичний вибір для програм, що стежать за клавіатурою.", "zh-Hant": "每 60 秒送出一次 F15。適合監測鍵盤的軟體的常見選擇。",
    },
    "Taps Shift every 60 s. Invisible, and nothing is typed.": {
        "hu": "60 másodpercenként megnyomja a Shiftet. Láthatatlan, és semmi nem íródik be.", "es": "Pulsa Mayús cada 60 s. Es invisible y no escribe nada.", "fr": "Appuie sur Maj toutes les 60 s. C’est invisible et rien n’est saisi.", "de": "Tippt alle 60 s auf die Umschalttaste. Unsichtbar, und es wird nichts eingegeben.", "zh-Hans": "每 60 秒按一次 Shift。不会显示，也不会输入任何内容。",
        "it": "Tocca Maiusc ogni 60 s. È invisibile e non viene digitato nulla.", "ja": "60 秒ごとに Shift を押します。見えず、何も入力されません。", "ko": "60초마다 Shift를 누릅니다. 보이지 않으며 아무것도 입력되지 않습니다.", "ru": "Нажимает Shift каждые 60 с. Это незаметно и ничего не вводится.", "pt-BR": "Pressiona Shift a cada 60 s. É invisível e nada é digitado.", "tr": "Her 60 sn’de Shift’e basar. Görünmezdir ve hiçbir şey yazılmaz.", "pl": "Naciska Shift co 60 s. Jest to niewidoczne i nic nie zostanie wpisane.", "uk": "Натискає Shift кожні 60 с. Це непомітно, і нічого не вводиться.", "zh-Hant": "每 60 秒按一次 Shift。不會顯示，也不會輸入任何內容。",
    },
    "Taps the recorded key every 60 s. Prefer a function key or modifier.": {
        "hu": "60 másodpercenként megnyomja a rögzített billentyűt. Inkább funkcióbillentyűt vagy módosítót válasszon.", "es": "Pulsa la tecla grabada cada 60 s. Es preferible una tecla de función o modificadora.", "fr": "Appuie sur la touche enregistrée toutes les 60 s. Préférez une touche de fonction ou de modification.", "de": "Tippt alle 60 s auf die aufgezeichnete Taste. Bevorzuge eine Funktions- oder Modifikatortaste.", "zh-Hans": "每 60 秒按一次录制的按键。建议使用功能键或修饰键。",
        "it": "Tocca il tasto registrato ogni 60 s. Preferisci un tasto funzione o modificatore.", "ja": "60 秒ごとに記録したキーを押します。ファンクションキーまたは修飾キーを推奨します。", "ko": "60초마다 기록한 키를 누릅니다. 기능 키나 보조 키를 사용하는 것이 좋습니다.", "ru": "Нажимает записанную клавишу каждые 60 с. Лучше выбрать функциональную клавишу или модификатор.", "pt-BR": "Pressiona a tecla gravada a cada 60 s. Prefira uma tecla de função ou modificadora.", "tr": "Kaydedilen tuşa her 60 sn’de basar. İşlev tuşunu veya değiştirici tuşu tercih edin.", "pl": "Naciska zarejestrowany klawisz co 60 s. Lepiej wybrać klawisz funkcyjny lub modyfikator.", "uk": "Натискає записану клавішу кожні 60 с. Краще вибрати функціональну клавішу або модифікатор.", "zh-Hant": "每 60 秒按一次錄製的按鍵。建議使用功能鍵或修飾鍵。",
    },
    "Posts a 1-pixel mouse move every 60 s. For software that watches the pointer.": {
        "hu": "60 másodpercenként 1 képpontos egérmozgást küld. A mutatót figyelő szoftverekhez.", "es": "Envía un movimiento de ratón de 1 píxel cada 60 s. Para software que vigila el puntero.", "fr": "Envoie un mouvement de souris d’un pixel toutes les 60 s. Pour les logiciels qui surveillent le pointeur.", "de": "Sendet alle 60 s eine Mausbewegung um 1 Pixel. Für Software, die den Zeiger überwacht.", "zh-Hans": "每 60 秒发送一次 1 像素的鼠标移动。适用于监测指针的软件。",
        "it": "Invia un movimento del mouse di 1 pixel ogni 60 s. Per i software che osservano il puntatore.", "ja": "60 秒ごとに 1 ピクセルのマウス移動を送信します。ポインタを監視するソフトウェア向けです。", "ko": "60초마다 1픽셀 마우스 이동을 보냅니다. 포인터를 감시하는 소프트웨어용입니다.", "ru": "Отправляет движение мыши на 1 пиксель каждые 60 с. Для ПО, отслеживающего указатель.", "pt-BR": "Envia um movimento de mouse de 1 pixel a cada 60 s. Para softwares que observam o ponteiro.", "tr": "Her 60 sn’de 1 piksellik fare hareketi gönderir. İşaretçiyi izleyen yazılımlar içindir.", "pl": "Wysyła ruch myszy o 1 piksel co 60 s. Dla oprogramowania obserwującego wskaźnik.", "uk": "Надсилає рух миші на 1 піксель кожні 60 с. Для програм, що стежать за вказівником.", "zh-Hant": "每 60 秒送出一次 1 像素的滑鼠移動。適用於監測游標的軟體。",
    },
    "Helper installed. Closed-display mode, Keyboard Cleaner, fan boost, AWDL pausing, and DNS flush work without password prompts.": {
        "hu": "A segéd telepítve. A csukott fedél mód, a Billentyűzettisztító, a ventilátorfokozás, az AWDL szüneteltetése és a DNS ürítése jelszókérés nélkül működik.", "es": "Asistente instalado. El modo con pantalla cerrada, el Limpiador de teclado, el refuerzo de ventiladores, la pausa de AWDL y el vaciado de DNS funcionan sin solicitudes de contraseña.", "fr": "Assistant installé. Le mode écran fermé, le nettoyeur de clavier, l’accélération des ventilateurs, la mise en pause d’AWDL et le vidage DNS fonctionnent sans demande de mot de passe.", "de": "Hilfsdienst installiert. Modus bei geschlossenem Display, Tastaturreiniger, Lüfter-Boost, AWDL-Pausierung und DNS-Leerung funktionieren ohne Passwortabfragen.", "zh-Hans": "助理已安装。合盖模式、键盘清洁器、风扇加速、AWDL 暂停和 DNS 刷新都无需弹出密码请求即可使用。",
        "it": "Assistente installato. La modalità a schermo chiuso, il Pulitore della tastiera, l’aumento delle ventole, la pausa di AWDL e lo svuotamento DNS funzionano senza richieste di password.", "ja": "ヘルパーをインストールしました。クラムシェルモード、キーボードクリーナー、ファン増速、AWDL の一時停止、DNS フラッシュがパスワードの要求なしで動作します。", "ko": "도우미가 설치되었습니다. 디스플레이 닫힘 모드, 키보드 클리너, 팬 부스트, AWDL 일시 정지 및 DNS 플러시가 암호 요청 없이 작동합니다.", "ru": "Помощник установлен. Режим закрытого дисплея, очистка клавиатуры, ускорение вентиляторов, приостановка AWDL и очистка DNS работают без запроса пароля.", "pt-BR": "Assistente instalado. O modo com tela fechada, o Limpador de teclado, o reforço das ventoinhas, a pausa de AWDL e a limpeza de DNS funcionam sem solicitações de senha.", "tr": "Yardımcı yüklendi. Kapalı ekran modu, Klavye Temizleyici, fan hızlandırma, AWDL duraklatma ve DNS temizleme parola istemleri olmadan çalışır.", "pl": "Pomocnik zainstalowany. Tryb zamkniętej pokrywy, czyszczenie klawiatury, zwiększanie obrotów wentylatorów, wstrzymywanie AWDL i czyszczenie DNS działają bez próśb o hasło.", "uk": "Помічника встановлено. Режим закритої кришки, очищення клавіатури, прискорення вентиляторів, призупинення AWDL і очищення DNS працюють без запитів пароля.", "zh-Hant": "輔助程式已安裝。闔蓋模式、鍵盤清潔工具、風扇加速、AWDL 暫停與 DNS 清除皆可在無需輸入密碼的情況下運作。",
    },
    "Install a small helper service so closed-display mode, Keyboard Cleaner, the thermal fan boost, AWDL pausing, and DNS flush work without password prompts. macOS will ask you to allow it in System Settings, once. Nothing else changes.": {
        "hu": "Telepítsen egy kis segédszolgáltatást, hogy a csukott fedél mód, a Billentyűzettisztító, a hővédelmi ventilátorfokozás, az AWDL szüneteltetése és a DNS ürítése jelszókérés nélkül működjön. A macOS egyszer engedélyt kér hozzá a Rendszerbeállításokban. Semmi más nem változik.", "es": "Instala un pequeño servicio auxiliar para que el modo con pantalla cerrada, el Limpiador de teclado, el refuerzo térmico de los ventiladores, la pausa de AWDL y el vaciado de DNS funcionen sin solicitudes de contraseña. macOS te pedirá autorizarlo una vez en Ajustes del Sistema. No cambia nada más.", "fr": "Installez un petit service d’assistance afin que le mode écran fermé, le nettoyeur de clavier, l’accélération thermique des ventilateurs, la mise en pause d’AWDL et le vidage DNS fonctionnent sans demande de mot de passe. macOS vous demandera de l’autoriser une fois dans Réglages Système. Rien d’autre ne change.", "de": "Installiere einen kleinen Hilfsdienst, damit Modus bei geschlossenem Display, Tastaturreiniger, thermischer Lüfter-Boost, AWDL-Pausierung und DNS-Leerung ohne Passwortabfragen funktionieren. macOS wird dich einmal bitten, ihn in den Systemeinstellungen zu erlauben. Sonst ändert sich nichts.", "zh-Hans": "安装一个小型助理服务，让合盖模式、键盘清洁器、散热风扇加速、AWDL 暂停和 DNS 刷新无需弹出密码请求即可使用。macOS 会要求你在系统设置中允许它一次。不会有其他变化。",
        "it": "Installa un piccolo servizio di supporto affinché la modalità a schermo chiuso, il Pulitore della tastiera, l’aumento termico delle ventole, la pausa di AWDL e lo svuotamento DNS funzionino senza richieste di password. macOS ti chiederà di autorizzarlo una volta in Impostazioni di Sistema. Non cambia nient’altro.", "ja": "小さなヘルパーサービスをインストールすると、クラムシェルモード、キーボードクリーナー、熱によるファン増速、AWDL の一時停止、DNS フラッシュがパスワードの要求なしで動作します。macOS はシステム設定で一度だけ許可を求めます。ほかには何も変わりません。", "ko": "작은 도우미 서비스를 설치하면 디스플레이 닫힘 모드, 키보드 클리너, 열 관리 팬 부스트, AWDL 일시 정지 및 DNS 플러시가 암호 요청 없이 작동합니다. macOS가 시스템 설정에서 한 번 허용을 요청합니다. 그 외에는 아무것도 바뀌지 않습니다.", "ru": "Установите небольшую службу-помощник, чтобы режим закрытого дисплея, очистка клавиатуры, термоускорение вентиляторов, приостановка AWDL и очистка DNS работали без запроса пароля. macOS один раз попросит разрешить её в Системных настройках. Больше ничего не изменится.", "pt-BR": "Instale um pequeno serviço auxiliar para que o modo com tela fechada, o Limpador de teclado, o reforço térmico das ventoinhas, a pausa de AWDL e a limpeza de DNS funcionem sem solicitações de senha. O macOS pedirá que você o autorize uma vez nos Ajustes do Sistema. Nada mais muda.", "tr": "Kapalı ekran modunun, Klavye Temizleyici'nin, termal fan hızlandırmanın, AWDL duraklatmanın ve DNS temizlemenin parola istemleri olmadan çalışması için küçük bir yardımcı hizmet yükleyin. macOS, Sistem Ayarları'nda bunu bir kez onaylamanızı ister. Başka hiçbir şey değişmez.", "pl": "Zainstaluj małą usługę pomocniczą, aby tryb zamkniętej pokrywy, czyszczenie klawiatury, termiczne zwiększanie obrotów wentylatorów, wstrzymywanie AWDL i czyszczenie DNS działały bez próśb o hasło. macOS poprosi Cię o zezwolenie na nią raz w Ustawieniach systemowych. Nic innego się nie zmieni.", "uk": "Установіть невелику службу-помічник, щоб режим закритої кришки, очищення клавіатури, термічне прискорення вентиляторів, призупинення AWDL і очищення DNS працювали без запитів пароля. macOS один раз попросить дозволити її в Системних параметрах. Більше нічого не зміниться.", "zh-Hant": "安裝一個小型輔助服務，讓闔蓋模式、鍵盤清潔工具、散熱風扇加速、AWDL 暫停與 DNS 清除皆可在無需輸入密碼的情況下運作。macOS 會要求您在系統設定中核准一次。其他項目不會有任何變動。",
    },
}
