# -*- coding: utf-8 -*-
# Keepresso v1.21 app-window strings: English source -> all supported locales.

APP = {
    "Keyboard Cleaner": {
        "hu": "Billentyűzet tisztítása", "es": "Limpiador de teclado", "fr": "Nettoyage du clavier", "de": "Tastaturreiniger", "zh-Hans": "键盘清洁", "it": "Pulizia della tastiera", "ja": "キーボードクリーナー", "ko": "키보드 청소", "ru": "Очистка клавиатуры", "pt-BR": "Limpeza do teclado", "tr": "Klavye Temizleyici", "pl": "Czyszczenie klawiatury", "uk": "Очищення клавіатури", "zh-Hant": "鍵盤清潔",
    },
    "Locks the keys so you can wipe the keyboard without typing into whatever is in front. The pointer still works: click Unlock when you are done.": {
        "hu": "Lezárja a billentyűket, így letörölheti a billentyűzetet anélkül, hogy bármit beírna az előtérben lévő alkalmazásba. A mutató továbbra is működik: ha végzett, kattintson a Feloldásra.", "es": "Bloquea las teclas para que puedas limpiar el teclado sin escribir en lo que tengas delante. El puntero sigue funcionando: haz clic en Desbloquear cuando termines.", "fr": "Verrouille les touches pour vous permettre d’essuyer le clavier sans écrire dans ce qui se trouve au premier plan. Le pointeur fonctionne toujours : cliquez sur Déverrouiller quand vous avez terminé.", "de": "Sperrt die Tasten, damit du die Tastatur abwischen kannst, ohne in das gerade geöffnete Fenster zu tippen. Der Zeiger funktioniert weiter: Klicke auf Entsperren, wenn du fertig bist.", "zh-Hans": "锁定按键，这样你可以擦拭键盘，而不会在前台内容中输入文字。指针仍可使用：完成后点按“解锁”。", "it": "Blocca i tasti così puoi pulire la tastiera senza digitare in ciò che hai davanti. Il puntatore continua a funzionare: fai clic su Sblocca quando hai finito.", "ja": "キー入力をロックするので、手前の画面に入力せずキーボードを拭けます。ポインタは引き続き使えます。終わったら「ロック解除」をクリックしてください。", "ko": "키를 잠그므로 앞에 있는 내용에 입력하지 않고 키보드를 닦을 수 있습니다. 포인터는 계속 작동합니다. 끝나면 잠금 해제를 클릭하세요.", "ru": "Блокирует клавиши, чтобы вы могли протереть клавиатуру, ничего не вводя в активное окно. Указатель продолжает работать: когда закончите, нажмите «Разблокировать».", "pt-BR": "Bloqueia as teclas para você limpar o teclado sem digitar no que estiver à frente. O ponteiro continua funcionando: clique em Desbloquear quando terminar.", "tr": "Tuşları kilitler; böylece öndeki içeriğe yazmadan klavyeyi silebilirsiniz. İşaretçi çalışmaya devam eder: işiniz bittiğinde Kilidi Aç’ı tıklayın.", "pl": "Blokuje klawisze, dzięki czemu możesz wyczyścić klawiaturę bez wpisywania czegokolwiek w aktywnym oknie. Wskaźnik nadal działa: po zakończeniu kliknij Odblokuj.", "uk": "Блокує клавіші, щоб ви могли протерти клавіатуру, не вводячи текст у вікні попереду. Вказівник і далі працює: коли завершите, натисніть «Розблокувати».", "zh-Hant": "鎖定按鍵，讓你擦拭鍵盤時不會在前景內容中輸入文字。指標仍可使用：完成後按一下「解鎖」。",
    },
    "Lock for": {
        "hu": "Zárolás ideje", "es": "Bloquear durante", "fr": "Verrouiller pendant", "de": "Sperren für", "zh-Hans": "锁定时长", "it": "Blocca per", "ja": "ロックする時間", "ko": "잠금 시간", "ru": "Заблокировать на", "pt-BR": "Bloquear por", "tr": "Kilitleme süresi", "pl": "Blokuj na", "uk": "Заблокувати на", "zh-Hant": "鎖定時間",
    },
    "Until I click": {
        "hu": "Amíg nem kattintok", "es": "Hasta que haga clic", "fr": "Jusqu’à ce que je clique", "de": "Bis ich klicke", "zh-Hans": "直到我点按", "it": "Finché non faccio clic", "ja": "クリックするまで", "ko": "클릭할 때까지", "ru": "Пока я не нажму", "pt-BR": "Até eu clicar", "tr": "Tıklayana kadar", "pl": "Aż kliknę", "uk": "Доки не натисну", "zh-Hant": "直到我按一下",
    },
    "Keyboard is locked. Wipe away.": {
        "hu": "A billentyűzet zárolva van. Nyugodtan törölje le.", "es": "El teclado está bloqueado. Límpialo sin problema.", "fr": "Le clavier est verrouillé. Vous pouvez l’essuyer.", "de": "Die Tastatur ist gesperrt. Du kannst sie jetzt abwischen.", "zh-Hans": "键盘已锁定。放心擦拭。", "it": "La tastiera è bloccata. Puoi pulirla.", "ja": "キーボードはロックされています。どうぞ拭いてください。", "ko": "키보드가 잠겼습니다. 닦아도 됩니다.", "ru": "Клавиатура заблокирована. Можно протирать.", "pt-BR": "O teclado está bloqueado. Pode limpar.", "tr": "Klavye kilitli. Silmeye başlayabilirsiniz.", "pl": "Klawiatura jest zablokowana. Możesz ją wyczyścić.", "uk": "Клавіатуру заблоковано. Можете протирати.", "zh-Hant": "鍵盤已鎖定。可以放心擦拭。",
    },
    "Could not lock keys globally (another tool may own the keyboard). Keys are only ignored while this overlay is in front.": {
        "hu": "A billentyűket nem sikerült globálisan zárolni (lehet, hogy egy másik eszköz használja a billentyűzetet). A billentyűleütéseket csak akkor hagyja figyelmen kívül, amíg ez az átfedés van elöl.", "es": "No se pudieron bloquear las teclas globalmente (puede que otra herramienta controle el teclado). Las teclas solo se ignoran mientras esta superposición está al frente.", "fr": "Impossible de verrouiller les touches globalement (un autre outil contrôle peut-être le clavier). Les touches sont ignorées uniquement tant que cette superposition est au premier plan.", "de": "Die Tasten konnten nicht systemweit gesperrt werden (möglicherweise verwendet ein anderes Werkzeug die Tastatur). Tasten werden nur ignoriert, solange diese Einblendung im Vordergrund ist.", "zh-Hans": "无法全局锁定按键（可能有其他工具正在控制键盘）。只有此覆盖层位于前台时，按键才会被忽略。", "it": "Non è stato possibile bloccare i tasti a livello globale (un altro strumento potrebbe controllare la tastiera). I tasti vengono ignorati solo mentre questa sovrapposizione è in primo piano.", "ja": "キーをシステム全体でロックできませんでした（別のツールがキーボードを使用している可能性があります）。このオーバーレイが前面にある間だけキー入力は無視されます。", "ko": "키를 전체적으로 잠글 수 없습니다(다른 도구가 키보드를 사용 중일 수 있습니다). 이 오버레이가 앞에 있는 동안에만 키 입력이 무시됩니다.", "ru": "Не удалось заблокировать клавиши во всей системе (возможно, клавиатуру использует другой инструмент). Клавиши игнорируются только пока это наложение находится на переднем плане.", "pt-BR": "Não foi possível bloquear as teclas globalmente (outra ferramenta pode estar controlando o teclado). As teclas só são ignoradas enquanto esta sobreposição estiver em primeiro plano.", "tr": "Tuşlar sistem genelinde kilitlenemedi (başka bir araç klavyeyi kullanıyor olabilir). Tuşlar yalnızca bu kaplama öndeyken yok sayılır.", "pl": "Nie można było zablokować klawiszy globalnie (inne narzędzie może przejmować klawiaturę). Klawisze są ignorowane tylko wtedy, gdy ta nakładka jest na pierwszym planie.", "uk": "Не вдалося глобально заблокувати клавіші (можливо, клавіатуру використовує інший інструмент). Клавіші ігноруються лише тоді, коли ця накладка перебуває на передньому плані.", "zh-Hant": "無法全域鎖定按鍵（可能有其他工具正在使用鍵盤）。只有此覆蓋層位於前景時，按鍵才會被忽略。",
    },
    "lock the keyboard": {
        "hu": "a billentyűzet zárolásához", "es": "bloquear el teclado", "fr": "verrouiller le clavier", "de": "die Tastatur zu sperren", "zh-Hans": "锁定键盘", "it": "bloccare la tastiera", "ja": "キーボードをロックする", "ko": "키보드를 잠그는", "ru": "заблокировать клавиатуру", "pt-BR": "bloquear o teclado", "tr": "klavyeyi kilitlemek", "pl": "zablokować klawiaturę", "uk": "заблокувати клавіатуру", "zh-Hant": "鎖定鍵盤",
    },
    "Unlock": {
        "hu": "Feloldás", "es": "Desbloquear", "fr": "Déverrouiller", "de": "Entsperren", "zh-Hans": "解锁", "it": "Sblocca", "ja": "ロック解除", "ko": "잠금 해제", "ru": "Разблокировать", "pt-BR": "Desbloquear", "tr": "Kilidi Aç", "pl": "Odblokuj", "uk": "Розблокувати", "zh-Hant": "解鎖",
    },
    "Lock Keyboard": {
        "hu": "Billentyűzet zárolása", "es": "Bloquear teclado", "fr": "Verrouiller le clavier", "de": "Tastatur sperren", "zh-Hans": "锁定键盘", "it": "Blocca tastiera", "ja": "キーボードをロック", "ko": "키보드 잠그기", "ru": "Заблокировать клавиатуру", "pt-BR": "Bloquear teclado", "tr": "Klavyeyi Kilitle", "pl": "Zablokuj klawiaturę", "uk": "Заблокувати клавіатуру", "zh-Hant": "鎖定鍵盤",
    },
    "%d min %d sec": {
        "hu": "%d perc %d mp", "es": "%d min %d s", "fr": "%d min %d s", "de": "%d Min. %d Sek.", "zh-Hans": "%d 分 %d 秒", "it": "%d min %d sec", "ja": "%d 分 %d 秒", "ko": "%d분 %d초", "ru": "%d мин. %d сек.", "pt-BR": "%d min %d s", "tr": "%d dk. %d sn.", "pl": "%d min %d s", "uk": "%d хв. %d с", "zh-Hant": "%d 分 %d 秒",
    },
    "%d sec": {
        "hu": "%d mp", "es": "%d s", "fr": "%d s", "de": "%d Sek.", "zh-Hans": "%d 秒", "it": "%d sec", "ja": "%d 秒", "ko": "%d초", "ru": "%d сек.", "pt-BR": "%d s", "tr": "%d sn.", "pl": "%d s", "uk": "%d с", "zh-Hant": "%d 秒",
    },
    "Keyboard is locked": {
        "hu": "A billentyűzet zárolva van", "es": "El teclado está bloqueado", "fr": "Le clavier est verrouillé", "de": "Die Tastatur ist gesperrt", "zh-Hans": "键盘已锁定", "it": "La tastiera è bloccata", "ja": "キーボードはロックされています", "ko": "키보드가 잠겼습니다", "ru": "Клавиатура заблокирована", "pt-BR": "O teclado está bloqueado", "tr": "Klavye kilitli", "pl": "Klawiatura jest zablokowana", "uk": "Клавіатуру заблоковано", "zh-Hant": "鍵盤已鎖定",
    },
    "Wipe away. The pointer still works. Click Unlock when you are done.": {
        "hu": "Nyugodtan törölje le. A mutató továbbra is működik. Ha végzett, kattintson a Feloldásra.", "es": "Límpialo sin problema. El puntero sigue funcionando. Haz clic en Desbloquear cuando termines.", "fr": "Vous pouvez l’essuyer. Le pointeur fonctionne toujours. Cliquez sur Déverrouiller quand vous avez terminé.", "de": "Du kannst sie jetzt abwischen. Der Zeiger funktioniert weiter. Klicke auf Entsperren, wenn du fertig bist.", "zh-Hans": "放心擦拭。指针仍可使用。完成后点按“解锁”。", "it": "Puoi pulirla. Il puntatore continua a funzionare. Fai clic su Sblocca quando hai finito.", "ja": "どうぞ拭いてください。ポインタは引き続き使えます。終わったら「ロック解除」をクリックしてください。", "ko": "닦아도 됩니다. 포인터는 계속 작동합니다. 끝나면 잠금 해제를 클릭하세요.", "ru": "Можно протирать. Указатель продолжает работать. Когда закончите, нажмите «Разблокировать».", "pt-BR": "Pode limpar. O ponteiro continua funcionando. Clique em Desbloquear quando terminar.", "tr": "Silmeye başlayabilirsiniz. İşaretçi çalışmaya devam eder. İşiniz bittiğinde Kilidi Aç’ı tıklayın.", "pl": "Możesz ją wyczyścić. Wskaźnik nadal działa. Po zakończeniu kliknij Odblokuj.", "uk": "Можете протирати. Вказівник і далі працює. Коли завершите, натисніть «Розблокувати».", "zh-Hant": "可以放心擦拭。指標仍可使用。完成後按一下「解鎖」。",
    },
    "Keys are only ignored while this overlay is in front.": {
        "hu": "A billentyűleütéseket csak akkor hagyja figyelmen kívül, amíg ez az átfedés van elöl.", "es": "Las teclas solo se ignoran mientras esta superposición está al frente.", "fr": "Les touches sont ignorées uniquement tant que cette superposition est au premier plan.", "de": "Tasten werden nur ignoriert, solange diese Einblendung im Vordergrund ist.", "zh-Hans": "只有此覆盖层位于前台时，按键才会被忽略。", "it": "I tasti vengono ignorati solo mentre questa sovrapposizione è in primo piano.", "ja": "このオーバーレイが前面にある間だけキー入力は無視されます。", "ko": "이 오버레이가 앞에 있는 동안에만 키 입력이 무시됩니다.", "ru": "Клавиши игнорируются только пока это наложение находится на переднем плане.", "pt-BR": "As teclas só são ignoradas enquanto esta sobreposição estiver em primeiro plano.", "tr": "Tuşlar yalnızca bu kaplama öndeyken yok sayılır.", "pl": "Klawisze są ignorowane tylko wtedy, gdy ta nakładka jest na pierwszym planie.", "uk": "Клавіші ігноруються лише тоді, коли ця накладка перебуває на передньому плані.", "zh-Hant": "只有此覆蓋層位於前景時，按鍵才會被忽略。",
    },
    "Public Wi-Fi": {
        "hu": "Nyilvános Wi-Fi", "es": "Wi-Fi público", "fr": "Wi-Fi public", "de": "Öffentliches WLAN", "zh-Hans": "公共 Wi-Fi", "it": "Wi-Fi pubblico", "ja": "公共 Wi-Fi", "ko": "공용 Wi-Fi", "ru": "Общедоступный Wi-Fi", "pt-BR": "Wi-Fi público", "tr": "Genel Wi-Fi", "pl": "Publiczne Wi-Fi", "uk": "Загальнодоступний Wi-Fi", "zh-Hant": "公共 Wi-Fi",
    },
    "When a cafe or airport network associates but never shows a login page, start here. Nothing runs until you click a button.": {
        "hu": "Ha egy kávézó vagy repülőtér hálózata csatlakozik, de nem jelenik meg a bejelentkezési oldal, kezdje itt. Semmi sem fut le, amíg nem kattint egy gombra.", "es": "Si una red de una cafetería o aeropuerto se conecta pero nunca muestra una página de inicio de sesión, empieza aquí. No se ejecuta nada hasta que haces clic en un botón.", "fr": "Si le réseau d’un café ou d’un aéroport se connecte sans jamais afficher de page de connexion, commencez ici. Rien ne s’exécute avant que vous cliquiez sur un bouton.", "de": "Wenn sich ein Café- oder Flughafennetzwerk verbindet, aber keine Anmeldeseite zeigt, starte hier. Es passiert nichts, bis du auf eine Taste klickst.", "zh-Hans": "如果咖啡馆或机场网络已连接却始终不显示登录页面，请从这里开始。点按按钮前不会执行任何操作。", "it": "Se una rete di un bar o di un aeroporto si connette ma non mostra mai una pagina di accesso, inizia qui. Non viene eseguito nulla finché non fai clic su un pulsante.", "ja": "カフェや空港のネットワークに接続しているのにログインページが表示されない場合は、ここから始めてください。ボタンをクリックするまで何も実行されません。", "ko": "카페나 공항 네트워크에 연결되었는데 로그인 페이지가 표시되지 않으면 여기서 시작하세요. 버튼을 클릭하기 전에는 아무 작업도 실행되지 않습니다.", "ru": "Если сеть кафе или аэропорта подключилась, но страница входа так и не появилась, начните здесь. Пока вы не нажмёте кнопку, ничего не выполняется.", "pt-BR": "Se a rede de um café ou aeroporto conectar, mas não mostrar uma página de login, comece aqui. Nada é executado até você clicar em um botão.", "tr": "Bir kafe veya havalimanı ağına bağlanıp giriş sayfası hiç görünmüyorsa buradan başlayın. Bir düğmeye tıklayana kadar hiçbir şey çalışmaz.", "pl": "Jeśli sieć w kawiarni lub na lotnisku połączy się, ale nie wyświetli strony logowania, zacznij tutaj. Nic nie zostanie uruchomione, dopóki nie klikniesz przycisku.", "uk": "Якщо мережа в кафе чи аеропорту підключилася, але сторінка входу так і не з’явилася, почніть тут. Доки ви не натиснете кнопку, нічого не виконується.", "zh-Hant": "如果咖啡館或機場網路已連線，卻始終沒有顯示登入頁面，請從這裡開始。按一下按鈕前不會執行任何操作。",
    },
    "Open login page": {
        "hu": "Bejelentkezési oldal megnyitása", "es": "Abrir página de inicio de sesión", "fr": "Ouvrir la page de connexion", "de": "Anmeldeseite öffnen", "zh-Hans": "打开登录页面", "it": "Apri la pagina di accesso", "ja": "ログインページを開く", "ko": "로그인 페이지 열기", "ru": "Открыть страницу входа", "pt-BR": "Abrir página de login", "tr": "Giriş sayfasını aç", "pl": "Otwórz stronę logowania", "uk": "Відкрити сторінку входу", "zh-Hant": "開啟登入頁面",
    },
    "Open login page anyway": {
        "hu": "Bejelentkezési oldal megnyitása mégis", "es": "Abrir página de inicio de sesión de todos modos", "fr": "Ouvrir quand même la page de connexion", "de": "Anmeldeseite trotzdem öffnen", "zh-Hans": "仍然打开登录页面", "it": "Apri comunque la pagina di accesso", "ja": "ログインページをとにかく開く", "ko": "그래도 로그인 페이지 열기", "ru": "Всё равно открыть страницу входа", "pt-BR": "Abrir página de login mesmo assim", "tr": "Yine de giriş sayfasını aç", "pl": "Mimo to otwórz stronę logowania", "uk": "Все одно відкрити сторінку входу", "zh-Hant": "仍要開啟登入頁面",
    },
    "Open portal URL": {
        "hu": "Portál URL megnyitása", "es": "Abrir URL del portal", "fr": "Ouvrir l’URL du portail", "de": "Portal-URL öffnen", "zh-Hans": "打开门户 URL", "it": "Apri l’URL del portale", "ja": "ポータル URL を開く", "ko": "포털 URL 열기", "ru": "Открыть URL портала", "pt-BR": "Abrir URL do portal", "tr": "Portal URL'sini aç", "pl": "Otwórz adres URL portalu", "uk": "Відкрити URL порталу", "zh-Hant": "開啟入口 URL",
    },
    "Turn Wi-Fi off and on": {
        "hu": "Wi-Fi ki- és bekapcsolása", "es": "Apagar y encender el Wi-Fi", "fr": "Désactiver puis réactiver le Wi-Fi", "de": "WLAN aus- und einschalten", "zh-Hans": "关闭后重新打开 Wi-Fi", "it": "Spegni e riaccendi il Wi-Fi", "ja": "Wi-Fi をオフにしてオンにする", "ko": "Wi-Fi 껐다 켜기", "ru": "Выключить и включить Wi-Fi", "pt-BR": "Desligar e ligar o Wi-Fi", "tr": "Wi-Fi'yi kapatıp aç", "pl": "Wyłącz i włącz Wi-Fi", "uk": "Вимкнути й увімкнути Wi-Fi", "zh-Hant": "關閉後重新開啟 Wi-Fi",
    },
    "Flush DNS": {
        "hu": "DNS gyorsítótár ürítése", "es": "Vaciar la caché DNS", "fr": "Vider le cache DNS", "de": "DNS-Cache leeren", "zh-Hans": "清除 DNS 缓存", "it": "Svuota la cache DNS", "ja": "DNS キャッシュを消去", "ko": "DNS 캐시 비우기", "ru": "Очистить кеш DNS", "pt-BR": "Limpar o cache DNS", "tr": "DNS önbelleğini temizle", "pl": "Wyczyść pamięć podręczną DNS", "uk": "Очистити кеш DNS", "zh-Hant": "清除 DNS 快取",
    },
    "Copy diagnostics": {
        "hu": "Diagnosztika másolása", "es": "Copiar diagnósticos", "fr": "Copier les diagnostics", "de": "Diagnoseinformationen kopieren", "zh-Hans": "复制诊断信息", "it": "Copia diagnostica", "ja": "診断情報をコピー", "ko": "진단 정보 복사", "ru": "Копировать диагностику", "pt-BR": "Copiar diagnóstico", "tr": "Tanı bilgilerini kopyala", "pl": "Kopiuj diagnostykę", "uk": "Копіювати діагностику", "zh-Hant": "複製診斷資訊",
    },
    "Opened Captive Network Assistant.": {
        "hu": "Megnyílt a Captive Network Assistant.", "es": "Se abrió el Asistente de red cautiva.", "fr": "Assistant de réseau captif ouvert.", "de": "Der Captive Network Assistant wurde geöffnet.", "zh-Hans": "已打开受限网络助理。", "it": "Assistente rete con captive portal aperto.", "ja": "キャプティブネットワークアシスタントを開きました。", "ko": "캡티브 네트워크 지원을 열었습니다.", "ru": "Открыт помощник для сетей с авторизацией.", "pt-BR": "O Assistente de Rede Cativa foi aberto.", "tr": "Captive Network Assistant açıldı.", "pl": "Otwarto Asystenta sieci z portalem logowania.", "uk": "Відкрито помічник мережі з авторизацією.", "zh-Hant": "已開啟受限網路輔助程式。",
    },
    "Opened captive.apple.com in your browser.": {
        "hu": "Megnyílt a captive.apple.com a böngészőjében.", "es": "Se abrió captive.apple.com en tu navegador.", "fr": "captive.apple.com a été ouvert dans votre navigateur.", "de": "captive.apple.com wurde in deinem Browser geöffnet.", "zh-Hans": "已在浏览器中打开 captive.apple.com。", "it": "captive.apple.com è stato aperto nel browser.", "ja": "ブラウザで captive.apple.com を開きました。", "ko": "브라우저에서 captive.apple.com을 열었습니다.", "ru": "captive.apple.com открыт в вашем браузере.", "pt-BR": "captive.apple.com foi aberto no navegador.", "tr": "captive.apple.com tarayıcınızda açıldı.", "pl": "Otworzono captive.apple.com w przeglądarce.", "uk": "captive.apple.com відкрито у вашому браузері.", "zh-Hant": "已在瀏覽器中開啟 captive.apple.com。",
    },
    "Couldn't reach the Wi-Fi interface.": {
        "hu": "Nem sikerült elérni a Wi-Fi-csatolót.", "es": "No se pudo acceder a la interfaz Wi-Fi.", "fr": "Impossible d’accéder à l’interface Wi-Fi.", "de": "Die WLAN-Schnittstelle konnte nicht erreicht werden.", "zh-Hans": "无法访问 Wi-Fi 接口。", "it": "Impossibile raggiungere l’interfaccia Wi-Fi.", "ja": "Wi-Fi インターフェイスにアクセスできませんでした。", "ko": "Wi-Fi 인터페이스에 연결할 수 없습니다.", "ru": "Не удалось получить доступ к интерфейсу Wi-Fi.", "pt-BR": "Não foi possível acessar a interface Wi-Fi.", "tr": "Wi-Fi arayüzüne ulaşılamadı.", "pl": "Nie można było uzyskać dostępu do interfejsu Wi-Fi.", "uk": "Не вдалося отримати доступ до інтерфейсу Wi-Fi.", "zh-Hant": "無法存取 Wi-Fi 介面。",
    },
    "Wi-Fi was turned off and back on.": {
        "hu": "A Wi-Fi ki-, majd bekapcsolt.", "es": "El Wi-Fi se apagó y se volvió a encender.", "fr": "Le Wi-Fi a été désactivé puis réactivé.", "de": "WLAN wurde aus- und wieder eingeschaltet.", "zh-Hans": "Wi-Fi 已关闭并重新打开。", "it": "Il Wi-Fi è stato spento e riacceso.", "ja": "Wi-Fi をオフにしてからオンにしました。", "ko": "Wi-Fi를 껐다가 다시 켰습니다.", "ru": "Wi-Fi был выключен и снова включён.", "pt-BR": "O Wi-Fi foi desligado e ligado novamente.", "tr": "Wi-Fi kapatılıp yeniden açıldı.", "pl": "Wi-Fi zostało wyłączone i ponownie włączone.", "uk": "Wi-Fi було вимкнено та знову ввімкнено.", "zh-Hant": "Wi-Fi 已關閉並重新開啟。",
    },
    "Wi-Fi was turned off but could not be turned back on. Use Control Center.": {
        "hu": "A Wi-Fi kikapcsolt, de nem sikerült újra bekapcsolni. Használja a Vezérlőközpontot.", "es": "El Wi-Fi se apagó, pero no se pudo volver a encender. Usa el Centro de control.", "fr": "Le Wi-Fi a été désactivé, mais n’a pas pu être réactivé. Utilisez le Centre de contrôle.", "de": "WLAN wurde ausgeschaltet, konnte aber nicht wieder eingeschaltet werden. Verwende das Kontrollzentrum.", "zh-Hans": "Wi-Fi 已关闭，但无法重新打开。请使用控制中心。", "it": "Il Wi-Fi è stato spento ma non è stato possibile riaccenderlo. Usa il Centro di Controllo.", "ja": "Wi-Fi はオフになりましたが、再びオンにできませんでした。コントロールセンターを使ってください。", "ko": "Wi-Fi가 꺼졌지만 다시 켤 수 없습니다. 제어 센터를 사용하세요.", "ru": "Wi-Fi был выключен, но включить его снова не удалось. Воспользуйтесь Пунктом управления.", "pt-BR": "O Wi-Fi foi desligado, mas não foi possível ligá-lo novamente. Use a Central de Controle.", "tr": "Wi-Fi kapatıldı ancak yeniden açılamadı. Denetim Merkezi’ni kullanın.", "pl": "Wi-Fi zostało wyłączone, ale nie można było włączyć go ponownie. Użyj Centrum sterowania.", "uk": "Wi-Fi було вимкнено, але не вдалося ввімкнути його знову. Скористайтеся Центром керування.", "zh-Hant": "Wi-Fi 已關閉，但無法重新開啟。請使用控制中心。",
    },
    "Couldn't toggle Wi-Fi from here. The command is on the clipboard.": {
        "hu": "Innen nem sikerült átváltani a Wi-Fit. A parancs a vágólapon van.", "es": "No se pudo cambiar el Wi-Fi desde aquí. El comando está en el portapapeles.", "fr": "Impossible de basculer le Wi-Fi depuis ici. La commande est dans le presse-papiers.", "de": "WLAN konnte von hier aus nicht umgeschaltet werden. Der Befehl befindet sich in der Zwischenablage.", "zh-Hans": "无法从这里切换 Wi-Fi。命令已复制到剪贴板。", "it": "Non è stato possibile attivare o disattivare il Wi-Fi da qui. Il comando è negli appunti.", "ja": "ここから Wi-Fi を切り替えられませんでした。コマンドはクリップボードにあります。", "ko": "여기에서 Wi-Fi를 전환할 수 없습니다. 명령어가 클립보드에 있습니다.", "ru": "Не удалось переключить Wi-Fi отсюда. Команда находится в буфере обмена.", "pt-BR": "Não foi possível alternar o Wi-Fi por aqui. O comando está na área de transferência.", "tr": "Wi-Fi buradan açılıp kapatılamadı. Komut panoda.", "pl": "Nie udało się przełączyć Wi-Fi stąd. Polecenie jest w schowku.", "uk": "Не вдалося перемкнути Wi-Fi звідси. Команда є в буфері обміну.", "zh-Hant": "無法從這裡切換 Wi-Fi。指令已複製到剪貼簿。",
    },
    "DNS cache flushed.": {
        "hu": "A DNS-gyorsítótár kiürítve.", "es": "Se vació la caché DNS.", "fr": "Le cache DNS a été vidé.", "de": "Der DNS-Cache wurde geleert.", "zh-Hans": "DNS 缓存已清除。", "it": "La cache DNS è stata svuotata.", "ja": "DNS キャッシュを消去しました。", "ko": "DNS 캐시를 비웠습니다.", "ru": "Кеш DNS очищен.", "pt-BR": "O cache DNS foi limpo.", "tr": "DNS önbelleği temizlendi.", "pl": "Pamięć podręczna DNS została wyczyszczona.", "uk": "Кеш DNS очищено.", "zh-Hant": "DNS 快取已清除。",
    },
    "The flush didn't land. The command is on the clipboard.": {
        "hu": "Az ürítés nem sikerült. A parancs a vágólapon van.", "es": "No se pudo vaciar la caché. El comando está en el portapapeles.", "fr": "L’opération de vidage a échoué. La commande est dans le presse-papiers.", "de": "Das Leeren ist fehlgeschlagen. Der Befehl befindet sich in der Zwischenablage.", "zh-Hans": "清除操作未成功。命令已复制到剪贴板。", "it": "Lo svuotamento non è riuscito. Il comando è negli appunti.", "ja": "消去に失敗しました。コマンドはクリップボードにあります。", "ko": "캐시를 비우지 못했습니다. 명령어가 클립보드에 있습니다.", "ru": "Очистить кеш не удалось. Команда находится в буфере обмена.", "pt-BR": "A limpeza não foi concluída. O comando está na área de transferência.", "tr": "Temizleme gerçekleşmedi. Komut panoda.", "pl": "Czyszczenie się nie powiodło. Polecenie jest w schowku.", "uk": "Очищення не вдалося. Команда є в буфері обміну.", "zh-Hant": "清除未成功。指令已複製到剪貼簿。",
    },
    "The helper isn't installed or is still updating, so the flush command is on the clipboard.": {
        "hu": "A segéd nincs telepítve, vagy még frissül, ezért az ürítési parancs a vágólapon van.", "es": "El asistente no está instalado o todavía se está actualizando, así que el comando para vaciar la caché está en el portapapeles.", "fr": "L’assistant n’est pas installé ou se met encore à jour, donc la commande de vidage est dans le presse-papiers.", "de": "Der Hilfsdienst ist nicht installiert oder wird noch aktualisiert. Deshalb befindet sich der Befehl zum Leeren in der Zwischenablage.", "zh-Hans": "助理未安装或仍在更新，因此清除命令已复制到剪贴板。", "it": "L’assistente non è installato o si sta ancora aggiornando, quindi il comando per svuotare la cache è negli appunti.", "ja": "ヘルパーがインストールされていないか、まだ更新中です。消去コマンドはクリップボードにあります。", "ko": "도우미가 설치되지 않았거나 아직 업데이트 중이므로, 캐시 비우기 명령어가 클립보드에 있습니다.", "ru": "Помощник не установлен или ещё обновляется, поэтому команда очистки находится в буфере обмена.", "pt-BR": "O assistente não está instalado ou ainda está sendo atualizado, então o comando de limpeza está na área de transferência.", "tr": "Yardımcı yüklü değil veya hâlâ güncelleniyor; bu yüzden temizleme komutu panoda.", "pl": "Narzędzie pomocnicze nie jest zainstalowane albo nadal się aktualizuje, więc polecenie czyszczenia jest w schowku.", "uk": "Помічник не встановлено або він ще оновлюється, тому команда очищення є в буфері обміну.", "zh-Hant": "輔助程式尚未安裝或仍在更新，因此清除指令已複製到剪貼簿。",
    },
}
