# -*- coding: utf-8 -*-
# KeepressoCore localized strings: English source -> {lang: translation}.
# Product/technical terms kept verbatim: Keepresso, Mac, macOS, Wi-Fi, VPN,
# Bluetooth, SSH, VNC, FileVault, MyAgens, GitHub, AWDL, AirDrop, Handoff.

CORE = {
    # --- Trigger / rule labels ---
    "On AC power": {"hu": "Hálózati tápon", "es": "Con corriente CA", "fr": "Sur secteur", "de": "Am Netzstrom", "zh-Hans": "接通电源时"},
    "On battery": {"hu": "Akkumulátorról", "es": "Con batería", "fr": "Sur batterie", "de": "Im Akkubetrieb", "zh-Hans": "使用电池时"},
    "Charging": {"hu": "Töltés alatt", "es": "Cargando", "fr": "En charge", "de": "Wird geladen", "zh-Hans": "正在充电"},
    "External display connected": {"hu": "Külső kijelző csatlakoztatva", "es": "Pantalla externa conectada", "fr": "Écran externe connecté", "de": "Externes Display verbunden", "zh-Hans": "已连接外接显示器"},
    "is running": {"hu": "fut", "es": "en ejecución", "fr": "en cours d’exécution", "de": "wird ausgeführt", "zh-Hans": "正在运行"},
    "is frontmost": {"hu": "előtérben van", "es": "en primer plano", "fr": "au premier plan", "de": "im Vordergrund", "zh-Hans": "位于最前"},
    "Audio playing": {"hu": "Hang lejátszása", "es": "Reproduciendo audio", "fr": "Lecture audio en cours", "de": "Audiowiedergabe", "zh-Hans": "正在播放音频"},
    "VPN connected": {"hu": "VPN csatlakoztatva", "es": "VPN conectada", "fr": "VPN connecté", "de": "VPN verbunden", "zh-Hans": "已连接 VPN"},
    "Calendar event in progress": {"hu": "Naptáresemény folyamatban", "es": "Evento de calendario en curso", "fr": "Événement de calendrier en cours", "de": "Kalenderereignis läuft", "zh-Hans": "日历事件进行中"},
    "Playing a game": {"hu": "Játék folyamatban", "es": "Jugando", "fr": "Jeu en cours", "de": "Ein Spiel läuft", "zh-Hans": "正在玩游戏"},
    "AI agent working": {"hu": "AI-ügynök dolgozik", "es": "Agente de IA trabajando", "fr": "Agent IA au travail", "de": "KI-Agent arbeitet", "zh-Hans": "AI 代理工作中"},
    "Camera in use": {"hu": "Kamera használatban", "es": "Cámara en uso", "fr": "Caméra utilisée", "de": "Kamera in Benutzung", "zh-Hans": "摄像头使用中"},
    "Microphone in use": {"hu": "Mikrofon használatban", "es": "Micrófono en uso", "fr": "Micro utilisé", "de": "Mikrofon in Benutzung", "zh-Hans": "麦克风使用中"},
    "On Wi-Fi “%@”": {"hu": "A(z) „%@” Wi-Fi hálózaton", "es": "En la red Wi-Fi «%@»", "fr": "Sur le Wi-Fi « %@ »", "de": "Im WLAN „%@“", "zh-Hans": "在 Wi-Fi “%@” 上"},
    "Process “%@” running": {"hu": "A(z) „%@” folyamat fut", "es": "Proceso «%@» en ejecución", "fr": "Processus « %@ » en cours", "de": "Prozess „%@“ läuft", "zh-Hans": "进程 “%@” 正在运行"},
    "Volume “%@” mounted": {"hu": "A(z) „%@” kötet csatolva", "es": "Volumen «%@» montado", "fr": "Volume « %@ » monté", "de": "Volume „%@“ aktiviert", "zh-Hans": "已装载宗卷 “%@”"},
    "Bluetooth “%@” connected": {"hu": "„%@” Bluetooth-eszköz csatlakoztatva", "es": "Bluetooth «%@» conectado", "fr": "Bluetooth « %@ » connecté", "de": "Bluetooth „%@“ verbunden", "zh-Hans": "已连接蓝牙 “%@”"},
    "Downloading in “%@”": {"hu": "Letöltés a(z) „%@” mappában", "es": "Descargando en «%@»", "fr": "Téléchargement dans « %@ »", "de": "Download in „%@“", "zh-Hans": "正在 “%@” 中下载"},
    "CPU above %d%%": {"hu": "CPU %d%% felett", "es": "CPU por encima del %d%%", "fr": "Processeur au-dessus de %d%%", "de": "CPU über %d%%", "zh-Hans": "CPU 高于 %d%%"},
    "Network above %@": {"hu": "Hálózat %@ felett", "es": "Red por encima de %@", "fr": "Réseau au-dessus de %@", "de": "Netzwerk über %@", "zh-Hans": "网络高于 %@"},
    "App %@": {"hu": "%@ alkalmazás", "es": "App %@", "fr": "App %@", "de": "App %@", "zh-Hans": "App %@"},

    # --- Time window ---
    "Every day": {"hu": "Minden nap", "es": "Todos los días", "fr": "Tous les jours", "de": "Täglich", "zh-Hans": "每天"},
    "Weekdays": {"hu": "Hétköznap", "es": "Días laborables", "fr": "En semaine", "de": "Wochentags", "zh-Hans": "工作日"},
    "Weekends": {"hu": "Hétvégén", "es": "Fines de semana", "fr": "Le week-end", "de": "Am Wochenende", "zh-Hans": "周末"},

    # --- Session end action ---
    "Do nothing": {"hu": "Ne tegyen semmit", "es": "No hacer nada", "fr": "Ne rien faire", "de": "Nichts tun", "zh-Hans": "不执行任何操作"},
    "Sleep the display": {"hu": "Kijelző altatása", "es": "Suspender la pantalla", "fr": "Éteindre l’écran", "de": "Display in Ruhezustand", "zh-Hans": "使显示器进入睡眠"},
    "Start the screen saver": {"hu": "Képernyővédő indítása", "es": "Iniciar el salvapantallas", "fr": "Lancer l’économiseur d’écran", "de": "Bildschirmschoner starten", "zh-Hans": "启动屏幕保护程序"},

    # --- Built-in preset names ---
    "AI Agent": {"hu": "AI-ügynök", "es": "Agente de IA", "fr": "Agent IA", "de": "KI-Agent", "zh-Hans": "AI 代理"},
    "AI Agent Working": {"hu": "AI-ügynök dolgozik", "es": "Agente de IA trabajando", "fr": "Agent IA au travail", "de": "KI-Agent arbeitet", "zh-Hans": "AI 代理工作中"},
    "On AC Power": {"hu": "Hálózati tápon", "es": "Con corriente CA", "fr": "Sur secteur", "de": "Am Netzstrom", "zh-Hans": "接通电源"},
    "External Display Connected": {"hu": "Külső kijelző csatlakoztatva", "es": "Pantalla externa conectada", "fr": "Écran externe connecté", "de": "Externes Display verbunden", "zh-Hans": "已连接外接显示器"},
    "Remote Session (SSH)": {"hu": "Távoli munkamenet (SSH)", "es": "Sesión remota (SSH)", "fr": "Session distante (SSH)", "de": "Remote-Sitzung (SSH)", "zh-Hans": "远程会话 (SSH)"},
    "Backup Running": {"hu": "Biztonsági mentés fut", "es": "Copia de seguridad en curso", "fr": "Sauvegarde en cours", "de": "Backup läuft", "zh-Hans": "备份进行中"},
    "Media Render": {"hu": "Médiarenderelés", "es": "Renderizado multimedia", "fr": "Rendu multimédia", "de": "Medien-Rendering", "zh-Hans": "媒体渲染"},
    "Meetings": {"hu": "Értekezletek", "es": "Reuniones", "fr": "Réunions", "de": "Meetings", "zh-Hans": "会议"},
    "Cloud Gaming": {"hu": "Felhőalapú játék", "es": "Juego en la nube", "fr": "Cloud gaming", "de": "Cloud-Gaming", "zh-Hans": "云游戏"},
    "Remote Control": {"hu": "Távvezérlés", "es": "Control remoto", "fr": "Contrôle à distance", "de": "Fernsteuerung", "zh-Hans": "远程控制"},

    # --- Headless readiness (Setup screen) ---
    "Remote Login (SSH)": {"hu": "Távoli bejelentkezés (SSH)", "es": "Inicio de sesión remoto (SSH)", "fr": "Connexion à distance (SSH)", "de": "Entfernte Anmeldung (SSH)", "zh-Hans": "远程登录 (SSH)"},
    "Remote Login is on, so you can reach this Mac over SSH.": {"hu": "A távoli bejelentkezés be van kapcsolva, így SSH-n keresztül eléri ezt a Macet.", "es": "El inicio de sesión remoto está activado, por lo que puedes acceder a este Mac por SSH.", "fr": "La connexion à distance est activée, vous pouvez donc atteindre ce Mac via SSH.", "de": "Die entfernte Anmeldung ist aktiviert, du kannst diesen Mac also per SSH erreichen.", "zh-Hans": "远程登录已开启，因此你可以通过 SSH 访问这台 Mac。"},
    "Remote Login is off. You might want to enable it for SSH access to a headless Mac.": {"hu": "A távoli bejelentkezés ki van kapcsolva. Érdemes lehet bekapcsolni egy monitor nélküli Mac SSH-eléréséhez.", "es": "El inicio de sesión remoto está desactivado. Quizá quieras activarlo para acceder por SSH a un Mac sin pantalla.", "fr": "La connexion à distance est désactivée. Vous pouvez l’activer pour un accès SSH à un Mac sans écran.", "de": "Die entfernte Anmeldung ist deaktiviert. Für SSH-Zugriff auf einen Mac ohne Bildschirm solltest du sie aktivieren.", "zh-Hans": "远程登录已关闭。若要通过 SSH 访问无显示器的 Mac，建议开启它。"},
    "Couldn't confirm Remote Login. If you want SSH access, enable it in System Settings.": {"hu": "Nem sikerült megerősíteni a távoli bejelentkezést. Ha SSH-elérést szeretne, kapcsolja be a Rendszerbeállításokban.", "es": "No se pudo confirmar el inicio de sesión remoto. Si quieres acceso SSH, actívalo en Ajustes del Sistema.", "fr": "Impossible de confirmer la connexion à distance. Pour un accès SSH, activez-la dans Réglages Système.", "de": "Die entfernte Anmeldung konnte nicht bestätigt werden. Für SSH-Zugriff aktiviere sie in den Systemeinstellungen.", "zh-Hans": "无法确认远程登录状态。若需要 SSH 访问，请在“系统设置”中开启。"},
    "Screen Sharing": {"hu": "Képernyőmegosztás", "es": "Compartir pantalla", "fr": "Partage d’écran", "de": "Bildschirmfreigabe", "zh-Hans": "屏幕共享"},
    "Screen Sharing is on, so you can connect with the Screen Sharing app or VNC.": {"hu": "A képernyőmegosztás be van kapcsolva, így csatlakozhat a Képernyőmegosztás alkalmazással vagy VNC-vel.", "es": "Compartir pantalla está activado, por lo que puedes conectarte con la app Compartir Pantalla o VNC.", "fr": "Le partage d’écran est activé, vous pouvez donc vous connecter avec l’app Partage d’écran ou VNC.", "de": "Die Bildschirmfreigabe ist aktiviert, du kannst dich also mit der Bildschirmfreigabe-App oder VNC verbinden.", "zh-Hans": "屏幕共享已开启，因此你可以使用“屏幕共享”App 或 VNC 连接。"},
    "Screen Sharing is off. You might want to enable it to view a headless Mac's screen.": {"hu": "A képernyőmegosztás ki van kapcsolva. Érdemes lehet bekapcsolni egy monitor nélküli Mac képernyőjének megtekintéséhez.", "es": "Compartir pantalla está desactivado. Quizá quieras activarlo para ver la pantalla de un Mac sin monitor.", "fr": "Le partage d’écran est désactivé. Vous pouvez l’activer pour voir l’écran d’un Mac sans moniteur.", "de": "Die Bildschirmfreigabe ist deaktiviert. Um den Bildschirm eines Macs ohne Monitor zu sehen, solltest du sie aktivieren.", "zh-Hans": "屏幕共享已关闭。若要查看无显示器 Mac 的屏幕，建议开启它。"},
    "Couldn't confirm Screen Sharing. If you want remote viewing, enable it in System Settings.": {"hu": "Nem sikerült megerősíteni a képernyőmegosztást. Ha távoli megtekintést szeretne, kapcsolja be a Rendszerbeállításokban.", "es": "No se pudo confirmar Compartir pantalla. Si quieres visualización remota, actívalo en Ajustes del Sistema.", "fr": "Impossible de confirmer le partage d’écran. Pour la visualisation à distance, activez-le dans Réglages Système.", "de": "Die Bildschirmfreigabe konnte nicht bestätigt werden. Für Fernansicht aktiviere sie in den Systemeinstellungen.", "zh-Hans": "无法确认屏幕共享状态。若需要远程查看，请在“系统设置”中开启。"},
    "Enable it in System Settings ▸ General ▸ Sharing.": {"hu": "Kapcsolja be a Rendszerbeállítások ▸ Általános ▸ Megosztás menüben.", "es": "Actívalo en Ajustes del Sistema ▸ General ▸ Compartir.", "fr": "Activez-le dans Réglages Système ▸ Général ▸ Partage.", "de": "Aktiviere es in Systemeinstellungen ▸ Allgemein ▸ Freigabe.", "zh-Hans": "在“系统设置 ▸ 通用 ▸ 共享”中开启它。"},
    "Run AI agents on this Mac with MyAgens": {"hu": "Futtasson AI-ügynököket ezen a Macen a MyAgens segítségével", "es": "Ejecuta agentes de IA en este Mac con MyAgens", "fr": "Exécutez des agents IA sur ce Mac avec MyAgens", "de": "Führe KI-Agenten auf diesem Mac mit MyAgens aus", "zh-Hans": "使用 MyAgens 在这台 Mac 上运行 AI 代理"},
    "MyAgens lets AI agents operate your Mac and help with your work, which is handy on an always-on machine you mostly reach remotely.": {"hu": "A MyAgens lehetővé teszi, hogy AI-ügynökök kezeljék a Macet és segítsenek a munkájában, ami hasznos egy folyamatosan bekapcsolt, többnyire távolról elért gépen.", "es": "MyAgens permite que agentes de IA manejen tu Mac y te ayuden con el trabajo, algo útil en una máquina siempre encendida a la que accedes sobre todo en remoto.", "fr": "MyAgens permet à des agents IA de piloter votre Mac et de vous aider dans votre travail, pratique sur une machine toujours allumée que vous atteignez surtout à distance.", "de": "Mit MyAgens können KI-Agenten deinen Mac bedienen und dir bei der Arbeit helfen, praktisch auf einem dauerhaft laufenden Rechner, den du meist per Fernzugriff nutzt.", "zh-Hans": "MyAgens 让 AI 代理操作你的 Mac 并协助工作，这对于一台常开、主要远程访问的机器很方便。"},
    "Learn more about MyAgens:": {"hu": "Tudjon meg többet a MyAgensről:", "es": "Más información sobre MyAgens:", "fr": "En savoir plus sur MyAgens :", "de": "Mehr über MyAgens erfahren:", "zh-Hans": "详细了解 MyAgens："},
    "GitHub": {"hu": "GitHub", "es": "GitHub", "fr": "GitHub", "de": "GitHub", "zh-Hans": "GitHub"},
    "Read more": {"hu": "Tovább", "es": "Leer más", "fr": "En savoir plus", "de": "Weiterlesen", "zh-Hans": "阅读更多"},
    "Wake for network access": {"hu": "Ébredés hálózati hozzáféréskor", "es": "Activar al acceder por red", "fr": "Réactivation pour l’accès réseau", "de": "Aktivieren bei Netzwerkzugriff", "zh-Hans": "网络访问时唤醒"},
    "The Mac wakes when accessed over the network.": {"hu": "A Mac felébred, ha a hálózaton keresztül elérik.", "es": "El Mac se activa cuando se accede a él por la red.", "fr": "Le Mac se réactive lorsqu’on y accède via le réseau.", "de": "Der Mac wacht auf, wenn über das Netzwerk auf ihn zugegriffen wird.", "zh-Hans": "通过网络访问时，Mac 会唤醒。"},
    "The Mac won't wake for network access, so remote logins may fail.": {"hu": "A Mac nem ébred fel hálózati hozzáféréskor, így a távoli bejelentkezések meghiúsulhatnak.", "es": "El Mac no se activará al acceder por red, por lo que los inicios de sesión remotos pueden fallar.", "fr": "Le Mac ne se réactivera pas pour l’accès réseau, les connexions à distance peuvent donc échouer.", "de": "Der Mac wacht bei Netzwerkzugriff nicht auf, entfernte Anmeldungen können daher fehlschlagen.", "zh-Hans": "Mac 不会因网络访问而唤醒，因此远程登录可能失败。"},
    "Couldn't read the power settings.": {"hu": "Nem sikerült beolvasni az energiabeállításokat.", "es": "No se pudieron leer los ajustes de energía.", "fr": "Impossible de lire les réglages d’énergie.", "de": "Die Energieeinstellungen konnten nicht gelesen werden.", "zh-Hans": "无法读取电源设置。"},
    "Enable “Wake for network access”.": {"hu": "Kapcsolja be az „Ébredés hálózati hozzáféréskor” beállítást.", "es": "Activa «Activar al acceder por red».", "fr": "Activez « Réactivation pour l’accès réseau ».", "de": "Aktiviere „Aktivieren bei Netzwerkzugriff“.", "zh-Hans": "开启“网络访问时唤醒”。"},
    "Restart after power failure": {"hu": "Újraindítás áramkimaradás után", "es": "Reiniciar tras un corte de energía", "fr": "Redémarrer après une coupure de courant", "de": "Neustart nach Stromausfall", "zh-Hans": "断电后重新启动"},
    "The Mac restarts automatically after a power failure.": {"hu": "A Mac áramkimaradás után automatikusan újraindul.", "es": "El Mac se reinicia automáticamente tras un corte de energía.", "fr": "Le Mac redémarre automatiquement après une coupure de courant.", "de": "Der Mac startet nach einem Stromausfall automatisch neu.", "zh-Hans": "断电后 Mac 会自动重新启动。"},
    "The Mac stays off after a power cut, so it won't come back headless.": {"hu": "A Mac áramkimaradás után kikapcsolva marad, így monitor nélkül nem tér vissza.", "es": "El Mac permanece apagado tras un corte de energía, así que no volverá por sí solo sin pantalla.", "fr": "Le Mac reste éteint après une coupure, il ne redémarrera donc pas seul sans écran.", "de": "Der Mac bleibt nach einem Stromausfall aus und kommt ohne Bildschirm nicht von selbst zurück.", "zh-Hans": "断电后 Mac 会保持关机，因此在无显示器时不会自行恢复。"},
    "Enable automatic restart after a power failure.": {"hu": "Kapcsolja be az automatikus újraindítást áramkimaradás után.", "es": "Activa el reinicio automático tras un corte de energía.", "fr": "Activez le redémarrage automatique après une coupure de courant.", "de": "Aktiviere den automatischen Neustart nach einem Stromausfall.", "zh-Hans": "开启断电后自动重新启动。"},
    "System sleep disabled": {"hu": "Rendszeraltatás kikapcsolva", "es": "Suspensión del sistema desactivada", "fr": "Veille du système désactivée", "de": "Systemruhezustand deaktiviert", "zh-Hans": "已停用系统睡眠"},
    "Idle system sleep is disabled, so the Mac stays reachable.": {"hu": "Az inaktív rendszeraltatás ki van kapcsolva, így a Mac elérhető marad.", "es": "La suspensión del sistema por inactividad está desactivada, por lo que el Mac sigue accesible.", "fr": "La veille du système en cas d’inactivité est désactivée, le Mac reste donc accessible.", "de": "Der Systemruhezustand bei Inaktivität ist deaktiviert, der Mac bleibt also erreichbar.", "zh-Hans": "已停用空闲时的系统睡眠，因此 Mac 保持可访问。"},
    "The Mac sleeps when idle; Keepresso prevents this while a session runs, but a global setting is safer headless.": {"hu": "A Mac inaktivitáskor elalszik; a Keepresso ezt megakadályozza munkamenet közben, de monitor nélkül biztonságosabb egy globális beállítás.", "es": "El Mac se suspende cuando está inactivo; Keepresso lo evita mientras hay una sesión, pero un ajuste global es más seguro sin pantalla.", "fr": "Le Mac se met en veille en cas d’inactivité ; Keepresso l’empêche pendant une session, mais un réglage global est plus sûr sans écran.", "de": "Der Mac geht bei Inaktivität in den Ruhezustand; Keepresso verhindert das während einer Sitzung, aber ohne Bildschirm ist eine globale Einstellung sicherer.", "zh-Hans": "Mac 空闲时会进入睡眠；Keepresso 会在会话期间阻止这一点，但对于无显示器使用，全局设置更稳妥。"},
    "Disable idle system sleep.": {"hu": "Kapcsolja ki az inaktív rendszeraltatást.", "es": "Desactiva la suspensión del sistema por inactividad.", "fr": "Désactivez la veille du système en cas d’inactivité.", "de": "Deaktiviere den Systemruhezustand bei Inaktivität.", "zh-Hans": "停用空闲时的系统睡眠。"},
    "FileVault disabled": {"hu": "FileVault kikapcsolva", "es": "FileVault desactivado", "fr": "FileVault désactivé", "de": "FileVault deaktiviert", "zh-Hans": "已停用 FileVault"},
    "FileVault is off, so the Mac can reboot unattended to the login window.": {"hu": "A FileVault ki van kapcsolva, így a Mac felügyelet nélkül újraindulhat a bejelentkezési ablakig.", "es": "FileVault está desactivado, por lo que el Mac puede reiniciarse sin supervisión hasta la ventana de inicio de sesión.", "fr": "FileVault est désactivé, le Mac peut donc redémarrer sans surveillance jusqu’à la fenêtre de connexion.", "de": "FileVault ist deaktiviert, der Mac kann also unbeaufsichtigt bis zum Anmeldefenster neu starten.", "zh-Hans": "FileVault 已关闭，因此 Mac 可在无人值守下重启到登录窗口。"},
    "FileVault is on, so a reboot blocks at the disk-unlock screen until someone types the password, defeating headless restart.": {"hu": "A FileVault be van kapcsolva, így az újraindítás megáll a lemezfeloldó képernyőnél, amíg valaki be nem írja a jelszót, ellehetetlenítve a monitor nélküli újraindítást.", "es": "FileVault está activado, así que un reinicio se detiene en la pantalla de desbloqueo del disco hasta que alguien escribe la contraseña, lo que impide el reinicio sin pantalla.", "fr": "FileVault est activé : un redémarrage se bloque à l’écran de déverrouillage du disque jusqu’à saisie du mot de passe, ce qui empêche un redémarrage sans écran.", "de": "FileVault ist aktiviert, ein Neustart bleibt daher am Entsperrbildschirm hängen, bis jemand das Passwort eingibt, was einen Neustart ohne Bildschirm verhindert.", "zh-Hans": "FileVault 已开启，因此重启会停在磁盘解锁界面，直到有人输入密码，这会导致无显示器重启失败。"},
    "Couldn't determine the FileVault status.": {"hu": "Nem sikerült megállapítani a FileVault állapotát.", "es": "No se pudo determinar el estado de FileVault.", "fr": "Impossible de déterminer l’état de FileVault.", "de": "Der FileVault-Status konnte nicht ermittelt werden.", "zh-Hans": "无法确定 FileVault 状态。"},
    "For an unattended Mac, consider turning FileVault off (weigh the security trade-off).": {"hu": "Felügyelet nélküli Mac esetén fontolja meg a FileVault kikapcsolását (mérlegelje a biztonsági kompromisszumot).", "es": "Para un Mac sin supervisión, considera desactivar FileVault (sopesa el compromiso de seguridad).", "fr": "Pour un Mac sans surveillance, envisagez de désactiver FileVault (pesez le compromis de sécurité).", "de": "Für einen unbeaufsichtigten Mac solltest du FileVault deaktivieren (den Sicherheitskompromiss abwägen).", "zh-Hans": "对于无人值守的 Mac，可考虑关闭 FileVault（请权衡安全性取舍）。"},
    "Automatic login": {"hu": "Automatikus bejelentkezés", "es": "Inicio de sesión automático", "fr": "Connexion automatique", "de": "Automatische Anmeldung", "zh-Hans": "自动登录"},
    "Automatic login is on (%@), so the Mac reaches the desktop after a reboot without a keyboard.": {"hu": "Az automatikus bejelentkezés be van kapcsolva (%@), így a Mac billentyűzet nélkül is eljut az asztalig újraindítás után.", "es": "El inicio de sesión automático está activado (%@), por lo que el Mac llega al escritorio tras reiniciar sin teclado.", "fr": "La connexion automatique est activée (%@), le Mac atteint donc le bureau après un redémarrage sans clavier.", "de": "Die automatische Anmeldung ist aktiviert (%@), der Mac erreicht nach einem Neustart also ohne Tastatur den Schreibtisch.", "zh-Hans": "自动登录已开启 (%@)，因此 Mac 重启后无需键盘即可进入桌面。"},
    "Automatic login is off. After a reboot the Mac waits at the login window for a password.": {"hu": "Az automatikus bejelentkezés ki van kapcsolva. Újraindítás után a Mac a bejelentkezési ablakban vár a jelszóra.", "es": "El inicio de sesión automático está desactivado. Tras reiniciar, el Mac espera la contraseña en la ventana de inicio de sesión.", "fr": "La connexion automatique est désactivée. Après un redémarrage, le Mac attend le mot de passe à la fenêtre de connexion.", "de": "Die automatische Anmeldung ist deaktiviert. Nach einem Neustart wartet der Mac am Anmeldefenster auf das Passwort.", "zh-Hans": "自动登录已关闭。重启后，Mac 会在登录窗口等待输入密码。"},
    "Turn on automatic login for this account.": {"hu": "Kapcsolja be az automatikus bejelentkezést ehhez a fiókhoz.", "es": "Activa el inicio de sesión automático para esta cuenta.", "fr": "Activez la connexion automatique pour ce compte.", "de": "Aktiviere die automatische Anmeldung für dieses Konto.", "zh-Hans": "为此账户开启自动登录。"},

    # --- Notifications ---
    "Keepresso stopped": {"hu": "A Keepresso leállt", "es": "Keepresso se detuvo", "fr": "Keepresso s’est arrêté", "de": "Keepresso wurde gestoppt", "zh-Hans": "Keepresso 已停止"},
    "Your keep-awake session has ended.": {"hu": "Az ébrentartási munkamenet véget ért.", "es": "Tu sesión para mantener despierto ha terminado.", "fr": "Votre session de maintien en éveil est terminée.", "de": "Deine Wachhalte-Sitzung ist beendet.", "zh-Hans": "你的保持唤醒会话已结束。"},
    "Keepresso stops soon": {"hu": "A Keepresso hamarosan leáll", "es": "Keepresso se detendrá pronto", "fr": "Keepresso s’arrête bientôt", "de": "Keepresso stoppt bald", "zh-Hans": "Keepresso 即将停止"},
    "Your keep-awake session ends in about %@.": {"hu": "Az ébrentartási munkamenet körülbelül %@ múlva véget ér.", "es": "Tu sesión para mantener despierto termina en unos %@.", "fr": "Votre session de maintien en éveil se termine dans environ %@.", "de": "Deine Wachhalte-Sitzung endet in etwa %@.", "zh-Hans": "你的保持唤醒会话将在约 %@ 后结束。"},
    "Paused on low battery": {"hu": "Szüneteltetve alacsony töltöttség miatt", "es": "En pausa por batería baja", "fr": "En pause : batterie faible", "de": "Wegen niedrigem Akku pausiert", "zh-Hans": "因电量低已暂停"},
    "Battery is at %d%%. Keepresso is letting the Mac sleep until you plug in to charge.": {"hu": "Az akkumulátor %d%%-on áll. A Keepresso hagyja elaludni a Macet, amíg nem csatlakoztatja töltőre.", "es": "La batería está al %d%%. Keepresso deja que el Mac se suspenda hasta que lo conectes a cargar.", "fr": "La batterie est à %d%%. Keepresso laisse le Mac se mettre en veille jusqu’à ce que vous le branchiez.", "de": "Der Akku ist bei %d%%. Keepresso lässt den Mac schlafen, bis du ihn zum Laden anschließt.", "zh-Hans": "电量为 %d%%。Keepresso 将让 Mac 进入睡眠，直到你接通电源充电。"},
    "Keepresso is still brewing": {"hu": "A Keepresso még főz", "es": "Keepresso sigue en marcha", "fr": "Keepresso continue de veiller", "de": "Keepresso brüht noch", "zh-Hans": "Keepresso 仍在运行"},
    "Your Mac is still awake. It's been %@.": {"hu": "A Mac még ébren van. Már %@ eltelt.", "es": "Tu Mac sigue despierto. Han pasado %@.", "fr": "Votre Mac est toujours éveillé. Cela fait %@.", "de": "Dein Mac ist noch wach. Es sind %@ vergangen.", "zh-Hans": "你的 Mac 仍处于唤醒状态，已持续 %@。"},
    "Your Mac has been kept awake for %@.": {"hu": "A Macet %@ ideje tartja ébren.", "es": "Tu Mac se ha mantenido despierto durante %@.", "fr": "Votre Mac est maintenu éveillé depuis %@.", "de": "Dein Mac wird seit %@ wach gehalten.", "zh-Hans": "你的 Mac 已保持唤醒 %@。"},

    # --- Decisions log reasons ---
    "Started manually": {"hu": "Kézzel elindítva", "es": "Iniciado manualmente", "fr": "Démarré manuellement", "de": "Manuell gestartet", "zh-Hans": "已手动启动"},
    "Restarted manually": {"hu": "Kézzel újraindítva", "es": "Reiniciado manualmente", "fr": "Redémarré manuellement", "de": "Manuell neu gestartet", "zh-Hans": "已手动重新启动"},
    "Started by a command": {"hu": "Paranccsal elindítva", "es": "Iniciado por un comando", "fr": "Démarré par une commande", "de": "Durch einen Befehl gestartet", "zh-Hans": "由命令启动"},
    "Restarted by a command": {"hu": "Paranccsal újraindítva", "es": "Reiniciado por un comando", "fr": "Redémarré par une commande", "de": "Durch einen Befehl neu gestartet", "zh-Hans": "由命令重新启动"},
    "Timed session ended": {"hu": "Időzített munkamenet véget ért", "es": "Sesión temporizada finalizada", "fr": "Session minutée terminée", "de": "Zeitgesteuerte Sitzung beendet", "zh-Hans": "定时会话已结束"},
    "Paused, battery below %d%%": {"hu": "Szüneteltetve, az akkumulátor %d%% alatt", "es": "En pausa, batería por debajo del %d%%", "fr": "En pause, batterie sous %d%%", "de": "Pausiert, Akku unter %d%%", "zh-Hans": "已暂停，电量低于 %d%%"},
    "Not started, battery below %d%%": {"hu": "Nem indult el, az akkumulátor %d%% alatt", "es": "No iniciado, batería por debajo del %d%%", "fr": "Non démarré, batterie sous %d%%", "de": "Nicht gestartet, Akku unter %d%%", "zh-Hans": "未启动，电量低于 %d%%"},
    "Stopped manually": {"hu": "Kézzel leállítva", "es": "Detenido manualmente", "fr": "Arrêté manuellement", "de": "Manuell gestoppt", "zh-Hans": "已手动停止"},
    "Stopped by a command": {"hu": "Paranccsal leállítva", "es": "Detenido por un comando", "fr": "Arrêté par une commande", "de": "Durch einen Befehl gestoppt", "zh-Hans": "由命令停止"},
    "Trigger conditions met": {"hu": "A triggerfeltételek teljesülnek", "es": "Condiciones de disparo cumplidas", "fr": "Conditions de déclenchement remplies", "de": "Auslöserbedingungen erfüllt", "zh-Hans": "触发条件已满足"},
    "Trigger conditions ended": {"hu": "A triggerfeltételek megszűntek", "es": "Condiciones de disparo finalizadas", "fr": "Conditions de déclenchement terminées", "de": "Auslöserbedingungen beendet", "zh-Hans": "触发条件已结束"},

    # --- Trigger-gated session reason + grace-period rule label ---
    "Triggers: %@": {"hu": "Triggerek: %@", "es": "Disparadores: %@", "fr": "Déclencheurs : %@", "de": "Auslöser: %@", "zh-Hans": "触发条件：%@"},
    "%@ (+%ds)": {"hu": "%@ (+%d mp)", "es": "%@ (+%d s)", "fr": "%@ (+%d s)", "de": "%@ (+%d s)", "zh-Hans": "%@（+%d 秒）"},

    # --- Helper / watchdog / sleep-setting errors ---
    "Couldn't create the watchdog flag file.": {"hu": "Nem sikerült létrehozni a figyelő jelzőfájlját.", "es": "No se pudo crear el archivo indicador del vigilante.", "fr": "Impossible de créer le fichier indicateur de la surveillance.", "de": "Die Kennungsdatei der Überwachung konnte nicht erstellt werden.", "zh-Hans": "无法创建看守标志文件。"},
    "Couldn't run the watchdog command.": {"hu": "Nem sikerült futtatni a figyelő parancsát.", "es": "No se pudo ejecutar el comando del vigilante.", "fr": "Impossible d’exécuter la commande de la surveillance.", "de": "Der Befehl der Überwachung konnte nicht ausgeführt werden.", "zh-Hans": "无法运行看守命令。"},
    "The watchdog couldn't be started.": {"hu": "A figyelőt nem sikerült elindítani.", "es": "No se pudo iniciar el vigilante.", "fr": "Impossible de démarrer la surveillance.", "de": "Die Überwachung konnte nicht gestartet werden.", "zh-Hans": "无法启动看守。"},
    "Couldn't create the sleep watchdog flag file.": {"hu": "Nem sikerült létrehozni az altatásfigyelő jelzőfájlját.", "es": "No se pudo crear el archivo indicador del vigilante de suspensión.", "fr": "Impossible de créer le fichier indicateur de la surveillance de veille.", "de": "Die Kennungsdatei der Ruhezustand-Überwachung konnte nicht erstellt werden.", "zh-Hans": "无法创建睡眠看守标志文件。"},
    "Couldn't run the sleep watchdog command.": {"hu": "Nem sikerült futtatni az altatásfigyelő parancsát.", "es": "No se pudo ejecutar el comando del vigilante de suspensión.", "fr": "Impossible d’exécuter la commande de la surveillance de veille.", "de": "Der Befehl der Ruhezustand-Überwachung konnte nicht ausgeführt werden.", "zh-Hans": "无法运行睡眠看守命令。"},
    "The sleep watchdog couldn't be started.": {"hu": "Az altatásfigyelőt nem sikerült elindítani.", "es": "No se pudo iniciar el vigilante de suspensión.", "fr": "Impossible de démarrer la surveillance de veille.", "de": "Die Ruhezustand-Überwachung konnte nicht gestartet werden.", "zh-Hans": "无法启动睡眠看守。"},
    "Couldn't run the sleep setting command.": {"hu": "Nem sikerült futtatni az altatásbeállítási parancsot.", "es": "No se pudo ejecutar el comando de ajuste de suspensión.", "fr": "Impossible d’exécuter la commande de réglage de veille.", "de": "Der Befehl für die Ruhezustand-Einstellung konnte nicht ausgeführt werden.", "zh-Hans": "无法运行睡眠设置命令。"},
    "The sleep setting couldn't be changed.": {"hu": "Az altatásbeállítást nem sikerült módosítani.", "es": "No se pudo cambiar el ajuste de suspensión.", "fr": "Impossible de modifier le réglage de veille.", "de": "Die Ruhezustand-Einstellung konnte nicht geändert werden.", "zh-Hans": "无法更改睡眠设置。"},
    "The Keepresso helper isn't responding.": {"hu": "A Keepresso segéd nem válaszol.", "es": "El asistente de Keepresso no responde.", "fr": "L’assistant Keepresso ne répond pas.", "de": "Der Keepresso-Hilfsdienst antwortet nicht.", "zh-Hans": "Keepresso 助理无响应。"},
    "The Keepresso helper couldn't change the setting.": {"hu": "A Keepresso segéd nem tudta módosítani a beállítást.", "es": "El asistente de Keepresso no pudo cambiar el ajuste.", "fr": "L’assistant Keepresso n’a pas pu modifier le réglage.", "de": "Der Keepresso-Hilfsdienst konnte die Einstellung nicht ändern.", "zh-Hans": "Keepresso 助理无法更改设置。"},

    # --- Experimental virtual display errors ---
    "Virtual displays aren't available on this macOS version.": {"hu": "A virtuális kijelzők nem érhetők el ezen a macOS-verzión.", "es": "Las pantallas virtuales no están disponibles en esta versión de macOS.", "fr": "Les écrans virtuels ne sont pas disponibles sur cette version de macOS.", "de": "Virtuelle Displays sind auf dieser macOS-Version nicht verfügbar.", "zh-Hans": "此 macOS 版本不支持虚拟显示器。"},
    "Couldn't create the virtual display.": {"hu": "Nem sikerült létrehozni a virtuális kijelzőt.", "es": "No se pudo crear la pantalla virtual.", "fr": "Impossible de créer l’écran virtuel.", "de": "Das virtuelle Display konnte nicht erstellt werden.", "zh-Hans": "无法创建虚拟显示器。"},

    # --- Diagnostics: power-assertion effect descriptions ---
    "Preventing system sleep": {"hu": "Megakadályozza a rendszer elalvását", "es": "Evitando la suspensión del sistema", "fr": "Empêche la veille du système", "de": "Verhindert den Systemruhezustand", "zh-Hans": "正在阻止系统睡眠"},
    "Preventing display sleep": {"hu": "Megakadályozza a kijelző elalvását", "es": "Evitando la suspensión de la pantalla", "fr": "Empêche la veille de l’écran", "de": "Verhindert den Display-Ruhezustand", "zh-Hans": "正在阻止显示器睡眠"},
    "Keeping disks awake": {"hu": "Ébren tartja a lemezeket", "es": "Manteniendo los discos activos", "fr": "Maintient les disques actifs", "de": "Hält die Festplatten aktiv", "zh-Hans": "正在让磁盘保持活动"},
    "Declaring the user active": {"hu": "Aktívnak nyilvánítja a felhasználót", "es": "Declarando al usuario como activo", "fr": "Déclare l’utilisateur actif", "de": "Erklärt den Benutzer als aktiv", "zh-Hans": "正在将用户声明为活动"},
    "Holding off idle sleep for a background task": {"hu": "Késlelteti az inaktív elalvást egy háttérfeladat miatt", "es": "Aplazando la suspensión por inactividad para una tarea en segundo plano", "fr": "Diffère la veille d’inactivité pour une tâche en arrière-plan", "de": "Verzögert den Ruhezustand bei Inaktivität für eine Hintergrundaufgabe", "zh-Hans": "正在为后台任务推迟空闲睡眠"},

    # --- Jitter-test result summary clauses (joined with ", ") ---
    "Not enough replies to measure.": {"hu": "Nincs elég válasz a méréshez.", "es": "No hay suficientes respuestas para medir.", "fr": "Pas assez de réponses pour mesurer.", "de": "Nicht genug Antworten zum Messen.", "zh-Hans": "回复不足，无法测量。"},
    "Baseline %d ms": {"hu": "alapérték %d ms", "es": "base %d ms", "fr": "référence %d ms", "de": "Basiswert %d ms", "zh-Hans": "基线 %d ms"},
    "%d spike up to %d ms": {"hu": "%d kiugrás %d ms-ig", "es": "%d pico de hasta %d ms", "fr": "%d pic jusqu’à %d ms", "de": "%d Ausschlag bis %d ms", "zh-Hans": "%d 次尖峰，最高 %d ms"},
    "%d spikes up to %d ms": {"hu": "%d kiugrás %d ms-ig", "es": "%d picos de hasta %d ms", "fr": "%d pics jusqu’à %d ms", "de": "%d Ausschläge bis %d ms", "zh-Hans": "%d 次尖峰，最高 %d ms"},
    "max %d ms": {"hu": "max. %d ms", "es": "máx. %d ms", "fr": "max %d ms", "de": "max. %d ms", "zh-Hans": "最高 %d ms"},
    "%d lost": {"hu": "%d elveszett", "es": "%d perdidas", "fr": "%d perdues", "de": "%d verloren", "zh-Hans": "%d 个丢失"},

    # --- Streaming readiness: Wired network check ---
    "Wired network": {"hu": "Vezetékes hálózat", "es": "Red por cable", "fr": "Réseau filaire", "de": "Kabelnetzwerk", "zh-Hans": "有线网络"},
    "Couldn't read the network interfaces.": {"hu": "Nem sikerült beolvasni a hálózati interfészeket.", "es": "No se pudieron leer las interfaces de red.", "fr": "Impossible de lire les interfaces réseau.", "de": "Die Netzwerkschnittstellen konnten nicht gelesen werden.", "zh-Hans": "无法读取网络接口。"},
    "Ethernet is connected (%@). A wired link sidesteps Wi-Fi jitter entirely, the most reliable fix.": {"hu": "Az Ethernet csatlakoztatva (%@). A vezetékes kapcsolat teljesen megkerüli a Wi-Fi jittert, ez a legmegbízhatóbb megoldás.", "es": "Ethernet está conectado (%@). Un enlace por cable evita por completo el jitter de Wi-Fi, la solución más fiable.", "fr": "Ethernet est connecté (%@). Une liaison filaire évite entièrement la gigue du Wi-Fi, la solution la plus fiable.", "de": "Ethernet ist verbunden (%@). Eine Kabelverbindung umgeht WLAN-Jitter vollständig, die zuverlässigste Lösung.", "zh-Hans": "已连接以太网 (%@)。有线连接可完全避开 Wi-Fi 抖动，是最可靠的解决办法。"},
    "An Ethernet adapter is available but no cable is connected.": {"hu": "Egy Ethernet-adapter elérhető, de nincs kábel csatlakoztatva.", "es": "Hay un adaptador Ethernet disponible, pero no hay ningún cable conectado.", "fr": "Un adaptateur Ethernet est disponible, mais aucun câble n’est connecté.", "de": "Ein Ethernet-Adapter ist verfügbar, aber es ist kein Kabel angeschlossen.", "zh-Hans": "有可用的以太网适配器，但未连接网线。"},
    "For gaming or streaming, a wired connection beats any Wi-Fi tuning.": {"hu": "Játékhoz vagy streameléshez a vezetékes kapcsolat felülmúl minden Wi-Fi-hangolást.", "es": "Para juegos o streaming, una conexión por cable supera cualquier ajuste de Wi-Fi.", "fr": "Pour le jeu ou le streaming, une connexion filaire surpasse tout réglage du Wi-Fi.", "de": "Für Gaming oder Streaming schlägt eine Kabelverbindung jede WLAN-Optimierung.", "zh-Hans": "对于游戏或串流，有线连接胜过任何 Wi-Fi 调优。"},
    "No wired network adapter found.": {"hu": "Nem található vezetékes hálózati adapter.", "es": "No se encontró ningún adaptador de red por cable.", "fr": "Aucun adaptateur réseau filaire trouvé.", "de": "Kein Kabelnetzwerk-Adapter gefunden.", "zh-Hans": "未找到有线网络适配器。"},
    "A USB-C or Thunderbolt Ethernet adapter sidesteps Wi-Fi jitter entirely.": {"hu": "Egy USB-C vagy Thunderbolt Ethernet-adapter teljesen megkerüli a Wi-Fi jittert.", "es": "Un adaptador Ethernet USB-C o Thunderbolt evita por completo el jitter de Wi-Fi.", "fr": "Un adaptateur Ethernet USB-C ou Thunderbolt évite entièrement la gigue du Wi-Fi.", "de": "Ein USB-C- oder Thunderbolt-Ethernet-Adapter umgeht WLAN-Jitter vollständig.", "zh-Hans": "USB-C 或 Thunderbolt 以太网适配器可完全避开 Wi-Fi 抖动。"},

    # --- Streaming readiness: Wi-Fi channel check ---
    # The "channel %d at %d MHz" / "channel %d" clauses are substituted into the
    # sentence keys below; the sentences carry the band prefix and grammar.
    "Wi-Fi channel": {"hu": "Wi-Fi csatorna", "es": "Canal de Wi-Fi", "fr": "Canal Wi-Fi", "de": "WLAN-Kanal", "zh-Hans": "Wi-Fi 信道"},
    "Not connected to Wi-Fi, or its details are unreadable.": {"hu": "Nincs Wi-Fi-kapcsolat, vagy a részletei nem olvashatók.", "es": "Sin conexión a Wi-Fi, o sus detalles no se pueden leer.", "fr": "Non connecté au Wi-Fi, ou ses détails sont illisibles.", "de": "Nicht mit dem WLAN verbunden, oder die Details sind nicht lesbar.", "zh-Hans": "未连接 Wi-Fi，或其详细信息无法读取。"},
    "If you game or stream over Wi-Fi, re-check while connected.": {"hu": "Ha Wi-Fin játszik vagy streamel, ellenőrizze újra csatlakoztatva.", "es": "Si juegas o transmites por Wi-Fi, vuelve a comprobarlo mientras estés conectado.", "fr": "Si vous jouez ou streamez en Wi-Fi, revérifiez une fois connecté.", "de": "Wenn du über WLAN spielst oder streamst, prüfe erneut, während du verbunden bist.", "zh-Hans": "如果你通过 Wi-Fi 游戏或串流，请在连接时重新检查。"},
    "channel %d at %d MHz": {"hu": "%d. csatorna, %d MHz", "es": "canal %d a %d MHz", "fr": "canal %d à %d MHz", "de": "Kanal %d bei %d MHz", "zh-Hans": "信道 %d，%d MHz"},
    "channel %d": {"hu": "%d. csatorna", "es": "canal %d", "fr": "canal %d", "de": "Kanal %d", "zh-Hans": "信道 %d"},
    "On 2.4 GHz (%@), the slowest band, where every AWDL hop costs the most.": {"hu": "2.4 GHz-en (%@), a leglassabb sávon, ahol minden AWDL-ugrás a legtöbbe kerül.", "es": "En 2.4 GHz (%@), la banda más lenta, donde cada salto de AWDL cuesta más.", "fr": "Sur 2.4 GHz (%@), la bande la plus lente, où chaque saut d’AWDL coûte le plus cher.", "de": "Auf 2.4 GHz (%@), dem langsamsten Band, wo jeder AWDL-Sprung am meisten kostet.", "zh-Hans": "在 2.4 GHz (%@) 上，这是最慢的频段，每次 AWDL 跳频代价最大。"},
    "Prefer a 5 GHz network on %@ at 80 MHz. If 2.4 GHz is unavoidable, set the router to channel 6, AWDL's 2.4 GHz social channel.": {"hu": "Válasszon inkább egy 5 GHz-es hálózatot a következőn: %@ (80 MHz). Ha a 2.4 GHz elkerülhetetlen, állítsa a routert a 6. csatornára, ez az AWDL 2.4 GHz-es közösségi csatornája.", "es": "Prefiere una red de 5 GHz en %@ a 80 MHz. Si no puedes evitar 2.4 GHz, configura el router en el canal 6, el canal social de AWDL en 2.4 GHz.", "fr": "Préférez un réseau 5 GHz sur %@ à 80 MHz. Si 2.4 GHz est inévitable, réglez le routeur sur le canal 6, le canal social d’AWDL en 2.4 GHz.", "de": "Bevorzuge ein 5-GHz-Netzwerk auf %@ bei 80 MHz. Wenn 2.4 GHz unvermeidbar ist, stelle den Router auf Kanal 6, den 2.4-GHz-Social-Channel von AWDL.", "zh-Hans": "优先选择 %@ 上的 5 GHz 网络（80 MHz）。如果无法避免 2.4 GHz，请将路由器设为 6 信道，即 AWDL 在 2.4 GHz 的社交信道。"},
    "On 6 GHz (%@). AWDL's social channels live on 2.4 and 5 GHz, so there's nothing to align here. If stutter persists, a 5 GHz network on %@ keeps AWDL's hops on-channel.": {"hu": "6 GHz-en (%@). Az AWDL közösségi csatornái a 2.4 és 5 GHz-en vannak, így itt nincs mit összehangolni. Ha az akadozás megmarad, egy 5 GHz-es hálózat a következőn: %@ a csatornán tartja az AWDL ugrásait.", "es": "En 6 GHz (%@). Los canales sociales de AWDL están en 2.4 y 5 GHz, así que aquí no hay nada que alinear. Si los tirones persisten, una red de 5 GHz en %@ mantiene los saltos de AWDL en canal.", "fr": "Sur 6 GHz (%@). Les canaux sociaux d’AWDL sont sur 2.4 et 5 GHz, il n’y a donc rien à aligner ici. Si les saccades persistent, un réseau 5 GHz sur %@ garde les sauts d’AWDL sur le canal.", "de": "Auf 6 GHz (%@). Die Social-Channels von AWDL liegen auf 2.4 und 5 GHz, hier gibt es also nichts auszurichten. Wenn das Ruckeln anhält, hält ein 5-GHz-Netzwerk auf %@ die Sprünge von AWDL auf dem Kanal.", "zh-Hans": "在 6 GHz (%@) 上。AWDL 的社交信道位于 2.4 和 5 GHz，因此这里没有需要对齐的。如果卡顿持续，%@ 上的 5 GHz 网络可让 AWDL 的跳频保持在同一信道。"},
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel.": {"hu": "%@, összehangolva az AWDL 5 GHz-es közösségi csatornájával, így az ugrásai a csatornán maradnak.", "es": "%@, alineado con el canal social de AWDL en 5 GHz, así que sus saltos se mantienen en canal.", "fr": "%@, aligné sur le canal social d’AWDL en 5 GHz, ses sauts restent donc sur le canal.", "de": "%@, ausgerichtet auf den 5-GHz-Social-Channel von AWDL, seine Sprünge bleiben also auf dem Kanal.", "zh-Hans": "%@，与 AWDL 的 5 GHz 社交信道对齐，因此其跳频保持在同一信道。"},
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel. Raising the router to 80 MHz width completes the alignment.": {"hu": "%@, összehangolva az AWDL 5 GHz-es közösségi csatornájával, így az ugrásai a csatornán maradnak. A router 80 MHz-es sávszélességre emelése teljessé teszi az összehangolást.", "es": "%@, alineado con el canal social de AWDL en 5 GHz, así que sus saltos se mantienen en canal. Subir el router a un ancho de 80 MHz completa la alineación.", "fr": "%@, aligné sur le canal social d’AWDL en 5 GHz, ses sauts restent donc sur le canal. Passer le routeur à une largeur de 80 MHz complète l’alignement.", "de": "%@, ausgerichtet auf den 5-GHz-Social-Channel von AWDL, seine Sprünge bleiben also auf dem Kanal. Den Router auf 80 MHz Breite anzuheben vervollständigt die Ausrichtung.", "zh-Hans": "%@，与 AWDL 的 5 GHz 社交信道对齐，因此其跳频保持在同一信道。将路由器提升到 80 MHz 带宽即可完成对齐。"},
    "On 5 GHz %@. AWDL's off-channel hops leave this channel roughly every second.": {"hu": "5 GHz-en, %@. Az AWDL csatornán kívüli ugrásai nagyjából másodpercenként elhagyják ezt a csatornát.", "es": "En 5 GHz, %@. Los saltos fuera de canal de AWDL abandonan este canal aproximadamente cada segundo.", "fr": "Sur 5 GHz, %@. Les sauts hors canal d’AWDL quittent ce canal environ chaque seconde.", "de": "Auf 5 GHz, %@. Die kanalfremden Sprünge von AWDL verlassen diesen Kanal etwa jede Sekunde.", "zh-Hans": "在 5 GHz 上，%@。AWDL 的离信道跳频大约每秒一次离开此信道。"},
    "Set the router to %@ at 80 MHz so AWDL's hops stay on-channel.": {"hu": "Állítsa a routert erre: %@ (80 MHz), hogy az AWDL ugrásai a csatornán maradjanak.", "es": "Configura el router en %@ a 80 MHz para que los saltos de AWDL se mantengan en canal.", "fr": "Réglez le routeur sur %@ à 80 MHz pour que les sauts d’AWDL restent sur le canal.", "de": "Stelle den Router auf %@ bei 80 MHz, damit die Sprünge von AWDL auf dem Kanal bleiben.", "zh-Hans": "将路由器设为 %@（80 MHz），让 AWDL 的跳频保持在同一信道。"},
    "channel 44 (the EU social channel) or 149 (the US and Canada social channel), whichever your region allows": {"hu": "44. csatorna (az EU közösségi csatornája) vagy 149. csatorna (az USA és Kanada közösségi csatornája), amelyiket a régiója engedi", "es": "el canal 44 (el canal social de la UE) o el 149 (el canal social de EE. UU. y Canadá), el que permita tu región", "fr": "le canal 44 (le canal social de l’UE) ou 149 (le canal social des États-Unis et du Canada), selon ce que votre région autorise", "de": "Kanal 44 (der EU-Social-Channel) oder 149 (der Social-Channel für die USA und Kanada), je nachdem, was deine Region erlaubt", "zh-Hans": "44 信道（欧盟社交信道）或 149 信道（美国和加拿大社交信道），以你所在地区允许的为准"},
    "channel 44, AWDL's 5 GHz social channel in the EU": {"hu": "44. csatorna, az AWDL 5 GHz-es közösségi csatornája az EU-ban", "es": "el canal 44, el canal social de AWDL en 5 GHz en la UE", "fr": "le canal 44, le canal social d’AWDL en 5 GHz dans l’UE", "de": "Kanal 44, der 5-GHz-Social-Channel von AWDL in der EU", "zh-Hans": "44 信道，AWDL 在欧盟的 5 GHz 社交信道"},
    "channel 149, AWDL's 5 GHz social channel where UNII-3 is allowed (the US, Canada, and most of the world)": {"hu": "149. csatorna, az AWDL 5 GHz-es közösségi csatornája ott, ahol a UNII-3 engedélyezett (az USA, Kanada és a világ nagy része)", "es": "el canal 149, el canal social de AWDL en 5 GHz donde se permite UNII-3 (EE. UU., Canadá y gran parte del mundo)", "fr": "le canal 149, le canal social d’AWDL en 5 GHz là où l’UNII-3 est autorisé (les États-Unis, le Canada et la majeure partie du monde)", "de": "Kanal 149, der 5-GHz-Social-Channel von AWDL dort, wo UNII-3 erlaubt ist (die USA, Kanada und der Großteil der Welt)", "zh-Hans": "149 信道，AWDL 在允许 UNII-3 的地区（美国、加拿大及世界大部分地区）的 5 GHz 社交信道"},

    # --- Streaming readiness: Bluetooth during play check ---
    "Bluetooth during play": {"hu": "Bluetooth játék közben", "es": "Bluetooth durante el juego", "fr": "Bluetooth pendant le jeu", "de": "Bluetooth beim Spielen", "zh-Hans": "游戏时的蓝牙"},
    "Bluetooth is on. It shares the radio chip with Wi-Fi, so heavy Bluetooth traffic (audio, controllers) can add its own blips.": {"hu": "A Bluetooth be van kapcsolva. A rádiócsipet megosztja a Wi-Fivel, így az erős Bluetooth-forgalom (hang, kontrollerek) saját apró kimaradásokat okozhat.", "es": "El Bluetooth está activado. Comparte el chip de radio con la Wi-Fi, así que un tráfico Bluetooth intenso (audio, mandos) puede añadir sus propios microcortes.", "fr": "Le Bluetooth est activé. Il partage la puce radio avec le Wi-Fi, donc un trafic Bluetooth intense (audio, manettes) peut ajouter ses propres micro-coupures.", "de": "Bluetooth ist an. Es teilt sich den Funkchip mit dem WLAN, daher kann starker Bluetooth-Verkehr (Audio, Controller) eigene kleine Aussetzer verursachen.", "zh-Hans": "蓝牙已开启。它与 Wi-Fi 共用无线芯片，因此繁重的蓝牙流量（音频、手柄）可能带来自己的瞬时卡顿。"},
    "Nothing to fix: just a variable to know about if stutter persists on a clean channel.": {"hu": "Nincs mit javítani: csak egy tényező, amiről érdemes tudni, ha az akadozás megmarad egy tiszta csatornán.", "es": "No hay nada que arreglar: solo es una variable a tener en cuenta si los tirones persisten en un canal limpio.", "fr": "Rien à corriger : juste un paramètre à connaître si les saccades persistent sur un canal propre.", "de": "Nichts zu beheben: nur ein Faktor, den man kennen sollte, falls das Ruckeln auf einem sauberen Kanal anhält.", "zh-Hans": "无需修复：只是一个在干净信道上仍出现卡顿时需要了解的因素。"},
    "Bluetooth is off, so it isn't competing with Wi-Fi for the radio.": {"hu": "A Bluetooth ki van kapcsolva, így nem verseng a Wi-Fivel a rádióért.", "es": "El Bluetooth está desactivado, así que no compite con la Wi-Fi por la radio.", "fr": "Le Bluetooth est désactivé, il ne concurrence donc pas le Wi-Fi pour la radio.", "de": "Bluetooth ist aus, es konkurriert also nicht mit dem WLAN um den Funk.", "zh-Hans": "蓝牙已关闭，因此不会与 Wi-Fi 争用无线电。"},
    "Couldn't read the Bluetooth radio state.": {"hu": "Nem sikerült beolvasni a Bluetooth-rádió állapotát.", "es": "No se pudo leer el estado de la radio Bluetooth.", "fr": "Impossible de lire l’état de la radio Bluetooth.", "de": "Der Zustand des Bluetooth-Funks konnte nicht gelesen werden.", "zh-Hans": "无法读取蓝牙无线电状态。"},

    # --- Streaming readiness: standing tips (Game Mode, cloud gaming, Location) ---
    "Game Mode": {"hu": "Játék mód", "es": "Modo Juego", "fr": "Mode Jeu", "de": "Spielemodus", "zh-Hans": "游戏模式"},
    "macOS turns on Game Mode by itself when a game runs full screen: the game gets CPU and GPU priority, and Bluetooth controllers and audio get faster sampling. If the game-controller icon doesn't appear in the menu bar while playing, put the game into full screen.": {"hu": "A macOS magától bekapcsolja a Játék módot, amikor egy játék teljes képernyőn fut: a játék CPU- és GPU-prioritást kap, a Bluetooth-kontrollerek és a hang pedig gyorsabb mintavételezést. Ha a játékvezérlő ikon nem jelenik meg a menüsorban játék közben, tegye a játékot teljes képernyőre.", "es": "macOS activa el Modo Juego por sí solo cuando un juego se ejecuta a pantalla completa: el juego obtiene prioridad de CPU y GPU, y los mandos Bluetooth y el audio obtienen un muestreo más rápido. Si el icono del mando no aparece en la barra de menús mientras juegas, pon el juego a pantalla completa.", "fr": "macOS active le Mode Jeu de lui-même quand un jeu s’exécute en plein écran : le jeu obtient la priorité CPU et GPU, et les manettes Bluetooth et l’audio bénéficient d’un échantillonnage plus rapide. Si l’icône de manette n’apparaît pas dans la barre des menus pendant le jeu, passez le jeu en plein écran.", "de": "macOS aktiviert den Spielemodus von selbst, wenn ein Spiel im Vollbild läuft: Das Spiel erhält CPU- und GPU-Priorität, und Bluetooth-Controller und Audio erhalten eine schnellere Abtastung. Wenn das Controller-Symbol beim Spielen nicht in der Menüleiste erscheint, versetze das Spiel in den Vollbildmodus.", "zh-Hans": "当游戏全屏运行时，macOS 会自行开启游戏模式：游戏获得 CPU 和 GPU 优先级，蓝牙手柄和音频获得更快的采样。如果游戏时菜单栏中未出现游戏手柄图标，请将游戏切换到全屏。"},
    "How Game Mode works:": {"hu": "Hogyan működik a Játék mód:", "es": "Cómo funciona el Modo Juego:", "fr": "Comment fonctionne le Mode Jeu :", "de": "So funktioniert der Spielemodus:", "zh-Hans": "游戏模式的工作原理："},
    "Learn more": {"hu": "Tudjon meg többet", "es": "Más información", "fr": "En savoir plus", "de": "Mehr erfahren", "zh-Hans": "了解更多"},
    "Cloud gaming in the browser": {"hu": "Felhőalapú játék a böngészőben", "es": "Juego en la nube en el navegador", "fr": "Cloud gaming dans le navigateur", "de": "Cloud-Gaming im Browser", "zh-Hans": "浏览器中的云游戏"},
    "Xbox Cloud Gaming and the web versions of GeForce NOW run in a browser tab, so there's no app for the gaming condition to spot. The “Audio playing” condition covers them: game sound keeps the session brewing.": {"hu": "Az Xbox Cloud Gaming és a GeForce NOW webes verziói egy böngészőlapon futnak, így nincs alkalmazás, amit a játékfeltétel észlelhetne. A „Hang lejátszása” feltétel lefedi őket: a játék hangja főzésben tartja a munkamenetet.", "es": "Xbox Cloud Gaming y las versiones web de GeForce NOW se ejecutan en una pestaña del navegador, así que no hay ninguna app que la condición de juego pueda detectar. La condición «Reproduciendo audio» los cubre: el sonido del juego mantiene la sesión en marcha.", "fr": "Xbox Cloud Gaming et les versions web de GeForce NOW s’exécutent dans un onglet de navigateur, il n’y a donc aucune app que la condition de jeu puisse repérer. La condition « Lecture audio en cours » les couvre : le son du jeu maintient la session en infusion.", "de": "Xbox Cloud Gaming und die Webversionen von GeForce NOW laufen in einem Browser-Tab, es gibt also keine App, die die Gaming-Bedingung erkennen könnte. Die Bedingung „Audiowiedergabe“ deckt sie ab: Der Spielton hält die Sitzung am Brühen.", "zh-Hans": "Xbox Cloud Gaming 和 GeForce NOW 的网页版在浏览器标签页中运行，因此没有可供游戏条件识别的 App。“正在播放音频”条件涵盖了它们：游戏声音会让会话保持运行。"},
    "Add it under Preferences ▸ Triggers ▸ Add ▸ Apps & Activity ▸ Media.": {"hu": "Adja hozzá a Beállítások ▸ Triggerek ▸ Hozzáadás ▸ Alkalmazások és tevékenység ▸ Média menüben.", "es": "Añádela en Ajustes ▸ Disparadores ▸ Añadir ▸ Apps y actividad ▸ Multimedia.", "fr": "Ajoutez-la dans Réglages ▸ Déclencheurs ▸ Ajouter ▸ Apps et activité ▸ Multimédia.", "de": "Füge sie unter Einstellungen ▸ Auslöser ▸ Hinzufügen ▸ Apps und Aktivität ▸ Medien hinzu.", "zh-Hans": "在“偏好设置 ▸ 触发条件 ▸ 添加 ▸ App 与活动 ▸ 媒体”中添加它。"},
    "Location Services and Wi-Fi scans": {"hu": "Helymeghatározó szolgáltatások és Wi-Fi-keresések", "es": "Localización y búsquedas de Wi-Fi", "fr": "Service de localisation et recherches Wi-Fi", "de": "Ortungsdienste und WLAN-Suchen", "zh-Hans": "定位服务与 Wi-Fi 扫描"},
    "Location Services triggers independent Wi-Fi scans, another source of occasional blips. Keepresso itself uses Location to read Wi-Fi network names for triggers, so weigh that before turning anything off.": {"hu": "A Helymeghatározó szolgáltatások független Wi-Fi-kereséseket indítanak, ami újabb forrása az alkalmi apró kimaradásoknak. A Keepresso maga is használja a helymeghatározást a Wi-Fi hálózatok nevének beolvasásához a triggerekhez, ezért mérlegelje ezt, mielőtt bármit kikapcsol.", "es": "La Localización desencadena búsquedas de Wi-Fi independientes, otra fuente de microcortes ocasionales. Keepresso usa la Localización para leer los nombres de las redes Wi-Fi de tus disparadores, así que sopésalo antes de desactivar nada.", "fr": "Le Service de localisation déclenche des recherches Wi-Fi indépendantes, une autre source de micro-coupures occasionnelles. Keepresso utilise lui-même la localisation pour lire les noms des réseaux Wi-Fi de vos déclencheurs, pesez donc cela avant de désactiver quoi que ce soit.", "de": "Die Ortungsdienste lösen eigenständige WLAN-Suchen aus, eine weitere Quelle gelegentlicher Aussetzer. Keepresso selbst nutzt die Ortung, um WLAN-Namen für deine Auslöser zu lesen, wäge das also ab, bevor du etwas ausschaltest.", "zh-Hans": "定位服务会触发独立的 Wi-Fi 扫描，这是偶发瞬时卡顿的另一个来源。Keepresso 本身也使用定位来读取 Wi-Fi 网络名称以用于触发条件，因此在关闭任何设置前请权衡。"},
    "Review which apps use Location:": {"hu": "Nézze át, mely alkalmazások használják a helymeghatározást:", "es": "Revisa qué apps usan la Localización:", "fr": "Vérifiez quelles apps utilisent la localisation :", "de": "Prüfe, welche Apps die Ortung verwenden:", "zh-Hans": "查看哪些 App 使用定位："},
    "Why streams stutter once a second": {"hu": "Miért akadoznak a streamek másodpercenként", "es": "Por qué los streams se entrecortan una vez por segundo", "fr": "Pourquoi les streams saccadent une fois par seconde", "de": "Warum Streams jede Sekunde ruckeln", "zh-Hans": "为何串流每秒卡顿一次"},
    "The Wi-Fi radio hops off-channel for AWDL (AirDrop, Handoff, Sidecar, Continuity) roughly every second, which shows up as 50-100 ms ping spikes. The jitter test reproduces the diagnosis; the AWDL watchdog is the session-scoped fix.": {"hu": "A Wi-Fi rádió körülbelül másodpercenként lekapcsol a csatornáról az AWDL (AirDrop, Handoff, Sidecar, Continuity) miatt, ami 50–100 ms-os ping-kiugrásokként jelentkezik. A jitterteszt reprodukálja a diagnózist; az AWDL-figyelő a munkamenetre szabott megoldás.", "es": "La radio Wi-Fi salta fuera de canal para AWDL (AirDrop, Handoff, Sidecar, Continuity) aproximadamente cada segundo, lo que se manifiesta como picos de ping de 50-100 ms. La prueba de jitter reproduce el diagnóstico; el vigilante de AWDL es la solución acotada a la sesión.", "fr": "La radio Wi-Fi saute hors canal pour AWDL (AirDrop, Handoff, Sidecar, Continuity) environ chaque seconde, ce qui se traduit par des pics de ping de 50 à 100 ms. Le test de gigue reproduit le diagnostic ; la surveillance AWDL est le correctif limité à la session.", "de": "Der WLAN-Funk wechselt für AWDL (AirDrop, Handoff, Sidecar, Continuity) etwa jede Sekunde vom Kanal weg, was sich als Ping-Spitzen von 50 bis 100 ms zeigt. Der Jitter-Test reproduziert die Diagnose; die AWDL-Überwachung ist die auf die Sitzung begrenzte Lösung.", "zh-Hans": "Wi-Fi 无线电大约每秒一次为 AWDL（AirDrop、Handoff、随航、连续互通）切换到其他信道，这表现为 50-100 ms 的 ping 尖峰。抖动测试可重现该诊断；AWDL 看守是限于本次会话的修复方法。"},
    "The full story:": {"hu": "A teljes történet:", "es": "La historia completa:", "fr": "L’histoire complète :", "de": "Die ganze Geschichte:", "zh-Hans": "完整说明："},
}


# --- Agent hooks (Claude Code connection) ---
_AGENT_HOOKS = {
    "running command": {"hu": "parancsot futtat", "es": "ejecutando un comando", "fr": "exécute une commande", "de": "führt Befehl aus", "zh-Hans": "正在运行命令"},
    "editing": {"hu": "szerkeszt", "es": "editando", "fr": "édite", "de": "bearbeitet", "zh-Hans": "正在编辑"},
    "reading": {"hu": "olvas", "es": "leyendo", "fr": "lit", "de": "liest", "zh-Hans": "正在读取"},
    "searching": {"hu": "keres", "es": "buscando", "fr": "recherche", "de": "sucht", "zh-Hans": "正在搜索"},
    "running subagent": {"hu": "alügynököt futtat", "es": "ejecutando un subagente", "fr": "exécute un sous-agent", "de": "führt Subagenten aus", "zh-Hans": "正在运行子代理"},
    "browsing": {"hu": "böngészik", "es": "navegando", "fr": "navigue sur le web", "de": "durchsucht das Web", "zh-Hans": "正在浏览网页"},
    "using %@": {"hu": "%@ használata", "es": "usando %@", "fr": "utilise %@", "de": "verwendet %@", "zh-Hans": "正在使用 %@"},
    "waiting for approval": {"hu": "jóváhagyásra vár", "es": "esperando aprobación", "fr": "attend une approbation", "de": "wartet auf Freigabe", "zh-Hans": "等待批准"},
    "waiting": {"hu": "várakozik", "es": "esperando", "fr": "en attente", "de": "wartet", "zh-Hans": "等待中"},
    "terminal": {"hu": "terminál", "es": "terminal", "fr": "terminal", "de": "Terminal", "zh-Hans": "终端"},
    "Claude app": {"hu": "Claude app", "es": "app Claude", "fr": "app Claude", "de": "Claude-App", "zh-Hans": "Claude 应用"},
    "IDE": {"hu": "IDE", "es": "IDE", "fr": "IDE", "de": "IDE", "zh-Hans": "IDE"},
}
CORE.update(_AGENT_HOOKS)
