# -*- coding: utf-8 -*-
"""Granular menu presentation strings, with every shipping translation."""

_LANGS = ['hu', 'es', 'fr', 'de', 'zh-Hans', 'it', 'ja', 'ko', 'ru', 'pt-BR', 'tr', 'pl', 'uk', 'zh-Hant']
_ROWS = '''
Accent color|Kiemelőszín|Color de acento|Couleur d’accentuation|Akzentfarbe|强调色|Colore di accento|アクセントカラー|강조 색상|Акцентный цвет|Cor de destaque|Vurgu rengi|Kolor akcentu|Акцентний колір|強調色
Clear style|Letisztult stílus|Estilo discreto|Style épuré|Schlichter Stil|简洁样式|Stile essenziale|シンプルなスタイル|간결한 스타일|Сдержанный стиль|Estilo discreto|Sade stil|Stonowany styl|Стриманий стиль|簡潔樣式
Control style|Vezérlők stílusa|Estilo de los controles|Style des commandes|Stil der Bedienelemente|控件样式|Stile dei controlli|操作のスタイル|컨트롤 스타일|Стиль элементов управления|Estilo dos controles|Kontrol stili|Styl elementów sterujących|Стиль елементів керування|控制項樣式
AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL|AWDL
Agent rows: %d|Ügynöksorok: %d|Filas de agentes: %d|Lignes d’agents : %d|Agentenzeilen: %d|智能体行数：%d|Righe agenti: %d|エージェント行数: %d|에이전트 행: %d|Строки агентов: %d|Linhas de agentes: %d|Aracı satırları: %d|Wiersze agentów: %d|Рядки агентів: %d|智能體列數：%d
All visible controls|Minden látható vezérlő|Todos los controles visibles|Toutes les commandes visibles|Alle sichtbaren Bedienelemente|所有可见控件|Tutti i controlli visibili|表示するすべての操作|표시되는 모든 컨트롤|Все видимые элементы управления|Todos os controles visíveis|Tüm görünür kontroller|Wszystkie widoczne elementy|Усі видимі елементи керування|所有可見控制項
Allow screen saver after|Képernyővédő engedélyezése ennyi idő után|Permitir salvapantallas después de|Autoriser l’économiseur après|Bildschirmschoner zulassen nach|允许屏幕保护程序的等待时间|Consenti salvaschermo dopo|スクリーンセーバーを許可するまで|화면 보호기 허용 대기 시간|Разрешить заставку через|Permitir protetor de tela após|Ekran koruyucuya izin verme süresi|Zezwól na wygaszacz po|Дозволити заставку через|允許螢幕保護程式的等待時間
App shortcuts|Alkalmazás-parancsok|Accesos de la app|Raccourcis de l’app|App-Verknüpfungen|应用快捷入口|Scorciatoie dell’app|アプリのショートカット|앱 바로가기|Ярлыки приложения|Atalhos do app|Uygulama kısayolları|Skróty aplikacji|Ярлики програми|App 快捷入口
Automation leases|Automatizálási foglalások|Concesiones de automatización|Baux d’automatisation|Automatisierungs-Leases|自动化租约|Lease di automazione|自動化リース|자동화 임대|Аренды автоматизации|Concessões de automação|Otomasyon kiraları|Dzierżawy automatyzacji|Оренди автоматизації|自動化租約
Balanced|Kiegyensúlyozott|Equilibrado|Équilibré|Ausgewogen|均衡|Bilanciato|バランス|균형|Сбалансированный|Equilibrado|Dengeli|Zrównoważony|Збалансований|均衡
Card|Kártya|Tarjeta|Carte|Karte|卡片|Scheda|カード|카드|Карточка|Cartão|Kart|Karta|Картка|卡片
Comfortable|Kényelmes|Cómodo|Confortable|Komfortabel|舒适|Comodo|標準|보통|Удобный|Confortável|Rahat|Wygodne|Зручний|舒適
Compact|Kompakt|Compacto|Compact|Kompakt|紧凑|Compatto|コンパクト|좁게|Компактный|Compacto|Kompakt|Zwarte|Компактний|緊湊
Compact menu|Kompakt menü|Menú compacto|Menu compact|Kompaktes Menü|精简菜单|Menu compatto|コンパクトメニュー|간소화 메뉴|Компактное меню|Menu compacto|Kompakt menü|Zwarte menu|Компактне меню|精簡選單
Controls|Vezérlők|Controles|Commandes|Bedienelemente|控件|Controlli|操作|컨트롤|Элементы управления|Controles|Kontroller|Elementy sterujące|Елементи керування|控制項
Customize Menu|Menü testreszabása|Personalizar menú|Personnaliser le menu|Menü anpassen|自定义菜单|Personalizza menu|メニューをカスタマイズ|메뉴 사용자화|Настроить меню|Personalizar menu|Menüyü özelleştir|Dostosuj menu|Налаштувати меню|自訂選單
Customize Menu…|Menü testreszabása…|Personalizar menú…|Personnaliser le menu…|Menü anpassen…|自定义菜单…|Personalizza menu…|メニューをカスタマイズ…|메뉴 사용자화…|Настроить меню…|Personalizar menu…|Menüyü özelleştir…|Dostosuj menu…|Налаштувати меню…|自訂選單…
Detailed|Részletes|Detallado|Détaillé|Detailliert|详细|Dettagliato|詳細|자세히|Подробный|Detalhado|Ayrıntılı|Szczegółowy|Докладний|詳細
Details|Részletek|Detalles|Détails|Details|详情|Dettagli|詳細|세부 정보|Подробности|Detalhes|Ayrıntılar|Szczegóły|Подробиці|詳細資訊
Dim after idle|Sötétítés tétlenség után|Atenuar tras inactividad|Atténuer après inactivité|Nach Inaktivität dimmen|空闲后调暗|Attenua dopo inattività|操作がないときに暗くする|유휴 상태 후 어둡게|Затемнять при бездействии|Escurecer após inatividade|Boştayken karart|Przyciemnij po bezczynności|Приглушувати після бездіяльності|閒置後調暗
Elapsed time|Eltelt idő|Tiempo transcurrido|Temps écoulé|Verstrichene Zeit|已用时间|Tempo trascorso|経過時間|경과 시간|Прошедшее время|Tempo decorrido|Geçen süre|Upływ czasu|Минулий час|經過時間
End action|Befejezéskori művelet|Acción al finalizar|Action de fin|Abschlussaktion|结束操作|Azione finale|終了時の操作|종료 동작|Действие при завершении|Ação ao finalizar|Bitiş eylemi|Działanie po zakończeniu|Дія після завершення|結束動作
End time|Befejezés ideje|Hora de finalización|Heure de fin|Endzeit|结束时间|Ora di fine|終了時刻|종료 시간|Время завершения|Horário de término|Bitiş saati|Czas zakończenia|Час завершення|結束時間
Fans|Ventilátorok|Ventiladores|Ventilateurs|Lüfter|风扇|Ventole|ファン|팬|Вентиляторы|Ventoinhas|Fanlar|Wentylatory|Вентилятори|風扇
Find controls|Vezérlők keresése|Buscar controles|Rechercher des commandes|Bedienelemente suchen|查找控件|Cerca controlli|操作を検索|컨트롤 찾기|Найти элементы управления|Buscar controles|Kontrol ara|Znajdź elementy sterujące|Знайти елементи керування|尋找控制項
First sections|Első szakaszok|Primeras secciones|Premières sections|Erste Abschnitte|前几个分组|Prime sezioni|先頭のセクション|첫 번째 섹션|Первые разделы|Primeiras seções|İlk bölümler|Pierwsze sekcje|Перші розділи|前幾個群組
Follow countdown setting|Visszaszámlálás beállításának követése|Usar ajuste de cuenta atrás|Suivre le réglage du compte à rebours|Countdown-Einstellung verwenden|遵循倒计时设置|Segui impostazione del conto alla rovescia|カウントダウン設定に従う|카운트다운 설정 따르기|Использовать настройку обратного отсчёта|Seguir ajuste da contagem regressiva|Geri sayım ayarını kullan|Zgodnie z ustawieniem odliczania|За налаштуванням відліку|依照倒數計時設定
Icon only|Csak ikon|Solo icono|Icône seule|Nur Symbol|仅图标|Solo icona|アイコンのみ|아이콘만|Только значок|Somente ícone|Yalnızca simge|Tylko ikona|Лише значок|僅圖示
Keep in Show less|Megtartás a „Kevesebb megjelenítése” nézetben|Mantener en Mostrar menos|Garder dans Afficher moins|Bei Weniger anzeigen behalten|在“显示更少”中保留|Mantieni in Mostra meno|「詳細を隠す」でも残す|“간략히 보기”에도 유지|Оставить в режиме «Показать меньше»|Manter em Mostrar menos|Daha az göster görünümünde tut|Zachowaj w widoku Pokaż mniej|Залишити в режимі «Показати менше»|在「顯示較少」中保留
Minimal|Minimális|Mínimo|Minimal|Minimal|极简|Minimale|最小限|최소|Минимальный|Mínimo|En az|Minimalny|Мінімальний|極簡
Move to section|Áthelyezés szakaszba|Mover a sección|Déplacer vers une section|In Abschnitt verschieben|移至分组|Sposta nella sezione|セクションに移動|섹션으로 이동|Переместить в раздел|Mover para seção|Bölüme taşı|Przenieś do sekcji|Перемістити до розділу|移至群組
No matching triggers|Nincs teljesülő feltétel|Ninguna condición coincide|Aucune condition remplie|Keine erfüllten Bedingungen|没有满足的触发条件|Nessuna condizione soddisfatta|一致する条件はありません|일치하는 트리거 없음|Нет выполненных условий|Nenhuma condição atendida|Eşleşen tetikleyici yok|Brak spełnionych warunków|Немає виконаних умов|沒有符合的觸發條件
Only show matching triggers|Csak a teljesülő feltételek mutatása|Mostrar solo condiciones coincidentes|Afficher uniquement les conditions remplies|Nur erfüllte Bedingungen anzeigen|仅显示满足的触发条件|Mostra solo condizioni soddisfatte|一致する条件のみ表示|일치하는 트리거만 표시|Показывать только выполненные условия|Mostrar apenas condições atendidas|Yalnızca eşleşen tetikleyicileri göster|Pokaż tylko spełnione warunki|Показувати лише виконані умови|僅顯示符合的觸發條件
Other apps|Más alkalmazások|Otras apps|Autres apps|Andere Apps|其他应用|Altre app|ほかのアプリ|다른 앱|Другие приложения|Outros apps|Diğer uygulamalar|Inne aplikacje|Інші програми|其他 App
Panel width: %d pt|Panel szélessége: %d pt|Ancho del panel: %d pt|Largeur du panneau : %d pt|Panelbreite: %d pt|面板宽度：%d pt|Larghezza pannello: %d pt|パネル幅: %d pt|패널 너비: %d pt|Ширина панели: %d пт|Largura do painel: %d pt|Panel genişliği: %d pt|Szerokość panelu: %d pt|Ширина панелі: %d пт|面板寬度：%d pt
Pause / Resume Triggers|Triggerek szüneteltetése / folytatása|Pausar / Reanudar disparadores|Suspendre / Reprendre les déclencheurs|Auslöser pausieren / fortsetzen|暂停 / 恢复触发条件|Sospendi / Riprendi attivatori|トリガーを一時停止 / 再開|트리거 일시 정지 / 재개|Приостановить / Возобновить триггеры|Pausar / Retomar gatilhos|Tetikleyicileri duraklat / sürdür|Wstrzymaj / Wznów wyzwalacze|Призупинити / Відновити тригери|暫停 / 繼續觸發條件
Pin controls to keep them visible in Show less.|Rögzítsd a vezérlőket, hogy a „Kevesebb megjelenítése” nézetben is láthatók maradjanak.|Fija controles para mantenerlos visibles en Mostrar menos.|Épinglez les commandes pour les garder visibles dans Afficher moins.|Bedienelemente anheften, damit sie bei Weniger anzeigen sichtbar bleiben.|固定控件，使其在“显示更少”中保持可见。|Fissa i controlli per mantenerli visibili in Mostra meno.|操作をピン留めすると「詳細を隠す」でも表示されます。|컨트롤을 고정하면 “간략히 보기”에도 표시됩니다.|Закрепите элементы, чтобы они оставались видны в режиме «Показать меньше».|Fixe controles para mantê-los visíveis em Mostrar menos.|Daha az göster görünümünde görünür kalmaları için kontrolleri sabitleyin.|Przypnij elementy, aby były widoczne w widoku Pokaż mniej.|Закріпіть елементи, щоб вони залишалися видимими в режимі «Показати менше».|釘選控制項，使其在「顯示較少」中保持可見。
Pinned controls|Rögzített vezérlők|Controles fijados|Commandes épinglées|Angeheftete Bedienelemente|固定的控件|Controlli fissati|ピン留めした操作|고정한 컨트롤|Закреплённые элементы|Controles fixados|Sabitlenmiş kontroller|Przypięte elementy|Закріплені елементи|釘選的控制項
Remaining time|Hátralévő idő|Tiempo restante|Temps restant|Verbleibende Zeit|剩余时间|Tempo rimanente|残り時間|남은 시간|Оставшееся время|Tempo restante|Kalan süre|Pozostały czas|Час, що залишився|剩餘時間
Reset customization|Testreszabás alaphelyzetbe|Restablecer personalización|Réinitialiser la personnalisation|Anpassung zurücksetzen|重置自定义|Reimposta personalizzazione|カスタマイズをリセット|사용자화 초기화|Сбросить настройку меню|Redefinir personalização|Özelleştirmeyi sıfırla|Resetuj dostosowanie|Скинути налаштування меню|重置自訂
Sections: %d|Szakaszok: %d|Secciones: %d|Sections : %d|Abschnitte: %d|分组数：%d|Sezioni: %d|セクション数: %d|섹션: %d|Разделы: %d|Seções: %d|Bölümler: %d|Sekcje: %d|Розділи: %d|群組數：%d
Show agent details|Ügynökrészletek mutatása|Mostrar detalles de agentes|Afficher les détails des agents|Agentendetails anzeigen|显示智能体详情|Mostra dettagli agenti|エージェントの詳細を表示|에이전트 세부 정보 표시|Показывать подробности агентов|Mostrar detalhes dos agentes|Aracı ayrıntılarını göster|Pokaż szczegóły agentów|Показувати подробиці агентів|顯示智能體詳細資訊
Show cup icon|Csészeikon mutatása|Mostrar icono de taza|Afficher l’icône de tasse|Tassensymbol anzeigen|显示咖啡杯图标|Mostra icona della tazza|カップアイコンを表示|컵 아이콘 표시|Показывать значок чашки|Mostrar ícone da xícara|Fincan simgesini göster|Pokaż ikonę filiżanki|Показувати значок чашки|顯示咖啡杯圖示
Show more / Show less|Több megjelenítése / Kevesebb megjelenítése|Mostrar más / Mostrar menos|Afficher plus / Afficher moins|Mehr anzeigen / Weniger anzeigen|显示更多 / 显示更少|Mostra altro / Mostra meno|詳細を表示 / 詳細を隠す|더 보기 / 간략히 보기|Показать больше / Показать меньше|Mostrar mais / Mostrar menos|Daha fazla göster / Daha az göster|Pokaż więcej / Pokaż mniej|Показати більше / Показати менше|顯示更多 / 顯示較少
Show section dividers|Szakaszelválasztók mutatása|Mostrar separadores de sección|Afficher les séparateurs de section|Abschnittstrenner anzeigen|显示分组分隔线|Mostra separatori di sezione|セクションの区切りを表示|섹션 구분선 표시|Показывать разделители разделов|Mostrar divisórias de seção|Bölüm ayırıcılarını göster|Pokaż separatory sekcji|Показувати роздільники розділів|顯示群組分隔線
Show section headings|Szakaszcímek mutatása|Mostrar títulos de sección|Afficher les titres de section|Abschnittstitel anzeigen|显示分组标题|Mostra titoli delle sezioni|セクションの見出しを表示|섹션 제목 표시|Показывать заголовки разделов|Mostrar títulos de seção|Bölüm başlıklarını göster|Pokaż nagłówki sekcji|Показувати заголовки розділів|顯示群組標題
Show, hide, pin, reorder, or move any control to another section.|Bármely vezérlőt megjelenítheted, elrejtheted, rögzítheted, átrendezheted vagy másik szakaszba helyezheted.|Muestra, oculta, fija, reordena o mueve cualquier control a otra sección.|Affichez, masquez, épinglez, réordonnez ou déplacez une commande vers une autre section.|Jedes Bedienelement lässt sich anzeigen, ausblenden, anheften, umordnen oder in einen anderen Abschnitt verschieben.|显示、隐藏、固定、排序或将任何控件移至其他分组。|Mostra, nascondi, fissa, riordina o sposta qualsiasi controllo in un’altra sezione.|操作を表示、非表示、ピン留め、並べ替え、別のセクションへの移動ができます。|모든 컨트롤을 표시, 숨기기, 고정, 재정렬하거나 다른 섹션으로 옮길 수 있습니다.|Показывайте, скрывайте, закрепляйте, меняйте порядок или переносите элементы в другой раздел.|Mostre, oculte, fixe, reordene ou mova qualquer controle para outra seção.|Her kontrolü gösterin, gizleyin, sabitleyin, yeniden sıralayın veya başka bölüme taşıyın.|Pokazuj, ukrywaj, przypinaj, zmieniaj kolejność lub przenoś elementy do innej sekcji.|Показуйте, приховуйте, закріплюйте, змінюйте порядок або переносьте елементи до іншого розділу.|顯示、隱藏、釘選、排序或將任何控制項移至其他群組。
Spacing|Térköz|Espaciado|Espacement|Abstände|间距|Spaziatura|間隔|간격|Интервалы|Espaçamento|Aralık|Odstępy|Відступи|間距
Spacious|Tágas|Amplio|Aéré|Großzügig|宽松|Ampio|広め|넓게|Просторный|Amplo|Geniş|Przestronne|Просторий|寬鬆
Start collapsed|Induláskor összecsukva|Iniciar contraído|Réduit au départ|Anfangs eingeklappt|初始收起|Avvia compresso|最初は折りたたむ|처음에 접기|Изначально свёрнут|Iniciar recolhido|Daraltılmış başlat|Początkowo zwinięte|Спочатку згорнуто|初始收合
Starting layout|Kezdő elrendezés|Diseño inicial|Disposition de départ|Ausgangslayout|起始布局|Layout iniziale|基本レイアウト|시작 레이아웃|Начальная компоновка|Layout inicial|Başlangıç düzeni|Układ początkowy|Початкове компонування|起始版面配置
Status|Állapot|Estado|État|Status|状态|Stato|状態|상태|Состояние|Estado|Durum|Stan|Стан|狀態
Status explanation|Állapot magyarázata|Explicación del estado|Explication de l’état|Statuserklärung|状态说明|Spiegazione dello stato|状態の説明|상태 설명|Пояснение состояния|Explicação do estado|Durum açıklaması|Opis stanu|Пояснення стану|狀態說明
Status header|Állapotfejléc|Cabecera de estado|En-tête d’état|Statuskopf|状态标题|Intestazione dello stato|状態の見出し|상태 머리글|Заголовок состояния|Cabeçalho de estado|Durum başlığı|Nagłówek stanu|Заголовок стану|狀態標題
Text only|Csak szöveg|Solo texto|Texte seul|Nur Text|仅文本|Solo testo|テキストのみ|텍스트만|Только текст|Somente texto|Yalnızca metin|Tylko tekst|Лише текст|僅文字
These choices change the menu, while your feature settings stay the same.|Ezek a beállítások a menüt módosítják, a funkciók beállításai megmaradnak.|Estas opciones cambian el menú y mantienen los ajustes de las funciones.|Ces choix modifient le menu et conservent les réglages des fonctions.|Diese Optionen ändern das Menü. Ihre Funktionseinstellungen bleiben erhalten.|这些选项更改菜单，功能设置保持不变。|Queste scelte cambiano il menu e mantengono le impostazioni delle funzioni.|メニューの表示を変更します。機能の設定は保持されます。|이 선택 사항은 메뉴를 변경하며 기능 설정은 유지됩니다.|Эти параметры меняют меню, сохраняя настройки функций.|Estas opções alteram o menu e mantêm os ajustes dos recursos.|Bu seçimler menüyü değiştirir; özellik ayarlarınız aynı kalır.|Te opcje zmieniają menu, zachowując ustawienia funkcji.|Ці параметри змінюють меню, зберігаючи налаштування функцій.|這些選項更改選單，功能設定保持不變。
Trigger conditions|Aktiválási feltételek|Condiciones de activación|Conditions d’activation|Auslösebedingungen|触发条件|Condizioni di attivazione|起動条件|트리거 조건|Условия активации|Condições de ativação|Tetikleyici koşulları|Warunki aktywacji|Умови активації|觸發條件
Trigger rows: %d|Feltételsorok: %d|Filas de condiciones: %d|Lignes de conditions : %d|Bedingungszeilen: %d|触发条件行数：%d|Righe condizioni: %d|条件の行数: %d|트리거 행: %d|Строки условий: %d|Linhas de condições: %d|Tetikleyici satırları: %d|Wiersze warunków: %d|Рядки умов: %d|觸發條件列數：%d
Trigger summary|Feltételek összegzése|Resumen de condiciones|Résumé des conditions|Bedingungsübersicht|触发条件摘要|Riepilogo condizioni|条件の概要|트리거 요약|Сводка условий|Resumo das condições|Tetikleyici özeti|Podsumowanie warunków|Зведення умов|觸發條件摘要
Use standard menu|Szokásos menü használata|Usar menú estándar|Utiliser le menu standard|Standardmenü verwenden|使用标准菜单|Usa menu standard|標準メニューを使用|기본 메뉴 사용|Использовать стандартное меню|Usar menu padrão|Standart menüyü kullan|Użyj standardowego menu|Використати стандартне меню|使用標準選單
Warnings stay visible. Preferences and Quit are also available by right-clicking the cup.|A figyelmeztetések láthatók maradnak. A Beállítások és a Kilépés a csészére jobb gombbal kattintva is elérhető.|Los avisos siguen visibles. Ajustes y Salir también están disponibles al hacer clic derecho en la taza.|Les avertissements restent visibles. Réglages et Quitter sont aussi accessibles par un clic droit sur la tasse.|Warnungen bleiben sichtbar. Einstellungen und Beenden sind auch per Rechtsklick auf die Tasse erreichbar.|警告会保持可见。右键点击咖啡杯也可访问偏好设置和退出。|Gli avvisi restano visibili. Impostazioni ed Esci sono disponibili anche facendo clic destro sulla tazza.|警告は常に表示されます。カップを右クリックして設定や終了を選ぶこともできます。|경고는 계속 표시됩니다. 컵을 오른쪽 클릭하면 환경설정과 종료도 사용할 수 있습니다.|Предупреждения остаются видимыми. Настройки и выход также доступны по правому клику на чашке.|Os avisos continuam visíveis. Preferências e Sair também estão disponíveis ao clicar com o botão direito na xícara.|Uyarılar görünür kalır. Fincana sağ tıklayarak Tercihler ve Çıkış seçeneklerine de ulaşabilirsiniz.|Ostrzeżenia pozostają widoczne. Ustawienia i Wyjdź są też dostępne po kliknięciu filiżanki prawym przyciskiem.|Попередження залишаються видимими. Налаштування та вихід також доступні через праве клацання на чашці.|警告會保持可見。按右鍵點擊咖啡杯也可存取偏好設定和結束。
A compact session menu with Only while brewing.|Kompakt munkamenü a Csak főzés közben kapcsolóval.|Un menú compacto con el interruptor «Solo mientras está en marcha».|Un menu compact avec l’option «Uniquement pendant l’infusion».|Kompaktes Sitzungsmenü mit „Nur während des Brühens“.|带有“仅在保持唤醒会话期间”开关的精简会话菜单。|Un menu compatto con l’opzione «Solo durante l’infusione».|「抽出中のみ」のスイッチを備えたコンパクトなメニュー。|“깨어 있게 유지 세션 중에만” 스위치가 있는 간소화 세션 메뉴.|Компактное меню сеанса с переключателем «Только во время заваривания».|Menu compacto com a opção “Somente durante o preparo”.|“Yalnızca demlenirken” anahtarı olan kompakt oturum menüsü.|Zwarte menu sesji z przełącznikiem „Tylko podczas parzenia”.|Компактне меню сеансу з перемикачем «Лише під час заварювання».|具有「僅在保持喚醒工作階段期間」開關的精簡工作階段選單。
A compact session menu with the closed-display switch.|Kompakt munkamenü a csukott kijelzős mód kapcsolójával.|Un menú compacto con el interruptor de pantalla cerrada.|Un menu compact avec le mode écran fermé.|Kompaktes Sitzungsmenü mit Schalter für den geschlossenen Bildschirm.|带有合盖模式开关的精简会话菜单。|Un menu compatto con l’interruttore dello schermo chiuso.|ディスプレイを閉じたまま動作させるスイッチを備えたメニュー。|덮개를 닫은 모드 스위치가 있는 간소화 세션 메뉴.|Компактное меню сеанса с переключателем закрытого дисплея.|Menu compacto com o interruptor de tela fechada.|Kapalı ekran anahtarı olan kompakt oturum menüsü.|Zwarte menu sesji z przełącznikiem zamkniętej pokrywy.|Компактне меню сеансу з перемикачем закритого дисплея.|具有闔蓋模式開關的精簡工作階段選單。
A small session menu with status and quick timers.|Kis munkamenü állapottal és gyors időzítőkkel.|Un menú pequeño con estado y temporizadores rápidos.|Un petit menu avec l’état et des minuteries rapides.|Kleines Sitzungsmenü mit Status und schnellen Timern.|带有状态和快捷计时器的小型会话菜单。|Un piccolo menu con stato e timer rapidi.|状態とクイックタイマーを表示する小さなメニュー。|상태와 빠른 타이머가 있는 작은 세션 메뉴.|Небольшое меню сеанса со статусом и быстрыми таймерами.|Menu pequeno com estado e temporizadores rápidos.|Durum ve hızlı zamanlayıcıları olan küçük oturum menüsü.|Małe menu sesji ze stanem i szybkimi timerami.|Невелике меню сеансу зі станом і швидкими таймерами.|具有狀態和快捷計時器的小型工作階段選單。
Adapt controls to manual or trigger sessions|Vezérlők igazítása a kézi vagy feltételes munkamenethez|Adaptar controles a sesiones manuales o por condiciones|Adapter les commandes aux sessions manuelles ou automatiques|Bedienelemente an manuelle oder bedingungsgesteuerte Sitzungen anpassen|按手动或触发会话调整控件|Adatta i controlli alle sessioni manuali o automatiche|手動または条件による実行に合わせて操作を表示|수동 또는 트리거 세션에 맞게 컨트롤 표시|Адаптировать элементы к ручным или автоматическим сеансам|Adaptar controles a sessões manuais ou por condições|Kontrolleri elle veya tetikleyicili oturumlara uyarla|Dostosuj elementy do sesji ręcznych lub automatycznych|Адаптувати елементи до ручних чи автоматичних сеансів|依手動或觸發工作階段調整控制項
All controls available. Settings, conditions, and shortcuts start collapsed.|Minden vezérlő elérhető. A beállítások, feltételek és parancsok összecsukva indulnak.|Todos los controles disponibles. Ajustes, condiciones y accesos empiezan contraídos.|Toutes les commandes disponibles. Réglages, conditions et raccourcis sont réduits au départ.|Alle Bedienelemente verfügbar. Einstellungen, Bedingungen und Verknüpfungen starten eingeklappt.|所有控件均可用。设置、条件和快捷入口初始收起。|Tutti i controlli disponibili. Impostazioni, condizioni e scorciatoie iniziano compressi.|すべての操作が利用できます。設定、条件、ショートカットは折りたたまれます。|모든 컨트롤을 사용할 수 있습니다. 설정, 조건, 바로가기는 처음에 접혀 있습니다.|Все элементы доступны. Настройки, условия и ярлыки изначально свёрнуты.|Todos os controles disponíveis. Ajustes, condições e atalhos começam recolhidos.|Tüm kontroller kullanılabilir. Ayarlar, koşullar ve kısayollar daraltılmış başlar.|Wszystkie elementy dostępne. Ustawienia, warunki i skróty są początkowo zwinięte.|Усі елементи доступні. Налаштування, умови та ярлики спочатку згорнуто.|所有控制項皆可用。設定、條件和快捷入口初始收合。
Brewing controls|Főzésvezérlők|Controles de actividad|Commandes d’activité|Betriebssteuerung|运行控制|Controlli attività|実行時の操作|실행 컨트롤|Управление работой|Controles de atividade|Çalışma kontrolleri|Sterowanie działaniem|Керування роботою|執行控制
Custom|Egyéni|Personalizado|Personnalisé|Benutzerdefiniert|自定义|Personalizzato|カスタム|사용자 지정|Свой вариант|Personalizado|Özel|Własny|Власний варіант|自訂
Enable customization to edit the menu.|A menü szerkesztéséhez engedélyezd a testreszabást.|Activa la personalización para editar el menú.|Activez la personnalisation pour modifier le menu.|Anpassung aktivieren, um das Menü zu bearbeiten.|启用自定义以编辑菜单。|Attiva la personalizzazione per modificare il menu.|カスタマイズを有効にしてメニューを編集してください。|메뉴를 편집하려면 사용자화를 켜세요.|Включите настройку меню для редактирования.|Ative a personalização para editar o menu.|Menüyü düzenlemek için özelleştirmeyi açın.|Włącz dostosowanie, aby edytować menu.|Увімкніть налаштування меню для редагування.|啟用自訂以編輯選單。
Just the session controls. Manual timers or trigger controls, at the standard width.|Csak a munkamenet vezérlői. Kézi időzítők vagy feltételek, a szokásos szélességgel.|Solo controles de sesión. Temporizadores manuales o condiciones, con el ancho estándar.|Seulement les commandes de session. Minuteries ou conditions, à la largeur standard.|Nur Sitzungssteuerung. Manuelle Timer oder Bedingungen, mit Standardbreite.|仅会话控件。手动计时器或触发控制，保持标准宽度。|Solo controlli di sessione. Timer manuali o condizioni, con larghezza standard.|実行の操作のみ。手動タイマーまたは条件の操作を標準幅で表示。|세션 컨트롤만 표시합니다. 기본 너비로 수동 타이머 또는 트리거 컨트롤을 표시합니다.|Только управление сеансом. Ручные таймеры или условия, со стандартной шириной.|Somente controles de sessão. Temporizadores manuais ou condições, na largura padrão.|Yalnızca oturum kontrolleri. Standart genişlikte elle zamanlayıcılar veya tetikleyiciler.|Tylko sterowanie sesją. Ręczne timery lub warunki, ze standardową szerokością.|Лише керування сеансом. Ручні таймери чи умови, зі стандартною шириною.|僅工作階段控制項。手動計時器或觸發控制，保持標準寬度。
Lid controls|Fedélvezérlők|Controles de tapa|Commandes du capot|Deckelsteuerung|合盖控制|Controlli coperchio|蓋を閉じたときの操作|덮개 컨트롤|Управление крышкой|Controles da tampa|Kapak kontrolleri|Sterowanie pokrywą|Керування кришкою|闔蓋控制
Live|Élő|En vivo|En direct|Live|实时|Dal vivo|ライブ|실시간|В реальном времени|Ao vivo|Canlı|Na żywo|Наживо|即時
Preview|Előnézet|Vista previa|Aperçu|Vorschau|预览|Anteprima|プレビュー|미리보기|Предпросмотр|Prévia|Önizleme|Podgląd|Попередній перегляд|預覽
Preview only. Controls do not change your session.|Csak előnézet. A vezérlők nem módosítják a munkamenetedet.|Solo vista previa. Los controles no cambian la sesión.|Aperçu uniquement. Les commandes ne modifient pas votre session.|Nur Vorschau. Die Bedienelemente ändern Ihre Sitzung nicht.|仅供预览。控件不会更改会话。|Solo anteprima. I controlli non cambiano la sessione.|プレビューのみです。操作しても実行状態は変わりません。|미리보기 전용입니다. 컨트롤은 세션을 변경하지 않습니다.|Только предпросмотр. Элементы не меняют ваш сеанс.|Somente prévia. Os controles não alteram sua sessão.|Yalnızca önizleme. Kontroller oturumunuzu değiştirmez.|Tylko podgląd. Elementy nie zmieniają sesji.|Лише попередній перегляд. Елементи не змінюють сеанс.|僅供預覽。控制項不會更改工作階段。
Show inactive controls|Inaktív vezérlők mutatása|Mostrar controles inactivos|Afficher les commandes inactives|Inaktive Bedienelemente anzeigen|显示未激活的控件|Mostra controlli inattivi|非アクティブな操作も表示|비활성 컨트롤 표시|Показывать неактивные элементы|Mostrar controles inativos|Etkin olmayan kontrolleri göster|Pokaż nieaktywne elementy|Показувати неактивні елементи|顯示未啟用的控制項
Standard width|Szokásos szélesség|Ancho estándar|Largeur standard|Standardbreite|标准宽度|Larghezza standard|標準幅|기본 너비|Стандартная ширина|Largura padrão|Standart genişlik|Standardowa szerokość|Стандартна ширина|標準寬度
Start manual session|Kézi munkamenet indítása|Iniciar sesión manual|Démarrer une session manuelle|Manuelle Sitzung starten|启动手动会话|Avvia sessione manuale|手動で実行を開始|수동 세션 시작|Начать ручной сеанс|Iniciar sessão manual|Elle oturum başlat|Rozpocznij sesję ręczną|Почати ручний сеанс|啟動手動工作階段
Status and activity only, without session buttons.|Csak állapot és tevékenység, munkamenetgombok nélkül.|Solo estado y actividad, sin botones de sesión.|État et activité seuls, sans boutons de session.|Nur Status und Aktivität, ohne Sitzungsschaltflächen.|仅显示状态和活动，不显示会话按钮。|Solo stato e attività, senza pulsanti di sessione.|状態とアクティビティのみ。実行ボタンは表示されません。|세션 버튼 없이 상태와 활동만 표시합니다.|Только состояние и активность, без кнопок сеанса.|Somente estado e atividade, sem botões de sessão.|Oturum düğmeleri olmadan yalnızca durum ve etkinlik.|Tylko stan i aktywność, bez przycisków sesji.|Лише стан і активність, без кнопок сеансу.|僅顯示狀態和活動，不顯示工作階段按鈕。
Status only|Csak állapot|Solo estado|État seul|Nur Status|仅状态|Solo stato|状態のみ|상태만|Только состояние|Somente estado|Yalnızca durum|Tylko stan|Лише стан|僅狀態
The familiar menu, with settings and tools tucked away.|A megszokott menü, összecsukott beállításokkal és eszközökkel.|El menú habitual, con ajustes y herramientas recogidos.|Le menu habituel, avec réglages et outils repliés.|Das vertraute Menü mit eingeklappten Einstellungen und Werkzeugen.|熟悉的菜单，设置和工具默认收起。|Il menu abituale, con impostazioni e strumenti raccolti.|おなじみのメニュー。設定とツールは折りたたまれます。|설정과 도구가 접혀 있는 익숙한 메뉴.|Привычное меню со свёрнутыми настройками и инструментами.|O menu habitual, com ajustes e ferramentas recolhidos.|Ayarları ve araçları daraltılmış tanıdık menü.|Znane menu ze zwiniętymi ustawieniami i narzędziami.|Звичне меню зі згорнутими налаштуваннями й інструментами.|熟悉的選單，設定和工具預設收合。
Replaces the standard dropdown with your own layout. Open Customize Menu… to show, hide, or reorder controls, change their style and spacing, and choose what the menu-bar item shows.|A szokásos lenyíló panel helyett a saját elrendezésedet használja. A Menü testreszabása… megnyitásával megjeleníthetsz, elrejthetsz vagy átrendezhetsz vezérlőket, módosíthatod a stílusukat és a térközt, és kiválaszthatod, mit mutasson a menüsori elem.|Sustituye el desplegable estándar por tu propio diseño. Abre Personalizar menú… para mostrar, ocultar o reordenar controles, cambiar su estilo y espaciado, y elegir qué muestra el elemento de la barra de menús.|Remplace le menu déroulant standard par votre propre disposition. Ouvrez Personnaliser le menu… pour afficher, masquer ou réorganiser les commandes, modifier leur style et leur espacement, et choisir ce qu’affiche l’élément de la barre des menus.|Ersetzt das Standard-Dropdown durch dein eigenes Layout. Öffne Menü anpassen…, um Bedienelemente anzuzeigen, auszublenden oder neu anzuordnen, ihren Stil und die Abstände zu ändern und festzulegen, was in der Menüleiste erscheint.|用你自己的布局替换标准下拉面板。打开“自定义菜单…”即可显示、隐藏或重新排序控件，更改其样式和间距，并选择菜单栏项目显示的内容。|Sostituisce il menu standard con il tuo layout. Apri Personalizza menu… per mostrare, nascondere o riordinare i controlli, cambiarne stile e spaziatura e scegliere cosa mostra l’elemento nella barra dei menu.|標準のドロップダウンを、あなた独自のレイアウトに置き換えます。「メニューをカスタマイズ…」を開くと、操作の表示・非表示や並べ替え、スタイルと間隔の変更、メニューバー項目に表示する内容の選択ができます。|기본 드롭다운을 직접 구성한 레이아웃으로 바꿉니다. 메뉴 사용자화…를 열어 컨트롤을 표시, 숨기기 또는 순서 변경하고, 스타일과 간격을 바꾸고, 메뉴 막대 항목에 표시할 내용을 선택할 수 있습니다.|Заменяет стандартное меню вашей компоновкой. Откройте «Настроить меню…», чтобы показать, скрыть или переставить элементы управления, изменить их стиль и интервалы и выбрать, что отображается в строке меню.|Substitui o menu padrão pelo seu próprio layout. Abra Personalizar menu… para mostrar, ocultar ou reordenar os controles, mudar o estilo e o espaçamento deles e escolher o que o item da barra de menus exibe.|Standart açılır menüyü kendi düzeninizle değiştirir. Kontrolleri göstermek, gizlemek veya yeniden sıralamak, stillerini ve aralıklarını değiştirmek ve menü çubuğu öğesinde nelerin görüneceğini seçmek için Menüyü özelleştir… seçeneğini açın.|Zastępuje standardowe menu rozwijane twoim własnym układem. Otwórz Dostosuj menu…, aby pokazać, ukryć lub zmienić kolejność elementów sterujących, zmienić ich styl i odstępy oraz wybrać, co pokazuje element na pasku menu.|Замінює стандартне меню вашим власним компонуванням. Відкрийте «Налаштувати меню…», щоб показати, приховати або переставити елементи керування, змінити їхній стиль і відступи та вибрати, що показує елемент у рядку меню.|以您自己的版面配置取代標準下拉面板。開啟「自訂選單…」即可顯示、隱藏或重新排序控制項，變更其樣式和間距，並選擇選單列項目顯示的內容。
'''

APP = {}
for _row in _ROWS.strip().splitlines():
    _key, *_translations = _row.split('|')
    assert len(_translations) == len(_LANGS), _key
    assert _key not in APP, _key
    APP[_key] = dict(zip(_LANGS, _translations))
