#!/usr/bin/env python3
"""Generate Localizable.strings for the Keepresso app and KeepressoCore.

Single source of truth for every localized string. Emits, for each locale,
`<lang>.lproj/Localizable.strings` under the app and Core source trees.

English is the development language: its keys ARE the English source strings,
so en.lproj only needs to exist (empty) to register the region. We still write
en.lproj with identity values for clarity and for `String(localized:)` lookups.
"""
import os

LANGS = ["hu", "es", "fr", "de", "zh-Hans"]

APP_DIR = "Sources/Keepresso"
CORE_DIR = "Sources/KeepressoCore"
WIDGET_DIR = "Sources/KeepressoWidget"


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def emit(base_dir: str, catalog: dict):
    # en: identity
    write_table(base_dir, "en", {k: k for k in catalog})
    for lang in LANGS:
        table = {}
        for k, tr in catalog.items():
            table[k] = tr.get(lang, k)
        write_table(base_dir, lang, table)


def write_table(base_dir: str, lang: str, table: dict):
    lproj = os.path.join(base_dir, f"{lang}.lproj")
    os.makedirs(lproj, exist_ok=True)
    path = os.path.join(lproj, "Localizable.strings")
    lines = ["/* Keepresso localized strings. Generated by tools/localization/gen_strings.py; edit the catalogs there. */", ""]
    for k, v in table.items():
        lines.append(f'"{esc(k)}" = "{esc(v)}";')
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path} ({len(table)} keys)")


# Catalogs are imported from catalog_app.py / catalog_core.py / catalog_widget.py
# to keep this file small. They map English source string -> {lang: translation}.
from catalog_app import APP
from catalog_core import CORE
from catalog_widget import WIDGET

if __name__ == "__main__":
    emit(APP_DIR, APP)
    emit(CORE_DIR, CORE)
    emit(WIDGET_DIR, WIDGET)
