#!/usr/bin/env python3
"""Generate Localizable.strings for the Keepresso app and KeepressoCore.

Single source of truth for every localized string. Emits, for each locale,
`<lang>.lproj/Localizable.strings` under the app and Core source trees.

English is the development language: its keys ARE the English source strings,
so en.lproj only needs to exist (empty) to register the region. We still write
en.lproj with identity values for clarity and for `String(localized:)` lookups.
"""
import os

LANGS = ["hu", "es", "fr", "de", "zh-Hans", "it", "ja", "ko", "ru", "pt-BR", "tr", "pl", "uk", "zh-Hant"]

# Languages whose translations live in per-language overlay files
# (extra/<stem>_app.py with APP, extra/<stem>_core.py with CORE and WIDGET)
# instead of inline in the catalogs. Merged into the catalogs before emitting;
# validate an overlay on its own with check_extra.py.
EXTRA_LANGS = ["it", "ja", "ko", "ru", "pt-BR", "tr", "pl", "uk", "zh-Hant"]

# Anchored to the repo root (two levels above this script), so running it
# from any working directory writes to the real source trees instead of
# silently creating a stray Sources/ next to the cwd.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP_DIR = os.path.join(_REPO_ROOT, "Sources/Keepresso")
CORE_DIR = os.path.join(_REPO_ROOT, "Sources/KeepressoCore")
WIDGET_DIR = os.path.join(_REPO_ROOT, "Sources/KeepressoWidget")


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def emit(base_dir: str, catalog: dict):
    # en: identity
    write_table(base_dir, "en", {k: k for k in catalog})
    for lang in LANGS:
        table = {}
        for k, tr in catalog.items():
            table[k] = tr.get(lang, k)
        write_table(base_dir, lang, table)


def write_table(base_dir: str, lang: str, table: dict):
    lproj = os.path.join(base_dir, f"{lang}.lproj")
    os.makedirs(lproj, exist_ok=True)
    path = os.path.join(lproj, "Localizable.strings")
    lines = ["/* Keepresso localized strings. Generated by tools/localization/gen_strings.py; edit the catalogs there. */", ""]
    for k, v in table.items():
        lines.append(f'"{esc(k)}" = "{esc(v)}";')
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path} ({len(table)} keys)")


# Catalogs are imported from catalog_app.py / catalog_core.py / catalog_widget.py
# to keep this file small. They map English source string -> {lang: translation}.
from catalog_app import APP
from catalog_core import CORE
from catalog_widget import WIDGET


def merge_overlay(catalog: dict, lang: str, table: dict, name: str):
    missing = [k for k in catalog if k not in table]
    unknown = [k for k in table if k not in catalog]
    if missing or unknown:
        raise SystemExit(
            f"{lang} {name}: {len(missing)} missing / {len(unknown)} unknown keys, "
            f"e.g. {(missing + unknown)[:3]!r}"
        )
    for k, v in table.items():
        catalog[k][lang] = v


def merge_extra_langs():
    import importlib
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "extra"))
    for lang in EXTRA_LANGS:
        stem = lang.replace("-", "_")
        merge_overlay(APP, lang, importlib.import_module(f"{stem}_app").APP, "APP")
        core_mod = importlib.import_module(f"{stem}_core")
        merge_overlay(CORE, lang, core_mod.CORE, "CORE")
        merge_overlay(WIDGET, lang, core_mod.WIDGET, "WIDGET")


def merge_release_strings():
    """Merge strings added after the main and per-language catalogs shipped."""
    from v117_main_strings import APP as main_app
    from v117_main_strings import CORE as main_core
    from v117_main_strings import validate as validate_main
    from v117_east_strings import APP as east_app
    from v117_east_strings import CORE as east_core
    from v117_east_strings import validate as validate_east
    from v117_west_strings import APP as west_app
    from v117_west_strings import CORE as west_core
    from v117_west_strings import validate as validate_west

    validate_main()
    validate_east()
    validate_west()

    for name, catalog, overlays in (
        ("APP", APP, (main_app, east_app, west_app)),
        ("CORE", CORE, (main_core, east_core, west_core)),
    ):
        expected_keys = set(overlays[0])
        for overlay in overlays[1:]:
            actual_keys = set(overlay)
            if actual_keys != expected_keys:
                missing = sorted(expected_keys - actual_keys)
                unknown = sorted(actual_keys - expected_keys)
                raise SystemExit(
                    f"v1.17 {name}: {len(missing)} missing / {len(unknown)} unknown keys, "
                    f"e.g. {(missing + unknown)[:3]!r}"
                )

        duplicate_keys = sorted(expected_keys.intersection(catalog))
        if duplicate_keys:
            raise SystemExit(
                f"v1.17 {name}: release keys already exist in the main catalog, "
                f"e.g. {duplicate_keys[:3]!r}"
            )

        for key in overlays[0]:
            translations = {}
            for overlay in overlays:
                translations.update(overlay[key])
            actual_languages = set(translations)
            expected_languages = set(LANGS)
            if actual_languages != expected_languages:
                missing = sorted(expected_languages - actual_languages)
                unknown = sorted(actual_languages - expected_languages)
                raise SystemExit(
                    f"v1.17 {name} {key!r}: languages missing {missing!r}, "
                    f"unknown {unknown!r}"
                )
            catalog[key] = translations


if __name__ == "__main__":
    merge_extra_langs()
    merge_release_strings()
    emit(APP_DIR, APP)
    emit(CORE_DIR, CORE)
    emit(WIDGET_DIR, WIDGET)
