#!/usr/bin/env python3
"""Generate Localizable.strings for the Keepresso app and KeepressoCore.

Single source of truth for every localized string. Emits, for each locale,
`<lang>.lproj/Localizable.strings` under the app and Core source trees.

English is the development language: its keys ARE the English source strings,
so en.lproj only needs to exist (empty) to register the region. We still write
en.lproj with identity values for clarity and for `String(localized:)` lookups.
"""
import os

LANGS = ["hu", "es", "fr", "de", "zh-Hans", "it", "ja", "ko", "ru", "pt-BR", "tr", "pl", "uk", "zh-Hant"]

# Languages whose translations live in per-language overlay files
# (extra/<stem>_app.py with APP, extra/<stem>_core.py with CORE and WIDGET)
# instead of inline in the catalogs. Merged into the catalogs before emitting;
# validate an overlay on its own with check_extra.py.
EXTRA_LANGS = ["it", "ja", "ko", "ru", "pt-BR", "tr", "pl", "uk", "zh-Hant"]

# Anchored to the repo root (two levels above this script), so running it
# from any working directory writes to the real source trees instead of
# silently creating a stray Sources/ next to the cwd.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP_DIR = os.path.join(_REPO_ROOT, "Sources/Keepresso")
CORE_DIR = os.path.join(_REPO_ROOT, "Sources/KeepressoCore")
WIDGET_DIR = os.path.join(_REPO_ROOT, "Sources/KeepressoWidget")


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def emit(base_dir: str, catalog: dict):
    for lang in ["en"] + LANGS:
        write_table(base_dir, lang, table_for(catalog, lang))


def render_table(table: dict) -> str:
    """The exact file contents for a table. Factored out so check_all.py can
    compare what the catalogs would emit against what is committed, without
    writing anything."""
    lines = ["/* Keepresso localized strings. Generated by tools/localization/gen_strings.py; edit the catalogs there. */", ""]
    for k, v in table.items():
        lines.append(f'"{esc(k)}" = "{esc(v)}";')
    return "\n".join(lines) + "\n"


def table_for(catalog: dict, lang: str) -> dict:
    """The table emitted for one language. `en` is the development language,
    so its keys are the source strings."""
    if lang == "en":
        return {k: k for k in catalog}
    return {k: tr.get(lang, k) for k, tr in catalog.items()}


def write_table(base_dir: str, lang: str, table: dict):
    lproj = os.path.join(base_dir, f"{lang}.lproj")
    os.makedirs(lproj, exist_ok=True)
    path = os.path.join(lproj, "Localizable.strings")
    with open(path, "w", encoding="utf-8") as f:
        f.write(render_table(table))
    print(f"wrote {path} ({len(table)} keys)")


# Catalogs are imported from catalog_app.py / catalog_core.py / catalog_widget.py
# to keep this file small. They map English source string -> {lang: translation}.
from catalog_app import APP
from catalog_core import CORE
from catalog_widget import WIDGET
from catalog_v121_app_settings import APP as V121_APP_SETTINGS
from catalog_v121_app_windows import APP as V121_APP_WINDOWS
from catalog_v121_core import CORE as V121_CORE


def merge_overlay(catalog: dict, lang: str, table: dict, name: str):
    missing = [k for k in catalog if k not in table]
    unknown = [k for k in table if k not in catalog]
    if missing or unknown:
        raise SystemExit(
            f"{lang} {name}: {len(missing)} missing / {len(unknown)} unknown keys, "
            f"e.g. {(missing + unknown)[:3]!r}"
        )
    for k, v in table.items():
        catalog[k][lang] = v


def merge_extra_langs():
    import importlib
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "extra"))
    for lang in EXTRA_LANGS:
        stem = lang.replace("-", "_")
        merge_overlay(APP, lang, importlib.import_module(f"{stem}_app").APP, "APP")
        core_mod = importlib.import_module(f"{stem}_core")
        merge_overlay(CORE, lang, core_mod.CORE, "CORE")
        merge_overlay(WIDGET, lang, core_mod.WIDGET, "WIDGET")

    # Feature batches added after the per-language overlays already contain all
    # shipping languages in one place. Merge them only after validating the
    # older overlays, otherwise every overlay would need placeholder entries
    # for keys whose translations live in these supplemental catalogs.
    APP.update(V121_APP_WINDOWS)
    APP.update(V121_APP_SETTINGS)
    CORE.update(V121_CORE)


if __name__ == "__main__":
    merge_extra_langs()
    emit(APP_DIR, APP)
    emit(CORE_DIR, CORE)
    emit(WIDGET_DIR, WIDGET)
