# -*- coding: utf-8 -*-
"""New user-facing strings for 1.16.0. Merged into catalogs + EXTRA overlays.

Keys map to {lang: translation}. Main catalog langs: hu, es, fr, de, zh-Hans.
EXTRA overlay langs: it, ja, ko, ru, pt-BR, tr, pl, uk, zh-Hant.
"""

# Shared helpers for short UI words that appear in both trees.
_SHORT = {
    "Cancel": {
        "hu": "Mégsem", "es": "Cancelar", "fr": "Annuler", "de": "Abbrechen", "zh-Hans": "取消",
        "it": "Annulla", "ja": "キャンセル", "ko": "취소", "ru": "Отмена", "pt-BR": "Cancelar",
        "tr": "Vazgeç", "pl": "Anuluj", "uk": "Скасувати", "zh-Hant": "取消",
    },
    "Off": {
        "hu": "Ki", "es": "Desactivado", "fr": "Désactivé", "de": "Aus", "zh-Hans": "关",
        "it": "Disattivato", "ja": "オフ", "ko": "끔", "ru": "Выкл.", "pt-BR": "Desligado",
        "tr": "Kapalı", "pl": "Wył.", "uk": "Вимк.", "zh-Hant": "關",
    },
    "Time": {
        "hu": "Időpont", "es": "Hora", "fr": "Heure", "de": "Zeit", "zh-Hans": "时间",
        "it": "Ora", "ja": "時刻", "ko": "시간", "ru": "Время", "pt-BR": "Horário",
        "tr": "Saat", "pl": "Godzina", "uk": "Час", "zh-Hant": "時間",
    },
    "Total": {
        "hu": "Összesen", "es": "Total", "fr": "Total", "de": "Gesamt", "zh-Hans": "合计",
        "it": "Totale", "ja": "合計", "ko": "합계", "ru": "Всего", "pt-BR": "Total",
        "tr": "Toplam", "pl": "Razem", "uk": "Разом", "zh-Hant": "合計",
    },
    "Indefinite": {
        "hu": "Határozatlan", "es": "Indefinida", "fr": "Indéfinie", "de": "Unbegrenzt", "zh-Hans": "不限时",
        "it": "Indefinita", "ja": "無期限", "ko": "무기한", "ru": "Без срока", "pt-BR": "Indefinida",
        "tr": "Süresiz", "pl": "Bezterminowa", "uk": "Безстроково", "zh-Hant": "無限期",
    },
    "Scheduled wake": {
        "hu": "Ütemezett ébresztés", "es": "Despertar programado", "fr": "Réveil planifié",
        "de": "Geplantes Aufwecken", "zh-Hans": "计划唤醒",
        "it": "Sveglia programmata", "ja": "スケジュール起床", "ko": "예약 깨우기",
        "ru": "Запланированное пробуждение", "pt-BR": "Despertar agendado",
        "tr": "Zamanlanmış uyandırma", "pl": "Zaplanzone wybudzenie", "uk": "Заплановане пробудження",
        "zh-Hant": "排程喚醒",
    },
    "One-shot wake": {
        "hu": "Egyszeri ébresztés", "es": "Despertar único", "fr": "Réveil unique",
        "de": "Einmaliges Aufwecken", "zh-Hans": "单次唤醒",
        "it": "Sveglia una tantum", "ja": "1回だけの起床", "ko": "일회성 깨우기",
        "ru": "Разовое пробуждение", "pt-BR": "Despertar único",
        "tr": "Tek seferlik uyandırma", "pl": "Jednorazowe wybudzenie", "uk": "Одноразове пробудження",
        "zh-Hant": "單次喚醒",
    },
}

NEW_APP = {
    **_SHORT,
    "Wake schedule": {
        "hu": "Ébresztési ütemezés", "es": "Programación de despertar", "fr": "Planning de réveil",
        "de": "Aufweckplan", "zh-Hans": "唤醒计划",
        "it": "Programma di sveglia", "ja": "起床スケジュール", "ko": "깨우기 일정",
        "ru": "Расписание пробуждения", "pt-BR": "Agenda de despertar",
        "tr": "Uyandırma planı", "pl": "Harmonogram wybudzeń", "uk": "Розклад пробудження",
        "zh-Hant": "喚醒排程",
    },
    "Wake at": {
        "hu": "Ébresztés ekkor", "es": "Despertar a las", "fr": "Réveiller à",
        "de": "Aufwecken um", "zh-Hans": "唤醒时间",
        "it": "Sveglia alle", "ja": "起床時刻", "ko": "깨울 시각",
        "ru": "Разбудить в", "pt-BR": "Despertar às",
        "tr": "Uyandırma saati", "pl": "Wybudź o", "uk": "Розбудити о",
        "zh-Hant": "喚醒時間",
    },
    "Repeat daily / weekly": {
        "hu": "Napi / heti ismétlés", "es": "Repetir a diario / semanalmente",
        "fr": "Répéter chaque jour / semaine", "de": "Täglich / wöchentlich wiederholen",
        "zh-Hans": "每日/每周重复",
        "it": "Ripeti ogni giorno / settimana", "ja": "毎日／毎週繰り返す", "ko": "매일/매주 반복",
        "ru": "Повторять ежедневно / еженедельно", "pt-BR": "Repetir diariamente / semanalmente",
        "tr": "Günlük / haftalık tekrarla", "pl": "Powtarzaj codziennie / co tydzień",
        "uk": "Повторювати щодня / щотижня", "zh-Hant": "每日／每週重複",
    },
    "Start keep-awake on wake": {
        "hu": "Ébredéskor tartsa ébren", "es": "Mantener despierto al despertar",
        "fr": "Garder éveillé au réveil", "de": "Beim Aufwachen wach halten",
        "zh-Hans": "唤醒后保持不休眠",
        "it": "Mantieni sveglio al risveglio", "ja": "起床後にスリープ防止を開始",
        "ko": "깨어난 뒤 절전 방지 시작", "ru": "Не давать уснуть после пробуждения",
        "pt-BR": "Manter acordado ao despertar", "tr": "Uyanınca uyanık tut",
        "pl": "Po wybudzeniu utrzymaj w stanie czuwania", "uk": "Після пробудження тримати без сну",
        "zh-Hant": "喚醒後保持不休眠",
    },
    "Starts keep-awake on wake": {
        "hu": "Ébredéskor elindítja a tartást", "es": "Inicia el mantener despierto al despertar",
        "fr": "Démarre le maintien éveillé au réveil", "de": "Startet Wachhalten beim Aufwachen",
        "zh-Hans": "唤醒时启动保持唤醒",
        "it": "Avvia il keep-awake al risveglio", "ja": "起床時にスリープ防止を開始",
        "ko": "깨어날 때 절전 방지 시작", "ru": "При пробуждении включает удержание",
        "pt-BR": "Inicia o keep-awake ao despertar", "tr": "Uyanınca keep-awake başlatır",
        "pl": "Przy wybudzeniu uruchamia keep-awake", "uk": "При пробудженні вмикає keep-awake",
        "zh-Hant": "喚醒時啟動保持喚醒",
    },
    "Session length": {
        "hu": "Munkamenet hossza", "es": "Duración de la sesión", "fr": "Durée de la session",
        "de": "Sitzungsdauer", "zh-Hans": "会话时长",
        "it": "Durata sessione", "ja": "セッションの長さ", "ko": "세션 길이",
        "ru": "Длительность сеанса", "pt-BR": "Duração da sessão",
        "tr": "Oturum süresi", "pl": "Długość sesji", "uk": "Тривалість сеансу",
        "zh-Hant": "工作階段長度",
    },
    "Turn Off Wake Schedule": {
        "hu": "Ébresztés kikapcsolása", "es": "Desactivar despertar programado",
        "fr": "Désactiver le réveil planifié", "de": "Aufweckplan ausschalten",
        "zh-Hans": "关闭唤醒计划",
        "it": "Disattiva sveglia programmata", "ja": "起床スケジュールをオフ",
        "ko": "깨우기 일정 끄기", "ru": "Выключить расписание пробуждения",
        "pt-BR": "Desativar agenda de despertar", "tr": "Uyandırma planını kapat",
        "pl": "Wyłącz harmonogram wybudzeń", "uk": "Вимкнути розклад пробудження",
        "zh-Hant": "關閉喚醒排程",
    },
    "Awake this week": {
        "hu": "Ébren ez a héten", "es": "Despierto esta semana", "fr": "Éveillé cette semaine",
        "de": "Diese Woche wach gehalten", "zh-Hans": "本周保持唤醒",
        "it": "Sveglio questa settimana", "ja": "今週の起動時間", "ko": "이번 주 깨어 있음",
        "ru": "Бодрствование за неделю", "pt-BR": "Acordado esta semana",
        "tr": "Bu hafta uyanık", "pl": "Czuwanie w tym tygodniu", "uk": "Без сну цього тижня",
        "zh-Hant": "本週保持喚醒",
    },
    "No held-awake time in the last week.": {
        "hu": "Az elmúlt héten nem tartotta ébren.", "es": "No hubo tiempo en vela la última semana.",
        "fr": "Aucun maintien éveillé la semaine dernière.", "de": "In der letzten Woche keine Wachzeit.",
        "zh-Hans": "过去一周没有保持唤醒的时间。",
        "it": "Nessun tempo di keep-awake nell’ultima settimana.",
        "ja": "この1週間、スリープ防止の記録はありません。",
        "ko": "지난 일주일간 절전 방지 기록이 없습니다.",
        "ru": "За прошлую неделю удержания не было.",
        "pt-BR": "Nenhum tempo acordado na última semana.",
        "tr": "Geçen hafta uyanık tutma yok.",
        "pl": "W zeszłym tygodniu brak czasu czuwania.",
        "uk": "Минулого тижня не було утримання.",
        "zh-Hant": "過去一週沒有保持喚醒時間。",
    },
    "−%d%% battery": {
        "hu": "−%d%% akku", "es": "−%d%% batería", "fr": "−%d %% batterie",
        "de": "−%d %% Akku", "zh-Hans": "−%d%% 电量",
        "it": "−%d%% batteria", "ja": "−%d%% バッテリー", "ko": "−%d%% 배터리",
        "ru": "−%d%% батареи", "pt-BR": "−%d%% bateria",
        "tr": "−%d%% pil", "pl": "−%d%% baterii", "uk": "−%d%% батареї",
        "zh-Hant": "−%d%% 電量",
    },
    "%dh %dm": {
        "hu": "%dó %d p", "es": "%dh %dm", "fr": "%d h %d min", "de": "%d Std. %d Min.",
        "zh-Hans": "%d小时 %d分",
        "it": "%dh %dm", "ja": "%d時間 %d分", "ko": "%d시간 %d분",
        "ru": "%d ч %d мин", "pt-BR": "%dh %dm",
        "tr": "%d sa %d dk", "pl": "%d godz. %d min", "uk": "%d год %d хв",
        "zh-Hant": "%d小時 %d分",
    },
    "%dm": {
        "hu": "%d p", "es": "%dm", "fr": "%d min", "de": "%d Min.", "zh-Hans": "%d分",
        "it": "%dm", "ja": "%d分", "ko": "%d분", "ru": "%d мин", "pt-BR": "%dm",
        "tr": "%d dk", "pl": "%d min", "uk": "%d хв", "zh-Hant": "%d分",
    },
    "One-shot: %@": {
        "hu": "Egyszeri: %@", "es": "Único: %@", "fr": "Unique : %@", "de": "Einmalig: %@",
        "zh-Hans": "单次：%@",
        "it": "Una tantum: %@", "ja": "1回：%@", "ko": "일회：%@",
        "ru": "Разово: %@", "pt-BR": "Único: %@",
        "tr": "Tek sefer: %@", "pl": "Jednorazowo: %@", "uk": "Одноразово: %@",
        "zh-Hant": "單次：%@",
    },
    "Repeating: every day at %@": {
        "hu": "Ismétlődő: minden nap %@", "es": "Repetir: cada día a las %@",
        "fr": "Répétition : chaque jour à %@", "de": "Wiederholt: täglich um %@",
        "zh-Hans": "重复：每天 %@",
        "it": "Ripeti: ogni giorno alle %@", "ja": "繰り返し：毎日 %@",
        "ko": "반복: 매일 %@", "ru": "Повтор: каждый день в %@",
        "pt-BR": "Repetir: todos os dias às %@", "tr": "Tekrar: her gün %@",
        "pl": "Powtarzaj: codziennie o %@", "uk": "Повтор: щодня о %@",
        "zh-Hant": "重複：每天 %@",
    },
    "System one-shot wakes: %@": {
        "hu": "Rendszer egyszeri ébresztései: %@", "es": "Despertares únicos del sistema: %@",
        "fr": "Réveils uniques du système : %@", "de": "Einmalige System-Aufweckzeiten: %@",
        "zh-Hans": "系统单次唤醒：%@",
        "it": "Sveglie una tantum di sistema: %@", "ja": "システムの1回起床：%@",
        "ko": "시스템 일회 깨우기: %@", "ru": "Разовые пробуждения системы: %@",
        "pt-BR": "Despertares únicos do sistema: %@", "tr": "Sistem tek seferlik uyandırmaları: %@",
        "pl": "Jednorazowe wybudzenia systemu: %@", "uk": "Одноразові пробудження системи: %@",
        "zh-Hant": "系統單次喚醒：%@",
    },
    "System repeating: %@": {
        "hu": "Rendszer ismétlődő: %@", "es": "Repetición del sistema: %@",
        "fr": "Répétition système : %@", "de": "System-Wiederholung: %@",
        "zh-Hans": "系统重复：%@",
        "it": "Ripetizione di sistema: %@", "ja": "システムの繰り返し：%@",
        "ko": "시스템 반복: %@", "ru": "Повтор системы: %@",
        "pt-BR": "Repetição do sistema: %@", "tr": "Sistem tekrarı: %@",
        "pl": "Powtórzenie systemowe: %@", "uk": "Повтор системи: %@",
        "zh-Hant": "系統重複：%@",
    },
    "Wake schedule not installed": {
        "hu": "Az ébresztés nincs telepítve", "es": "Despertar no instalado",
        "fr": "Réveil non installé", "de": "Aufweckplan nicht installiert",
        "zh-Hans": "未安装唤醒计划",
        "it": "Sveglia non installata", "ja": "起床スケジュールを設定できませんでした",
        "ko": "깨우기 일정을 설치하지 못함", "ru": "Расписание пробуждения не установлено",
        "pt-BR": "Agenda de despertar não instalada", "tr": "Uyandırma planı kurulmadı",
        "pl": "Nie zainstalowano harmonogramu wybudzeń", "uk": "Розклад пробудження не встановлено",
        "zh-Hant": "未安裝喚醒排程",
    },
    "Installing a wake schedule needs the administrator helper (Preferences ▸ General).": {
        "hu": "Az ébresztéshez rendszergazdai segéd kell (Beállítások ▸ Általános).",
        "es": "Programar un despertar necesita el asistente de administrador (Preferencias ▸ General).",
        "fr": "Planifier un réveil nécessite l’assistant administrateur (Préférences ▸ Général).",
        "de": "Ein Aufweckplan braucht den Administrator-Helfer (Einstellungen ▸ Allgemein).",
        "zh-Hans": "设置唤醒计划需要管理员助理（偏好设置 ▸ 通用）。",
        "it": "Programmare una sveglia richiede l’assistente amministratore (Preferenze ▸ Generali).",
        "ja": "起床スケジュールには管理者ヘルパーが必要です（環境設定 ▸ 一般）。",
        "ko": "깨우기 일정에는 관리자 도우미가 필요합니다(환경설정 ▸ 일반).",
        "ru": "Для расписания пробуждения нужен помощник администратора (Настройки ▸ Основные).",
        "pt-BR": "Agendar um despertar precisa do assistente de administrador (Preferências ▸ Geral).",
        "tr": "Uyandırma planı için yönetici yardımcısı gerekir (Tercihler ▸ Genel).",
        "pl": "Harmonogram wybudzeń wymaga pomocnika administratora (Ustawienia ▸ Ogólne).",
        "uk": "Для розкладу пробудження потрібен помічник адміністратора (Параметри ▸ Загальні).",
        "zh-Hant": "設定喚醒排程需要管理員輔助程式（偏好設定 ▸ 一般）。",
    },
    "The administrator helper could not update the system wake schedule.": {
        "hu": "A rendszergazdai segéd nem tudta frissíteni a rendszer ébresztését.",
        "es": "El asistente no pudo actualizar la programación de despertar del sistema.",
        "fr": "L’assistant n’a pas pu mettre à jour le réveil système.",
        "de": "Der Hilfsdienst konnte den System-Aufweckplan nicht aktualisieren.",
        "zh-Hans": "管理员助理无法更新系统唤醒计划。",
        "it": "L’assistente non ha potuto aggiornare la sveglia di sistema.",
        "ja": "ヘルパーがシステムの起床スケジュールを更新できませんでした。",
        "ko": "도우미가 시스템 깨우기 일정을 갱신하지 못했습니다.",
        "ru": "Помощник не смог обновить системное расписание пробуждения.",
        "pt-BR": "O assistente não pôde atualizar a agenda de despertar do sistema.",
        "tr": "Yardımcı sistem uyandırma planını güncelleyemedi.",
        "pl": "Pomocnik nie mógł zaktualizować systemowego harmonogramu wybudzeń.",
        "uk": "Помічник не зміг оновити системний розклад пробудження.",
        "zh-Hant": "管理員輔助程式無法更新系統喚醒排程。",
    },
    "Locks via System Events. macOS may ask once for Automation access for Keepresso.": {
        "hu": "A System Events zárol. A macOS egyszer kérhet Automatizálás-hozzáférést a Keepressóhoz.",
        "es": "Bloquea con System Events. macOS puede pedir una vez acceso de Automatización para Keepresso.",
        "fr": "Verrouille via System Events. macOS peut demander une fois l’accès Automatisation pour Keepresso.",
        "de": "Sperrt über System Events. macOS kann einmal Automatisierungszugriff für Keepresso anfordern.",
        "zh-Hans": "通过 System Events 锁定。macOS 可能向 Keepresso 请求一次“自动化”权限。",
        "it": "Blocca tramite System Events. macOS può chiedere una volta l’accesso Automazione per Keepresso.",
        "ja": "System Events でロックします。macOS が Keepresso に自動化の許可を一度求めることがあります。",
        "ko": "System Events로 잠급니다. macOS가 Keepresso에 자동화 접근을 한 번 요청할 수 있습니다.",
        "ru": "Блокирует через System Events. macOS может один раз запросить доступ к Автоматизации для Keepresso.",
        "pt-BR": "Trava via System Events. O macOS pode pedir uma vez acesso de Automação para o Keepresso.",
        "tr": "System Events ile kilitler. macOS Keepresso için bir kez Otomasyon erişimi isteyebilir.",
        "pl": "Blokuje przez System Events. macOS może raz poprosić o dostęp Automacji dla Keepresso.",
        "uk": "Блокує через System Events. macOS може один раз запитати доступ Автоматизації для Keepresso.",
        "zh-Hant": "透過 System Events 鎖定。macOS 可能向 Keepresso 要求一次「自動化」權限。",
    },
    "Sleeps the Mac through the administrator helper (instant, no extra prompts).": {
        "hu": "A Macet a rendszergazdai segéddel altatja (azonnal, extra kérés nélkül).",
        "es": "Suspende el Mac con el asistente de administrador (instantáneo, sin más avisos).",
        "fr": "Met le Mac en veille via l’assistant administrateur (immédiat, sans invite).",
        "de": "Schläfert den Mac über den Administrator-Helfer ein (sofort, ohne weitere Abfragen).",
        "zh-Hans": "通过管理员助理让 Mac 睡眠（即时，无额外提示）。",
        "it": "Mette in stop il Mac tramite l’assistente (immediato, senza altre richieste).",
        "ja": "管理者ヘルパー経由で Mac をスリープします（即時、追加の確認なし）。",
        "ko": "관리자 도우미로 Mac을 잠자기합니다(즉시, 추가 프롬프트 없음).",
        "ru": "Усыпляет Mac через помощника администратора (сразу, без лишних запросов).",
        "pt-BR": "Suspende o Mac pelo assistente de administrador (instantâneo, sem novos avisos).",
        "tr": "Yönetici yardımcısıyla Mac’i uyutur (anında, ek istem yok).",
        "pl": "Uśpia Maca przez pomocnika administratora (natychmiast, bez dodatkowych pytań).",
        "uk": "Присипляє Mac через помічника адміністратора (одразу, без зайвих запитів).",
        "zh-Hant": "透過管理員輔助程式讓 Mac 睡眠（即時，無額外提示）。",
    },
    "Without the administrator helper, sleep uses System Events and may ask for Automation access once. Install the helper under Preferences ▸ General for instant, silent sleep.": {
        "hu": "Segéd nélkül a System Events altat, és egyszer Automatizálás-hozzáférést kérhet. Az azonnali, csendes altatáshoz telepítse a segédet: Beállítások ▸ Általános.",
        "es": "Sin el asistente, la suspensión usa System Events y puede pedir Automatización una vez. Instálalo en Preferencias ▸ General para suspensión silenciosa.",
        "fr": "Sans l’assistant, la veille passe par System Events et peut demander Automatisation une fois. Installez-le dans Préférences ▸ Général pour une veille silencieuse.",
        "de": "Ohne Hilfsdienst nutzt der Schlaf System Events und kann einmal Automatisierung anfordern. Installiere ihn unter Einstellungen ▸ Allgemein für stillen Schlaf.",
        "zh-Hans": "没有管理员助理时，睡眠走 System Events，可能请求一次自动化权限。在偏好设置 ▸ 通用安装助理可即时、静默睡眠。",
        "it": "Senza assistente, lo stop usa System Events e può chiedere Automazione una volta. Installalo in Preferenze ▸ Generali per uno stop silenzioso.",
        "ja": "ヘルパーがない場合、スリープは System Events 経由となり、自動化の許可を一度求めることがあります。環境設定 ▸ 一般でヘルパーを入れると即時・無音でスリープできます。",
        "ko": "도우미가 없으면 잠자기는 System Events를 쓰며 자동화 접근을 한 번 요청할 수 있습니다. 환경설정 ▸ 일반에서 도우미를 설치하면 즉시·조용히 잠잡니다.",
        "ru": "Без помощника сон идёт через System Events и может один раз запросить Автоматизацию. Установите помощника в Настройки ▸ Основные для тихого сна.",
        "pt-BR": "Sem o assistente, o sono usa System Events e pode pedir Automação uma vez. Instale em Preferências ▸ Geral para sono silencioso.",
        "tr": "Yardımcı yoksa uyku System Events kullanır ve bir kez Otomasyon isteyebilir. Anında sessiz uyku için Tercihler ▸ Genel’den yardımcı kurun.",
        "pl": "Bez pomocnika sen idzie przez System Events i może raz poprosić o Automację. Zainstaluj go w Ustawienia ▸ Ogólne, by spać cicho.",
        "uk": "Без помічника сон іде через System Events і може один раз запитати Автоматизацію. Встановіть помічника в Параметри ▸ Загальні для тихого сну.",
        "zh-Hant": "沒有管理員輔助程式時，睡眠走 System Events，可能要求一次自動化權限。在偏好設定 ▸ 一般安裝輔助程式可即時、靜默睡眠。",
    },
    "The helper is waiting for approval in System Settings. Until then, sleep falls back to System Events, which may ask for Automation access once.": {
        "hu": "A segéd a Rendszerbeállításokban vár jóváhagyásra. Addig a System Events altat, ami egyszer Automatizálást kérhet.",
        "es": "El asistente espera aprobación en Ajustes del Sistema. Mientras, la suspensión usa System Events y puede pedir Automatización una vez.",
        "fr": "L’assistant attend l’approbation dans Réglages Système. En attendant, la veille passe par System Events, qui peut demander Automatisation une fois.",
        "de": "Der Helfer wartet in den Systemeinstellungen auf Freigabe. Bis dahin nutzt der Schlaf System Events und kann einmal Automatisierung anfordern.",
        "zh-Hans": "助理正在系统设置中等待批准。在此之前，睡眠回退到 System Events，可能请求一次自动化权限。",
        "it": "L’assistente attende l’approvazione in Impostazioni di Sistema. Finché non c’è, lo stop usa System Events e può chiedere Automazione una volta.",
        "ja": "ヘルパーはシステム設定での承認待ちです。それまでは System Events にフォールバックし、自動化の許可を一度求めることがあります。",
        "ko": "도우미가 시스템 설정에서 승인을 기다립니다. 그동안 잠자기는 System Events로 돌아가며 자동화 접근을 한 번 요청할 수 있습니다.",
        "ru": "Помощник ждёт разрешения в Системных настройках. До этого сон идёт через System Events, возможен один запрос Автоматизации.",
        "pt-BR": "O assistente aguarda aprovação em Ajustes do Sistema. Até lá, o sono usa System Events e pode pedir Automação uma vez.",
        "tr": "Yardımcı Sistem Ayarları’nda onay bekliyor. O zamana kadar uyku System Events’e düşer ve bir kez Otomasyon isteyebilir.",
        "pl": "Pomocnik czeka na zatwierdzenie w Ustawieniach systemowych. Do tego czasu sen idzie przez System Events i może raz poprosić o Automację.",
        "uk": "Помічник чекає схвалення в Системних параметрах. Доти сон через System Events і можливий один запит Автоматизації.",
        "zh-Hant": "輔助程式正在系統設定中等待核准。在此之前，睡眠退回 System Events，可能要求一次自動化權限。",
    },
    "The helper is updating itself. Until that finishes, sleep falls back to System Events, which may ask for Automation access once.": {
        "hu": "A segéd frissíti magát. Amíg tart, a System Events altat, ami egyszer Automatizálást kérhet.",
        "es": "El asistente se actualiza. Mientras, la suspensión usa System Events y puede pedir Automatización una vez.",
        "fr": "L’assistant se met à jour. En attendant, la veille passe par System Events, qui peut demander Automatisation une fois.",
        "de": "Der Helfer aktualisiert sich. Bis dahin nutzt der Schlaf System Events und kann einmal Automatisierung anfordern.",
        "zh-Hans": "助理正在自行更新。完成前，睡眠回退到 System Events，可能请求一次自动化权限。",
        "it": "L’assistente si sta aggiornando. Finché non finisce, lo stop usa System Events e può chiedere Automazione una volta.",
        "ja": "ヘルパーは自己更新中です。完了までは System Events にフォールバックし、自動化の許可を一度求めることがあります。",
        "ko": "도우미가 스스로 업데이트 중입니다. 끝날 때까지 잠자기는 System Events로 돌아가며 자동화 접근을 한 번 요청할 수 있습니다.",
        "ru": "Помощник обновляется. До завершения сон идёт через System Events, возможен один запрос Автоматизации.",
        "pt-BR": "O assistente está se atualizando. Até terminar, o sono usa System Events e pode pedir Automação uma vez.",
        "tr": "Yardımcı kendini güncelliyor. Bitene kadar uyku System Events’e düşer ve bir kez Otomasyon isteyebilir.",
        "pl": "Pomocnik się aktualizuje. Do końca sen idzie przez System Events i może raz poprosić o Automację.",
        "uk": "Помічник оновлюється. До завершення сон через System Events і можливий один запит Автоматизації.",
        "zh-Hant": "輔助程式正在自行更新。完成前，睡眠退回 System Events，可能要求一次自動化權限。",
    },
    "One step left: allow Keepresso under Login Items in System Settings. Scheduled wake unlocks by itself.": {
        "hu": "Még egy lépés: engedélyezze a Keepressót a Bejelentkezési elemeknél a Rendszerbeállításokban. Az ütemezett ébresztés magától feloldódik.",
        "es": "Un paso más: permite Keepresso en Ítems de inicio en Ajustes del Sistema. El despertar programado se desbloquea solo.",
        "fr": "Une étape restante : autorisez Keepresso dans Ouverture au démarrage (Réglages Système). Le réveil planifié se déverrouille tout seul.",
        "de": "Noch ein Schritt: erlaube Keepresso unter Anmeldeobjekte in den Systemeinstellungen. Geplantes Aufwecken entsperrt sich selbst.",
        "zh-Hans": "还差一步：在系统设置的登录项中允许 Keepresso。计划唤醒会自行解锁。",
        "it": "Un passo ancora: consenti Keepresso in Elementi di login (Impostazioni di Sistema). La sveglia programmata si sblocca da sola.",
        "ja": "あと一歩：システム設定のログイン項目で Keepresso を許可してください。スケジュール起床は自動で解除されます。",
        "ko": "한 단계 남음: 시스템 설정의 로그인 항목에서 Keepresso를 허용하세요. 예약 깨우기는 자동으로 잠금 해제됩니다.",
        "ru": "Остался шаг: разрешите Keepresso в объектах входа в Системных настройках. Запланированное пробуждение разблокируется само.",
        "pt-BR": "Falta um passo: permita o Keepresso em Itens de abertura nos Ajustes do Sistema. O despertar agendado desbloqueia sozinho.",
        "tr": "Son adım: Sistem Ayarları’nda Giriş Öğeleri altında Keepresso’ya izin verin. Zamanlanmış uyandırma kendiliğinden açılır.",
        "pl": "Jeszcze jeden krok: zezwól na Keepresso w Elementach logowania w Ustawieniach systemowych. Zaplanowane wybudzenie odblokuje się samo.",
        "uk": "Ще один крок: дозвольте Keepresso в об’єктах входу в Системних параметрах. Заплановане пробудження розблокується само.",
        "zh-Hant": "還差一步：在系統設定的登入項目中允許 Keepresso。排程喚醒會自行解鎖。",
    },
    "The helper is updating itself (no password). Scheduled wake unlocks when that finishes, usually under a minute.": {
        "hu": "A segéd frissíti magát (jelszó nélkül). Az ütemezett ébresztés a végén feloldódik, általában egy percen belül.",
        "es": "El asistente se actualiza (sin contraseña). El despertar programado se desbloquea al terminar, suele ser menos de un minuto.",
        "fr": "L’assistant se met à jour (sans mot de passe). Le réveil planifié se déverrouille à la fin, en général en moins d’une minute.",
        "de": "Der Helfer aktualisiert sich (ohne Passwort). Geplantes Aufwecken entsperrt sich danach, meist unter einer Minute.",
        "zh-Hans": "助理正在自行更新（无需密码）。完成后计划唤醒会解锁，通常不到一分钟。",
        "it": "L’assistente si aggiorna (senza password). La sveglia programmata si sblocca a fine aggiornamento, di solito in meno di un minuto.",
        "ja": "ヘルパーは自己更新中です（パスワード不要）。完了するとスケジュール起床が解除され、通常1分以内です。",
        "ko": "도우미가 스스로 업데이트 중입니다(암호 없음). 끝나면 예약 깨우기가 잠금 해제되며, 보통 1분 이내입니다.",
        "ru": "Помощник обновляется (без пароля). Запланированное пробуждение разблокируется по завершении, обычно меньше минуты.",
        "pt-BR": "O assistente se atualiza (sem senha). O despertar agendado desbloqueia ao terminar, em geral em menos de um minuto.",
        "tr": "Yardımcı kendini güncelliyor (parola yok). Bitince zamanlanmış uyandırma açılır, genelde bir dakikadan az.",
        "pl": "Pomocnik się aktualizuje (bez hasła). Zaplanowane wybudzenie odblokuje się po zakończeniu, zwykle poniżej minuty.",
        "uk": "Помічник оновлюється (без пароля). Заплановане пробудження розблокується після завершення, зазвичай менш як за хвилину.",
        "zh-Hant": "輔助程式正在自行更新（無需密碼）。完成後排程喚醒會解鎖，通常不到一分鐘。",
    },
    "Scheduled wake needs the administrator helper, the same one closed-display mode and fan boost use. Install once, and macOS asks for approval in System Settings.": {
        "hu": "Az ütemezett ébresztéshez a rendszergazdai segéd kell, ugyanaz, mint a csukott kijelzőhöz és a ventilátor-erősítéshez. Egyszer telepítse, és a macOS a Rendszerbeállításokban kér jóváhagyást.",
        "es": "El despertar programado necesita el asistente de administrador, el mismo que el modo tapa cerrada y el impulso de ventiladores. Instálalo una vez, y macOS pide aprobación en Ajustes del Sistema.",
        "fr": "Le réveil planifié nécessite l’assistant administrateur, le même que le mode écran fermé et l’accélération des ventilateurs. Installez-le une fois, et macOS demande l’approbation dans Réglages Système.",
        "de": "Geplantes Aufwecken braucht den Administrator-Helfer, denselben wie Klappenmodus und Lüfterboost. Einmal installieren, und macOS fragt in den Systemeinstellungen nach Freigabe.",
        "zh-Hans": "计划唤醒需要管理员助理，与合盖模式和风扇加速相同。安装一次即可，macOS 会在系统设置中请求批准。",
        "it": "La sveglia programmata richiede l’assistente amministratore, lo stesso di modalità coperchio chiuso e boost ventole. Installalo una volta: macOS chiede l’approvazione in Impostazioni di Sistema.",
        "ja": "スケジュール起床には管理者ヘルパーが必要です（クローズドディスプレイやファンブーストと同じ）。一度インストールすれば、macOS がシステム設定で承認を求めます。",
        "ko": "예약 깨우기에는 관리자 도우미가 필요합니다(닫힌 디스플레이 모드·팬 부스트와 동일). 한 번 설치하면 macOS가 시스템 설정에서 승인을 요청합니다.",
        "ru": "Для запланированного пробуждения нужен помощник администратора, тот же, что для режима с закрытой крышкой и разгона вентиляторов. Установите один раз, и macOS попросит разрешение в Системных настройках.",
        "pt-BR": "O despertar agendado precisa do assistente de administrador, o mesmo do modo com tampa fechada e do impulso das ventoinhas. Instale uma vez: o macOS pede aprovação em Ajustes do Sistema.",
        "tr": "Zamanlanmış uyandırma, kapalı ekran modu ve fan güçlendirmeyle aynı yönetici yardımcısını ister. Bir kez kurun: macOS Sistem Ayarları’nda onay ister.",
        "pl": "Zaplanowane wybudzenie wymaga pomocnika administratora, tego samego co tryb zamkniętej klapy i boost wentylatorów. Zainstaluj raz, a macOS poprosi o zgodę w Ustawieniach systemowych.",
        "uk": "Для запланованого пробудження потрібен помічник адміністратора, той самий, що для режиму із закритою кришкою та розгону вентиляторів. Встановіть один раз, і macOS попросить дозвіл у Системних параметрах.",
        "zh-Hant": "排程喚醒需要管理員輔助程式，與合蓋模式和風扇加速相同。安裝一次即可；macOS 會在系統設定中要求核准。",
    },
    "A wake schedule is saved, but it is not active on this Mac until the administrator helper is ready. The system will not wake from this plan.": {
        "hu": "Van mentett ébresztés, de a segéd nélkül nem aktív. A rendszer ebből a tervből nem ébred fel.",
        "es": "Hay un despertar guardado, pero no está activo hasta que el asistente esté listo. El sistema no despertará con este plan.",
        "fr": "Un réveil est enregistré, mais inactif tant que l’assistant n’est pas prêt. Le système ne se réveillera pas avec ce plan.",
        "de": "Ein Aufweckplan ist gespeichert, aber erst aktiv, wenn der Helfer bereit ist. Das System wacht mit diesem Plan nicht auf.",
        "zh-Hans": "已保存唤醒计划，但要等管理员助理就绪才生效。系统不会按此计划唤醒。",
        "it": "C’è una sveglia salvata, ma non è attiva finché l’assistente non è pronto. Il sistema non si sveglierà con questo piano.",
        "ja": "起床スケジュールは保存されていますが、ヘルパーが準備できるまで無効です。この計画ではシステムは起きません。",
        "ko": "깨우기 일정은 저장됐지만 도우미가 준비될 때까지 비활성입니다. 이 계획으로는 시스템이 깨어나지 않습니다.",
        "ru": "Расписание сохранено, но не активно, пока помощник не готов. Система не проснётся по этому плану.",
        "pt-BR": "Há um despertar salvo, mas inativo até o assistente estar pronto. O sistema não acordará com este plano.",
        "tr": "Bir uyandırma planı kayıtlı ama yardımcı hazır olana kadar etkin değil. Sistem bu plandan uyanmaz.",
        "pl": "Harmonogram jest zapisany, ale nieaktywny, dopóki pomocnik nie będzie gotowy. System nie wybudzi się z tego planu.",
        "uk": "Розклад збережено, але він неактивний, доки помічник не буде готовий. Система не прокинеться за цим планом.",
        "zh-Hant": "已儲存喚醒排程，但要等管理員輔助程式就緒才會生效。系統不會依此計劃喚醒。",
    },
    "Reliable on AC power. On battery the firmware may skip the wake.": {
        "hu": "Hálózati tápon megbízható. Akkuról a firmware kihagyhatja az ébresztést.",
        "es": "Fiable con corriente. Con batería el firmware puede omitir el despertar.",
        "fr": "Fiable sur secteur. Sur batterie le microprogramme peut ignorer le réveil.",
        "de": "Zuverlässig am Netz. Im Akkubetrieb kann die Firmware das Aufwecken überspringen.",
        "zh-Hans": "接通电源时可靠。用电池时固件可能跳过唤醒。",
        "it": "Affidabile a corrente. A batteria il firmware può saltare la sveglia.",
        "ja": "電源接続時は確実です。バッテリーではファームウェアが起床を省略することがあります。",
        "ko": "전원 연결 시 안정적입니다. 배터리에서는 펌웨어가 깨우기를 건너뛸 수 있습니다.",
        "ru": "Надёжно от сети. От батареи прошивка может пропустить пробуждение.",
        "pt-BR": "Confiável na tomada. Na bateria o firmware pode pular o despertar.",
        "tr": "Şebekede güvenilir. Pilde ürün yazılımı uyandırmayı atlayabilir.",
        "pl": "Niezawodne na zasilaniu. Na baterii firmware może pominąć wybudzenie.",
        "uk": "Надійно від мережі. Від батареї прошивка може пропустити пробудження.",
        "zh-Hant": "接電源時可靠。使用電池時韌體可能略過喚醒。",
    },
    "Uses every day (MTWRFSU). macOS allows only one system-wide repeating power schedule.": {
        "hu": "Minden nap (MTWRFSU). A macOS csak egy rendszerszintű ismétlődő energiaütemezést enged.",
        "es": "Todos los días (MTWRFSU). macOS solo permite un horario de energía repetitivo en el sistema.",
        "fr": "Tous les jours (MTWRFSU). macOS n’autorise qu’un seul planning d’alimentation récurrent.",
        "de": "Täglich (MTWRFSU). macOS erlaubt nur einen systemweiten wiederkehrenden Energieplan.",
        "zh-Hans": "每天（MTWRFSU）。macOS 全系统只允许一套重复电源计划。",
        "it": "Ogni giorno (MTWRFSU). macOS consente un solo piano di alimentazione ricorrente di sistema.",
        "ja": "毎日（MTWRFSU）。macOS はシステム全体で繰り返し電源スケジュールを1つだけ許可します。",
        "ko": "매일(MTWRFSU). macOS는 시스템 전체 반복 전원 일정을 하나만 허용합니다.",
        "ru": "Каждый день (MTWRFSU). В macOS допустимо только одно системное повторяющееся расписание питания.",
        "pt-BR": "Todos os dias (MTWRFSU). O macOS permite só uma agenda de energia repetitiva no sistema.",
        "tr": "Her gün (MTWRFSU). macOS sistem genelinde yalnızca bir yinelenen güç planına izin verir.",
        "pl": "Codziennie (MTWRFSU). macOS zezwala tylko na jeden systemowy powtarzalny harmonogram zasilania.",
        "uk": "Щодня (MTWRFSU). macOS дозволяє лише один загальносистемний повторюваний розклад живлення.",
        "zh-Hant": "每天（MTWRFSU）。macOS 全系統只允許一套重複電源排程。",
    },
    "Turn on a one-shot time, a repeating time, or both. With neither, nothing is installed on the system.": {
        "hu": "Kapcsoljon be egyszeri vagy ismétlődő időt, vagy mindkettőt. Egyik sem: a rendszerre semmi sem kerül.",
        "es": "Activa una hora única, una repetida o ambas. Sin ninguna, no se instala nada en el sistema.",
        "fr": "Activez une heure unique, une répétition, ou les deux. Sinon, rien n’est installé sur le système.",
        "de": "Schalte eine einmalige Zeit, eine Wiederholung oder beides ein. Sonst wird nichts am System eingerichtet.",
        "zh-Hans": "打开单次时间、重复时间，或两者都开。都不开则不会在系统上安装任何内容。",
        "it": "Attiva un orario una tantum, uno ricorrente o entrambi. Altrimenti non viene installato nulla sul sistema.",
        "ja": "1回の時刻、繰り返しの時刻、または両方をオンにしてください。どちらもオフだとシステムには何も設定されません。",
        "ko": "일회 시각, 반복 시각, 또는 둘 다 켜세요. 둘 다 끄면 시스템에 아무것도 설치되지 않습니다.",
        "ru": "Включите разовое время, повторяющееся или оба. Иначе на системе ничего не устанавливается.",
        "pt-BR": "Ative um horário único, um repetido ou ambos. Sem nenhum, nada é instalado no sistema.",
        "tr": "Tek seferlik saat, yinelenen saat veya ikisini de açın. İkisi de kapalıysa sisteme bir şey kurulmaz.",
        "pl": "Włącz czas jednorazowy, powtarzany albo oba. Bez żadnego nic nie trafi do systemu.",
        "uk": "Увімкніть одноразовий час, повторюваний або обидва. Інакше в системі нічого не встановлюється.",
        "zh-Hant": "開啟單次時間、重複時間，或兩者都開。都不開則不會在系統上安裝任何內容。",
    },
    "When the Mac wakes near this schedule, Keepresso starts a session so it does not fall back asleep. Works best with triggers off for that window, or with a trigger that stays satisfied.": {
        "hu": "Ha a Mac e körüli időben ébred, a Keepresso elindít egy munkamenetet, hogy ne aludjon vissza. Legjobb, ha a triggerek ki vannak kapcsolva, vagy egy feltétel végig teljesül.",
        "es": "Si el Mac despierta cerca de esta hora, Keepresso inicia una sesión para que no se duerma otra vez. Funciona mejor con disparadores off o con uno que siga cumpliéndose.",
        "fr": "Si le Mac se réveille près de cette heure, Keepresso démarre une session pour qu’il ne se rendorme pas. Idéal avec les déclencheurs coupés, ou un qui reste vrai.",
        "de": "Wacht der Mac um diese Zeit auf, startet Keepresso eine Sitzung, damit er nicht gleich wieder schläft. Am besten mit ausgeschalteten Auslösern oder einem, der erfüllt bleibt.",
        "zh-Hans": "若 Mac 在此计划附近唤醒，Keepresso 会启动会话以免立刻再睡。该时段最好关闭触发条件，或使用会持续满足的条件。",
        "it": "Se il Mac si sveglia vicino a questo orario, Keepresso avvia una sessione così non si riaddormenta. Meglio con i trigger spenti o con uno che resta soddisfatto.",
        "ja": "この時刻付近で Mac が起きると、Keepresso がセッションを開始してすぐ再スリープしないようにします。その時間帯はトリガーをオフにするか、満たされ続ける条件がおすすめです。",
        "ko": "이 일정 근처에서 Mac이 깨어나면 Keepresso가 세션을 시작해 다시 잠들지 않게 합니다. 그 구간에는 트리거를 끄거나 계속 만족되는 조건이 좋습니다.",
        "ru": "Если Mac просыпается около этого времени, Keepresso запускает сеанс, чтобы он снова не уснул. Лучше с выключенными триггерами или с условием, которое остаётся истинным.",
        "pt-BR": "Se o Mac acordar perto deste horário, o Keepresso inicia uma sessão para não dormir de novo. Funciona melhor com gatilhos desligados ou um que continue válido.",
        "tr": "Mac bu saate yakın uyanırsa Keepresso oturum başlatır ki hemen uyumasın. O aralıkta tetikleyiciler kapalı veya sürekli sağlanan bir koşul en iyisidir.",
        "pl": "Gdy Mac budzi się koło tej godziny, Keepresso startuje sesję, by nie zasnął z powrotem. Najlepiej z wyłączonymi wyzwalaczami albo jednym, który pozostaje spełniony.",
        "uk": "Якщо Mac прокидається близько цього часу, Keepresso запускає сеанс, щоб знову не заснув. Краще з вимкненими тригерами або умовою, що лишається істинною.",
        "zh-Hant": "若 Mac 在此排程附近喚醒，Keepresso 會啟動工作階段以免立刻再睡。該時段最好關閉觸發條件，或使用會持續滿足的條件。",
    },
    "Fires a few seconds after a natural end, not on a manual stop or a safety pause.": {
        "hu": "Néhány másodperccel a természetes vég után fut le, nem kézi leállításkor vagy biztonsági szünetnél.",
        "es": "Se ejecuta unos segundos tras un fin natural, no al parar a mano ni en una pausa de seguridad.",
        "fr": "Se déclenche quelques secondes après une fin naturelle, pas un arrêt manuel ni une pause de sécurité.",
        "de": "Läuft einige Sekunden nach einem natürlichen Ende, nicht bei manuellem Stopp oder Sicherheitspause.",
        "zh-Hans": "在自然结束后数秒执行，手动停止或安全暂停时不会。",
        "it": "Parte pochi secondi dopo una fine naturale, non su stop manuale o pausa di sicurezza.",
        "ja": "自然終了の数秒後に実行され、手動停止や安全一時停止では動きません。",
        "ko": "자연 종료 후 몇 초 뒤에 실행되며, 수동 중지·안전 일시 정지에서는 실행되지 않습니다.",
        "ru": "Срабатывает через несколько секунд после естественного конца, не при ручной остановке или защитной паузе.",
        "pt-BR": "Dispara alguns segundos após um fim natural, não em parada manual ou pausa de segurança.",
        "tr": "Doğal bitişten birkaç saniye sonra çalışır; elle durdurma veya güvenlik duraklatmasında değil.",
        "pl": "Uruchamia się kilka sekund po naturalnym końcu, nie przy ręcznym stopie ani pauzie bezpieczeństwa.",
        "uk": "Спрацьовує за кілька секунд після природного кінця, не при ручній зупинці чи паузі безпеки.",
        "zh-Hant": "在自然結束後數秒執行，手動停止或安全暫停時不會。",
    },
    "Notifications fire when a session ends on its own, not when you stop it yourself.": {
        "hu": "Az értesítések maguktól végződő munkamenetnél jönnek, nem ha te állítod le.",
        "es": "Los avisos suenan cuando la sesión termina sola, no si la paras tú.",
        "fr": "Les notifications partent quand la session se termine d’elle-même, pas si vous l’arrêtez.",
        "de": "Benachrichtigungen bei selbstständigem Sitzungsende, nicht wenn du sie stoppst.",
        "zh-Hans": "会话自行结束时会通知，你自己停止时不会。",
        "it": "Le notifiche partono quando la sessione finisce da sola, non se la fermi tu.",
        "ja": "セッションが自分で終わったときに通知し、自分で止めたときは出しません。",
        "ko": "세션이 스스로 끝날 때 알림이 오며, 직접 멈출 때는 오지 않습니다.",
        "ru": "Уведомления при самостоятельном конце сеанса, не когда вы останавливаете сами.",
        "pt-BR": "As notificações saem quando a sessão termina sozinha, não quando você a para.",
        "tr": "Bildirimler oturum kendi kendine bitince gelir; siz durdurunca gelmez.",
        "pl": "Powiadomienia przy samoczynnym końcu sesji, nie gdy zatrzymasz ją sam.",
        "uk": "Сповіщення, коли сеанс завершується сам, а не коли зупиняєте ви.",
        "zh-Hant": "工作階段自行結束時會通知，你自己停止時不會。",
    },
    "Run a Shortcut, post a webhook, or a shell command on session and trigger events. No helper required.": {
        "hu": "Futtasson Parancsot, webhookot vagy shell-parancsot munkamenet- és triggereseményekre. Segéd nem kell.",
        "es": "Ejecuta un Atajo, un webhook o un comando shell en eventos de sesión y disparadores. No hace falta el asistente.",
        "fr": "Lancez un Raccourci, un webhook ou une commande shell sur les événements de session et de déclencheur. Pas d’assistant requis.",
        "de": "Kurzbefehl, Webhook oder Shell-Befehl bei Sitzungs- und Auslöserereignissen. Kein Helfer nötig.",
        "zh-Hans": "在会话和触发事件上运行快捷指令、Webhook 或 shell 命令。不需要助理。",
        "it": "Esegui un Comando, un webhook o uno shell su eventi di sessione e trigger. Nessun assistente richiesto.",
        "ja": "セッションやトリガーのイベントでショートカット、Webhook、シェルを実行。ヘルパーは不要です。",
        "ko": "세션·트리거 이벤트에 단축어, 웹훅, 셸 명령을 실행합니다. 도우미 불필요.",
        "ru": "Запускайте команду, вебхук или shell на событиях сеанса и триггеров. Помощник не нужен.",
        "pt-BR": "Execute um Atalho, webhook ou comando shell em eventos de sessão e gatilhos. Sem assistente.",
        "tr": "Oturum ve tetikleyici olaylarında Kestirme, webhook veya shell çalıştırın. Yardımcı gerekmez.",
        "pl": "Uruchom Skrót, webhook lub polecenie shell przy zdarzeniach sesji i wyzwalaczy. Pomocnik nie jest potrzebny.",
        "uk": "Запускайте команду, вебхук або shell на подіях сеансу й тригерів. Помічник не потрібен.",
        "zh-Hant": "在工作階段與觸發事件上執行捷徑、Webhook 或 shell 指令。不需要輔助程式。",
    },
    "How long Keepresso held the Mac awake each day, from the decision log. Battery drop is shown when both ends of a session had a reading.": {
        "hu": "Mennyi ideig tartotta ébren a Keepresso a Macet naponta, a döntési naplóból. Az akkucsökkenés akkor látszik, ha a munkamenet mindkét végén volt mérés.",
        "es": "Cuánto tiempo Keepresso mantuvo despierto el Mac cada día, del registro de decisiones. La bajada de batería aparece si ambos extremos de la sesión tuvieron lectura.",
        "fr": "Combien de temps Keepresso a maintenu le Mac éveillé chaque jour, d’après le journal. La baisse de batterie s’affiche si les deux bouts de la session ont une mesure.",
        "de": "Wie lange Keepresso den Mac pro Tag wach hielt, aus dem Entscheidungsprotokoll. Akkurückgang nur, wenn Start und Ende einen Messwert hatten.",
        "zh-Hans": "根据决策日志，Keepresso 每天保持 Mac 唤醒多久。仅当会话两端都有读数时才显示耗电。",
        "it": "Per quanto Keepresso ha tenuto sveglio il Mac ogni giorno, dal registro decisioni. Il calo batteria compare se entrambi i capi della sessione avevano una lettura.",
        "ja": "決定ログから、Keepresso が1日どれだけ Mac を起こしていたか。セッションの開始と終了の両方に測定があるときだけバッテリー低下を表示します。",
        "ko": "결정 로그 기준 Keepresso가 하루 동안 Mac을 얼마나 깨워 두었는지. 세션 양끝에 측정이 있을 때만 배터리 감소를 표시합니다.",
        "ru": "Сколько Keepresso держал Mac бодрствующим за день, по журналу решений. Падение батареи показано, если на обоих концах сеанса было измерение.",
        "pt-BR": "Quanto tempo o Keepresso manteve o Mac acordado por dia, pelo registro. A queda de bateria aparece se os dois lados da sessão tiveram leitura.",
        "tr": "Karar günlüğünden Keepresso’nun Mac’i günde ne kadar uyanık tuttuğu. Pil düşüşü, oturumun iki ucunda da okuma varsa gösterilir.",
        "pl": "Jak długo Keepresso trzymał Maca w czuwaniu każdego dnia, z dziennika decyzji. Spadek baterii, gdy oba końce sesji miały odczyt.",
        "uk": "Скільки Keepresso тримав Mac без сну щодня, з журналу рішень. Падіння батареї показано, якщо на обох кінцях сеансу був вимір.",
        "zh-Hant": "依決策日誌，Keepresso 每天讓 Mac 保持喚醒多久。僅當工作階段兩端都有讀數時才顯示耗電。",
    },
    "Why each session started or stopped, newest first. Saved on disk and restored after a relaunch.": {
        "hu": "Miért indult vagy állt le a munkamenet, legújabb elöl. Lemezen mentve, újraindítás után is megmarad.",
        "es": "Por qué empezó o paró cada sesión, lo más reciente primero. Guardado en disco y restaurado al reabrir.",
        "fr": "Pourquoi chaque session a démarré ou s’est arrêtée, les plus récentes en premier. Enregistré sur disque et restauré après relance.",
        "de": "Warum jede Sitzung startete oder stoppte, neueste zuerst. Auf der Platte gespeichert und nach Neustart wieder da.",
        "zh-Hans": "每次会话为何开始或停止，最新在前。已存盘，重新启动后恢复。",
        "it": "Perché ogni sessione è partita o si è fermata, le più recenti prima. Salvato su disco e ripristinato al riavvio.",
        "ja": "各セッションが始まった／止まった理由。新しい順。ディスクに保存され、再起動後も復元されます。",
        "ko": "각 세션이 시작·중지된 이유, 최신이 위. 디스크에 저장되며 다시 실행해도 복원됩니다.",
        "ru": "Почему каждый сеанс начался или остановился, новые сверху. На диске и восстанавливается после перезапуска.",
        "pt-BR": "Por que cada sessão começou ou parou, as mais recentes primeiro. Salvo no disco e restaurado após reabrir.",
        "tr": "Her oturumun neden başladığı veya durduğu, en yeniler üstte. Diskte saklanır, yeniden açılışta geri yüklenir.",
        "pl": "Dlaczego sesja wystartowała lub stanęła, najnowsze na górze. Zapis na dysku, odtworzenie po restarcie.",
        "uk": "Чому кожен сеанс почався чи зупинився, найновіші зверху. На диску й відновлюється після перезапуску.",
        "zh-Hant": "每次工作階段為何開始或停止，最新在前。已存磁碟，重新啟動後還原。",
    },
    # Long section info strings
    "When a keep-awake session ends on its own (a timer expiring, or trigger conditions dropping), Keepresso can put the display to sleep, lock the screen, start the screen saver, or sleep the Mac. Off by default so a timed session never surprises you. Manual stops, and the battery and thermal safety pauses, never run this action. A brief debounce cancels it if the session restarts right away.": {
        "hu": "Ha a tartás magától véget ér (lejár az időzítő, vagy a triggerek elengednek), a Keepresso altathatja a kijelzőt, zárolhatja a képernyőt, indíthatja a képernyővédőt, vagy altathatja a Macet. Alapból ki, hogy az időzített munkamenet ne lepjen meg. Kézi leállítás, akkumulátor- és hőszünet soha nem futtatja. Rövid debounce törli, ha a munkamenet azonnal újraindul.",
        "es": "Cuando una sesión de mantener despierto termina sola (timer o condiciones), Keepresso puede suspender la pantalla, bloquear, iniciar el salvapantallas o suspender el Mac. Desactivado por defecto para no sorprender. Las paradas manuales y las pausas de batería o térmica no lo ejecutan. Un breve retraso lo cancela si la sesión reinicia al momento.",
        "fr": "Quand une session se termine d’elle-même (minuteur ou déclencheurs), Keepresso peut éteindre l’écran, verrouiller, lancer l’économiseur ou mettre le Mac en veille. Désactivé par défaut pour ne pas surprendre. Arrêts manuels et pauses batterie/thermique ne le lancent pas. Un court debounce l’annule si la session redémarre tout de suite.",
        "de": "Endet eine Wachhalte-Sitzung von selbst (Timer oder Auslöser), kann Keepresso Display schlafen legen, sperren, Bildschirmschoner starten oder den Mac schlafen legen. Standard aus, damit Timed-Sitzungen nicht überraschen. Manueller Stopp und Akku-/Thermopausen führen es nie aus. Kurzes Entprellen bricht ab, wenn die Sitzung sofort neu startet.",
        "zh-Hans": "当保持唤醒会话自行结束（计时到期或触发条件消失）时，Keepresso 可使显示器睡眠、锁定屏幕、启动屏保或让 Mac 睡眠。默认关闭，以免定时会话吓人。手动停止以及电池/热安全暂停从不执行此操作。若会话立刻重启，短暂防抖会取消它。",
        "it": "Quando una sessione di keep-awake finisce da sola (timer o condizioni), Keepresso può spegnere il display, bloccare, avviare il salvaschermo o mettere in stop il Mac. Disattivo di default per non sorprendere. Stop manuali e pause batteria/termiche non la eseguono. Un breve debounce la annulla se la sessione riparte subito.",
        "ja": "スリープ防止セッションが自分で終わると（タイマー満了やトリガー解除）、Keepresso はディスプレイ睡眠、ロック、スクリーンセーバー、Mac のスリープができます。既定はオフで、時間制限セッションに驚かないようにします。手動停止とバッテリー／温度の安全一時停止では実行しません。すぐに再開すると短いデバウンスで取り消します。",
        "ko": "절전 방지 세션이 스스로 끝나면(타이머 만료·트리거 해제) Keepresso가 디스플레이 잠자기, 잠금, 화면 보호기, Mac 잠자기를 할 수 있습니다. 기본은 꺼짐이라 시간 제한 세션이 놀라게 하지 않습니다. 수동 중지와 배터리·열 안전 일시 정지에서는 실행되지 않습니다. 세션이 바로 다시 시작되면 짧은 디바운스로 취소됩니다.",
        "ru": "Когда сеанс удержания заканчивается сам (таймер или триггеры), Keepresso может усыпить дисплей, заблокировать экран, запустить заставку или усыпить Mac. По умолчанию выкл., чтобы таймер не удивлял. Ручная остановка и паузы по батарее/теплу не выполняют это. Короткий debounce отменяет действие, если сеанс сразу стартует снова.",
        "pt-BR": "Quando uma sessão de keep-awake termina sozinha (timer ou condições), o Keepresso pode suspender a tela, bloquear, iniciar o protetor ou suspender o Mac. Desligado por padrão para não surpreender. Paradas manuais e pausas de bateria/térmica não executam. Um debounce curto cancela se a sessão reiniciar na hora.",
        "tr": "Keep-awake oturumu kendi kendine biterse (süre veya tetikleyiciler), Keepresso ekranı uyutabilir, kilitleyebilir, ekran koruyucu açabilir veya Mac’i uyutabilir. Sürpriz olmasın diye varsayılan kapalı. Elle durdurma ve pil/ısı güvenlik durakları bunu çalıştırmaz. Oturum hemen yeniden başlarsa kısa debounce iptal eder.",
        "pl": "Gdy sesja keep-awake kończy się sama (timer lub wyzwalacze), Keepresso może uśpić wyświetlacz, zablokować ekran, włączyć wygaszacz lub uśpić Maca. Domyślnie wyłączone, by nie zaskoczyć. Ręczny stop oraz pauzy baterii/termiczne tego nie robią. Krótki debounce anuluje, jeśli sesja od razu wróci.",
        "uk": "Коли сеанс утримання завершується сам (таймер або тригери), Keepresso може приспати дисплей, заблокувати екран, запустити заставку або приспати Mac. Типово вимкнено, щоб не дивувати. Ручна зупинка та паузи батареї/тепла цього не виконують. Короткий debounce скасовує, якщо сеанс одразу стартує знову.",
        "zh-Hant": "當保持喚醒工作階段自行結束（計時到期或觸發條件消失）時，Keepresso 可使顯示器睡眠、鎖定螢幕、啟動螢幕保護程式或讓 Mac 睡眠。預設關閉，以免定時工作階段嚇人。手動停止以及電池／熱安全暫停從不執行此動作。若工作階段立刻重啟，短暫防抖會取消它。",
    },
    "Wake the Mac at a set time through the administrator helper (pmset schedule / repeat), then optionally start a keep-awake session so it does not fall back asleep before the job runs. Pair with an end-of-session action above for wake, work, sleep. Scheduled wake is reliable on AC power. On battery the firmware may skip it. macOS only allows one system-wide repeating power schedule, so enabling ours replaces whatever was there. The controls stay locked until the helper is installed and ready, the same rule as the thermal fan boost.": {
        "hu": "Ébressze a Macet beállított időben a rendszergazdai segéddel (pmset schedule / repeat), majd opcionálisan indítson tartást, hogy a munka előtt ne aludjon vissza. Párosítsa a fenti munkamenet-végi művelettel: ébredés, munka, alvás. Hálózaton megbízható. Akkuról a firmware kihagyhatja. A macOS csak egy rendszerszintű ismétlődő energiaütemezést enged, a mienk felülírja a korábbit. A vezérlők a segéd telepítéséig zárva maradnak, mint a hőventilátor-erősítésnél.",
        "es": "Despierta el Mac a una hora con el asistente (pmset schedule / repeat) y opcionalmente inicia keep-awake para que no se duerma antes del trabajo. Combínalo con la acción al final de sesión: despertar, trabajar, dormir. Fiable con corriente. Con batería el firmware puede omitirlo. macOS solo permite un horario de energía repetitivo, así que el nuestro sustituye el anterior. Los controles permanecen bloqueados hasta que el asistente esté listo, igual que el impulso de ventiladores.",
        "fr": "Réveillez le Mac à une heure via l’assistant (pmset schedule / repeat), puis démarrez éventuellement une session pour qu’il ne se rendorme pas. Associez à l’action de fin de session : réveil, travail, veille. Fiable sur secteur. Sur batterie le microprogramme peut l’ignorer. macOS n’autorise qu’un planning d’alimentation récurrent, donc le nôtre remplace l’existant. Les commandes restent verrouillées tant que l’assistant n’est pas prêt, comme pour le boost des ventilateurs.",
        "de": "Weckt den Mac zur gewünschten Zeit über den Helfer (pmset schedule / repeat) und startet optional Wachhalten, damit er vor der Arbeit nicht wieder schläft. Kombiniere mit der Aktion nach Sitzungsende: wecken, arbeiten, schlafen. Zuverlässig am Netz. Im Akku kann die Firmware es überspringen. macOS erlaubt nur einen systemweiten Wiederhol-Energieplan, daher ersetzt unserer den vorhandenen. Die Steuerelemente bleiben gesperrt, bis der Helfer bereit ist, wie beim Lüfterboost.",
        "zh-Hans": "通过管理员助理在设定时间唤醒 Mac（pmset schedule / repeat），并可选择启动保持唤醒，以免任务开始前再次入睡。可与上方会话结束动作搭配：唤醒、工作、睡眠。接通电源时可靠。用电池时固件可能跳过。macOS 全系统只允许一套重复电源计划，启用我们的会替换已有计划。控件在助理就绪前保持锁定，与热风扇加速相同。",
        "it": "Sveglia il Mac a un orario con l’assistente (pmset schedule / repeat) e avvia opzionalmente il keep-awake così non si riaddormenta. Abbinalo all’azione di fine sessione: sveglia, lavoro, stop. Affidabile a corrente. A batteria il firmware può saltarlo. macOS consente un solo piano di alimentazione ricorrente; il nostro sostituisce quello esistente. I controlli restano bloccati finché l’assistente non è pronto, come per il boost ventole.",
        "ja": "管理者ヘルパーで指定時刻に Mac を起こし（pmset schedule / repeat）、必要ならスリープ防止を始めて作業前に再スリープしないようにします。上のセッション終了アクションと組み合わせて起床・作業・スリープ。電源接続時は確実、バッテリーでは省略されることがあります。macOS の繰り返し電源スケジュールはシステムで1つだけなので、有効にすると既存のものを置き換えます。ヘルパー準備までは熱ファンブーストと同様にロックされます。",
        "ko": "관리자 도우미로 지정 시각에 Mac을 깨우고(pmset schedule / repeat) 선택적으로 절전 방지를 시작해 작업 전에 다시 잠들지 않게 합니다. 위의 세션 종료 동작과 함께 깨우기·작업·잠자기를 구성하세요. 전원에서는 안정적이고 배터리에서는 펌웨어가 건너뛸 수 있습니다. macOS 반복 전원 일정은 시스템당 하나라 우리의 일정이 기존 것을 대체합니다. 도우미가 준비될 때까지 열 팬 부스트와 같이 잠깁니다.",
        "ru": "Будит Mac в заданное время через помощника (pmset schedule / repeat) и при желании запускает удержание, чтобы он не уснул до работы. Сочетайте с действием в конце сеанса: пробуждение, работа, сон. Надёжно от сети. От батареи прошивка может пропустить. В macOS одно системное повторяющееся расписание питания, и наше заменяет прежнее. Элементы заблокированы, пока помощник не готов, как у разгона вентиляторов.",
        "pt-BR": "Acorda o Mac num horário via assistente (pmset schedule / repeat) e opcionalmente inicia keep-awake para não dormir antes do trabalho. Combine com a ação de fim de sessão: acordar, trabalhar, dormir. Confiável na tomada. Na bateria o firmware pode pular. O macOS só permite uma agenda de energia repetitiva; a nossa substitui a existente. Os controlos ficam bloqueados até o assistente estar pronto, como o impulso das ventoinhas.",
        "tr": "Yönetici yardımcısıyla Mac’i ayarlı saatte uyandırır (pmset schedule / repeat) ve isteğe bağlı keep-awake başlatır ki işten önce tekrar uyumasın. Oturum sonu eylemiyle birleştirin: uyan, çalış, uyu. Şebekede güvenilir. Pilde atlanabilir. macOS tek yinelenen güç planına izin verir; bizimki eskisinin yerini alır. Yardımcı hazır olana kadar fan güçlendirmesi gibi kilitli kalır.",
        "pl": "Budzi Maca o zadanej porze przez pomocnika (pmset schedule / repeat) i opcjonalnie startuje keep-awake, by nie zasnął przed pracą. Połącz z akcją po sesji: budzenie, praca, sen. Niezawodne na zasilaniu. Na baterii firmware może pominąć. macOS ma jeden systemowy powtarzalny harmonogram zasilania, nasz zastępuje poprzedni. Sterowanie zablokowane do czasu gotowości pomocnika, jak przy booście wentylatorów.",
        "uk": "Будить Mac у заданий час через помічника (pmset schedule / repeat) і за бажанням запускає утримання, щоб знову не заснув до роботи. Поєднайте з дією в кінці сеансу: пробудження, робота, сон. Надійно від мережі. Від батареї прошивка може пропустити. У macOS є лише один загальносистемний повторюваний розклад живлення, тому наш замінює наявний. Елементи заблоковані, доки помічник не готовий, як у розгоні вентиляторів.",
        "zh-Hant": "透過管理員輔助程式在設定時間喚醒 Mac（pmset schedule / repeat），並可選擇啟動保持喚醒，以免工作開始前再次入睡。可與上方工作階段結束動作搭配：喚醒、工作、睡眠。接電源時可靠；使用電池時韌體可能略過。macOS 全系統只允許一套重複電源排程，啟用我們的會取代既有排程。控制項在輔助程式就緒前保持鎖定，與熱風扇加速相同。",
    },
    "When something happens in Keepresso, run a Shortcut, POST a webhook, or run a shell command. Useful for a push to your phone when an overnight agent finishes (ntfy, or a Shortcut that sends a notification). Hooks are suspended while you edit them, so a half-written command never runs. No administrator helper needed. User-authored shell commands are intentional in this unsandboxed app: only add commands you trust.": {
        "hu": "Ha a Keepressóban történik valami, futtasson Parancsot, webhookot vagy shell-parancsot. Hasznos éjszakai ügynök végén a telefonra (ntfy vagy értesítő Parancs). Szerkesztés közben a hookok szünetelnek. Rendszergazdai segéd nem kell. A saját shell-parancsok szándékosak ebben a nem sandboxolt appban: csak megbízható parancsokat adjon hozzá.",
        "es": "Cuando pasa algo en Keepresso, ejecuta un Atajo, un webhook o un comando shell. Útil para un aviso al teléfono al acabar un agente nocturno (ntfy o un Atajo). Los ganchos se suspenden al editarlos. No hace falta el asistente. Los comandos shell son a propósito en esta app sin sandbox: solo añade los de confianza.",
        "fr": "Quand quelque chose se passe dans Keepresso, lancez un Raccourci, un webhook ou une commande shell. Pratique pour une notif téléphone quand un agent de nuit finit (ntfy ou un Raccourci). Les hooks sont suspendus pendant l’édition. Pas d’assistant requis. Les commandes shell sont volontaires dans cette app non sandboxée : n’ajoutez que ce en quoi vous avez confiance.",
        "de": "Wenn in Keepresso etwas passiert, führe einen Kurzbefehl, Webhook oder Shell-Befehl aus. Nützlich fürs Handy, wenn ein Nacht-Agent fertig ist (ntfy oder Kurzbefehl). Hooks ruhen während der Bearbeitung. Kein Helfer nötig. Shell-Befehle sind in dieser unsandboxierten App beabsichtigt: nur vertrauenswürdige hinzufügen.",
        "zh-Hans": "Keepresso 中发生事件时，运行快捷指令、POST Webhook 或 shell 命令。适合通宵代理结束后推送到手机（ntfy 或发通知的快捷指令）。编辑时钩子暂停。不需要管理员助理。在此未沙盒应用中允许用户 shell 命令：只添加你信任的命令。",
        "it": "Quando succede qualcosa in Keepresso, esegui un Comando, un webhook o uno shell. Utile per un push al telefono a fine agente notturno (ntfy o un Comando). Gli hook sono sospesi in modifica. Nessun assistente. I comandi shell sono voluti in questa app non sandbox: aggiungi solo ciò di cui ti fidi.",
        "ja": "Keepresso で何かが起きるとショートカット、Webhook、シェルを実行します。夜間エージェント終了時のスマホ通知（ntfy や通知ショートカット）に便利。編集中はフックを停止。管理者ヘルパーは不要。サンドボックスなしの本アプリではユーザーシェルを許可します。信頼できるコマンドだけ追加してください。",
        "ko": "Keepresso에서 일이 생기면 단축어, 웹훅 POST, 셸을 실행합니다. 야간 에이전트가 끝날 때 폰 푸시(ntfy·알림 단축어)에 유용합니다. 편집 중에는 훅이 일시 중지됩니다. 관리자 도우미 불필요. 샌드박스 없는 이 앱에서 사용자 셸은 의도적입니다. 신뢰하는 명령만 추가하세요.",
        "ru": "Когда в Keepresso что-то происходит, запускайте команду, вебхук или shell. Удобно для пуша на телефон после ночного агента (ntfy или команда с уведомлением). Хуки приостановлены при правке. Помощник не нужен. Пользовательский shell намерен в непесочничном приложении: добавляйте только доверенные команды.",
        "pt-BR": "Quando algo acontece no Keepresso, execute um Atalho, webhook ou shell. Útil para push no telefone ao terminar um agente noturno (ntfy ou Atalho). Hooks ficam suspensos na edição. Sem assistente. Comandos shell são intencionais neste app sem sandbox: só adicione os de confiança.",
        "tr": "Keepresso’da bir şey olunca Kestirme, webhook veya shell çalıştırın. Gece ajanı bitince telefona push için (ntfy veya bildirim Kestirmesi). Düzenlerken kancalar durur. Yönetici yardımcısı gerekmez. Sandbox’suz bu uygulamada kullanıcı shell komutları bilerek var: yalnızca güvendiklerinizi ekleyin.",
        "pl": "Gdy w Keepresso coś się wydarzy, uruchom Skrót, webhook lub shell. Przydatne na push na telefon po nocnym agencie (ntfy lub Skrót). Haki wstrzymane podczas edycji. Pomocnik nie jest potrzebny. Polecenia shell są zamierzone w niesandboxowanej apce: dodawaj tylko zaufane.",
        "uk": "Коли в Keepresso щось відбувається, запускайте команду, вебхук або shell. Зручно для пуша на телефон після нічного агента (ntfy чи команда зі сповіщенням). Хуки призупинені під час редагування. Помічник не потрібен. Користувацький shell навмисний у незапісочниці: додавайте лише довірені команди.",
        "zh-Hant": "Keepresso 中發生事件時，執行捷徑、POST Webhook 或 shell 指令。適合通宵代理結束後推送到手機（ntfy 或發通知的捷徑）。編輯時鉤子暫停。不需要管理員輔助程式。在此未沙盒應用中允許使用者 shell 指令：只新增你信任的指令。",
    },
    "These cover the times a session ends without you: a timer expiring, or trigger conditions dropping. Stopping it yourself stays silent, since you already know. The warning is a heads-up a few minutes before a timed session runs out, so you can extend it before the Mac drops off. Actions that put the Mac to sleep live under Automation.": {
        "hu": "A munkamenet nélküled végződő eseteire: lejár az időzítő, vagy elengednek a triggerek. Ha te állítod le, csendben marad. A figyelmeztetés percekkel az időzített vég előtt jön, hogy meghosszabbíthasd. A Macet altató műveletek az Automatizálás alatt vannak.",
        "es": "Cubre cuando la sesión termina sin ti: timer o condiciones. Si la paras tú, no avisa. El aviso es unos minutos antes de que acabe un timer, para alargarla. Las acciones que duermen el Mac están en Automatización.",
        "fr": "Couvre les fins de session sans vous : minuteur ou déclencheurs. Un arrêt manuel reste silencieux. L’avertissement arrive quelques minutes avant la fin d’un minuteur. Les actions de veille sont sous Automatisation.",
        "de": "Für Sitzungsenden ohne dich: Timer oder Auslöser. Selbst stoppen bleibt still. Die Warnung kommt Minuten vor dem Timer-Ende. Aktionen, die den Mac schlafen legen, liegen unter Automatisierung.",
        "zh-Hans": "覆盖你不在场时会话结束的情况：计时到期或触发条件消失。自己停止则保持安静。警告在定时结束前几分钟发出，便于延长。让 Mac 睡眠的操作在“自动化”中。",
        "it": "Copre le fine sessione senza di te: timer o condizioni. Se la fermi tu, resta silenzioso. L’avviso arriva pochi minuti prima della fine a timer. Le azioni che mettono in stop il Mac sono in Automazione.",
        "ja": "タイマー満了やトリガー解除など、自分で止めない終了を対象にします。自分で止めたときは静かにします。警告は時間制限の数分前。Mac をスリープさせる操作は自動化にあります。",
        "ko": "타이머 만료·트리거 해제처럼 직접 멈추지 않은 종료를 다룹니다. 직접 중지하면 조용합니다. 경고는 시간 제한 몇 분 전입니다. Mac을 잠자기하는 동작은 자동화에 있습니다.",
        "ru": "Для конца сеанса без вас: таймер или триггеры. Ручная остановка молчит. Предупреждение за несколько минут до конца таймера. Действия сна Mac собраны в разделе Автоматизация.",
        "pt-BR": "Cobre quando a sessão termina sem você: timer ou condições. Se parar você mesmo, fica em silêncio. O aviso vem minutos antes do fim do timer. Ações que dormem o Mac ficam em Automação.",
        "tr": "Oturum sizin olmadan bittiğinde: süre veya tetikleyiciler. Kendiniz durdurursanız sessiz. Uyarı zamanlı bitişten birkaç dakika önce. Mac’i uyutan eylemler Otomasyon’da.",
        "pl": "Gdy sesja kończy się bez ciebie: timer lub wyzwalacze. Ręczny stop milczy. Ostrzeżenie na kilka minut przed końcem timera. Akcje usypiające Maca są w Automatyzacji.",
        "uk": "Коли сеанс завершується без вас: таймер або тригери. Ручна зупинка мовчить. Попередження за кілька хвилин до кінця таймера. Дії сну Mac розташовані в Автоматизації.",
        "zh-Hant": "涵蓋你不在場時工作階段結束的情況：計時到期或觸發條件消失。自己停止則保持安靜。警告在定時結束前幾分鐘發出，便於延長。讓 Mac 睡眠的操作在「自動化」中。",
    },
}

# Core already has hook event labels etc. from earlier session; nothing new required in CORE beyond what's there.
NEW_CORE = {}
