# -*- coding: utf-8 -*-
# Italian overlay for catalog_app.py: English source -> Italian.
APP = {
    "Add": "Aggiungi",
    "Add:": "Aggiungi:",
    "Clear": "Cancella",
    "Close": "Chiudi",
    "Done": "Fine",
    "Save": "Salva",
    "Enable": "Attiva",
    "Enabled": "Attivato",
    "Installed": "Installato",
    "Remove": "Rimuovi",
    "Remove condition": "Rimuovi condizione",
    "Resume": "Riprendi",
    "Later": "Più tardi",
    "Learn more": "Scopri di più",
    "Re-check": "Ricontrolla",
    "Run Test": "Esegui test",
    "Match": "Corrispondenza",
    "Threshold": "Soglia",
    "Battery threshold": "Soglia batteria",
    "Presence": "Presenza",
    "Menu bar": "Barra dei menu",
    "Battery": "Batteria",
    "Welcome": "Benvenuto",
    "Keeps the Mac running with the lid shut and no external display. This flips a system setting that needs administrator rights: silent with the administrator helper installed (Preferences ▸ General), otherwise macOS asks for your password.": "Mantiene il Mac in funzione con il coperchio chiuso e senza display esterno. Questo cambia un'impostazione di sistema che richiede i privilegi di amministratore: in silenzio con l'assistente amministratore installato (Impostazioni ▸ Generali), altrimenti macOS chiede la password.",
    "Turns closed-display mode on when a keep-awake session starts and off when it ends or Keepresso quits.": "Attiva la modalità a schermo chiuso quando inizia una sessione di veglia e la disattiva quando termina o Keepresso viene chiuso.",
    "Grace period": "Periodo di tolleranza",
    "Section": "Sezione",
    "Schedule": "Programmazione",
    "Set Duration": "Imposta durata",
    "For": "Per",
    "From": "Dalle",
    "To": "Alle",
    "Until": "Fino a",
    "When": "Quando",
    "Below": "Sotto",
    "Power": "Alimentazione",
    "Display": "Display",
    "Network": "Rete",
    "Media": "Multimedia",
    "Backup": "Backup",
    "Folder": "Cartella",
    "Downloads": "Download",
    "Touch": "Aggiorna",
    "Resolution": "Risoluzione",
    "Startup": "Avvio",
    "Gaming": "Gaming",
    "None": "Nessuno",
    "any": "una qualsiasi",
    "all": "tutte",
    "of these are true:": "di queste condizioni sono vere:",
    "1 minute": "1 minuto",
    "2 minutes": "2 minuti",
    "5 minutes": "5 minuti",
    "10 seconds": "10 secondi",
    "30 seconds": "30 secondi",
    "15 minutes": "15 minuti",
    "30 minutes": "30 minuti",
    "1 hour": "1 ora",
    "2 hours": "2 ore",
    "4 hours": "4 ore",
    "8 hours": "8 ore",
    "No grace": "Nessuna tolleranza",
    "Every 1 minute": "Ogni minuto",
    "Every 5 minutes": "Ogni 5 minuti",
    "Every 10 minutes": "Ogni 10 minuti",
    "Every 30 minutes": "Ogni 30 minuti",
    "Every": "Ogni",
    "After": "Dopo",
    "Keepresso": "Keepresso",
    "About Keepresso": "Informazioni su Keepresso",
    "Welcome to Keepresso": "Benvenuto in Keepresso",
    "Keepresso Setup": "Configurazione di Keepresso",
    "Keepresso Helper": "Assistente di Keepresso",
    "Preferences": "Impostazioni",
    "Preferences…": "Impostazioni…",
    "A menu-bar app that keeps your Mac awake on your terms.":
        "Un’app della barra dei menu che tiene sveglio il tuo Mac alle tue condizioni.",
    "AWDL watchdog": "Sorveglianza AWDL",
    "Activate by triggers": "Attiva tramite attivatori",
    "Administrator helper": "Assistente amministratore",
    "Allow Bluetooth access…": "Consenti l’accesso al Bluetooth…",
    "Allow Wi-Fi access…": "Consenti l’accesso al Wi-Fi…",
    "Allow calendar access…": "Consenti l’accesso al calendario…",
    "App is frontmost": "L’app è in primo piano",
    "App is running": "L’app è in esecuzione",
    "App match & grace period": "Corrispondenza dell’app e periodo di tolleranza",
    "Apply or remove": "Applica o rimuovi",
    "Approve…": "Approva…",
    "Apps & Activity": "App e attività",
    "Bluetooth device connected": "Dispositivo Bluetooth connesso",
    "Bluetooth rules need Bluetooth access (System Settings ▸ Privacy)":
        "Le regole Bluetooth richiedono l’accesso al Bluetooth (Impostazioni di Sistema ▸ Privacy)",
    "CPU load": "Carico della CPU",
    "CPU threshold": "Soglia della CPU",
    "Camera in use": "Fotocamera in uso",
    "Change…": "Modifica…",
    "Charging": "In carica",
    "Check for Updates…": "Verifica aggiornamenti…",
    "Closed-display mode": "Modalità a schermo chiuso",
    "Contacting the helper…": "Contatto dell’assistente in corso…",
    "Create a virtual display": "Crea un display virtuale",
    "Currently paused from the menu bar.": "Attualmente in pausa dalla barra dei menu.",
    "Custom Duration…": "Durata personalizzata…",
    "During calendar events": "Durante gli eventi del calendario",
    "Export Settings…": "Esporta impostazioni…",
    "Import Settings…": "Importa impostazioni…",
    "External display connected": "Display esterno collegato",
    "Fix…": "Correggi…",
    "GNU GPL v3.0": "GNU GPL v3.0",
    "Gaming & Streaming": "Gaming e streaming",
    "Gaming & Streaming…": "Gaming e streaming…",
    "Get Started": "Inizia",
    "Global shortcut": "Abbreviazione globale",
    "Headless Setup": "Configurazione senza monitor",
    "Headless Setup…": "Configurazione senza monitor…",
    "Headless virtual display (experimental)": "Display virtuale senza monitor (sperimentale)",
    "Helper installed and responding": "Assistente installato e funzionante",
    "HiDPI (Retina)": "HiDPI (Retina)",
    "How do you use your Mac?": "Come usi il tuo Mac?",
    "Install Helper…": "Installa assistente…",
    "Install…": "Installa…",
    "Jitter test": "Test del jitter",
    "Keep a disk spinning": "Mantieni un disco in rotazione",
    "Keep awake with lid closed": "Tieni sveglio con il coperchio chiuso",
    "Keep awake with the lid closed": "Tieni sveglio con il coperchio chiuso",
    "Keep awake": "Tieni sveglio",
    "Keep me active": "Mantienimi attivo",
    "Keeping the Mac awake now": "Il Mac è tenuto sveglio ora",
    "Keepresso decisions": "Decisioni di Keepresso",
    "Measuring, about 10 seconds…": "Misurazione in corso, circa 10 secondi…",
    "Microphone in use": "Microfono in uso",
    "Network & Devices": "Rete e dispositivi",
    "Network activity": "Attività di rete",
    "Network threshold": "Soglia di rete",
    "No Wi-Fi network joined": "Nessuna rete Wi-Fi connessa",
    "No apps running": "Nessuna app in esecuzione",
    "No conditions yet, so the Mac can sleep.":
        "Ancora nessuna condizione, quindi il Mac può andare in stop.",
    "No conditions yet. Add some in Preferences ▸ Triggers.":
        "Ancora nessuna condizione. Aggiungine qualcuna in Impostazioni ▸ Attivatori.",
    "No days selected means every day.": "Nessun giorno selezionato equivale a tutti i giorni.",
    "No paired devices": "Nessun dispositivo abbinato",
    "No session activity yet.": "Ancora nessuna attività di sessione.",
    "No volumes mounted": "Nessun volume montato",
    "Not available on this macOS version.": "Non disponibile in questa versione di macOS.",
    "Nothing is holding the Mac awake right now.": "Al momento nulla tiene sveglio il Mac.",
    "Notify when a session ends": "Avvisa quando una sessione termina",
    "Notify when auto-pausing and resuming": "Avvisa alla pausa e alla ripresa automatiche",
    "On AC power": "Collegato alla corrente",
    "On battery": "A batteria",
    "On session end": "Al termine della sessione",
    "Only while brewing": "Solo durante l’infusione",
    "Open Login Items": "Apri Elementi di login",
    "Open Settings": "Apri Impostazioni",
    "Overnight (22:00-6:00)": "Di notte (22:00-6:00)",
    "Pause AWDL automatically while gaming": "Sospendi AWDL automaticamente durante il gioco",
    "Pause AWDL now": "Sospendi AWDL ora",
    "Pause Triggers": "Sospendi attivatori",
    "Pause on low battery": "Sospendi con batteria scarica",
    "Play a sound": "Riproduci un suono",
    "Playing a game": "Gioco in corso",
    "Power & Display": "Alimentazione e display",
    "Presets": "Preset",
    "Prevent display sleep": "Impedisci lo stop del display",
    "Prevent system sleep": "Impedisci lo stop del sistema",
    "Process is running": "Il processo è in esecuzione",
    "Quit Keepresso": "Esci da Keepresso",
    "Reduce lag and jitter": "Riduci lag e jitter",
    "Reinstall Helper": "Reinstalla assistente",
    "Remind me it's still on": "Ricordami che è ancora attivo",
    "Repeat the reminder": "Ripeti il promemoria",
    "Restore default presets": "Ripristina i preset predefiniti",
    "Resume AWDL after leaving the game": "Riprendi AWDL dopo l’uscita dal gioco",
    "Resume Triggers": "Riprendi attivatori",
    "Session end": "Fine sessione",
    "Set Up…": "Configura…",
    "Show Welcome Screen…": "Mostra la schermata di benvenuto…",
    "Show countdown in menu bar": "Mostra il conto alla rovescia nella barra dei menu",
    "Show less": "Mostra meno",
    "Show more": "Mostra altro",
    "Start keep-awake on launch": "Avvia la veglia all’avvio",
    "The helper needs attention": "L’assistente richiede attenzione",
    "The test couldn't run. Check that you're online and try again.":
        "Impossibile eseguire il test. Verifica di essere online e riprova.",
    "The watchdog below should smooth this out; re-run the test with it on to confirm.":
        "La sorveglianza qui sotto dovrebbe attenuare il problema; riesegui il test con la sorveglianza attiva per conferma.",
    "Times & days": "Orari e giorni",
    "Toggle shortcut": "Abbreviazione per attivare/disattivare",
    "Triggers paused. Controlling manually for now.":
        "Attivatori sospesi. Per ora il controllo è manuale.",
    "Until a Time…": "Fino a un orario…",
    "VPN connected": "VPN connessa",
    "View on GitHub": "Vedi su GitHub",
    "Volume is mounted": "Il volume è montato",
    "Watch a folder for downloads…": "Monitora una cartella per i download…",
    "While frontmost": "Mentre è in primo piano",
    "While running": "Mentre è in esecuzione",
    "Work hours (weekdays 9:00-18:00)": "Orario di lavoro (feriali 9:00-18:00)",
    "Audio playing": "Audio in riproduzione",
    "Paused": "In pausa",
    "Brewing": "In infusione",
    "Idle": "Inattivo",
    "System can sleep": "Il sistema può andare in stop",
    "No conditions yet": "Ancora nessuna condizione",
    "Battery below %d%%, Keepresso sessions and Agent work paused until plugged in":
        "Batteria sotto il %d%%, sessioni di Keepresso e lavoro degli agenti in pausa fino al collegamento all'alimentazione",
    "Stops in %@": "Si ferma tra %@",
    "Awake for %@": "Sveglio da %@",
    "Active": "Attivo",
    "Held by %@": "Mantenuto da %@",
    "Waiting for any condition": "In attesa di una condizione qualsiasi",
    "Waiting on %@": "In attesa di %@",
    "%d condition": "%d condizione",
    "%d conditions": "%d condizioni",
    "Approve Keepresso again in System Settings.":
        "Approva di nuovo Keepresso in Impostazioni di Sistema.",
    "The helper isn't responding; reinstall it.": "L’assistente non risponde; reinstallalo.",
    "Waiting for a game to come to the front": "In attesa che un gioco passi in primo piano",
    "AWDL paused": "AWDL in pausa",
    "AWDL paused for gaming": "AWDL in pausa per il gioco",
    "Game closed, AWDL back in %ds": "Gioco chiuso, AWDL torna tra %d s",
    "Latency looks clean.": "La latenza sembra pulita.",
    "Once-a-second spikes: this looks like AWDL.":
        "Picchi una volta al secondo: sembra AWDL.",
    "Spiky, but not on AWDL's cadence (congestion or a weak signal).":
        "Picchi irregolari, ma non alla cadenza di AWDL (congestione o segnale debole).",
    "Not enough replies to judge.": "Risposte insufficienti per giudicare.",
    "AWDL is on right now": "AWDL è attivo in questo momento",
    "AWDL is off right now": "AWDL è disattivato in questo momento",
    "AWDL state unknown": "Stato di AWDL sconosciuto",
    "Agentic coding": "Programmazione con agenti",
    "Stay awake while Claude, Codex, or Grok is running.":
        "Resta sveglio mentre Claude, Codex o Grok è in esecuzione.",
    "Gaming & streaming": "Gaming e streaming",
    "Stay awake while a game or cloud-gaming app is in front.":
        "Resta sveglio mentre un gioco o un’app di cloud gaming è in primo piano.",
    "Meetings & calls": "Riunioni e chiamate",
    "Stay awake whenever the camera or microphone is in use.":
        "Resta sveglio quando la fotocamera o il microfono è in uso.",
    "Remote access": "Accesso remoto",
    "Stay awake while someone is connected over SSH.":
        "Resta sveglio mentre qualcuno è connesso via SSH.",
    "Keep it manual for now": "Per ora resta in manuale",
    "Just toggle keep-awake yourself, and set up your own triggers later in Preferences.":
        "Attiva e disattiva la veglia da solo, e configura i tuoi attivatori più avanti in Impostazioni.",
    "Launch at login": "Apri al login",
    "Start Keepresso automatically when you log in.":
        "Avvia Keepresso automaticamente quando esegui il login.",
    "Notifications": "Notifiche",
    "Let Keepresso remind you when a long session is still keeping the Mac awake.":
        "Lascia che Keepresso ti ricordi quando una lunga sessione sta ancora tenendo sveglio il Mac.",
    "Approve a small helper once and the privileged extras (lid-closed mode, AWDL pausing) never ask for your password again. Set and forget; removable in Preferences.":
        "Approva una volta un piccolo assistente e le funzioni con privilegi (modalità a schermo chiuso, pausa di AWDL) non chiederanno mai più la password. Imposta e dimentica; rimovibile dalle Impostazioni.",
    "Location access (Wi-Fi rules)": "Accesso alla posizione (regole Wi-Fi)",
    "Bluetooth access (device rules)": "Accesso al Bluetooth (regole dei dispositivi)",
    "Calendar access (event rule)": "Accesso al calendario (regola degli eventi)",
    "Keepresso launches at login, so it returns after a reboot.":
        "Keepresso si apre al login, quindi torna dopo un riavvio.",
    "Keepresso isn't set to launch at login, so it won't run after an unattended reboot.":
        "Keepresso non è impostato per aprirsi al login, quindi non sarà in esecuzione dopo un riavvio non presidiato.",
    "Turn on “Launch at login” in Keepresso's settings.":
        "Attiva “Apri al login” nelle impostazioni di Keepresso.",
    "Keepresso can read the current Wi-Fi network name for your Wi-Fi triggers.":
        "Keepresso può leggere il nome della rete Wi-Fi attuale per i tuoi attivatori Wi-Fi.",
    "Without Location access Keepresso can't read the Wi-Fi network name, so Wi-Fi triggers won't match.":
        "Senza l’accesso alla posizione Keepresso non può leggere il nome della rete Wi-Fi, quindi gli attivatori Wi-Fi non troveranno corrispondenza.",
    "Allow Location access for Keepresso.": "Consenti a Keepresso l’accesso alla posizione.",
    "Keepresso can see which paired devices are connected for your Bluetooth triggers.":
        "Keepresso può vedere quali dispositivi abbinati sono connessi per i tuoi attivatori Bluetooth.",
    "Without Bluetooth access Keepresso can't see paired devices, so Bluetooth triggers won't match.":
        "Senza l’accesso al Bluetooth Keepresso non può vedere i dispositivi abbinati, quindi gli attivatori Bluetooth non troveranno corrispondenza.",
    "Allow Bluetooth access for Keepresso.": "Consenti a Keepresso l’accesso al Bluetooth.",
    "Keepresso can see when a calendar event is in progress for your calendar trigger.":
        "Keepresso può vedere quando un evento del calendario è in corso per il tuo attivatore del calendario.",
    "Without full calendar access Keepresso can't see events, so the calendar trigger won't match.":
        "Senza l’accesso completo al calendario Keepresso non può vedere gli eventi, quindi l’attivatore del calendario non troverà corrispondenza.",
    "Allow full calendar access for Keepresso.":
        "Consenti a Keepresso l’accesso completo al calendario.",
    "Keepresso can post the “still brewing” reminder.":
        "Keepresso può inviare il promemoria “ancora in infusione”.",
    "Notifications are off, so the “still brewing” reminder can't appear.":
        "Le notifiche sono disattivate, quindi il promemoria “ancora in infusione” non può comparire.",
    "Allow notifications for Keepresso.": "Consenti le notifiche per Keepresso.",
    "Above %d%%": "Sopra il %d%%",
    "Above %@": "Sopra %@",
    "Version %@": "Versione %@",
    "Remove “%@”": "Rimuovi “%@”",
    "On current Wi-Fi (%@)": "Sulla rete Wi-Fi attuale (%@)",
    "keep the Mac awake with the lid closed":
        "tenere sveglio il Mac con il coperchio chiuso",
    "switch closed-display mode with the session":
        "attivare e disattivare la modalità a schermo chiuso con la sessione",
    "pause AWDL (turn off the Wi-Fi AirDrop/Handoff radio hops)":
        "sospendere AWDL (disattivare i salti radio Wi-Fi di AirDrop/Handoff)",
    "macOS is asking for your administrator password to %@. The dialog may be titled “osascript”: that's Keepresso running the command, and nothing else is changed. To stop these prompts for good, install the administrator helper (Preferences ▸ General).":
        "macOS sta chiedendo la password di amministratore per %@. La finestra di dialogo potrebbe intitolarsi “osascript”: è Keepresso che esegue il comando, e nient’altro viene modificato. Per eliminare per sempre queste richieste, installa l’assistente amministratore (Impostazioni ▸ Generali).",
    "Keepresso keeps your Mac awake on your terms. It lives in the menu bar near the clock, with no Dock icon. Click its cup any time to start or stop.":
        "Keepresso tiene sveglio il tuo Mac alle tue condizioni. Vive nella barra dei menu vicino all’orologio, senza icona nel Dock. Fai clic sulla sua tazzina in qualsiasi momento per avviare o fermare.",
    "Pick one to set up matching triggers, or keep it manual and add your own later. You can change this any time in Preferences.":
        "Scegline uno per configurare gli attivatori adatti, oppure resta in manuale e aggiungi i tuoi più avanti. Puoi cambiare in qualsiasi momento dalle Impostazioni.",
    "Activation is controlled by triggers.\nEdit them in Preferences.":
        "L’attivazione è controllata dagli attivatori.\nModificali nelle Impostazioni.",
    "Why each session started or stopped, newest first. Kept in memory; clears on relaunch.":
        "Perché ogni sessione è iniziata o terminata, dalla più recente. Conservato in memoria; si azzera al riavvio dell’app.",
    "Every app's live power assertions, not just Keepresso's, the same data pmset -g assertions prints.":
        "Le asserzioni di energia attive di ogni app, non solo quelle di Keepresso, gli stessi dati che stampa pmset -g assertions.",
    "Lets the Mac sleep once battery charge drops below this level, even mid-session, so it doesn't run flat.":
        "Lascia che il Mac vada in stop quando la carica della batteria scende sotto questo livello, anche a metà sessione, così non si scarica del tutto.",
    "Shows the remaining time next to the menu-bar icon during a timed session.":
        "Mostra il tempo rimanente accanto all’icona nella barra dei menu durante una sessione a tempo.",
    "Reopen the first-run welcome, with quick one-click setup for how you use your Mac.":
        "Riapre il benvenuto del primo avvio, con la configurazione rapida in un clic in base a come usi il Mac.",
    "If that time already passed today, it means tomorrow.":
        "Se quell’orario è già passato oggi, si intende domani.",
    "Runs past midnight into the next day.":
        "Prosegue oltre la mezzanotte fino al giorno successivo.",
    "Keeps the Mac awake while a partial-download file (.crdownload, .download, .part, and the like) exists in the chosen folder, then lets it sleep once the download finishes. Holds for 30 seconds between files in a batch.":
        "Tiene sveglio il Mac finché nella cartella scelta esiste un file di download parziale (.crdownload, .download, .part e simili), poi lo lascia andare in stop quando il download termina. Mantiene per 30 secondi tra un file e l’altro di una serie.",
    "Stays awake on battery too; the display turns off when the lid closes. Turn it off before putting it in a bag.":
        "Resta sveglio anche a batteria; il display si spegne quando chiudi il coperchio. Disattivalo prima di metterlo in una borsa.",
    "The calendar rule needs Calendar access (System Settings ▸ Privacy)":
        "La regola del calendario richiede l’accesso al Calendario (Impostazioni di Sistema ▸ Privacy)",
    "Wi-Fi rules need Location access (System Settings ▸ Privacy)":
        "Le regole Wi-Fi richiedono l’accesso alla posizione (Impostazioni di Sistema ▸ Privacy)",
    "Checks an always-on Mac (e.g. a headless Mac mini) needs. Keepresso can read these but can't change the system ones, so use the links and commands below.":
        "I controlli che servono a un Mac sempre acceso (ad es. un Mac mini senza monitor). Keepresso può leggerli ma non può modificare quelli di sistema, quindi usa i link e i comandi qui sotto.",
    "macOS hops the Wi-Fi radio off-channel for AWDL about once a second, which shows up as ping spikes mid-game or mid-stream. Diagnose it here, and pause AWDL for the session if it's the culprit.":
        "macOS sposta la radio Wi-Fi fuori canale per AWDL circa una volta al secondo, il che si manifesta come picchi di ping in piena partita o in pieno streaming. Diagnostica il problema qui e, se il colpevole è AWDL, sospendilo per la sessione.",
    "Pings 1.1.1.1 five times a second for 10 seconds and checks whether latency spikes on AWDL's once-a-second cadence.":
        "Esegue il ping di 1.1.1.1 cinque volte al secondo per 10 secondi e verifica se la latenza mostra picchi alla cadenza di una volta al secondo di AWDL.",
    "Counts only while a game (or a cloud-gaming app) is the active window, not just running in the background. Keeps holding for 5 minutes after you switch away.":
        "Conta solo mentre un gioco (o un’app di cloud gaming) è la finestra attiva, non se è semplicemente in esecuzione in background. Continua a mantenere per 5 minuti dopo che passi ad altro.",
    "How long the pause lingers after the game stops being the active window, so a quick alt-tab doesn't flap the radios. Shorter brings AirDrop and Handoff back faster; longer rides out launchers and loading screens.":
        "Per quanto tempo la pausa persiste dopo che il gioco smette di essere la finestra attiva, così un rapido alt-tab non fa oscillare le radio. Più breve riporta prima AirDrop e Handoff; più lunga supera launcher e schermate di caricamento.",
    "Posts a notification when a game is detected and AWDL pauses, and again when it resumes. A notice that your administrator password is needed is always sent (even behind a fullscreen game), regardless of this switch.":
        "Invia una notifica quando viene rilevato un gioco e AWDL va in pausa, e di nuovo quando riprende. L’avviso che serve la password di amministratore viene sempre inviato (anche dietro un gioco a tutto schermo), indipendentemente da questo interruttore.",
    "One step left, in System Settings: under General ▸ Login Items & Extensions (“Login Items” on older macOS), find Keepresso in the “Allow in the Background” list and turn its switch ON. macOS asks for your administrator password once; this updates by itself when you're done.":
        "Manca un passaggio, in Impostazioni di Sistema: in Generali ▸ Elementi di login ed estensioni (“Elementi di login” sui macOS meno recenti), trova Keepresso nell’elenco “Consenti in background” e attiva il suo interruttore. macOS chiede la password di amministratore una volta; questa voce si aggiorna da sola quando hai finito.",
    "Turns the pause on right now and keeps it on until you turn it off or quit Keepresso (it isn't tied to whether a keep-awake session is brewing). While it's on, AirDrop, Handoff, Sidecar, and Continuity Camera take a break, and the once-a-second lag spikes stop. Everything comes back the moment you turn it off or quit Keepresso; even if the app crashes, macOS is restored automatically. With the administrator helper installed the switch is always instant and silent; without it, macOS asks for your password once per launch (the system dialog may show “osascript”, which is Keepresso running the command).":
        "Attiva subito la pausa e la mantiene finché non la disattivi o esci da Keepresso (non è legata al fatto che una sessione di veglia sia in corso). Mentre è attiva, AirDrop, Handoff, Sidecar e Fotocamera Continuity si prendono una pausa, e i picchi di lag una volta al secondo cessano. Tutto torna nel momento in cui la disattivi o esci da Keepresso; anche se l’app va in crash, macOS viene ripristinato automaticamente. Con l’assistente amministratore installato l’interruttore è sempre istantaneo e silenzioso; senza, macOS chiede la password una volta per avvio (la finestra di sistema potrebbe mostrare “osascript”, cioè Keepresso che esegue il comando).",
    "Watches for a game (or a cloud-gaming app like GeForce NOW) as the active window and pauses AWDL on its own, then lifts the pause a little after you switch away (the delay below). It only counts while the game is in front and in use, not just running in the background. Without the administrator helper, turning this on asks for your password once per app run, right now rather than mid-game; with the helper it never asks at all. No trigger setup needed: leave this on and forget it.":
        "Controlla se un gioco (o un’app di cloud gaming come GeForce NOW) è la finestra attiva e sospende AWDL da solo, poi rimuove la pausa poco dopo che passi ad altro (il ritardo qui sotto). Conta solo mentre il gioco è in primo piano e in uso, non se è semplicemente in esecuzione in background. Senza l’assistente amministratore, attivare questa opzione chiede la password una volta per esecuzione dell’app, subito anziché a metà partita; con l’assistente non la chiede mai. Nessun attivatore da configurare: lascialo attivo e dimenticatene.",
    "Pause AWDL to steady your connection, and test your jitter, in Gaming & Streaming.":
        "Sospendi AWDL per stabilizzare la connessione e misura il jitter in Gaming e streaming.",
    "General": "Generali",
    "Triggers": "Attivatori",
    "Reminder": "Promemoria",
    "Disk": "Disco",
    "Activity": "Attività",
    "Indefinitely": "Indefinitamente",
    "Update Session": "Aggiorna sessione",
    "Start": "Avvia",
    "Met, in grace period": "Soddisfatta, in tolleranza",
    "Met": "Soddisfatta",
    "Not met": "Non soddisfatta",
    "Copied!": "Copiato!",
    "Copy command": "Copia comando",
    "OK": "OK",
    "Needs attention": "Richiede attenzione",
    "Tip": "Suggerimento",
    "Unknown": "Sconosciuto",
    "Checking the helper": "Verifica dell’assistente",
    "One approval needed": "Serve un’approvazione",
    "The helper needs a reinstall": "L’assistente va reinstallato",
    "All set": "Tutto pronto",
    "Making sure Keepresso's helper is awake and answering.":
        "Verifica che l’assistente di Keepresso sia attivo e risponda.",
    "macOS turned the helper's background switch off, so it needs your approval again: in System Settings, under Login Items & Extensions, find Keepresso in App Background Activity and turn it on. Everything is password-free again right after.":
        "macOS ha disattivato l’interruttore in background dell’assistente, quindi serve di nuovo la tua approvazione: in Impostazioni di Sistema, in Elementi di login ed estensioni, trova Keepresso in Attività in background delle app e attivalo. Subito dopo tutto torna a funzionare senza password.",
    "Keepresso repaired the helper's registration, but macOS keeps disabling it. An old copy of Keepresso in the Trash is the usual cause: empty the Trash, then reinstall the helper below. Nothing else about your setup changes.":
        "Keepresso ha riparato la registrazione dell’assistente, ma macOS continua a disattivarlo. La causa abituale è una vecchia copia di Keepresso nel Cestino: svuota il Cestino, poi reinstalla l’assistente qui sotto. Nient’altro della tua configurazione cambia.",
    "The helper is back. Closed-display mode and AWDL pausing work without password prompts again.":
        "L’assistente è tornato. La modalità a schermo chiuso e la pausa di AWDL funzionano di nuovo senza richieste di password.",
    "Waiting for the switch in System Settings; this updates by itself.":
        "In attesa dell’interruttore in Impostazioni di Sistema; questa voce si aggiorna da sola.",
    "Record": "Registra",
    "Press keys…": "Premi i tasti…",
    "Other process, e.g. rsync": "Altro processo, ad es. rsync",
    "Export Keepresso Settings": "Esporta impostazioni di Keepresso",
    "Import Keepresso Settings": "Importa impostazioni di Keepresso",
    "Exported to %@.": "Esportato in %@.",
    "Settings imported.": "Impostazioni importate.",
    "Couldn't export settings: %@": "Impossibile esportare le impostazioni: %@",
    "Couldn't read the file: %@": "Impossibile leggere il file: %@",
    "That file isn't a Keepresso settings export.":
        "Quel file non è un’esportazione di impostazioni di Keepresso.",
    "That export was made by a newer version of Keepresso.":
        "Quell’esportazione è stata creata da una versione più recente di Keepresso.",
    "Save current rules as…": "Salva le regole attuali come…",
    "A recurring notification every interval while a session runs, so a Mac left awake keeps reminding you.":
        "Una notifica ricorrente a ogni intervallo mentre una sessione è attiva, così un Mac lasciato sveglio continua a ricordartelo.",
    "A one-time notification once a session has run this long, in case you forget the Mac is awake.":
        "Una notifica singola quando una sessione dura da così tanto, nel caso ti dimentichi che il Mac è sveglio.",
    "Watch": "Monitora",
    "Keep awake while downloads are in progress in this folder.":
        "Tieni sveglio mentre ci sono download in corso in questa cartella.",
    "Keep Awake": "Tieni sveglio",
    "Choose a folder on the disk you want to keep spun up.":
        "Scegli una cartella sul disco che vuoi mantenere in rotazione.",
    "Keepresso needs a new approval": "Keepresso richiede una nuova approvazione",
    "macOS turned Keepresso's background switch off. Turn it back on under Login Items & Extensions in System Settings to keep the password-free helper.":
        "macOS ha disattivato l’interruttore in background di Keepresso. Riattivalo in Elementi di login ed estensioni in Impostazioni di Sistema per conservare l’assistente senza password.",
    "Keepresso needs your password": "Keepresso richiede la tua password",
    "Enter your administrator password to switch closed-display mode on for this session.":
        "Inserisci la password di amministratore per attivare la modalità a schermo chiuso per questa sessione.",
    "Enter your administrator password to pause AWDL for this game.":
        "Inserisci la password di amministratore per sospendere AWDL per questo gioco.",
    "Game detected": "Gioco rilevato",
    "Pausing AWDL to steady your connection.":
        "Sospensione di AWDL per stabilizzare la connessione.",
    "AWDL resumed": "AWDL ripristinato",
    "The game closed; AirDrop, Handoff and Continuity are back.":
        "Il gioco è stato chiuso; AirDrop, Handoff e Continuity sono di nuovo attivi.",
    "This copy of Keepresso isn't in the Applications folder, so it leaves the helper alone. Install from /Applications.":
        "Questa copia di Keepresso non è nella cartella Applicazioni, quindi non tocca l’assistente. Installa da /Applications.",
    "The helper wasn't found inside the app. Reinstall Keepresso and try again.":
        "L’assistente non è stato trovato dentro l’app. Reinstalla Keepresso e riprova.",
    "The helper couldn't be registered.": "Impossibile registrare l’assistente.",
    "The helper couldn't be removed: %@": "Impossibile rimuovere l’assistente: %@",
    "macOS still reports the helper as registered. Try again, or restart the Mac.":
        "macOS segnala ancora l’assistente come registrato. Riprova, oppure riavvia il Mac.",
    "Removed. System Settings may keep showing Keepresso under App Background Activity until macOS refreshes its list; restarting the Mac clears the leftover row.":
        "Rimosso. Impostazioni di Sistema può continuare a mostrare Keepresso in Attività in background delle app finché macOS non aggiorna l’elenco; riavviare il Mac elimina la riga residua.",
    "macOS is refusing the helper's registration outright. Reinstall the helper; if that doesn't take, restart the Mac and try once more.":
        "macOS rifiuta del tutto la registrazione dell’assistente. Reinstalla l’assistente; se non basta, riavvia il Mac e riprova ancora una volta.",
    "The helper isn't responding. If an old copy of Keepresso is in the Trash, empty the Trash first: macOS keeps disabling the helper while one is there. Then reinstall the helper.":
        "L’assistente non risponde. Se una vecchia copia di Keepresso è nel Cestino, svuota prima il Cestino: macOS continua a disattivare l’assistente finché ce n’è una. Poi reinstalla l’assistente.",
    "Old copy stuck in the Trash": "Vecchia copia bloccata nel Cestino",
    "An old copy of Keepresso in the Trash keeps the background helper from working. Please delete it from the Trash, or empty the Trash.":
        "Una vecchia copia di Keepresso nel Cestino impedisce all’assistente in background di funzionare. Eliminala dal Cestino, oppure svuota il Cestino.",
    "Language": "Lingua",
    "App language": "Lingua dell’app",
    "Follow System": "Come il sistema",
    "%d h %d min": "%d h %d min",
    "%d h": "%d h",
    "%d min": "%d min",
    "%d:%02d": "%d:%02d",
    "%ds": "%d s",
    "%d:%02d:%02d": "%d:%02d:%02d",
    "Keepresso: paused, battery low": "Keepresso: in pausa, batteria scarica",
    "Keepresso: brewing": "Keepresso: in infusione",
    "Keepresso: idle": "Keepresso: inattivo",
    "1920 × 1080": "1920 × 1080",
    "2560 × 1440": "2560 × 1440",
    "2880 × 1620": "2880 × 1620",
    "3840 × 2160 (4K)": "3840 × 2160 (4K)",
    "Stop in": "Interrompi tra",
    "Quick stop shortcuts": "Scorciatoie di arresto rapido",
    "Add Shortcut": "Aggiungi scorciatoia",
    "Shortcut %d": "Scorciatoia %d",
    "Remove shortcut": "Rimuovi scorciatoia",
    "Warn before a timed session ends": "Avvisa prima che termini una sessione a tempo",
    "Warn": "Avvisa",
    "1 minute before": "1 minuto prima",
    "2 minutes before": "2 minuti prima",
    "5 minutes before": "5 minuti prima",
    "10 minutes before": "10 minuti prima",
    "AI agents": "Agenti IA",
    "AI agent is working": "Un agente IA sta lavorando",
    "Keeps the Mac awake while a coding-agent session (claude, codex, gemini, aider, and the like) is actively working, judged by its CPU use, and lets it sleep once every session has gone idle for the grace period. The menu lists each detected session. A freshly started session can take a few seconds to read as working.": "Tiene sveglio il Mac mentre una sessione di agente di codifica (claude, codex, gemini, aider e simili) sta effettivamente lavorando, giudicandolo dall’uso della CPU, e lo lascia dormire quando ogni sessione è rimasta inattiva per il periodo di tolleranza. Il menu elenca ogni sessione rilevata. Una sessione appena avviata può impiegare qualche secondo prima di risultare al lavoro.",
    "Idle grace period": "Tolleranza dopo l’inattività",
    "Instantly": "Immediatamente",
    "10 minutes": "10 minuti",
    "working": "al lavoro",
    "idle": "inattivo",
    "+%d more": "+%d altre",
    'Two independent switches. Preventing system sleep keeps the Mac itself running: work finishes, downloads complete, and it stays reachable over the network, while the screen is still free to turn off. Preventing display sleep also keeps the screen lit, which is what you want for a dashboard or a video, and what drains a battery fastest. Most setups want system sleep prevented and display sleep left alone.': 'Due interruttori indipendenti. Impedire lo stop del sistema mantiene il Mac stesso in funzione: il lavoro si completa, i download finiscono e resta raggiungibile in rete, mentre lo schermo può comunque spegnersi liberamente. Impedire lo stop del display mantiene anche lo schermo acceso, utile per una dashboard o un video, ed è ciò che scarica la batteria più in fretta. La maggior parte delle configurazioni vuole impedire lo stop del sistema e lasciare invariato quello del display.',
    "“Launch at login” starts Keepresso itself when you log in, so the cup is always in the menu bar. “Start keep-awake on launch” goes further and begins a session right away, using the default duration, for an always-on Mac that shouldn't need a rule to stay up. It's ignored while triggers are controlling activation, since your conditions decide then.": '“Apri al login” avvia lo stesso Keepresso quando accedi, così la tazzina è sempre nella barra dei menu. “Avvia la veglia all’avvio” va oltre e inizia subito una sessione, con la durata predefinita, per un Mac sempre acceso che non dovrebbe aver bisogno di una regola per restare sveglio. Viene ignorato mentre gli attivatori controllano l’attivazione, perché in quel caso decidono le tue condizioni.',
    'Starts a session as soon as Keepresso launches.': 'Avvia una sessione all’apertura di Keepresso.',
    "System-wide, so it starts or stops keep-awake whatever app you're in. It needs at least one modifier key (Command, Option, Control, or Shift) so it can't fire while you're typing. Recording it asks for no Accessibility or Input Monitoring permission.": 'È valida in tutto il sistema, quindi avvia o ferma la veglia da qualsiasi app tu sia. Richiede almeno un tasto modificatore (Comando, Opzione, Control o Maiuscole) in modo che non possa scattare mentre digiti. Registrarla non richiede il permesso di Accessibilità né di Monitoraggio input.',
    'Starts or stops keep-awake from any app.': 'Avvia o ferma la veglia da qualsiasi app.',
    "Fifteen languages are available. Changing this relaunches Keepresso, so the menu, every window, and notifications all switch together instead of drifting apart. Set it back to “Follow System” to follow your Mac's language again.": 'Sono disponibili quindici lingue. Cambiarla riavvia Keepresso, così il menu, ogni finestra e le notifiche cambiano tutti insieme invece di disallinearsi. Riportalo su “Come il sistema” per seguire di nuovo la lingua del tuo Mac.',
    'Keepresso follows your system language by default.': 'Per impostazione predefinita Keepresso segue la lingua di sistema.',
    'Handles the privileged switches for Keepresso, with no password prompts.': 'Gestisce gli interruttori con privilegi di Keepresso, senza richieste di password.',
    "Keeping the Mac awake stops it sleeping, but it doesn't reset app-level or enterprise idle detection: remote-desktop and VDI sessions, meeting presence (Teams, Slack), and corporate idle-logout can still mark you away or log you out. This tells macOS you're active as well, which those do notice. It only steps in once you've been idle a few seconds, so it never nudges the pointer while you're using the Mac or gaming. Off by default, and some managed Macs flag simulated activity, so check your policy first.": 'Tenere sveglio il Mac ne impedisce lo stop, ma non azzera il rilevamento dell’inattività a livello di app o aziendale: le sessioni desktop remoto e VDI, la presenza nelle riunioni (Teams, Slack) e il logout aziendale per inattività possono comunque segnarti come assente o disconnetterti. Questo comunica anche a macOS che sei attivo, cosa che quei sistemi notano davvero. Interviene solo dopo qualche secondo di inattività, quindi non muove mai il puntatore mentre usi il Mac o giochi. Disattivato per impostazione predefinita, e alcuni Mac gestiti segnalano l’attività simulata, quindi controlla prima la tua policy.',
    "Also tells macOS you're active, so you aren't marked away.": 'Comunica anche a macOS che sei attivo, così non vieni segnato come assente.',
    'While a session runs, the menu shows these as one-click “Stop in” buttons. Clicking one converts the running session to end that much later, so the Mac goes back to sleeping on its own without you remembering to switch it off. It continues the session rather than restarting it, and clicking another button simply replaces the countdown. Up to four, and the list stays sorted.': 'Mentre una sessione è attiva, il menu mostra questi come pulsanti “Interrompi tra” a un clic. Facendo clic su uno, la sessione in corso viene fatta terminare quel tanto più tardi, così il Mac torna ad addormentarsi da solo senza che tu debba ricordarti di spegnerlo. Continua la sessione anziché riavviarla, e fare clic su un altro pulsante sostituisce semplicemente il conto alla rovescia. Fino a quattro, e l’elenco resta ordinato.',
    'One-click “Stop in” buttons shown in the menu while a session runs.': 'Pulsanti “Interrompi tra” a un clic mostrati nel menu mentre una sessione è attiva.',
    'A safety net for a session you forget about. If the charge falls this low, Keepresso pauses the session and lets the Mac sleep, even mid-session, and tells you why in a notification. The menu-bar cup shows the pause as a last sip of low-power yellow. Plugging in resumes it on its own. This is the same slider as the one in the menu, so the two always agree.': 'Una rete di sicurezza per una sessione che dimentichi. Se la carica scende sotto questo livello, Keepresso mette in pausa la sessione e lascia che il Mac si addormenti, anche a metà sessione, e ti dice il motivo in una notifica. La tazzina nella barra dei menu mostra la pausa come un ultimo sorso giallo di batteria scarica. Collegare l’alimentazione la riprende da sola. È lo stesso cursore di quello nel menu, quindi i due coincidono sempre.',
    'Lets the Mac sleep once charge drops below this level.': 'Lascia che il Mac si addormenti quando la carica scende sotto questo livello.',
    "Writes everything you've configured (settings, trigger rules, and presets) to a JSON file, to keep as a backup or to carry to another Mac. The file is version-stamped and checked on import, so a file from a newer Keepresso is refused rather than half-read. Importing replaces your current configuration and ends any running session.": 'Scrive tutto ciò che hai configurato (impostazioni, regole degli attivatori e preset) in un file JSON, da conservare come backup o da portare su un altro Mac. Il file è contrassegnato con una versione e viene controllato all’importazione, quindi un file proveniente da una versione più recente di Keepresso viene rifiutato anziché letto solo in parte. L’importazione sostituisce la configurazione attuale e termina qualsiasi sessione in corso.',
    'Save your settings, triggers, and presets to a JSON file.': 'Salva le tue impostazioni, i tuoi attivatori e i tuoi preset in un file JSON.',
    "Normally a MacBook sleeps the moment you shut the lid unless a display is attached. This keeps it running with the lid shut and nothing plugged in, on power or battery. The screen itself still turns off when the lid closes (unless an external display is attached), so it isn't lighting up uselessly inside the closed lid. It works by flipping a system setting (pmset disablesleep), so it stays in effect until you turn it off: closed and on battery, the Mac can still drain over time, so don't leave it on in a bag. “Only while brewing” ties it to the session instead, on when a keep-awake session starts, off when it ends or Keepresso quits (even after a crash). Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password, once per app run for “Only while brewing”.": 'Normalmente un MacBook si addormenta appena chiudi il coperchio, a meno che non sia collegato un display. Questa opzione lo mantiene in funzione con il coperchio chiuso e nulla collegato, ad alimentazione o a batteria. Il display si spegne comunque quando il coperchio si chiude (a meno che non sia collegato un display esterno), così non resta acceso inutilmente dentro il coperchio chiuso. Funziona modificando un’impostazione di sistema (pmset disablesleep), che quindi resta in vigore finché non la disattivi: chiuso e a batteria, il Mac può comunque scaricarsi col tempo, quindi non lasciarlo attivo in una borsa. “Solo durante l’infusione” lo collega invece alla sessione: attivo quando inizia una sessione di veglia, disattivato quando termina o Keepresso viene chiuso (anche dopo un crash). Entrambe richiedono i privilegi di amministratore: in silenzio con l’assistente amministratore installato (vedi in cima a questa scheda), altrimenti macOS chiede la password, una volta per esecuzione dell’app per “Solo durante l’infusione”.',
    'Keeps running with the lid shut and no external display.': 'Continua a funzionare con il coperchio chiuso e senza display esterno.',
    "A trigger is a condition Keepresso watches, checked once a second. With triggers on, they take over: Keepresso starts brewing the moment your conditions are met and stops when they aren't, so you never leave the Mac awake by accident. The manual switch in the menu steps aside while they're active. “Pause Triggers” in the menu bar stops them temporarily without touching your rules.": 'Un attivatore è una condizione che Keepresso monitora, controllata una volta al secondo. Con gli attivatori attivi, prendono il controllo: Keepresso inizia a essere in infusione nel momento in cui le tue condizioni sono soddisfatte e si ferma quando non lo sono più, così non lasci mai il Mac sveglio per errore. L’interruttore manuale nel menu si fa da parte mentre sono attivi. “Sospendi attivatori” nella barra dei menu li ferma temporaneamente senza toccare le tue regole.',
    'The listed conditions control the session instead of the manual switch.': 'Le condizioni elencate controllano la sessione al posto dell’interruttore manuale.',
    'A preset is a named bundle of trigger rules you apply in one click. The built-ins cover common setups (AI Agent, Meetings, Cloud Gaming, Remote Control, and more), and applying one replaces your current rules. Save your own rules under a name to reuse them or move between setups. Renaming a built-in makes it yours, and Keepresso stops updating it. “Restore default presets” brings back any built-in you removed.': 'Un preset è un insieme con nome di regole degli attivatori che applichi con un clic. Quelli integrati coprono configurazioni comuni (Agente IA, Riunioni, Cloud Gaming, Controllo remoto e altro), e applicarne uno sostituisce le tue regole attuali. Salva le tue regole con un nome per riutilizzarle o passare da una configurazione all’altra. Rinominare un preset integrato lo rende tuo, e Keepresso smette di aggiornarlo. “Ripristina i preset predefiniti” recupera qualsiasi preset integrato che hai rimosso.',
    '“any” keeps the Mac awake while at least one condition holds, so the rules pile up: add three and any of them is enough. “all” needs every one true at once, which narrows things down (on AC power and an external display connected means only while docked). Conditions are checked once a second, and Keepresso stops brewing as soon as they stop being met.': '“una qualsiasi” tiene sveglio il Mac finché è vera almeno una condizione, quindi le regole si sommano: aggiungine tre e ne basta una qualsiasi. “tutte” richiede che siano vere tutte insieme, il che restringe le cose (collegato alla corrente e display esterno collegato significa solo quando è agganciato). Le condizioni vengono controllate una volta al secondo, e Keepresso smette di essere in infusione non appena non sono più soddisfatte.',
    "Conditions Keepresso reads straight from the hardware, with no permission needed: whether you're on AC power, on battery, or charging, and whether an external display is connected. Good for a Mac that should only stay awake while it's docked or plugged in, especially combined with “all” to mean exactly that.": 'Condizioni che Keepresso legge direttamente dall’hardware, senza bisogno di permessi: se sei collegato alla corrente, a batteria o in carica, e se è collegato un display esterno. Utile per un Mac che deve restare sveglio solo quando è agganciato o collegato alla corrente, soprattutto se combinato con “tutte” per intendere esattamente questo.',
    'Conditions about what the Mac is connected to or busy with: a chosen Wi-Fi network, a VPN, a Bluetooth device such as headphones or a controller, a mounted volume, or sustained network throughput for a large download, upload, or sync. Reading Wi-Fi names needs Location permission and Bluetooth needs its own, both requested from this menu; the rest ask for nothing.': 'Condizioni su ciò a cui il Mac è collegato o con cui è occupato: una rete Wi-Fi scelta, una VPN, un dispositivo Bluetooth come cuffie o un controller, un volume montato, oppure un traffico di rete sostenuto per un grande download, upload o sincronizzazione. Leggere i nomi Wi-Fi richiede il permesso di localizzazione, e il Bluetooth richiede il proprio, entrambi richiesti da questo menu; il resto non richiede nulla.',
    "Conditions about what you're actually doing: an app running or frontmost, the camera or microphone in use, audio playing, a game in front, an AI agent working, a process by name, a download finishing in a folder you watch, CPU load above a threshold, a time window, or a calendar event in progress. The camera and microphone conditions read only the device's in-use signal (the green dot), never the stream, so neither asks for permission.": 'Condizioni su ciò che stai effettivamente facendo: un’app in esecuzione o in primo piano, la fotocamera o il microfono in uso, audio in riproduzione, un gioco in primo piano, un agente IA al lavoro, un processo per nome, un download che termina in una cartella che monitori, un carico della CPU sopra una soglia, una fascia oraria, o un evento del calendario in corso. Le condizioni di fotocamera e microfono leggono solo il segnale di utilizzo del dispositivo (il pallino verde), mai il flusso, quindi nessuna delle due richiede un permesso.',
    "A nudge while a session is running, so a Mac left awake doesn't stay awake all night unnoticed. Left off, a one-time reminder tells you once, after the session has run this long. “Repeat” tells you again at every interval until you stop the session. This never stops anything itself, it only reminds you, and the sound is optional. If you'd rather the session end on its own, use a timed session or a quick-stop button instead.": 'Un promemoria mentre una sessione è attiva, così un Mac lasciato sveglio non resta sveglio tutta la notte senza che tu te ne accorga. Disattivato, un promemoria singolo ti avvisa una volta, dopo che la sessione è attiva da questo tempo. “Ripeti” ti avvisa di nuovo a ogni intervallo finché non fermi la sessione. Questo non ferma mai nulla da solo, ti avvisa soltanto, e il suono è facoltativo. Se preferisci che la sessione termini da sola, usa invece una sessione a tempo o un pulsante di arresto rapido.',
    "These cover the times a session ends without you: a timer expiring, trigger conditions dropping, or a low-battery pause. Stopping it yourself stays silent, since you already know. The warning is a heads-up a few minutes before a timed session runs out, so you can extend it before the Mac drops off. The action runs when the session ends: sleep the display or start the screen saver, handy for a Mac you walk away from. It's off by default so a timed session never surprises you.": 'Questo copre i casi in cui una sessione termina senza di te: un timer che scade, condizioni degli attivatori che vengono meno, o una pausa per batteria scarica. Fermarla tu stesso resta silenzioso, perché lo sai già. L’avviso è un preavviso di pochi minuti prima che una sessione a tempo finisca, così puoi estenderla prima che il Mac si stacchi. L’azione viene eseguita alla fine della sessione: mettere in stop il display o avviare il salvaschermo, utile per un Mac da cui ti allontani. È disattivata per impostazione predefinita, così una sessione a tempo non ti sorprende mai.',
    'Fires when a session ends on its own, not when you stop it yourself.': 'Scatta quando una sessione termina da sola, non quando la fermi tu.',
    'A Mac with no monitor attached falls back to a fuzzy 1920 × 1080, which is what makes Screen Sharing and VNC look soft. This creates a higher-resolution HiDPI display in software, so the remote picture is crisp without plugging anything in. It uses a private macOS API, so treat it as experimental and expect it may break on a macOS update. A hardware HDMI or DisplayPort dummy plug does the same job with no software at all.': 'Un Mac senza monitor collegato torna a una risoluzione sfocata di 1920 × 1080, il che rende Condivisione Schermo e VNC poco nitidi. Questo crea via software un display HiDPI a risoluzione più alta, così l’immagine remota è nitida senza collegare nulla. Usa un’API privata di macOS, quindi trattalo come sperimentale e aspettati che possa rompersi con un aggiornamento di macOS. Un dummy plug hardware HDMI o DisplayPort svolge lo stesso compito senza alcun software.',
    'For a Mac with no monitor: a sharper picture over Screen Sharing and VNC.': 'Per un Mac senza monitor: un’immagine più nitida tramite Condivisione Schermo e VNC.',
    "Many external drives and NAS volumes park or disconnect after a few minutes idle, and the next thing that touches them stalls while they spin back up. Keepresso rewrites a tiny hidden marker file in the folder you choose, just enough activity to keep the volume awake. Pick an interval shorter than the drive's own idle timeout. This runs whenever Keepresso is running, with or without a keep-awake session, so a drive stays ready even when the Mac is free to sleep.": 'Molti dischi esterni e volumi NAS si arrestano o si disconnettono dopo alcuni minuti di inattività, e la prossima cosa che li tocca si blocca mentre tornano a girare. Keepresso riscrive un piccolo file marcatore nascosto nella cartella che scegli, giusto abbastanza attività da tenere sveglio il volume. Scegli un intervallo più breve del timeout di inattività proprio del disco. Questo viene eseguito ogni volta che Keepresso è in esecuzione, con o senza una sessione di veglia, così un disco resta pronto anche quando il Mac è libero di addormentarsi.',
    'Stops an external drive or NAS from spinning down.': 'Impedisce a un disco esterno o a un NAS di fermarsi.',
    '3 minutes': '3 minuti',
}


# --- Agent hooks (Claude Code connection) ---
APP.update({
    "Claude Code connected: sessions report working and waiting exactly.": "Claude Code connesso: le sessioni segnalano con esattezza lavoro e attesa.",
    "Connect Claude Code for exact session tracking (adds hooks to its settings).": "Collega Claude Code per un monitoraggio esatto delle sessioni (aggiunge hook alle sue impostazioni).",
    "Connect Claude Code": "Collega Claude Code",
    "Claude Code's settings file couldn't be read, so it was left untouched.": "Impossibile leggere il file delle impostazioni di Claude Code, quindi è rimasto intatto.",
    "Couldn't update Claude Code's settings file.": "Impossibile aggiornare il file delle impostazioni di Claude Code.",
})


# --- Desktop "disable sleep" naming ---
APP.update({
    "Disable system sleep": "Disattiva la sospensione del sistema",
    "Disable sleep": "Disattiva la sospensione",
    "disable system sleep": "disabilitare la sospensione del sistema",
    "switch the sleep override with the session": "attivare e disattivare il blocco della sospensione con la sessione",
    "The Mac won't sleep at all until you turn this off. The display still sleeps as usual.":
        "Il Mac non andrà mai in stop finché non disattivi questa opzione. Il display si spegne comunque come al solito.",
    "Turns the sleep override on when a keep-awake session starts and off when it ends or Keepresso quits.":
        "Attiva il blocco della sospensione quando inizia una sessione di veglia e lo disattiva quando termina o Keepresso viene chiuso.",
    "Stops the Mac from sleeping at all until you turn it off.":
        "Impedisce al Mac di andare in stop finché non disattivi questa opzione.",
    "Stops the Mac from sleeping at all, even with no session running. This flips a system setting that needs administrator rights: silent with the administrator helper installed (Preferences ▸ General), otherwise macOS asks for your password.":
        "Impedisce al Mac di andare in stop, anche senza una sessione in corso. Questo cambia un'impostazione di sistema che richiede i privilegi di amministratore: in silenzio con l'assistente amministratore installato (Impostazioni ▸ Generali), altrimenti macOS chiede la password.",
    "Stops the Mac from sleeping at all, even with no session running. It works by flipping a system setting (pmset disablesleep), so it stays in effect until you turn it off, even if Keepresso quits. The display still sleeps as usual. “Only while brewing” ties it to the session instead, on when a keep-awake session starts, off when it ends or Keepresso quits (even after a crash). Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password, once per app run for “Only while brewing”.":
        "Impedisce al Mac di andare in stop, anche senza una sessione in corso. Funziona modificando un’impostazione di sistema (pmset disablesleep), che quindi resta in vigore finché non la disattivi, anche se Keepresso viene chiuso. Il display si spegne comunque come al solito. “Solo durante l’infusione” lo collega invece alla sessione: attivo quando inizia una sessione di veglia, disattivato quando termina o Keepresso viene chiuso (anche dopo un crash). Entrambe richiedono i privilegi di amministratore: in silenzio con l’assistente amministratore installato (vedi in cima a questa scheda), altrimenti macOS chiede la password, una volta per esecuzione dell’app per “Solo durante l’infusione”.",
    "%@ before": "%@ prima",
})


# v1.15 thermal safety net, fan test, helper texts, glass slider.
APP.update({
    "(max %@)": "(max %@)",
    "15 seconds": "15 secondi",
    "A safety net for a Mac left running with the lid closed, slid into a bag with a session still holding it awake. It acts only in that trapped state: lid shut, with “Keep awake with the lid closed” overriding sleep. Watch macOS's own thermal pressure (works everywhere, “Serious” is where throttling bites) or specific temperature sensors, and if the reading stays over the threshold for the chosen time, Keepresso escalates: first, optionally, it boosts the fans (never below what the system chose, needs the administrator helper), and if it stays hot for the same time again, it pauses the session and switches the sleep override off, so the Mac can finally sleep and cool, telling you why in a notification. Opening the lid, or readings recovering, undoes everything: fan control returns to the system, the override comes back, and the session resumes. Die sensors on modern Macs routinely run at 90-100 °C under load, so thresholds around 95-100 °C are sensible.":
        "Una rete di sicurezza per un Mac lasciato acceso col coperchio chiuso, infilato in una borsa con una sessione che lo tiene ancora sveglio. Interviene solo in quella situazione: coperchio chiuso, con “Tieni sveglio con il coperchio chiuso” che sovrascrive lo stop. Monitora la pressione termica di macOS (funziona ovunque, “Seria” è il punto in cui inizia il throttling) oppure sensori di temperatura specifici, e se la lettura resta sopra la soglia per il tempo scelto, Keepresso intensifica la risposta: prima, facoltativamente, aumenta i giri delle ventole (mai sotto quanto scelto dal sistema, richiede l’assistente amministratore), e se resta calda per lo stesso tempo ancora, mette in pausa la sessione e disattiva il blocco della sospensione, così il Mac può finalmente andare in stop e raffreddarsi, spiegandotene il motivo in una notifica. Aprire il coperchio, o il rientro delle letture nella norma, annulla tutto: il controllo delle ventole torna al sistema, il blocco della sospensione ritorna attivo e la sessione riprende. I sensori del die sui Mac moderni raggiungono normalmente i 90-100 °C sotto carico, quindi soglie intorno ai 95-100 °C sono ragionevoli.",
    "A small system service for the switches that need administrator rights: closed-display mode below, the thermal fan boost, and AWDL pausing in Gaming & Streaming. Without it, macOS asks for your password once per app run (and fan boost stays off entirely: fan control can't prompt). With it, everything is instant and silent: macOS asks once, when you approve the helper under Login Items, and the approval survives restarts and app updates. Updates never need a reinstall, the service replaces itself with the app. It can only flip those specific switches, everything it changes is restored if Keepresso quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list. The status shown here is the real one.":
        "Un piccolo servizio di sistema per gli interruttori che richiedono i privilegi di amministratore: la modalità a schermo chiuso qui sotto, l’aumento termico delle ventole e la pausa di AWDL in Gaming e streaming. Senza di esso, macOS chiede la password una volta per ogni esecuzione dell’app (e l’aumento delle ventole resta del tutto disattivato: il controllo delle ventole non può chiedere conferma). Con esso, tutto è istantaneo e silenzioso: macOS chiede una sola volta, quando approvi l’assistente in Elementi di login, e l’approvazione sopravvive a riavvii e aggiornamenti dell’app. Gli aggiornamenti non richiedono mai una reinstallazione, il servizio si sostituisce da solo insieme all’app. Può soltanto attivare o disattivare quegli interruttori specifici, tutto ciò che modifica viene ripristinato se Keepresso viene chiuso o va in crash, e puoi rimuoverlo qui in qualsiasi momento. Aggiunge anche lo strumento da riga di comando keepresso al tuo PATH (le installazioni con Homebrew ce l’hanno già). Dopo la rimozione, Impostazioni di Sistema può continuare a mostrare una riga obsoleta in Elementi di login finché macOS non aggiorna l’elenco. Lo stato mostrato qui è quello reale.",
    "Above": "Sopra",
    "All good. Every fan followed the boost, and control is back with the system.":
        "Tutto a posto. Ogni ventola ha seguito l’aumento e il controllo è tornato al sistema.",
    "At or above": "Almeno",
    "Boost fans first": "Aumenta prima le ventole",
    "Boosting fans and switching off closed-display mode during a heat pause need the administrator helper. Watching temperatures and pausing work without it. Installing asks for your approval once, in System Settings.":
        "L’aumento delle ventole e la disattivazione della modalità a schermo chiuso durante una pausa per calore richiedono l’assistente amministratore. Il monitoraggio delle temperature e la pausa funzionano anche senza. L’installazione chiede la tua approvazione una sola volta, in Impostazioni di Sistema.",
    "Boosting fans needs the administrator helper (Preferences ▸ General). The rest of the thermal safety net still applies.":
        "L’aumento delle ventole richiede l’assistente amministratore (Impostazioni ▸ Generali). Il resto della rete di sicurezza termica resta comunque attivo.",
    "Boosting fans to %d%% and reading back…": "Aumento delle ventole al %d%% e lettura dei valori…",
    "Closed-display mode left on": "Modalità a schermo chiuso lasciata attiva",
    "Fan %d: %@ → %@ rpm": "Ventola %d: %@ → %@ rpm",
    "Fan boost": "Aumento ventole",
    "Fan boost ended": "Aumento ventole terminato",
    "Fans boosted to %d%% to cool the Mac": "Ventole aumentate al %d%% per raffreddare il Mac",
    "Fans not boosted": "Ventole non aumentate",
    "Helper installed. Closed-display mode, fan boost, and AWDL pausing work without password prompts.":
        "Assistente installato. La modalità a schermo chiuso, l’aumento delle ventole e la pausa di AWDL funzionano senza richieste di password.",
    "Hottest sensor during the test: %@.": "Sensore più caldo durante il test: %@.",
    "How see-through the menu-bar dropdown is. Frosty (0%) backs its glass with blur and a wash of the window color, so text stays crisp on any wallpaper. Sliding toward 100% thins that backing away until the panel is the system's bare Liquid Glass, letting the desktop shine through, with some contrast cost on busy or very dark wallpapers. Changes apply instantly, only to the dropdown (windows like this one keep their standard look), and the system's Reduce Transparency accessibility setting always wins.":
        "Quanto è trasparente il menu a comparsa nella barra dei menu. Sfumato (0%) rende il vetro sfocato e con una velatura del colore della finestra, così il testo resta nitido su qualsiasi sfondo. Spostando il cursore verso il 100% questa base si assottiglia finché il pannello non diventa il puro Liquid Glass di sistema, lasciando trasparire la scrivania, con un certo costo di contrasto su sfondi affollati o molto scuri. Le modifiche si applicano subito, solo al menu a comparsa (finestre come questa mantengono il loro aspetto standard), e l’impostazione di accessibilità Riduci trasparenza del sistema ha sempre la precedenza.",
    "Install a small helper service so closed-display mode, the thermal fan boost, and AWDL pausing work without password prompts. macOS will ask you to allow it in System Settings, once. Nothing else changes.":
        "Installa un piccolo servizio assistente così la modalità a schermo chiuso, l’aumento termico delle ventole e la pausa di AWDL non chiederanno mai più la password. macOS ti chiederà di consentirlo in Impostazioni di Sistema, una sola volta; nient’altro cambia.",
    "Keepresso paused for heat but can't switch off closed-display mode without the administrator helper (Preferences ▸ General).":
        "Keepresso si è messo in pausa per il calore ma non può disattivare la modalità a schermo chiuso senza l’assistente amministratore (Impostazioni ▸ Generali).",
    "Looking for heat? “Pause when running hot” lives in General ▸ Thermal: a safety net that overrides these rules when the Mac runs hot with the lid closed.":
        "Cerchi il controllo sul calore? “Sospendi con surriscaldamento” si trova in Generali ▸ Termico: una rete di sicurezza che sostituisce queste regole quando il Mac si scalda con il coperchio chiuso.",
    "No fans were found to test.": "Non sono state trovate ventole da testare.",
    "No temperature sensors found on this Mac. The thermal pressure signal above still works.":
        "Nessun sensore di temperatura trovato su questo Mac. Il segnale di pressione termica qui sopra funziona comunque.",
    "One step left, in System Settings: allow Keepresso under Login Items, and these unlock by themselves.":
        "Manca un passaggio, in Impostazioni di Sistema: consenti Keepresso in Elementi di login, e queste funzioni si sbloccano da sole.",
    "Pause when running hot": "Sospendi con surriscaldamento",
    "Reading the fans…": "Lettura delle ventole…",
    "Run a quick check: the fans step through three boost levels for about 12 seconds, with readings at each, then control goes back to the system.":
        "Esegui un controllo rapido: le ventole passano attraverso tre livelli di aumento per circa 12 secondi, con una lettura a ogni livello, poi il controllo torna al sistema.",
    "Running hot (%d °C), letting the Mac cool down": "Surriscaldato (%d °C), il Mac può raffreddarsi",
    "Running hot, letting the Mac cool down": "Surriscaldato, il Mac può raffreddarsi",
    "See-through": "Trasparenza",
    "Some selected sensors are unavailable on this Mac.": "Alcuni sensori selezionati non sono disponibili su questo Mac.",
    "Stop": "Ferma",
    "Sustained for": "Per almeno",
    "Switching off closed-display mode during a heat pause needs the administrator helper. Watching temperatures and pausing work without it. Installing asks for your approval once, in System Settings.":
        "La disattivazione della modalità a schermo chiuso durante una pausa per calore richiede l’assistente amministratore. Il monitoraggio delle temperature e la pausa funzionano anche senza. L’installazione chiede la tua approvazione una sola volta, in Impostazioni di Sistema.",
    "System thermal pressure": "Pressione termica del sistema",
    "Temperature sensors": "Sensori di temperatura",
    "Temperature threshold": "Soglia di temperatura",
    "Temperatures recovered": "Temperature tornate alla norma",
    "Test Fans": "Test ventole",
    "Test stopped. Fan control is back with the system.": "Test interrotto. Il controllo delle ventole è tornato al sistema.",
    "The Mac has cooled down. Keepresso is back to normal control.": "Il Mac si è raffreddato. Keepresso è tornato al controllo normale.",
    "The administrator helper didn't accept fan control. Check its status in the section above, then run the test again.":
        "L’assistente amministratore non ha accettato il controllo delle ventole. Controlla il suo stato nella sezione qui sopra, poi esegui di nuovo il test.",
    "The administrator helper didn't accept the fan boost. The rest of the thermal safety net still applies.":
        "L’assistente amministratore non ha accettato l’aumento delle ventole. Il resto della rete di sicurezza termica resta comunque attivo.",
    "The administrator helper is still updating itself to this version of Keepresso. Fan boost engages once that finishes, and the rest of the thermal safety net still applies.":
        "L’assistente amministratore si sta ancora aggiornando a questa versione di Keepresso. L’aumento delle ventole si attiva una volta terminato, e il resto della rete di sicurezza termica resta comunque attivo.",
    "The fan test needs the administrator helper.": "Il test delle ventole richiede l’assistente amministratore.",
    "The fans are boosted for heat right now, so the test stays off until readings recover.":
        "Le ventole sono aumentate per il calore in questo momento, quindi il test resta disattivato finché le letture non tornano alla norma.",
    "The fans didn't follow the boost, so this Mac's firmware likely refuses manual fan control. The rest of the thermal safety net still works, the boost stage will just be skipped.":
        "Le ventole non hanno risposto all’aumento, quindi il firmware di questo Mac probabilmente rifiuta il controllo manuale delle ventole. Il resto della rete di sicurezza termica funziona comunque, semplicemente la fase di aumento verrà saltata.",
    "The firmware kept refusing manual fan control, so the fans are back with the system. The rest of the thermal safety net still applies.":
        "Il firmware ha continuato a rifiutare il controllo manuale delle ventole, quindi le ventole sono tornate al sistema. Il resto della rete di sicurezza termica resta comunque attivo.",
    "The helper is updating itself to this version of Keepresso (no password needed). Fan boost and this test unlock when it finishes, usually under a minute.":
        "L’assistente si sta aggiornando a questa versione di Keepresso (non serve alcuna password). L’aumento delle ventole e questo test si sbloccano al termine, di solito in meno di un minuto.",
    "The helper service is updating itself to this version of Keepresso in the background. No reinstall or password is needed. Features new to this version wait until it finishes, usually under a minute.":
        "Il servizio assistente si sta aggiornando a questa versione di Keepresso in background. Non serve alcuna reinstallazione né password. Le funzioni nuove di questa versione attendono che finisca, di solito in meno di un minuto.",
    "Window transparency": "Trasparenza della finestra",
    "Thermal": "Termico",
    "Appearance": "Aspetto",
    "If the Mac runs hot with the lid closed, the session pauses so it can sleep and cool down.":
        "Se il Mac si scalda con il coperchio chiuso, la sessione va in pausa così può andare in stop e raffreddarsi.",
    "The menu-bar dropdown's glass, from frosty to clear Liquid Glass.":
        "Il vetro del menu a comparsa nella barra dei menu, da sfumato a Liquid Glass trasparente.",
    # 1.16.0
    'Cancel': 'Annulla',
    'Off': 'Disattivato',
    'Time': 'Ora',
    'Total': 'Totale',
    'Indefinite': 'Indefinita',
    'Scheduled wake': 'Sveglia programmata',
    'One-shot wake': 'Sveglia una tantum',
    'Wake schedule': 'Programma di sveglia',
    'Wake at': 'Sveglia alle',
    'Repeat daily / weekly': 'Ripeti ogni giorno / settimana',
    'Start keep-awake on wake': 'Mantieni sveglio al risveglio',
    'Starts keep-awake on wake': 'Avvia il keep-awake al risveglio',
    'Session length': 'Durata sessione',
    'Turn Off Wake Schedule': 'Disattiva sveglia programmata',
    'Awake this week': 'Sveglio questa settimana',
    'No held-awake time in the last week.': 'Nessun tempo di keep-awake nell’ultima settimana.',
    '−%d%% battery': '−%d%% batteria',
    '%dh %dm': '%dh %dm',
    '%dm': '%dm',
    'One-shot: %@': 'Una tantum: %@',
    'Repeating: every day at %@': 'Ripeti: ogni giorno alle %@',
    'System one-shot wakes: %@': 'Sveglie una tantum di sistema: %@',
    'System repeating: %@': 'Ripetizione di sistema: %@',
    'Wake schedule not installed': 'Sveglia non installata',
    'Installing a wake schedule needs the administrator helper (Preferences ▸ General).': 'Programmare una sveglia richiede l’assistente amministratore (Preferenze ▸ Generali).',
    'The administrator helper could not update the system wake schedule.': 'L’assistente non ha potuto aggiornare la sveglia di sistema.',
    'Locks via System Events. macOS may ask once for Automation access for Keepresso.': 'Blocca tramite System Events. macOS può chiedere una volta l’accesso Automazione per Keepresso.',
    'Sleeps the Mac through the administrator helper (instant, no extra prompts).': 'Mette in stop il Mac tramite l’assistente (immediato, senza altre richieste).',
    'Without the administrator helper, sleep uses System Events and may ask for Automation access once. Install the helper under Preferences ▸ General for instant, silent sleep.': 'Senza assistente, lo stop usa System Events e può chiedere Automazione una volta. Installalo in Preferenze ▸ Generali per uno stop silenzioso.',
    'The helper is waiting for approval in System Settings. Until then, sleep falls back to System Events, which may ask for Automation access once.': 'L’assistente attende l’approvazione in Impostazioni di Sistema. Finché non c’è, lo stop usa System Events e può chiedere Automazione una volta.',
    'The helper is updating itself. Until that finishes, sleep falls back to System Events, which may ask for Automation access once.': 'L’assistente si sta aggiornando. Finché non finisce, lo stop usa System Events e può chiedere Automazione una volta.',
    'One step left: allow Keepresso under Login Items in System Settings. Scheduled wake unlocks by itself.': 'Un passo ancora: consenti Keepresso in Elementi di login (Impostazioni di Sistema). La sveglia programmata si sblocca da sola.',
    'The helper is updating itself (no password). Scheduled wake unlocks when that finishes, usually under a minute.': 'L’assistente si aggiorna (senza password). La sveglia programmata si sblocca a fine aggiornamento, di solito in meno di un minuto.',
    'Scheduled wake needs the administrator helper, the same one closed-display mode and fan boost use. Install once, and macOS asks for approval in System Settings.': 'La sveglia programmata richiede l’assistente amministratore, lo stesso di modalità coperchio chiuso e boost ventole. Installalo una volta: macOS chiede l’approvazione in Impostazioni di Sistema.',
    'A wake schedule is saved, but it is not active on this Mac until the administrator helper is ready. The system will not wake from this plan.': 'C’è una sveglia salvata, ma non è attiva finché l’assistente non è pronto. Il sistema non si sveglierà con questo piano.',
    'Reliable on AC power. On battery the firmware may skip the wake.': 'Affidabile a corrente. A batteria il firmware può saltare la sveglia.',
    'Uses every day (MTWRFSU). macOS allows only one system-wide repeating power schedule.': 'Ogni giorno (MTWRFSU). macOS consente un solo piano di alimentazione ricorrente di sistema.',
    'Turn on a one-shot time, a repeating time, or both. With neither, nothing is installed on the system.': 'Attiva un orario una tantum, uno ricorrente o entrambi. Altrimenti non viene installato nulla sul sistema.',
    'When the Mac wakes near this schedule, Keepresso starts a session so it does not fall back asleep. Works best with triggers off for that window, or with a trigger that stays satisfied.': 'Se il Mac si sveglia vicino a questo orario, Keepresso avvia una sessione così non si riaddormenta. Meglio con i trigger spenti o con uno che resta soddisfatto.',
    'Fires a few seconds after a natural end, not on a manual stop or a safety pause.': 'Parte pochi secondi dopo una fine naturale, non su stop manuale o pausa di sicurezza.',
    'Notifications fire when a session ends on its own, not when you stop it yourself.': 'Le notifiche partono quando la sessione finisce da sola, non se la fermi tu.',
    'Run a Shortcut, post a webhook, or a shell command on session and trigger events. No helper required.': 'Esegui un Comando, un webhook o uno shell su eventi di sessione e trigger. Nessun assistente richiesto.',
    'How long Keepresso held the Mac awake each day, from the decision log. Battery drop is shown when both ends of a session had a reading.': 'Per quanto Keepresso ha tenuto sveglio il Mac ogni giorno, dal registro decisioni. Il calo batteria compare se entrambi i capi della sessione avevano una lettura.',
    'Why each session started or stopped, newest first. Saved on disk and restored after a relaunch.': 'Perché ogni sessione è partita o si è fermata, le più recenti prima. Salvato su disco e ripristinato al riavvio.',
    'When a keep-awake session ends on its own (a timer expiring, or trigger conditions dropping), Keepresso can put the display to sleep, lock the screen, start the screen saver, or sleep the Mac. Off by default so a timed session never surprises you. Manual stops, and the battery and thermal safety pauses, never run this action. A brief debounce cancels it if the session restarts right away.': 'Quando una sessione di keep-awake finisce da sola (timer o condizioni), Keepresso può spegnere il display, bloccare, avviare il salvaschermo o mettere in stop il Mac. Disattivo di default per non sorprendere. Stop manuali e pause batteria/termiche non la eseguono. Un breve debounce la annulla se la sessione riparte subito.',
    'Wake the Mac at a set time through the administrator helper (pmset schedule / repeat), then optionally start a keep-awake session so it does not fall back asleep before the job runs. Pair with an end-of-session action above for wake, work, sleep. Scheduled wake is reliable on AC power. On battery the firmware may skip it. macOS only allows one system-wide repeating power schedule, so enabling ours replaces whatever was there. The controls stay locked until the helper is installed and ready, the same rule as the thermal fan boost.': 'Sveglia il Mac a un orario con l’assistente (pmset schedule / repeat) e avvia opzionalmente il keep-awake così non si riaddormenta. Abbinalo all’azione di fine sessione: sveglia, lavoro, stop. Affidabile a corrente. A batteria il firmware può saltarlo. macOS consente un solo piano di alimentazione ricorrente; il nostro sostituisce quello esistente. I controlli restano bloccati finché l’assistente non è pronto, come per il boost ventole.',
    'When something happens in Keepresso, run a Shortcut, POST a webhook, or run a shell command. Useful for a push to your phone when an overnight agent finishes (ntfy, or a Shortcut that sends a notification). Hooks are suspended while you edit them, so a half-written command never runs. No administrator helper needed. User-authored shell commands are intentional in this unsandboxed app: only add commands you trust.': 'Quando succede qualcosa in Keepresso, esegui un Comando, un webhook o uno shell. Utile per un push al telefono a fine agente notturno (ntfy o un Comando). Gli hook sono sospesi in modifica. Nessun assistente. I comandi shell sono voluti in questa app non sandbox: aggiungi solo ciò di cui ti fidi.',
    'These cover the times a session ends without you: a timer expiring, or trigger conditions dropping. Stopping it yourself stays silent, since you already know. The warning is a heads-up a few minutes before a timed session runs out, so you can extend it before the Mac drops off. Actions that put the Mac to sleep live under Automation.': 'Copre le fine sessione senza di te: timer o condizioni. Se la fermi tu, resta silenzioso. L’avviso arriva pochi minuti prima della fine a timer. Le azioni che mettono in stop il Mac sono in Automazione.',

    # 1.16.0 fill (17)
    '/bin/sh -c …': '/bin/sh -c …',
    'Add Hook': 'Aggiungi hook',
    'Add Hook…': 'Aggiungi hook…',
    'After the session ends': 'Dopo la sessione',
    'Agent rule options': 'Opzioni regola agente',
    'Automation': 'Automazione',
    'Count waiting as working': 'Conta l’attesa come lavoro',
    'Do': 'Azione',
    'Edit Hook': 'Modifica hook',
    'Edit hook': 'Modifica hook',
    'Event hooks': 'Hook eventi',
    'No event hooks yet.': 'Nessun hook ancora.',
    'Shell': 'Shell',
    'Shortcut': 'Comando',
    'Shortcut name': 'Nome comando',
    'Webhook': 'Webhook',
    'https://…': 'https://…',

})
