# -*- coding: utf-8 -*-
# Japanese overlay for catalog_app.py: English source -> Japanese.
APP = {
    "Add": "追加",
    "Add:": "追加：",
    "Clear": "消去",
    "Close": "閉じる",
    "Done": "完了",
    "Save": "保存",
    "Enable": "有効にする",
    "Enabled": "有効",
    "Installed": "インストール済み",
    "Remove": "削除",
    "Remove condition": "条件を削除",
    "Resume": "再開",
    "Later": "後で",
    "Learn more": "詳しく知る",
    "Re-check": "再確認",
    "Run Test": "テストを実行",
    "Match": "一致",
    "Threshold": "しきい値",
    "Grace period": "猶予期間",
    "Section": "セクション",
    "Schedule": "スケジュール",
    "Set Duration": "継続時間を設定",
    "For": "期間",
    "From": "開始",
    "To": "終了",
    "Until": "まで",
    "When": "条件",
    "Below": "未満",
    "Power": "電源",
    "Display": "ディスプレイ",
    "Network": "ネットワーク",
    "Media": "メディア",
    "Backup": "バックアップ",
    "Folder": "フォルダ",
    "Downloads": "ダウンロード",
    "Touch": "更新",
    "Resolution": "解像度",
    "Startup": "起動",
    "Gaming": "ゲーム",
    "None": "なし",
    "any": "いずれか",
    "all": "すべて",
    "of these are true:": "の条件が成立：",
    "1 minute": "1 分",
    "2 minutes": "2 分",
    "5 minutes": "5 分",
    "10 seconds": "10 秒",
    "30 seconds": "30 秒",
    "15 minutes": "15 分",
    "30 minutes": "30 分",
    "1 hour": "1 時間",
    "2 hours": "2 時間",
    "4 hours": "4 時間",
    "8 hours": "8 時間",
    "No grace": "猶予なし",
    "Every 1 minute": "1 分ごと",
    "Every 5 minutes": "5 分ごと",
    "Every 10 minutes": "10 分ごと",
    "Every 30 minutes": "30 分ごと",
    "Every": "間隔",
    "After": "後",
    "Keepresso": "Keepresso",
    "About Keepresso": "Keepresso について",
    "Welcome to Keepresso": "Keepresso へようこそ",
    "Keepresso Setup": "Keepresso のセットアップ",
    "Keepresso Helper": "Keepresso ヘルパー",
    "Preferences": "設定",
    "Preferences…": "設定…",
    "A menu-bar app that keeps your Mac awake on your terms.": "あなたのルールで Mac のスリープを防ぐメニューバー App です。",
    "AWDL watchdog": "AWDL 監視",
    "Activate by triggers": "トリガーで有効化",
    "Administrator helper": "管理者ヘルパー",
    "Allow Bluetooth access…": "Bluetooth アクセスを許可…",
    "Allow Wi-Fi access…": "Wi-Fi アクセスを許可…",
    "Allow calendar access…": "カレンダーアクセスを許可…",
    "App is frontmost": "App が最前面",
    "App is running": "App が実行中",
    "App match & grace period": "App の一致と猶予期間",
    "Apply or remove": "適用または削除",
    "Approve…": "承認…",
    "Apps & Activity": "App とアクティビティ",
    "Bluetooth device connected": "Bluetooth デバイス接続中",
    "Bluetooth rules need Bluetooth access (System Settings ▸ Privacy)": "Bluetooth ルールには Bluetooth アクセスが必要です（システム設定 ▸ プライバシーとセキュリティ）",
    "CPU load": "CPU 負荷",
    "CPU threshold": "CPU しきい値",
    "Camera in use": "カメラ使用中",
    "Change…": "変更…",
    "Charging": "充電中",
    "Check for Updates…": "アップデートを確認…",
    "Closed-display mode": "クラムシェルモード",
    "Contacting the helper…": "ヘルパーに接続中…",
    "Create a virtual display": "仮想ディスプレイを作成",
    "Currently paused from the menu bar.": "現在メニューバーから一時停止中です。",
    "Custom Duration…": "カスタム継続時間…",
    "During calendar events": "カレンダーイベント中",
    "Export Settings…": "設定を書き出す…",
    "Import Settings…": "設定を読み込む…",
    "External display connected": "外部ディスプレイ接続中",
    "Fix…": "修正…",
    "GNU GPL v3.0": "GNU GPL v3.0",
    "Gaming & Streaming": "ゲームとストリーミング",
    "Gaming & Streaming…": "ゲームとストリーミング…",
    "Get Started": "はじめる",
    "Global shortcut": "グローバルショートカット",
    "Headless Setup": "ヘッドレスセットアップ",
    "Headless Setup…": "ヘッドレスセットアップ…",
    "Headless virtual display (experimental)": "ヘッドレス仮想ディスプレイ（実験的）",
    "Helper installed and responding": "ヘルパーはインストール済みで応答しています",
    "HiDPI (Retina)": "HiDPI（Retina）",
    "How do you use your Mac?": "Mac をどのように使いますか？",
    "Install Helper…": "ヘルパーをインストール…",
    "Install…": "インストール…",
    "Jitter test": "ジッターテスト",
    "Keep a disk spinning": "ディスクを回転させ続ける",
    "Keep awake with lid closed": "蓋を閉じたままスリープ防止",
    "Keep awake with the lid closed": "蓋を閉じたままスリープ防止",
    "Keep awake": "スリープ防止",
    "Keep me active": "自分をアクティブに保つ",
    "Keeping the Mac awake now": "Mac のスリープを防止中",
    "Keepresso decisions": "Keepresso の判断",
    "Measuring, about 10 seconds…": "測定中、約 10 秒…",
    "Microphone in use": "マイク使用中",
    "Network & Devices": "ネットワークとデバイス",
    "Network activity": "ネットワークアクティビティ",
    "Network threshold": "ネットワークしきい値",
    "No Wi-Fi network joined": "Wi-Fi ネットワークに未接続",
    "No apps running": "実行中の App なし",
    "No conditions yet, so the Mac can sleep.": "まだ条件がないため、Mac はスリープできます。",
    "No conditions yet. Add some in Preferences ▸ Triggers.": "まだ条件がありません。設定 ▸ トリガー で追加してください。",
    "No days selected means every day.": "日を選択しない場合は毎日を意味します。",
    "No paired devices": "ペアリング済みデバイスなし",
    "No session activity yet.": "まだセッションのアクティビティはありません。",
    "No volumes mounted": "マウント済みボリュームなし",
    "Not available on this macOS version.": "この macOS バージョンでは使用できません。",
    "Nothing is holding the Mac awake right now.": "現在、Mac のスリープを妨げているものはありません。",
    "Notify when a session ends": "セッション終了時に通知",
    "Notify when auto-pausing and resuming": "自動での一時停止と再開時に通知",
    "On AC power": "電源接続時",
    "On battery": "バッテリー使用時",
    "On session end": "セッション終了時",
    "Only while brewing": "抽出中のみ",
    "Open Login Items": "ログイン項目を開く",
    "Open Settings": "設定を開く",
    "Overnight (22:00-6:00)": "夜間（22:00〜6:00）",
    "Pause AWDL automatically while gaming": "ゲーム中に AWDL を自動的に一時停止",
    "Pause AWDL now": "AWDL を今すぐ一時停止",
    "Pause Triggers": "トリガーを一時停止",
    "Pause on low battery": "バッテリー低下時に一時停止",
    "Play a sound": "サウンドを再生",
    "Playing a game": "ゲームプレイ中",
    "Power & Display": "電源とディスプレイ",
    "Presets": "プリセット",
    "Prevent display sleep": "ディスプレイのスリープを防止",
    "Prevent system sleep": "システムのスリープを防止",
    "Process is running": "プロセスが実行中",
    "Quit Keepresso": "Keepresso を終了",
    "Reduce lag and jitter": "遅延とジッターを軽減",
    "Reinstall Helper": "ヘルパーを再インストール",
    "Remind me it's still on": "まだオンであることを通知",
    "Repeat the reminder": "リマインダーを繰り返す",
    "Restore default presets": "デフォルトのプリセットを復元",
    "Resume AWDL after leaving the game": "ゲームを離れた後に AWDL を再開",
    "Resume Triggers": "トリガーを再開",
    "Session end": "セッション終了",
    "Set Up…": "セットアップ…",
    "Show Welcome Screen…": "ようこそ画面を表示…",
    "Show countdown in menu bar": "メニューバーにカウントダウンを表示",
    "Start keep-awake on launch": "起動時にスリープ防止を開始",
    "The helper needs attention": "ヘルパーに対応が必要です",
    "The test couldn't run. Check that you're online and try again.": "テストを実行できませんでした。オンラインであることを確認して、もう一度お試しください。",
    "The watchdog below should smooth this out; re-run the test with it on to confirm.": "下の監視でこれが解消されるはずです。オンにしてテストを再実行し、確認してください。",
    "Times & days": "時間と曜日",
    "Toggle shortcut": "切り替えショートカット",
    "Triggers paused. Controlling manually for now.": "トリガーは一時停止中です。当面は手動で制御します。",
    "Until a Time…": "指定時刻まで…",
    "VPN connected": "VPN 接続中",
    "View on GitHub": "GitHub で表示",
    "Volume is mounted": "ボリュームがマウント済み",
    "Watch a folder for downloads…": "ダウンロードのためにフォルダを監視…",
    "While frontmost": "最前面のとき",
    "While running": "実行中のとき",
    "Work hours (weekdays 9:00-18:00)": "勤務時間（平日 9:00〜18:00）",
    "Audio playing": "オーディオ再生中",
    "Paused": "一時停止中",
    "Brewing": "抽出中",
    "Idle": "アイドル",
    "System can sleep": "システムはスリープできます",
    "No conditions yet": "まだ条件がありません",
    "Battery below %d%%, letting the Mac sleep": "バッテリーが %d%% 未満、Mac をスリープさせます",
    "Stops in %@": "%@ 後に停止",
    "Awake for %@": "%@ 間スリープ防止中",
    "Active": "アクティブ",
    "Held by %@": "%@ が保持中",
    "Waiting for any condition": "いずれかの条件を待機中",
    "Waiting on %@": "%@ を待機中",
    "%d condition": "%d 個の条件",
    "%d conditions": "%d 個の条件",
    "Approve Keepresso again in System Settings.": "システム設定で Keepresso を再度承認してください。",
    "The helper isn't responding; reinstall it.": "ヘルパーが応答していません。再インストールしてください。",
    "Waiting for a game to come to the front": "ゲームが最前面に来るのを待機中",
    "AWDL paused": "AWDL 一時停止中",
    "AWDL paused for gaming": "ゲームのため AWDL 一時停止中",
    "Game closed, AWDL back in %ds": "ゲーム終了、AWDL は %d 秒後に復帰",
    "Latency looks clean.": "レイテンシーは良好に見えます。",
    "Once-a-second spikes: this looks like AWDL.": "1 秒ごとのスパイク：これは AWDL のようです。",
    "Spiky, but not on AWDL's cadence (congestion or a weak signal).": "スパイクはありますが、AWDL のリズムではありません（混雑または信号の弱さ）。",
    "Not enough replies to judge.": "判断に十分な応答がありません。",
    "AWDL is on right now": "AWDL は現在オンです",
    "AWDL is off right now": "AWDL は現在オフです",
    "AWDL state unknown": "AWDL の状態は不明です",
    "Agentic coding": "エージェント型コーディング",
    "Stay awake while Claude, Codex, or Grok is running.": "Claude、Codex、または Grok の実行中はスリープしません。",
    "Gaming & streaming": "ゲームとストリーミング",
    "Stay awake while a game or cloud-gaming app is in front.": "ゲームまたはクラウドゲーミング App が最前面のときはスリープしません。",
    "Meetings & calls": "ミーティングと通話",
    "Stay awake whenever the camera or microphone is in use.": "カメラまたはマイクが使用中のときは常にスリープしません。",
    "Remote access": "リモートアクセス",
    "Stay awake while someone is connected over SSH.": "SSH で誰かが接続している間はスリープしません。",
    "Keep it manual for now": "当面は手動のまま",
    "Just toggle keep-awake yourself, and set up your own triggers later in Preferences.": "スリープ防止は自分で切り替え、独自のトリガーは後で設定で構成してください。",
    "Launch at login": "ログイン時に起動",
    "Start Keepresso automatically when you log in.": "ログイン時に Keepresso を自動的に起動します。",
    "Notifications": "通知",
    "Let Keepresso remind you when a long session is still keeping the Mac awake.": "長いセッションがまだ Mac のスリープを防止しているときに Keepresso が通知します。",
    "Approve a small helper once and the privileged extras (lid-closed mode, AWDL pausing) never ask for your password again. Set and forget; removable in Preferences.": "小さなヘルパーを一度承認すれば、特権的な追加機能（クラムシェルモード、AWDL の一時停止）が二度とパスワードを求めなくなります。設定すれば後は不要で、設定でいつでも削除できます。",
    "Location access (Wi-Fi rules)": "位置情報アクセス（Wi-Fi ルール）",
    "Bluetooth access (device rules)": "Bluetooth アクセス（デバイスルール）",
    "Calendar access (event rule)": "カレンダーアクセス（イベントルール）",
    "Keepresso launches at login, so it returns after a reboot.": "Keepresso はログイン時に起動するため、再起動後に復帰します。",
    "Keepresso isn't set to launch at login, so it won't run after an unattended reboot.": "Keepresso はログイン時に起動する設定になっていないため、無人の再起動後には実行されません。",
    "Turn on “Launch at login” in Keepresso's settings.": "Keepresso の設定で「ログイン時に起動」をオンにしてください。",
    "Keepresso can read the current Wi-Fi network name for your Wi-Fi triggers.": "Keepresso は Wi-Fi トリガー用に現在の Wi-Fi ネットワーク名を読み取れます。",
    "Without Location access Keepresso can't read the Wi-Fi network name, so Wi-Fi triggers won't match.": "位置情報アクセスがないと Keepresso は Wi-Fi ネットワーク名を読み取れないため、Wi-Fi トリガーが一致しません。",
    "Allow Location access for Keepresso.": "Keepresso に位置情報アクセスを許可してください。",
    "Keepresso can see which paired devices are connected for your Bluetooth triggers.": "Keepresso は Bluetooth トリガー用に、どのペアリング済みデバイスが接続されているかを確認できます。",
    "Without Bluetooth access Keepresso can't see paired devices, so Bluetooth triggers won't match.": "Bluetooth アクセスがないと Keepresso はペアリング済みデバイスを確認できないため、Bluetooth トリガーが一致しません。",
    "Allow Bluetooth access for Keepresso.": "Keepresso に Bluetooth アクセスを許可してください。",
    "Keepresso can see when a calendar event is in progress for your calendar trigger.": "Keepresso はカレンダートリガー用に、カレンダーイベントが進行中かどうかを確認できます。",
    "Without full calendar access Keepresso can't see events, so the calendar trigger won't match.": "完全なカレンダーアクセスがないと Keepresso はイベントを確認できないため、カレンダートリガーが一致しません。",
    "Allow full calendar access for Keepresso.": "Keepresso に完全なカレンダーアクセスを許可してください。",
    "Keepresso can post the “still brewing” reminder.": "Keepresso は「まだ抽出中」のリマインダーを表示できます。",
    "Notifications are off, so the “still brewing” reminder can't appear.": "通知がオフのため、「まだ抽出中」のリマインダーを表示できません。",
    "Allow notifications for Keepresso.": "Keepresso に通知を許可してください。",
    "Above %d%%": "%d%% 超",
    "Above %@": "%@ 超",
    "Version %@": "バージョン %@",
    "Remove “%@”": "「%@」を削除",
    "On current Wi-Fi (%@)": "現在の Wi-Fi (%@) で",
    "keep the Mac awake with the lid closed": "蓋を閉じたまま Mac のスリープを防止する",
    "switch closed-display mode with the session": "セッションに合わせてクラムシェルモードを切り替える",
    "pause AWDL (turn off the Wi-Fi AirDrop/Handoff radio hops)": "AWDL を一時停止する（Wi-Fi の AirDrop/Handoff 無線ホップをオフにする）",
    "macOS is asking for your administrator password to %@. The dialog may be titled “osascript”: that's Keepresso running the command, and nothing else is changed. To stop these prompts for good, install the administrator helper (Preferences ▸ General).": "%@ ために、macOS が管理者パスワードを求めています。ダイアログのタイトルが「osascript」と表示されることがありますが、これは Keepresso がコマンドを実行しているだけで、ほかには何も変更されません。これらの要求を完全になくすには、管理者ヘルパーをインストールしてください（設定 ▸ 一般）。",
    "Keepresso keeps your Mac awake on your terms. It lives in the menu bar near the clock, with no Dock icon. Click its cup any time to start or stop.": "Keepresso はあなたのルールで Mac のスリープを防ぎます。時計の近くのメニューバーに常駐し、Dock アイコンはありません。カップをクリックすると、いつでも開始・停止できます。",
    "Pick one to set up matching triggers, or keep it manual and add your own later. You can change this any time in Preferences.": "1 つ選ぶと対応するトリガーが設定されます。手動のままにして、後で独自のものを追加することもできます。これは設定でいつでも変更できます。",
    "When on, the listed conditions control the session instead of the manual switch.": "オンにすると、手動スイッチの代わりにリストの条件がセッションを制御します。",
    "Activation is controlled by triggers.\nEdit them in Preferences.": "有効化はトリガーによって制御されます。\n設定で編集してください。",
    "Why each session started or stopped, newest first. Kept in memory; clears on relaunch.": "各セッションが開始または停止した理由を、新しい順に表示します。メモリに保持され、再起動時に消去されます。",
    "Every app's live power assertions, not just Keepresso's, the same data pmset -g assertions prints.": "Keepresso だけでなく、すべての App のライブ電源アサーションを表示します。pmset -g assertions が出力するのと同じデータです。",
    "A system-wide keyboard shortcut that starts or stops keep-awake from any app. Needs at least one modifier key.": "どの App からでもスリープ防止を開始・停止できるシステム全体のキーボードショートカットです。修飾キーが少なくとも 1 つ必要です。",
    "Lets the Mac sleep once battery charge drops below this level, even mid-session, so it doesn't run flat.": "バッテリー残量がこのレベルを下回ると、セッション中でも Mac をスリープさせ、電池切れを防ぎます。",
    "Shows the remaining time next to the menu-bar icon during a timed session.": "タイマーセッション中、メニューバーアイコンの横に残り時間を表示します。",
    "Starts a session as soon as Keepresso launches, using the default duration. Ignored while triggers are controlling activation.": "Keepresso の起動と同時に、デフォルトの継続時間でセッションを開始します。トリガーが有効化を制御している間は無視されます。",
    "Reopen the first-run welcome, with quick one-click setup for how you use your Mac.": "初回起動時のようこそ画面を再表示します。Mac の使い方に応じたワンクリックの簡単セットアップ付きです。",
    "Fires when a timed session expires, trigger conditions drop, or a low-battery pause kicks in, not when you stop it yourself. The action is off by default so a timed session never surprises you.": "タイマーセッションの期限切れ、トリガー条件の解除、またはバッテリー低下による一時停止が発生したときに実行されます。自分で停止したときは実行されません。この操作はデフォルトでオフになっているため、タイマーセッションが不意に作動することはありません。",
    "If that time already passed today, it means tomorrow.": "その時刻が今日すでに過ぎている場合は、翌日を意味します。",
    "Runs past midnight into the next day.": "深夜 0 時を過ぎて翌日まで続きます。",
    "Save your settings, triggers, and presets to a JSON file to back them up or move them to another Mac. Importing replaces your current configuration and ends any running session.": "設定、トリガー、プリセットを JSON ファイルに保存して、バックアップしたり別の Mac に移したりできます。読み込むと現在の構成が置き換えられ、実行中のセッションはすべて終了します。",
    "Keeps the Mac awake while a partial-download file (.crdownload, .download, .part, and the like) exists in the chosen folder, then lets it sleep once the download finishes. Holds for 30 seconds between files in a batch.": "選択したフォルダにダウンロード中のファイル（.crdownload、.download、.part など）が存在する間は Mac のスリープを防止し、ダウンロードが完了するとスリープを許可します。バッチ内のファイルの間は 30 秒間保持します。",
    "Writes a tiny marker file on the chosen volume periodically to stop an external drive or NAS from spinning down.": "選択したボリュームに小さなマーカーファイルを定期的に書き込み、外付けドライブや NAS の回転停止を防ぎます。",
    "For a Mac with no monitor: creates a higher-resolution display so Screen Sharing and VNC look crisp instead of a fuzzy 1920 × 1080. It uses a private macOS API, so treat it as experimental and expect it may break on a macOS update. A hardware HDMI or DisplayPort dummy plug is a no-software alternative.": "モニターのない Mac 向け：より高解像度のディスプレイを作成し、画面共有や VNC がぼやけた 1920 × 1080 ではなく鮮明に見えるようにします。macOS の非公開 API を使用するため、実験的なものとして扱い、macOS のアップデートで動作しなくなる可能性があることを想定してください。ハードウェアの HDMI または DisplayPort のダミープラグは、ソフトウェア不要の代替手段です。",
    "Stays awake on battery too; the display turns off when the lid closes. Turn it off before putting it in a bag.": "バッテリー使用時もスリープしません。蓋を閉じるとディスプレイはオフになります。バッグに入れる前にオフにしてください。",
    "The calendar rule needs Calendar access (System Settings ▸ Privacy)": "カレンダールールにはカレンダーアクセスが必要です（システム設定 ▸ プライバシーとセキュリティ）",
    "Wi-Fi rules need Location access (System Settings ▸ Privacy)": "Wi-Fi ルールには位置情報アクセスが必要です（システム設定 ▸ プライバシーとセキュリティ）",
    "Checks an always-on Mac (e.g. a headless Mac mini) needs. Keepresso can read these but can't change the system ones, so use the links and commands below.": "常時稼働の Mac（例：ディスプレイのない Mac mini）に必要なチェック項目です。Keepresso はこれらを読み取れますが、システム側のものは変更できないため、以下のリンクとコマンドを使用してください。",
    "macOS hops the Wi-Fi radio off-channel for AWDL about once a second, which shows up as ping spikes mid-game or mid-stream. Diagnose it here, and pause AWDL for the session if it's the culprit.": "macOS は約 1 秒ごとに AWDL のために Wi-Fi 無線をオフチャンネルにホップさせ、これがゲームやストリーミング中の ping スパイクとして現れます。ここで診断し、これが原因であればセッション中は AWDL を一時停止してください。",
    "Pings 1.1.1.1 five times a second for 10 seconds and checks whether latency spikes on AWDL's once-a-second cadence.": "1.1.1.1 に 1 秒あたり 5 回、10 秒間 ping を送信し、AWDL の 1 秒ごとのリズムでレイテンシーがスパイクするかどうかを確認します。",
    "Counts only while a game (or a cloud-gaming app) is the active window, not just running in the background. Keeps holding for 5 minutes after you switch away.": "ゲーム（またはクラウドゲーミング App）が単にバックグラウンドで実行されているだけでなく、アクティブなウインドウであるときのみカウントします。切り替えた後も 5 分間保持し続けます。",
    "How long the pause lingers after the game stops being the active window, so a quick alt-tab doesn't flap the radios. Shorter brings AirDrop and Handoff back faster; longer rides out launchers and loading screens.": "ゲームがアクティブなウインドウでなくなった後に一時停止がどれだけ持続するかで、素早い Alt-Tab で無線が切り替わり続けないようにします。短くすると AirDrop と Handoff がより早く戻り、長くするとランチャーやロード画面をやり過ごせます。",
    "Posts a notification when a game is detected and AWDL pauses, and again when it resumes. A notice that your administrator password is needed is always sent (even behind a fullscreen game), regardless of this switch.": "ゲームが検出されて AWDL が一時停止したときと、再開したときに通知を表示します。管理者パスワードが必要であるという通知は、このスイッチに関係なく常に送信されます（フルスクリーンのゲームの背後でも）。",
    "Also tells macOS you're active while a session runs, so remote-desktop sessions, meeting presence (Teams, Slack), and corporate idle-logout don't mark you away. A plain keep-awake doesn't reach those. It only steps in once you've been idle a few seconds, so it never nudges the pointer while you're using the Mac or gaming. Off by default; some managed Macs flag simulated activity.": "セッションの実行中は macOS にあなたがアクティブであることも伝えるため、リモートデスクトップセッション、会議中のプレゼンス（Teams、Slack）、社内のアイドル自動ログアウトがあなたを離席として扱いません。単なるスリープ防止ではこれらに届きません。数秒間アイドル状態になってはじめて介入するため、Mac を使用中やゲーム中にポインタを動かすことは決してありません。デフォルトではオフです。一部の管理対象 Mac は模擬的なアクティビティを検出することがあります。",
    "Install a small helper service so closed-display mode and AWDL pausing never ask for your password again. macOS will ask you to allow it in System Settings, once; nothing else changes.": "小さなヘルパーサービスをインストールすると、クラムシェルモードと AWDL の一時停止が二度とパスワードを求めなくなります。macOS はシステム設定で一度だけ許可を求めます。ほかには何も変わりません。",
    "One step left, in System Settings: under General ▸ Login Items & Extensions (“Login Items” on older macOS), find Keepresso in the “Allow in the Background” list and turn its switch ON. macOS asks for your administrator password once; this updates by itself when you're done.": "あと 1 ステップ、システム設定で行います：一般 ▸ ログイン項目と機能拡張（古い macOS では「ログイン項目」）で、「バックグラウンドでの実行を許可」リストの中から Keepresso を見つけ、そのスイッチをオンにしてください。macOS は管理者パスワードを一度求めます。完了すると、この表示は自動的に更新されます。",
    "Keeps running with the lid shut and no external display, on power or battery. The display itself still turns off when the lid closes (unless an external display is attached), so it's not lighting up uselessly inside the closed lid. Changing this flips a system setting (pmset disablesleep), so it stays in effect until you turn it off. On battery and closed it can still drain the battery over time, so don't leave it on in a bag. With “Only while brewing” on, Keepresso instead switches it on when a keep-awake session starts and back off when it ends or the app quits. Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password (once per app run for “Only while brewing”).": "蓋を閉じて外部ディスプレイがない状態でも、電源でもバッテリーでも動作し続けます。蓋を閉じるとディスプレイ自体はオフになる（外部ディスプレイが接続されている場合を除く）ため、閉じた蓋の中で無駄に点灯することはありません。これを変更するとシステム設定（pmset disablesleep）が切り替わり、オフにするまで有効なままになります。バッテリー使用時に蓋を閉じていると、時間とともにバッテリーを消耗することがあるため、バッグの中でオンのままにしないでください。「抽出中のみ」をオンにすると、Keepresso はスリープ防止セッションの開始時にオンにし、終了時または App の終了時にオフに戻します。どちらにも管理者権限が必要です。管理者ヘルパーがインストールされていれば静かに実行されます（このタブの上部を参照）。そうでない場合、macOS がパスワードを求めます（「抽出中のみ」では App の実行ごとに 1 回）。",
    "Turns the pause on right now and keeps it on until you turn it off or quit Keepresso (it isn't tied to whether a keep-awake session is brewing). While it's on, AirDrop, Handoff, Sidecar, and Continuity Camera take a break, and the once-a-second lag spikes stop. Everything comes back the moment you turn it off or quit Keepresso; even if the app crashes, macOS is restored automatically. With the administrator helper installed the switch is always instant and silent; without it, macOS asks for your password once per launch (the system dialog may show “osascript”, which is Keepresso running the command).": "今すぐ一時停止をオンにし、オフにするか Keepresso を終了するまでオンのままにします（スリープ防止セッションが抽出中かどうかとは関係ありません）。オンの間は、AirDrop、Handoff、Sidecar、連係カメラが休止し、1 秒ごとの遅延スパイクが止まります。オフにするか Keepresso を終了した瞬間に、すべてが元に戻ります。App がクラッシュしても、macOS は自動的に復元されます。管理者ヘルパーがインストールされていれば、このスイッチは常に即座かつ静かに動作します。インストールされていない場合、macOS は起動ごとに 1 回パスワードを求めます（システムダイアログに「osascript」と表示されることがありますが、これは Keepresso がコマンドを実行しているものです）。",
    "Watches for a game (or a cloud-gaming app like GeForce NOW) as the active window and pauses AWDL on its own, then lifts the pause a little after you switch away (the delay below). It only counts while the game is in front and in use, not just running in the background. Without the administrator helper, turning this on asks for your password once per app run, right now rather than mid-game; with the helper it never asks at all. No trigger setup needed: leave this on and forget it.": "ゲーム（または GeForce NOW のようなクラウドゲーミング App）がアクティブなウインドウであるかを監視し、自動的に AWDL を一時停止します。その後、切り替えて離れてから少し経つと一時停止を解除します（下の遅延）。ゲームが最前面で使用中のときのみカウントし、単にバックグラウンドで実行されているだけではカウントしません。管理者ヘルパーがない場合、これをオンにすると App の実行ごとに 1 回、ゲーム中ではなく今すぐパスワードを求められます。ヘルパーがあれば一切求められません。トリガーの設定は不要です。オンにしておけば、あとは気にする必要はありません。",
    "Helper installed. Closed-display mode and AWDL pausing work without password prompts.": "ヘルパーがインストールされました。クラムシェルモードと AWDL の一時停止が、パスワードの要求なしで動作します。",
    "Pause AWDL to steady your connection, and test your jitter, in Gaming & Streaming.": "「ゲームとストリーミング」で AWDL を一時停止して接続を安定させ、ジッターをテストできます。",
    "A small system service that handles the privileged switches (closed-display mode below, AWDL pausing in Gaming & Streaming) for Keepresso, so no password prompts ever again: macOS asks once when you approve it under Login Items, and the approval survives restarts and updates. It can only flip those specific switches, everything it changes is restored if the app quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list; the status shown here is the real one.": "Keepresso のために特権的なスイッチ（下のクラムシェルモード、「ゲームとストリーミング」の AWDL 一時停止）を処理する小さなシステムサービスです。これにより、二度とパスワードの要求はありません。macOS はログイン項目で承認するときに一度だけ確認し、その承認は再起動やアップデート後も維持されます。切り替えられるのはそれらの特定のスイッチだけで、変更した内容は App の終了時やクラッシュ時にすべて復元され、ここでいつでも削除できます。また、keepresso コマンドラインツールを PATH に追加します（Homebrew でのインストールにはすでに含まれています）。削除後、macOS がリストを更新するまで、システム設定にログイン項目の古い行が表示され続けることがあります。ここに表示される状態が本当の状態です。",
    "General": "一般",
    "Triggers": "トリガー",
    "Reminder": "リマインダー",
    "Disk": "ディスク",
    "Activity": "アクティビティ",
    "Indefinitely": "無期限",
    "Update Session": "セッションを更新",
    "Start": "開始",
    "Met, in grace period": "満たされています、猶予期間中",
    "Met": "満たされています",
    "Not met": "満たされていません",
    "Copied!": "コピーしました！",
    "Copy command": "コマンドをコピー",
    "OK": "正常",
    "Needs attention": "要対応",
    "Tip": "ヒント",
    "Unknown": "不明",
    "Checking the helper": "ヘルパーを確認中",
    "One approval needed": "承認が 1 つ必要です",
    "The helper needs a reinstall": "ヘルパーの再インストールが必要です",
    "All set": "準備完了",
    "Making sure Keepresso's helper is awake and answering.": "Keepresso のヘルパーが起動して応答しているか確認しています。",
    "macOS turned the helper's background switch off, so it needs your approval again: in System Settings, under Login Items & Extensions, find Keepresso in App Background Activity and turn it on. Everything is password-free again right after.": "macOS がヘルパーのバックグラウンドスイッチをオフにしたため、再度承認が必要です：システム設定の「ログイン項目と機能拡張」で、「App のバックグラウンド活動」の中から Keepresso を見つけてオンにしてください。その直後から、再びすべてがパスワード不要になります。",
    "Keepresso repaired the helper's registration, but macOS keeps disabling it. An old copy of Keepresso in the Trash is the usual cause: empty the Trash, then reinstall the helper below. Nothing else about your setup changes.": "Keepresso はヘルパーの登録を修復しましたが、macOS が無効化し続けています。通常の原因は、ゴミ箱に残った古い Keepresso のコピーです：ゴミ箱を空にしてから、下でヘルパーを再インストールしてください。あなたの設定のほかの部分は変わりません。",
    "The helper is back. Closed-display mode and AWDL pausing work without password prompts again.": "ヘルパーが復帰しました。クラムシェルモードと AWDL の一時停止が、再びパスワードの要求なしで動作します。",
    "Waiting for the switch in System Settings; this updates by itself.": "システム設定でのスイッチ操作を待っています。この表示は自動的に更新されます。",
    "Record": "記録",
    "Press keys…": "キーを押してください…",
    "Other process, e.g. rsync": "その他のプロセス（例：rsync）",
    "Export Keepresso Settings": "Keepresso 設定を書き出す",
    "Import Keepresso Settings": "Keepresso 設定を読み込む",
    "Exported to %@.": "%@ に書き出しました。",
    "Settings imported.": "設定を読み込みました。",
    "Couldn't export settings: %@": "設定を書き出せませんでした：%@",
    "Couldn't read the file: %@": "ファイルを読み取れませんでした：%@",
    "That file isn't a Keepresso settings export.": "そのファイルは Keepresso の設定書き出しファイルではありません。",
    "That export was made by a newer version of Keepresso.": "その書き出しファイルは、より新しいバージョンの Keepresso で作成されています。",
    "Save current rules as…": "現在のルールを別名で保存…",
    "A recurring notification every interval while a session runs, so a Mac left awake keeps reminding you.": "セッションの実行中、一定間隔ごとに繰り返し通知します。スリープさせずに放置した Mac が通知し続けます。",
    "A one-time notification once a session has run this long, in case you forget the Mac is awake.": "セッションがこの時間実行された時点で一度だけ通知します。Mac が起きたままであることを忘れた場合に備えます。",
    "Watch": "監視",
    "Keep awake while downloads are in progress in this folder.": "このフォルダでダウンロードが進行中の間はスリープを防止します。",
    "Keep Awake": "スリープ防止",
    "Choose a folder on the disk you want to keep spun up.": "回転させ続けたいディスク上のフォルダを選択してください。",
    "Keepresso needs a new approval": "Keepresso に新しい承認が必要です",
    "macOS turned Keepresso's background switch off. Turn it back on under Login Items & Extensions in System Settings to keep the password-free helper.": "macOS が Keepresso のバックグラウンドスイッチをオフにしました。パスワード不要のヘルパーを維持するには、システム設定の「ログイン項目と機能拡張」で再度オンにしてください。",
    "Keepresso needs your password": "Keepresso にパスワードが必要です",
    "Enter your administrator password to switch closed-display mode on for this session.": "このセッションでクラムシェルモードをオンにするため、管理者パスワードを入力してください。",
    "Enter your administrator password to pause AWDL for this game.": "このゲームのために AWDL を一時停止するには、管理者パスワードを入力してください。",
    "Game detected": "ゲームを検出しました",
    "Pausing AWDL to steady your connection.": "接続を安定させるため AWDL を一時停止しています。",
    "AWDL resumed": "AWDL を再開しました",
    "The game closed; AirDrop, Handoff and Continuity are back.": "ゲームが終了しました。AirDrop、Handoff、連係が復帰しました。",
    "This copy of Keepresso isn't in the Applications folder, so it leaves the helper alone. Install from /Applications.": "この Keepresso のコピーは「アプリケーション」フォルダにないため、ヘルパーには手を触れません。/Applications からインストールしてください。",
    "The helper wasn't found inside the app. Reinstall Keepresso and try again.": "App 内にヘルパーが見つかりませんでした。Keepresso を再インストールして、もう一度お試しください。",
    "The helper couldn't be registered.": "ヘルパーを登録できませんでした。",
    "The helper couldn't be removed: %@": "ヘルパーを削除できませんでした：%@",
    "macOS still reports the helper as registered. Try again, or restart the Mac.": "macOS はまだヘルパーを登録済みと報告しています。もう一度試すか、Mac を再起動してください。",
    "Removed. System Settings may keep showing Keepresso under App Background Activity until macOS refreshes its list; restarting the Mac clears the leftover row.": "削除しました。macOS がリストを更新するまで、システム設定の「App のバックグラウンド活動」に Keepresso が表示され続けることがあります。Mac を再起動すると、残った行が消去されます。",
    "macOS is refusing the helper's registration outright. Reinstall the helper; if that doesn't take, restart the Mac and try once more.": "macOS がヘルパーの登録を完全に拒否しています。ヘルパーを再インストールしてください。それでも反映されない場合は、Mac を再起動してもう一度お試しください。",
    "The helper isn't responding. If an old copy of Keepresso is in the Trash, empty the Trash first: macOS keeps disabling the helper while one is there. Then reinstall the helper.": "ヘルパーが応答していません。古い Keepresso のコピーがゴミ箱にある場合は、まずゴミ箱を空にしてください：それがある間、macOS はヘルパーを無効化し続けます。その後、ヘルパーを再インストールしてください。",
    "Old copy stuck in the Trash": "古いコピーがゴミ箱に残っています",
    "An old copy of Keepresso in the Trash keeps the background helper from working. Please delete it from the Trash, or empty the Trash.": "ゴミ箱にある古い Keepresso のコピーが、バックグラウンドヘルパーの動作を妨げています。ゴミ箱からそれを削除するか、ゴミ箱を空にしてください。",
    "Language": "言語",
    "App language": "App の言語",
    "Follow System": "システムに従う",
    "Keepresso follows your system language by default. Changing this relaunches Keepresso so menus, windows, and notifications all switch together.": "Keepresso はデフォルトでシステムの言語に従います。これを変更すると Keepresso が再起動し、メニュー、ウインドウ、通知がすべて一緒に切り替わります。",
    "%d h %d min": "%d 時間 %d 分",
    "%d h": "%d 時間",
    "%d min": "%d 分",
    "%d:%02d": "%d:%02d",
    "%ds": "%d 秒",
    "%d:%02d:%02d": "%d:%02d:%02d",
    "Keepresso: paused, battery low": "Keepresso：一時停止中、バッテリー残量低下",
    "Keepresso: brewing": "Keepresso：抽出中",
    "Keepresso: idle": "Keepresso：アイドル",
    "1920 × 1080": "1920 × 1080",
    "2560 × 1440": "2560 × 1440",
    "2880 × 1620": "2880 × 1620",
    "3840 × 2160 (4K)": "3840 × 2160 (4K)",
    "Stop in": "停止までの時間",
    "Quick stop shortcuts": "クイック停止ショートカット",
    "Add Shortcut": "ショートカットを追加",
    "Shortcut %d": "ショートカット %d",
    "Remove shortcut": "ショートカットを削除",
    "One-click “Stop in” buttons shown in the menu while a session runs, so the Mac goes back to sleeping on its own that much later. Up to four; the list stays sorted.": "セッションの実行中にメニューに表示されるワンクリックの「停止までの時間」ボタン。指定した時間の経過後に Mac がひとりでにスリープへ戻れるようになります。最大 4 つで、リストは常に並べ替えられます。",
    "Warn before a timed session ends": "時間指定セッションの終了前に警告",
    "Warn": "警告",
    "1 minute before": "1 分前",
    "2 minutes before": "2 分前",
    "5 minutes before": "5 分前",
    "10 minutes before": "10 分前",
    "AI agents": "AI エージェント",
    "AI agent is working": "AI エージェントが作業中",
    "Keeps the Mac awake while a coding-agent session (claude, codex, gemini, aider, and the like) is actively working, judged by its CPU use, and lets it sleep once every session has gone idle for the grace period. The menu lists each detected session. A freshly started session can take a few seconds to read as working.": "コーディングエージェントのセッション（claude、codex、gemini、aider など）が CPU 使用率から見て実際に作業している間、Mac をスリープさせずに保ちます。すべてのセッションが猶予時間のあいだアイドルになると、Mac はスリープできるようになります。メニューには検出された各セッションが表示されます。起動直後のセッションが作業中と判定されるまで数秒かかることがあります。",
    "Idle grace period": "アイドル時の猶予時間",
    "Instantly": "すぐに",
    "10 minutes": "10 分",
    "working": "作業中",
    "idle": "アイドル",
    "+%d more": "他 %d 件",
}


# --- Agent hooks (Claude Code connection) ---
APP.update({
    "Claude Code connected: sessions report working and waiting exactly.": "Claude Code 接続済み: セッションが作業中と待機中を正確に報告します。",
    "Connect Claude Code for exact session tracking (adds hooks to its settings).": "Claude Code を接続するとセッションを正確に追跡できます（設定にフックを追加します）。",
    "Connect Claude Code": "Claude Code を接続",
    "Claude Code's settings file couldn't be read, so it was left untouched.": "Claude Code の設定ファイルを読み取れなかったため、変更していません。",
    "Couldn't update Claude Code's settings file.": "Claude Code の設定ファイルを更新できませんでした。",
})
