# -*- coding: utf-8 -*-
# Japanese overlay for catalog_core.py: English source -> Japanese.
CORE = {
    "On AC power": "電源接続時",
    "On battery": "バッテリー使用時",
    "Charging": "充電中",
    "External display connected": "外部ディスプレイ接続中",
    "is running": "実行中",
    "is frontmost": "最前面",
    "Audio playing": "オーディオ再生中",
    "VPN connected": "VPN 接続中",
    "Calendar event in progress": "カレンダーイベント進行中",
    "Playing a game": "ゲームプレイ中",
    "Camera in use": "カメラ使用中",
    "Microphone in use": "マイク使用中",
    "On Wi-Fi “%@”": "Wi-Fi「%@」に接続中",
    "Process “%@” running": "プロセス「%@」が実行中",
    "Volume “%@” mounted": "ボリューム「%@」がマウント済み",
    "Bluetooth “%@” connected": "Bluetooth「%@」が接続済み",
    "Downloading in “%@”": "「%@」でダウンロード中",
    "CPU above %d%%": "CPU が %d%% を超過",
    "Network above %@": "ネットワークが %@ を超過",
    "App %@": "App %@",
    "Every day": "毎日",
    "Weekdays": "平日",
    "Weekends": "週末",
    "Do nothing": "何もしない",
    "Sleep the display": "ディスプレイをスリープ",
    "Start the screen saver": "スクリーンセーバを開始",
    "AI Agent": "AI エージェント",
    "On AC Power": "電源接続時",
    "External Display Connected": "外部ディスプレイ接続中",
    "Remote Session (SSH)": "リモートセッション (SSH)",
    "Backup Running": "バックアップ実行中",
    "Media Render": "メディアレンダリング",
    "Meetings": "ミーティング",
    "Cloud Gaming": "クラウドゲーミング",
    "Remote Control": "リモートコントロール",
    "Remote Login (SSH)": "リモートログイン (SSH)",
    "Remote Login is on, so you can reach this Mac over SSH.": "リモートログインがオンになっているため、SSH でこの Mac にアクセスできます。",
    "Remote Login is off. You might want to enable it for SSH access to a headless Mac.": "リモートログインはオフです。ディスプレイのない Mac に SSH でアクセスするには、オンにするとよいでしょう。",
    "Couldn't confirm Remote Login. If you want SSH access, enable it in System Settings.": "リモートログインを確認できませんでした。SSH アクセスが必要な場合は、システム設定でオンにしてください。",
    "Screen Sharing": "画面共有",
    "Screen Sharing is on, so you can connect with the Screen Sharing app or VNC.": "画面共有がオンになっているため、「画面共有」App または VNC で接続できます。",
    "Screen Sharing is off. You might want to enable it to view a headless Mac's screen.": "画面共有はオフです。ディスプレイのない Mac の画面を表示するには、オンにするとよいでしょう。",
    "Couldn't confirm Screen Sharing. If you want remote viewing, enable it in System Settings.": "画面共有を確認できませんでした。リモートで表示したい場合は、システム設定でオンにしてください。",
    "Enable it in System Settings ▸ General ▸ Sharing.": "システム設定 ▸ 一般 ▸ 共有 でオンにしてください。",
    "Run AI agents on this Mac with MyAgens": "MyAgens でこの Mac 上で AI エージェントを実行",
    "MyAgens lets AI agents operate your Mac and help with your work, which is handy on an always-on machine you mostly reach remotely.": "MyAgens を使うと、AI エージェントが Mac を操作して作業を手伝えます。主にリモートでアクセスする常時稼働のマシンで便利です。",
    "Learn more about MyAgens:": "MyAgens について詳しくはこちら：",
    "GitHub": "GitHub",
    "Read more": "続きを読む",
    "Wake for network access": "ネットワークアクセスによるスリープ解除",
    "The Mac wakes when accessed over the network.": "ネットワーク経由でアクセスされると Mac がスリープ解除します。",
    "The Mac won't wake for network access, so remote logins may fail.": "Mac はネットワークアクセスでスリープ解除しないため、リモートログインが失敗する場合があります。",
    "Couldn't read the power settings.": "電源設定を読み取れませんでした。",
    "Enable “Wake for network access”.": "「ネットワークアクセスによるスリープ解除」をオンにしてください。",
    "Restart after power failure": "停電後に再起動",
    "The Mac restarts automatically after a power failure.": "停電後に Mac が自動的に再起動します。",
    "The Mac stays off after a power cut, so it won't come back headless.": "停電後 Mac はオフのままになるため、ディスプレイなしでは自動的に復帰しません。",
    "Enable automatic restart after a power failure.": "停電後の自動再起動をオンにしてください。",
    "System sleep disabled": "システムスリープ無効",
    "Idle system sleep is disabled, so the Mac stays reachable.": "アイドル時のシステムスリープが無効になっているため、Mac にアクセスし続けられます。",
    "The Mac sleeps when idle; Keepresso prevents this while a session runs, but a global setting is safer headless.": "Mac はアイドル時にスリープします。Keepresso はセッション中これを防ぎますが、ディスプレイなしではグローバル設定のほうが安全です。",
    "Disable idle system sleep.": "アイドル時のシステムスリープを無効にしてください。",
    "FileVault disabled": "FileVault 無効",
    "FileVault is off, so the Mac can reboot unattended to the login window.": "FileVault はオフのため、Mac は無人でログインウインドウまで再起動できます。",
    "FileVault is on, so a reboot blocks at the disk-unlock screen until someone types the password, defeating headless restart.": "FileVault はオンのため、再起動はディスクのロック解除画面で止まり、誰かがパスワードを入力するまで進みません。これではディスプレイなしの再起動ができません。",
    "Couldn't determine the FileVault status.": "FileVault の状態を判別できませんでした。",
    "For an unattended Mac, consider turning FileVault off (weigh the security trade-off).": "無人の Mac では、FileVault をオフにすることを検討してください（セキュリティとのトレードオフを考慮してください）。",
    "Automatic login": "自動ログイン",
    "Automatic login is on (%@), so the Mac reaches the desktop after a reboot without a keyboard.": "自動ログインがオン (%@) のため、Mac はキーボードなしで再起動後にデスクトップまで到達します。",
    "Automatic login is off. After a reboot the Mac waits at the login window for a password.": "自動ログインはオフです。再起動後、Mac はログインウインドウでパスワードの入力を待ちます。",
    "Turn on automatic login for this account.": "このアカウントの自動ログインをオンにしてください。",
    "Keepresso stopped": "Keepresso が停止しました",
    "Your keep-awake session has ended.": "スリープ防止セッションが終了しました。",
    "Paused on low battery": "バッテリー低下で一時停止",
    "Battery is at %d%%. Keepresso is letting the Mac sleep until you plug in to charge.": "バッテリー残量は %d%% です。充電のために電源を接続するまで、Keepresso は Mac をスリープさせます。",
    "Keepresso is still brewing": "Keepresso はまだ抽出中です",
    "Your Mac is still awake. It's been %@.": "Mac はまだスリープしていません。%@ が経過しました。",
    "Your Mac has been kept awake for %@.": "Mac は %@ の間スリープを防止されています。",
    "Started manually": "手動で開始",
    "Restarted manually": "手動で再開",
    "Started by a command": "コマンドで開始",
    "Restarted by a command": "コマンドで再開",
    "Timed session ended": "タイマーセッション終了",
    "Paused, battery below %d%%": "一時停止、バッテリーが %d%% 未満",
    "Not started, battery below %d%%": "未開始、バッテリーが %d%% 未満",
    "Stopped manually": "手動で停止",
    "Stopped by a command": "コマンドで停止",
    "Trigger conditions met": "トリガー条件を満たしました",
    "Trigger conditions ended": "トリガー条件が解除されました",
    "Triggers: %@": "トリガー：%@",
    "%@ (+%ds)": "%@（+%d 秒）",
    "Couldn't create the watchdog flag file.": "監視のフラグファイルを作成できませんでした。",
    "Couldn't run the watchdog command.": "監視コマンドを実行できませんでした。",
    "The watchdog couldn't be started.": "監視を開始できませんでした。",
    "Couldn't create the sleep watchdog flag file.": "スリープ監視のフラグファイルを作成できませんでした。",
    "Couldn't run the sleep watchdog command.": "スリープ監視コマンドを実行できませんでした。",
    "The sleep watchdog couldn't be started.": "スリープ監視を開始できませんでした。",
    "Couldn't run the sleep setting command.": "スリープ設定コマンドを実行できませんでした。",
    "The sleep setting couldn't be changed.": "スリープ設定を変更できませんでした。",
    "The Keepresso helper isn't responding.": "Keepresso ヘルパーが応答していません。",
    "The Keepresso helper couldn't change the setting.": "Keepresso ヘルパーが設定を変更できませんでした。",
    "Virtual displays aren't available on this macOS version.": "この macOS バージョンでは仮想ディスプレイを使用できません。",
    "Couldn't create the virtual display.": "仮想ディスプレイを作成できませんでした。",
    "Preventing system sleep": "システムスリープを防止中",
    "Preventing display sleep": "ディスプレイスリープを防止中",
    "Keeping disks awake": "ディスクを稼働状態に維持中",
    "Declaring the user active": "ユーザーをアクティブとして宣言中",
    "Holding off idle sleep for a background task": "バックグラウンドタスクのためアイドルスリープを保留中",
    "Not enough replies to measure.": "測定に十分な応答がありません。",
    "Baseline %d ms": "ベースライン %d ms",
    "%d spike up to %d ms": "%d 回のスパイク、最大 %d ms",
    "%d spikes up to %d ms": "%d 回のスパイク、最大 %d ms",
    "max %d ms": "最大 %d ms",
    "%d lost": "%d 個消失",
    "Wired network": "有線ネットワーク",
    "Couldn't read the network interfaces.": "ネットワークインターフェイスを読み取れませんでした。",
    "Ethernet is connected (%@). A wired link sidesteps Wi-Fi jitter entirely, the most reliable fix.": "Ethernet が接続されています (%@)。有線接続なら Wi-Fi のジッターを完全に回避でき、最も確実な解決策です。",
    "An Ethernet adapter is available but no cable is connected.": "Ethernet アダプタは利用できますが、ケーブルが接続されていません。",
    "For gaming or streaming, a wired connection beats any Wi-Fi tuning.": "ゲームやストリーミングでは、有線接続がどの Wi-Fi 調整よりも優れています。",
    "No wired network adapter found.": "有線ネットワークアダプタが見つかりません。",
    "A USB-C or Thunderbolt Ethernet adapter sidesteps Wi-Fi jitter entirely.": "USB-C または Thunderbolt の Ethernet アダプタなら、Wi-Fi のジッターを完全に回避できます。",
    "Wi-Fi channel": "Wi-Fi チャンネル",
    "Not connected to Wi-Fi, or its details are unreadable.": "Wi-Fi に接続していないか、その詳細を読み取れません。",
    "If you game or stream over Wi-Fi, re-check while connected.": "Wi-Fi でゲームやストリーミングをする場合は、接続中に再確認してください。",
    "channel %d at %d MHz": "チャンネル %d、%d MHz",
    "channel %d": "チャンネル %d",
    "On 2.4 GHz (%@), the slowest band, where every AWDL hop costs the most.": "2.4 GHz (%@)、最も遅い帯域で、AWDL のホップごとの影響が最も大きくなります。",
    "Prefer a 5 GHz network on %@ at 80 MHz. If 2.4 GHz is unavoidable, set the router to channel 6, AWDL's 2.4 GHz social channel.": "80 MHz の %@ で 5 GHz ネットワークを優先してください。2.4 GHz が避けられない場合は、ルーターを AWDL の 2.4 GHz ソーシャルチャンネルであるチャンネル 6 に設定してください。",
    "On 6 GHz (%@). AWDL's social channels live on 2.4 and 5 GHz, so there's nothing to align here. If stutter persists, a 5 GHz network on %@ keeps AWDL's hops on-channel.": "6 GHz (%@)。AWDL のソーシャルチャンネルは 2.4 GHz と 5 GHz にあるため、ここで合わせるものはありません。カクつきが続く場合は、%@ の 5 GHz ネットワークにすると AWDL のホップが同一チャンネルに保たれます。",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel.": "%@ は AWDL の 5 GHz ソーシャルチャンネルと一致しているため、そのホップは同一チャンネルに保たれます。",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel. Raising the router to 80 MHz width completes the alignment.": "%@ は AWDL の 5 GHz ソーシャルチャンネルと一致しているため、そのホップは同一チャンネルに保たれます。ルーターを 80 MHz 幅に上げると、位置合わせが完了します。",
    "On 5 GHz %@. AWDL's off-channel hops leave this channel roughly every second.": "5 GHz %@。AWDL のオフチャンネルホップは、約 1 秒ごとにこのチャンネルを離れます。",
    "Set the router to %@ at 80 MHz so AWDL's hops stay on-channel.": "AWDL のホップが同一チャンネルに保たれるよう、ルーターを 80 MHz の %@ に設定してください。",
    "channel 44 (the EU social channel) or 149 (the US and Canada social channel), whichever your region allows": "チャンネル 44（EU のソーシャルチャンネル）またはチャンネル 149（米国とカナダのソーシャルチャンネル）のうち、お住まいの地域で許可されているもの",
    "channel 44, AWDL's 5 GHz social channel in the EU": "チャンネル 44、EU における AWDL の 5 GHz ソーシャルチャンネル",
    "channel 149, AWDL's 5 GHz social channel where UNII-3 is allowed (the US, Canada, and most of the world)": "チャンネル 149、UNII-3 が許可されている地域（米国、カナダ、および世界の大部分）における AWDL の 5 GHz ソーシャルチャンネル",
    "Bluetooth during play": "プレイ中の Bluetooth",
    "Bluetooth is on. It shares the radio chip with Wi-Fi, so heavy Bluetooth traffic (audio, controllers) can add its own blips.": "Bluetooth はオンです。無線チップを Wi-Fi と共有しているため、Bluetooth の通信量が多い（オーディオ、コントローラー）と、それ自体が瞬間的な乱れを加えることがあります。",
    "Nothing to fix: just a variable to know about if stutter persists on a clean channel.": "修正すべきことはありません。クリーンなチャンネルでもカクつきが続く場合に知っておくべき要因の 1 つにすぎません。",
    "Bluetooth is off, so it isn't competing with Wi-Fi for the radio.": "Bluetooth はオフのため、無線を Wi-Fi と奪い合っていません。",
    "Couldn't read the Bluetooth radio state.": "Bluetooth 無線の状態を読み取れませんでした。",
    "Game Mode": "ゲームモード",
    "macOS turns on Game Mode by itself when a game runs full screen: the game gets CPU and GPU priority, and Bluetooth controllers and audio get faster sampling. If the game-controller icon doesn't appear in the menu bar while playing, put the game into full screen.": "macOS は、ゲームがフルスクリーンで実行されると自動的にゲームモードをオンにします。ゲームは CPU と GPU の優先度が上がり、Bluetooth コントローラーとオーディオのサンプリングが速くなります。プレイ中にメニューバーにゲームコントローラーのアイコンが表示されない場合は、ゲームをフルスクリーンにしてください。",
    "How Game Mode works:": "ゲームモードの仕組み：",
    "Learn more": "詳しく知る",
    "Cloud gaming in the browser": "ブラウザでのクラウドゲーミング",
    "Xbox Cloud Gaming and the web versions of GeForce NOW run in a browser tab, so there's no app for the gaming condition to spot. The “Audio playing” condition covers them: game sound keeps the session brewing.": "Xbox Cloud Gaming と GeForce NOW の Web 版はブラウザのタブで実行されるため、ゲーム条件が検出できる App はありません。「オーディオ再生中」条件がこれらをカバーします。ゲームの音がセッションを抽出状態に保ちます。",
    "Add it under Preferences ▸ Triggers ▸ Add ▸ Apps & Activity ▸ Media.": "設定 ▸ トリガー ▸ 追加 ▸ App とアクティビティ ▸ メディア で追加してください。",
    "Location Services and Wi-Fi scans": "位置情報サービスと Wi-Fi スキャン",
    "Location Services triggers independent Wi-Fi scans, another source of occasional blips. Keepresso itself uses Location to read Wi-Fi network names for triggers, so weigh that before turning anything off.": "位置情報サービスは独立した Wi-Fi スキャンを発生させ、これも時折の乱れの原因になります。Keepresso 自身もトリガー用に Wi-Fi ネットワーク名を読み取るために位置情報を使用するため、何かをオフにする前に考慮してください。",
    "Review which apps use Location:": "どの App が位置情報を使用しているか確認：",
    "Why streams stutter once a second": "ストリームが 1 秒ごとにカクつく理由",
    "The Wi-Fi radio hops off-channel for AWDL (AirDrop, Handoff, Sidecar, Continuity) roughly every second, which shows up as 50-100 ms ping spikes. The jitter test reproduces the diagnosis; the AWDL watchdog is the session-scoped fix.": "Wi-Fi 無線は約 1 秒ごとに AWDL（AirDrop、Handoff、Sidecar、連係）のためにオフチャンネルにホップし、これが 50〜100 ms の ping スパイクとして現れます。ジッターテストはこの診断を再現します。AWDL 監視はセッション単位の解決策です。",
    "The full story:": "詳しい説明：",
}

WIDGET = {
    "Keep Awake": "スリープ防止",
    "See and control whether Keepresso is keeping the Mac awake.": "Keepresso が Mac のスリープを防止しているかどうかを確認・操作できます。",
    "Start or stop keeping the Mac awake.": "Mac のスリープ防止を開始または停止します。",
    "Keepresso": "Keepresso",
    "Brewing": "抽出中",
    "Off": "オフ",
    "Keeping the Mac awake": "Mac のスリープを防止中",
    "The Mac can sleep": "Mac はスリープできます",
    "Stop": "停止",
    "Start": "開始",
    "Resume Triggers": "トリガーを再開",
    "Pause Triggers": "トリガーを一時停止",
}
