# -*- coding: utf-8 -*-
# Korean overlay for catalog_app.py: English source -> Korean.
APP = {
    "Add": "추가",
    "Add:": "추가:",
    "Clear": "지우기",
    "Close": "닫기",
    "Done": "완료",
    "Save": "저장",
    "Enable": "활성화",
    "Enabled": "활성화됨",
    "Installed": "설치됨",
    "Remove": "제거",
    "Remove condition": "조건 제거",
    "Resume": "재개",
    "Later": "나중에",
    "Learn more": "더 알아보기",
    "Re-check": "다시 확인",
    "Run Test": "테스트 실행",
    "Match": "일치",
    "Threshold": "임계값",
    "Battery threshold": "배터리 임계값",
    "Presence": "온라인 상태",
    "Menu bar": "메뉴 막대",
    "Battery": "배터리",
    "Welcome": "환영",
    "Keeps the Mac running with the lid shut and no external display. This flips a system setting that needs administrator rights: silent with the administrator helper installed (Preferences ▸ General), otherwise macOS asks for your password.": "덮개를 닫고 외부 디스플레이가 없어도 Mac이 계속 실행되도록 유지합니다. 이는 관리자 권한이 필요한 시스템 설정을 전환합니다. 관리자 도우미가 설치되어 있으면 조용히 처리되고 (환경설정 ▸ 일반), 그렇지 않으면 macOS가 암호를 요청합니다.",
    "Turns closed-display mode on when a keep-awake session starts and off when it ends or Keepresso quits.": "깨어 있게 유지 세션이 시작될 때 디스플레이 닫힘 모드를 켜고, 세션이 끝나거나 Keepresso가 종료될 때 끕니다.",
    "Grace period": "유예 시간",
    "Section": "섹션",
    "Schedule": "일정",
    "Set Duration": "지속 시간 설정",
    "For": "동안",
    "From": "시작",
    "To": "종료",
    "Until": "까지",
    "When": "시점",
    "Below": "미만",
    "Power": "전원",
    "Display": "디스플레이",
    "Network": "네트워크",
    "Media": "미디어",
    "Backup": "백업",
    "Folder": "폴더",
    "Downloads": "다운로드",
    "Touch": "터치",
    "Resolution": "해상도",
    "Startup": "시작",
    "Gaming": "게임",
    "None": "없음",
    "any": "임의",
    "all": "전체",
    "of these are true:": "다음 조건이 충족됩니다:",
    "1 minute": "1분",
    "2 minutes": "2분",
    "5 minutes": "5분",
    "10 seconds": "10초",
    "30 seconds": "30초",
    "15 minutes": "15분",
    "30 minutes": "30분",
    "1 hour": "1시간",
    "2 hours": "2시간",
    "4 hours": "4시간",
    "8 hours": "8시간",
    "No grace": "유예 없음",
    "Every 1 minute": "1분마다",
    "Every 5 minutes": "5분마다",
    "Every 10 minutes": "10분마다",
    "Every 30 minutes": "30분마다",
    "Every": "매",
    "After": "이후",
    "Keepresso": "Keepresso",
    "About Keepresso": "Keepresso 정보",
    "Welcome to Keepresso": "Keepresso에 오신 것을 환영합니다",
    "Keepresso Setup": "Keepresso 설정",
    "Keepresso Helper": "Keepresso 도우미",
    "Preferences": "환경설정",
    "Preferences…": "환경설정…",
    "A menu-bar app that keeps your Mac awake on your terms.": "원하는 조건에 따라 Mac을 깨어 있게 유지하는 메뉴 막대 앱입니다.",
    "AWDL watchdog": "AWDL 워치독",
    "Activate by triggers": "트리거로 활성화",
    "Administrator helper": "관리자 도우미",
    "Allow Bluetooth access…": "Bluetooth 접근 허용…",
    "Allow Wi-Fi access…": "Wi-Fi 접근 허용…",
    "Allow calendar access…": "캘린더 접근 허용…",
    "App is frontmost": "앱이 맨 앞에 있음",
    "App is running": "앱이 실행 중",
    "App match & grace period": "앱 일치 및 유예 시간",
    "Apply or remove": "적용 또는 제거",
    "Approve…": "승인…",
    "Apps & Activity": "앱 및 활동",
    "Bluetooth device connected": "Bluetooth 기기 연결됨",
    "Bluetooth rules need Bluetooth access (System Settings ▸ Privacy)": "Bluetooth 규칙에는 Bluetooth 접근 권한이 필요합니다 (시스템 설정 ▸ 개인정보 보호)",
    "CPU load": "CPU 부하",
    "CPU threshold": "CPU 임계값",
    "Camera in use": "카메라 사용 중",
    "Change…": "변경…",
    "Charging": "충전 중",
    "Check for Updates…": "업데이트 확인…",
    "Closed-display mode": "디스플레이 닫힘 모드",
    "Contacting the helper…": "도우미에 연결하는 중…",
    "Create a virtual display": "가상 디스플레이 생성",
    "Currently paused from the menu bar.": "현재 메뉴 막대에서 일시 정지됨.",
    "Custom Duration…": "사용자 지정 지속 시간…",
    "During calendar events": "캘린더 이벤트 동안",
    "Export Settings…": "설정 내보내기…",
    "Import Settings…": "설정 가져오기…",
    "External display connected": "외부 디스플레이 연결됨",
    "Fix…": "해결…",
    "GNU GPL v3.0": "GNU GPL v3.0",
    "Gaming & Streaming": "게임 및 스트리밍",
    "Gaming & Streaming…": "게임 및 스트리밍…",
    "Get Started": "시작하기",
    "Global shortcut": "전역 단축키",
    "Headless Setup": "헤드리스 설정",
    "Headless Setup…": "헤드리스 설정…",
    "Headless virtual display (experimental)": "헤드리스 가상 디스플레이 (실험적 기능)",
    "Helper installed and responding": "도우미가 설치되어 응답 중",
    "HiDPI (Retina)": "HiDPI (Retina)",
    "How do you use your Mac?": "Mac을 어떻게 사용하시나요?",
    "Install Helper…": "도우미 설치…",
    "Install…": "설치…",
    "Jitter test": "지터 테스트",
    "Keep a disk spinning": "디스크를 계속 회전시키기",
    "Keep awake with lid closed": "덮개를 닫은 채로 깨어 있게 유지",
    "Keep awake with the lid closed": "덮개를 닫은 채로 깨어 있게 유지",
    "Keep awake": "깨어 있게 유지",
    "Keep me active": "나를 활성 상태로 유지",
    "Keeping the Mac awake now": "지금 Mac을 깨어 있게 유지 중",
    "Keepresso decisions": "Keepresso 결정",
    "Measuring, about 10 seconds…": "측정 중, 약 10초…",
    "Microphone in use": "마이크 사용 중",
    "Network & Devices": "네트워크 및 기기",
    "Network activity": "네트워크 활동",
    "Network threshold": "네트워크 임계값",
    "No Wi-Fi network joined": "연결된 Wi-Fi 네트워크 없음",
    "No apps running": "실행 중인 앱 없음",
    "No conditions yet, so the Mac can sleep.": "아직 조건이 없어 Mac이 잠들 수 있습니다.",
    "No conditions yet. Add some in Preferences ▸ Triggers.": "아직 조건이 없습니다. 환경설정 ▸ 트리거에서 추가하십시오.",
    "No days selected means every day.": "선택한 요일이 없으면 매일을 의미합니다.",
    "No paired devices": "페어링된 기기 없음",
    "No session activity yet.": "아직 세션 활동이 없습니다.",
    "No volumes mounted": "마운트된 볼륨 없음",
    "Not available on this macOS version.": "이 macOS 버전에서는 사용할 수 없습니다.",
    "Nothing is holding the Mac awake right now.": "지금은 Mac을 깨어 있게 유지하는 항목이 없습니다.",
    "Notify when a session ends": "세션이 끝나면 알림",
    "Notify when auto-pausing and resuming": "자동 일시 정지 및 재개 시 알림",
    "On AC power": "전원 연결 시",
    "On battery": "배터리 사용 시",
    "On session end": "세션 종료 시",
    "Only while brewing": "실행 중일 때만",
    "Open Login Items": "로그인 항목 열기",
    "Open Settings": "설정 열기",
    "Overnight (22:00-6:00)": "야간 (22:00-6:00)",
    "Pause AWDL automatically while gaming": "게임 중 AWDL 자동 일시 정지",
    "Pause AWDL now": "지금 AWDL 일시 정지",
    "Pause Triggers": "트리거 일시 정지",
    "Pause on low battery": "배터리 부족 시 일시 정지",
    "Play a sound": "소리 재생",
    "Playing a game": "게임 플레이 중",
    "Power & Display": "전원 및 디스플레이",
    "Presets": "프리셋",
    "Prevent display sleep": "디스플레이 잠자기 방지",
    "Prevent system sleep": "시스템 잠자기 방지",
    "Process is running": "프로세스가 실행 중",
    "Quit Keepresso": "Keepresso 종료",
    "Reduce lag and jitter": "랙과 지터 감소",
    "Reinstall Helper": "도우미 다시 설치",
    "Remind me it's still on": "계속 켜져 있음을 알림",
    "Repeat the reminder": "알림 반복",
    "Restore default presets": "기본 프리셋 복원",
    "Resume AWDL after leaving the game": "게임을 나간 후 AWDL 재개",
    "Resume Triggers": "트리거 재개",
    "Session end": "세션 종료",
    "Set Up…": "설정…",
    "Show Welcome Screen…": "시작 화면 표시…",
    "Show countdown in menu bar": "메뉴 막대에 카운트다운 표시",
    "Start keep-awake on launch": "실행 시 깨어 있게 유지 시작",
    "The helper needs attention": "도우미에 조치가 필요합니다",
    "The test couldn't run. Check that you're online and try again.": "테스트를 실행할 수 없습니다. 인터넷에 연결되어 있는지 확인하고 다시 시도하십시오.",
    "The watchdog below should smooth this out; re-run the test with it on to confirm.": "아래 워치독이 이 문제를 완화해 줄 것입니다. 켠 상태로 테스트를 다시 실행하여 확인하십시오.",
    "Times & days": "시간 및 요일",
    "Toggle shortcut": "전환 단축키",
    "Triggers paused. Controlling manually for now.": "트리거가 일시 정지되었습니다. 지금은 수동으로 제어합니다.",
    "Until a Time…": "특정 시각까지…",
    "VPN connected": "VPN 연결됨",
    "View on GitHub": "GitHub에서 보기",
    "Volume is mounted": "볼륨이 마운트됨",
    "Watch a folder for downloads…": "폴더의 다운로드 감시…",
    "While frontmost": "맨 앞에 있을 때",
    "While running": "실행 중일 때",
    "Work hours (weekdays 9:00-18:00)": "업무 시간 (평일 9:00-18:00)",
    "Audio playing": "오디오 재생 중",
    "Paused": "일시 정지됨",
    "Brewing": "실행 중",
    "Idle": "유휴",
    "System can sleep": "시스템이 잠들 수 있음",
    "No conditions yet": "아직 조건 없음",
    "Battery below %d%%, letting the Mac sleep": "배터리가 %d%% 미만이어서 Mac이 잠들도록 함",
    "Stops in %@": "%@ 후 중지",
    "Awake for %@": "%@ 동안 깨어 있음",
    "Active": "활성",
    "Held by %@": "%@에 의해 유지됨",
    "Waiting for any condition": "임의의 조건을 기다리는 중",
    "Waiting on %@": "%@ 대기 중",
    "%d condition": "%d개 조건",
    "%d conditions": "%d개 조건",
    "Approve Keepresso again in System Settings.": "시스템 설정에서 Keepresso를 다시 승인하십시오.",
    "The helper isn't responding; reinstall it.": "도우미가 응답하지 않습니다. 다시 설치하십시오.",
    "Waiting for a game to come to the front": "게임이 맨 앞으로 오기를 기다리는 중",
    "AWDL paused": "AWDL 일시 정지됨",
    "AWDL paused for gaming": "게임을 위해 AWDL 일시 정지됨",
    "Game closed, AWDL back in %ds": "게임 종료됨, %d초 후 AWDL 복귀",
    "Latency looks clean.": "지연 시간이 깨끗해 보입니다.",
    "Once-a-second spikes: this looks like AWDL.": "1초에 한 번씩 발생하는 스파이크: AWDL로 보입니다.",
    "Spiky, but not on AWDL's cadence (congestion or a weak signal).": "스파이크가 있지만 AWDL의 주기와는 맞지 않습니다 (혼잡 또는 약한 신호).",
    "Not enough replies to judge.": "판단하기에 응답이 충분하지 않습니다.",
    "AWDL is on right now": "현재 AWDL이 켜져 있음",
    "AWDL is off right now": "현재 AWDL이 꺼져 있음",
    "AWDL state unknown": "AWDL 상태 알 수 없음",
    "Agentic coding": "에이전트 코딩",
    "Stay awake while Claude, Codex, or Grok is running.": "Claude, Codex 또는 Grok이 실행되는 동안 깨어 있게 유지합니다.",
    "Gaming & streaming": "게임 및 스트리밍",
    "Stay awake while a game or cloud-gaming app is in front.": "게임 또는 클라우드 게임 앱이 맨 앞에 있는 동안 깨어 있게 유지합니다.",
    "Meetings & calls": "회의 및 통화",
    "Stay awake whenever the camera or microphone is in use.": "카메라나 마이크가 사용 중일 때 깨어 있게 유지합니다.",
    "Remote access": "원격 접근",
    "Stay awake while someone is connected over SSH.": "누군가 SSH로 연결되어 있는 동안 깨어 있게 유지합니다.",
    "Keep it manual for now": "지금은 수동으로 유지",
    "Just toggle keep-awake yourself, and set up your own triggers later in Preferences.": "깨어 있게 유지를 직접 전환하고, 나중에 환경설정에서 자신만의 트리거를 설정하십시오.",
    "Launch at login": "로그인 시 실행",
    "Start Keepresso automatically when you log in.": "로그인할 때 Keepresso를 자동으로 시작합니다.",
    "Notifications": "알림",
    "Let Keepresso remind you when a long session is still keeping the Mac awake.": "긴 세션이 여전히 Mac을 깨어 있게 유지하고 있을 때 Keepresso가 알려 주도록 합니다.",
    "Approve a small helper once and the privileged extras (lid-closed mode, AWDL pausing) never ask for your password again. Set and forget; removable in Preferences.": "작은 도우미를 한 번 승인하면 권한이 필요한 부가 기능(덮개 닫힘 모드, AWDL 일시 정지)이 다시는 암호를 요청하지 않습니다. 설정한 뒤 잊어버려도 되며, 환경설정에서 제거할 수 있습니다.",
    "Location access (Wi-Fi rules)": "위치 접근 (Wi-Fi 규칙)",
    "Bluetooth access (device rules)": "Bluetooth 접근 (기기 규칙)",
    "Calendar access (event rule)": "캘린더 접근 (이벤트 규칙)",
    "Keepresso launches at login, so it returns after a reboot.": "Keepresso가 로그인 시 실행되므로 재시동 후에 다시 돌아옵니다.",
    "Keepresso isn't set to launch at login, so it won't run after an unattended reboot.": "Keepresso가 로그인 시 실행되도록 설정되어 있지 않아 무인 재시동 후에는 실행되지 않습니다.",
    "Turn on “Launch at login” in Keepresso's settings.": "Keepresso 설정에서 “로그인 시 실행”을 켜십시오.",
    "Keepresso can read the current Wi-Fi network name for your Wi-Fi triggers.": "Keepresso는 Wi-Fi 트리거를 위해 현재 Wi-Fi 네트워크 이름을 읽을 수 있습니다.",
    "Without Location access Keepresso can't read the Wi-Fi network name, so Wi-Fi triggers won't match.": "위치 접근 권한이 없으면 Keepresso가 Wi-Fi 네트워크 이름을 읽을 수 없어 Wi-Fi 트리거가 일치하지 않습니다.",
    "Allow Location access for Keepresso.": "Keepresso에 위치 접근을 허용하십시오.",
    "Keepresso can see which paired devices are connected for your Bluetooth triggers.": "Keepresso는 Bluetooth 트리거를 위해 어떤 페어링된 기기가 연결되어 있는지 확인할 수 있습니다.",
    "Without Bluetooth access Keepresso can't see paired devices, so Bluetooth triggers won't match.": "Bluetooth 접근 권한이 없으면 Keepresso가 페어링된 기기를 확인할 수 없어 Bluetooth 트리거가 일치하지 않습니다.",
    "Allow Bluetooth access for Keepresso.": "Keepresso에 Bluetooth 접근을 허용하십시오.",
    "Keepresso can see when a calendar event is in progress for your calendar trigger.": "Keepresso는 캘린더 트리거를 위해 캘린더 이벤트가 진행 중인지 확인할 수 있습니다.",
    "Without full calendar access Keepresso can't see events, so the calendar trigger won't match.": "전체 캘린더 접근 권한이 없으면 Keepresso가 이벤트를 확인할 수 없어 캘린더 트리거가 일치하지 않습니다.",
    "Allow full calendar access for Keepresso.": "Keepresso에 전체 캘린더 접근을 허용하십시오.",
    "Keepresso can post the “still brewing” reminder.": "Keepresso가 “아직 실행 중” 알림을 보낼 수 있습니다.",
    "Notifications are off, so the “still brewing” reminder can't appear.": "알림이 꺼져 있어 “아직 실행 중” 알림이 표시될 수 없습니다.",
    "Allow notifications for Keepresso.": "Keepresso에 알림을 허용하십시오.",
    "Above %d%%": "%d%% 초과",
    "Above %@": "%@ 초과",
    "Version %@": "버전 %@",
    "Remove “%@”": "“%@” 제거",
    "On current Wi-Fi (%@)": "현재 Wi-Fi (%@)에서",
    "keep the Mac awake with the lid closed": "덮개를 닫은 채로 Mac 깨어 있게 유지",
    "switch closed-display mode with the session": "세션에 따라 디스플레이 닫힘 모드 전환",
    "pause AWDL (turn off the Wi-Fi AirDrop/Handoff radio hops)": "AWDL 일시 정지 (Wi-Fi AirDrop/Handoff 무선 홉 끄기)",
    "macOS is asking for your administrator password to %@. The dialog may be titled “osascript”: that's Keepresso running the command, and nothing else is changed. To stop these prompts for good, install the administrator helper (Preferences ▸ General).": "macOS가 관리자 암호를 요청하고 있습니다: %@. 대화상자 제목이 “osascript”일 수 있는데, 이는 Keepresso가 명령을 실행하는 것이며 그 외에는 아무것도 변경되지 않습니다. 이러한 요청을 완전히 없애려면 관리자 도우미를 설치하십시오 (환경설정 ▸ 일반).",
    "Keepresso keeps your Mac awake on your terms. It lives in the menu bar near the clock, with no Dock icon. Click its cup any time to start or stop.": "Keepresso는 원하는 조건에 따라 Mac을 깨어 있게 유지합니다. 시계 근처 메뉴 막대에 있으며 Dock 아이콘은 없습니다. 컵을 아무 때나 클릭하여 시작하거나 중지하십시오.",
    "Pick one to set up matching triggers, or keep it manual and add your own later. You can change this any time in Preferences.": "하나를 선택하여 알맞은 트리거를 설정하거나, 수동으로 유지하고 나중에 직접 추가하십시오. 이 설정은 환경설정에서 언제든지 변경할 수 있습니다.",
    "Activation is controlled by triggers.\nEdit them in Preferences.": "활성화는 트리거로 제어됩니다.\n환경설정에서 편집하십시오.",
    "Why each session started or stopped, newest first. Kept in memory; clears on relaunch.": "각 세션이 시작되거나 중지된 이유를 최신순으로 표시합니다. 메모리에 보관되며 다시 실행하면 지워집니다.",
    "Every app's live power assertions, not just Keepresso's, the same data pmset -g assertions prints.": "Keepresso뿐 아니라 모든 앱의 실시간 전원 어서션으로, pmset -g assertions가 출력하는 것과 동일한 데이터입니다.",
    "Lets the Mac sleep once battery charge drops below this level, even mid-session, so it doesn't run flat.": "배터리 충전량이 이 수준 아래로 떨어지면 세션 도중에도 Mac이 잠들도록 하여 방전되지 않게 합니다.",
    "Shows the remaining time next to the menu-bar icon during a timed session.": "시간 제한 세션 동안 메뉴 막대 아이콘 옆에 남은 시간을 표시합니다.",
    "Reopen the first-run welcome, with quick one-click setup for how you use your Mac.": "Mac 사용 방식에 맞춘 원클릭 빠른 설정이 있는 최초 실행 시작 화면을 다시 엽니다.",
    "If that time already passed today, it means tomorrow.": "그 시각이 오늘 이미 지났다면 내일을 의미합니다.",
    "Runs past midnight into the next day.": "자정을 지나 다음 날까지 이어집니다.",
    "Keeps the Mac awake while a partial-download file (.crdownload, .download, .part, and the like) exists in the chosen folder, then lets it sleep once the download finishes. Holds for 30 seconds between files in a batch.": "선택한 폴더에 부분 다운로드 파일(.crdownload, .download, .part 등)이 있는 동안 Mac을 깨어 있게 유지하다가, 다운로드가 끝나면 잠들도록 합니다. 일괄 처리 중 파일 사이에서는 30초 동안 유지합니다.",
    "Stays awake on battery too; the display turns off when the lid closes. Turn it off before putting it in a bag.": "배터리 사용 시에도 깨어 있게 유지되며, 덮개를 닫으면 디스플레이 자체는 꺼집니다. 가방에 넣기 전에 꺼 두십시오.",
    "The calendar rule needs Calendar access (System Settings ▸ Privacy)": "캘린더 규칙에는 캘린더 접근 권한이 필요합니다 (시스템 설정 ▸ 개인정보 보호)",
    "Wi-Fi rules need Location access (System Settings ▸ Privacy)": "Wi-Fi 규칙에는 위치 접근 권한이 필요합니다 (시스템 설정 ▸ 개인정보 보호)",
    "Checks an always-on Mac (e.g. a headless Mac mini) needs. Keepresso can read these but can't change the system ones, so use the links and commands below.": "항상 켜져 있는 Mac(예: 헤드리스 Mac mini)에 필요한 확인 항목입니다. Keepresso는 이 항목들을 읽을 수 있지만 시스템 설정은 변경할 수 없으므로 아래의 링크와 명령을 사용하십시오.",
    "macOS hops the Wi-Fi radio off-channel for AWDL about once a second, which shows up as ping spikes mid-game or mid-stream. Diagnose it here, and pause AWDL for the session if it's the culprit.": "macOS는 약 1초에 한 번씩 AWDL을 위해 Wi-Fi 무선을 다른 채널로 전환하는데, 이는 게임이나 스트리밍 도중 ping 스파이크로 나타납니다. 여기서 진단하고, 원인이라면 세션 동안 AWDL을 일시 정지하십시오.",
    "Pings 1.1.1.1 five times a second for 10 seconds and checks whether latency spikes on AWDL's once-a-second cadence.": "1.1.1.1에 초당 5회씩 10초 동안 ping을 보내 AWDL의 1초 주기로 지연 시간이 튀는지 확인합니다.",
    "Counts only while a game (or a cloud-gaming app) is the active window, not just running in the background. Keeps holding for 5 minutes after you switch away.": "게임(또는 클라우드 게임 앱)이 백그라운드에서 실행 중인 것이 아니라 활성 창일 때만 계산합니다. 다른 창으로 전환한 후에도 5분 동안 유지합니다.",
    "How long the pause lingers after the game stops being the active window, so a quick alt-tab doesn't flap the radios. Shorter brings AirDrop and Handoff back faster; longer rides out launchers and loading screens.": "게임이 활성 창에서 벗어난 뒤 일시 정지가 얼마나 지속되는지로, 빠른 alt-tab이 무선을 깜빡이게 하지 않도록 합니다. 짧으면 AirDrop과 Handoff가 더 빨리 돌아오고, 길면 런처와 로딩 화면을 견뎌 냅니다.",
    "Posts a notification when a game is detected and AWDL pauses, and again when it resumes. A notice that your administrator password is needed is always sent (even behind a fullscreen game), regardless of this switch.": "게임이 감지되어 AWDL이 일시 정지될 때 알림을 보내고, 다시 재개될 때도 알립니다. 관리자 암호가 필요하다는 알림은 이 스위치와 관계없이 항상 전송됩니다(전체 화면 게임 뒤에서도).",
    "Install a small helper service so closed-display mode and AWDL pausing never ask for your password again. macOS will ask you to allow it in System Settings, once; nothing else changes.": "작은 도우미 서비스를 설치하면 디스플레이 닫힘 모드와 AWDL 일시 정지가 다시는 암호를 요청하지 않습니다. macOS가 시스템 설정에서 한 번 허용하도록 요청하며, 그 외에는 아무것도 변경되지 않습니다.",
    "One step left, in System Settings: under General ▸ Login Items & Extensions (“Login Items” on older macOS), find Keepresso in the “Allow in the Background” list and turn its switch ON. macOS asks for your administrator password once; this updates by itself when you're done.": "시스템 설정에서 한 단계가 남았습니다. 일반 ▸ 로그인 항목 및 확장 프로그램(구형 macOS에서는 “로그인 항목”)에서 “백그라운드에서 허용” 목록의 Keepresso를 찾아 스위치를 켜십시오. macOS가 관리자 암호를 한 번 요청하며, 완료하면 이 항목이 자동으로 업데이트됩니다.",
    "Turns the pause on right now and keeps it on until you turn it off or quit Keepresso (it isn't tied to whether a keep-awake session is brewing). While it's on, AirDrop, Handoff, Sidecar, and Continuity Camera take a break, and the once-a-second lag spikes stop. Everything comes back the moment you turn it off or quit Keepresso; even if the app crashes, macOS is restored automatically. With the administrator helper installed the switch is always instant and silent; without it, macOS asks for your password once per launch (the system dialog may show “osascript”, which is Keepresso running the command).": "지금 즉시 일시 정지를 켜고, 끄거나 Keepresso를 종료할 때까지 유지합니다(깨어 있게 유지 세션이 실행 중인지와는 무관합니다). 켜져 있는 동안 AirDrop, Handoff, Sidecar, 연속성 카메라가 잠시 멈추고, 1초에 한 번씩 발생하는 지연 스파이크가 멈춥니다. 끄거나 Keepresso를 종료하는 순간 모든 것이 돌아오며, 앱이 충돌하더라도 macOS가 자동으로 복원됩니다. 관리자 도우미가 설치되어 있으면 스위치가 항상 즉각적이고 조용합니다. 없으면 macOS가 실행당 한 번 암호를 요청합니다(시스템 대화상자에 “osascript”가 표시될 수 있는데, 이는 Keepresso가 명령을 실행하는 것입니다).",
    "Watches for a game (or a cloud-gaming app like GeForce NOW) as the active window and pauses AWDL on its own, then lifts the pause a little after you switch away (the delay below). It only counts while the game is in front and in use, not just running in the background. Without the administrator helper, turning this on asks for your password once per app run, right now rather than mid-game; with the helper it never asks at all. No trigger setup needed: leave this on and forget it.": "게임(또는 GeForce NOW 같은 클라우드 게임 앱)이 활성 창인지 감시하여 스스로 AWDL을 일시 정지하고, 다른 창으로 전환한 조금 뒤에 일시 정지를 해제합니다(아래 지연). 게임이 백그라운드에서 실행되는 것이 아니라 맨 앞에서 사용 중일 때만 계산합니다. 관리자 도우미가 없으면 이 기능을 켤 때 게임 도중이 아니라 지금 앱 실행당 한 번 암호를 요청합니다. 도우미가 있으면 전혀 요청하지 않습니다. 트리거 설정이 필요 없습니다. 켜 두고 잊어버리십시오.",
    "Helper installed. Closed-display mode and AWDL pausing work without password prompts.": "도우미가 설치되었습니다. 디스플레이 닫힘 모드와 AWDL 일시 정지가 암호 요청 없이 작동합니다.",
    "Pause AWDL to steady your connection, and test your jitter, in Gaming & Streaming.": "게임 및 스트리밍에서 AWDL을 일시 정지하여 연결을 안정시키고 지터를 테스트하십시오.",
    "General": "일반",
    "Triggers": "트리거",
    "Reminder": "미리 알림",
    "Disk": "디스크",
    "Activity": "활동",
    "Indefinitely": "무기한",
    "Update Session": "세션 업데이트",
    "Start": "시작",
    "Met, in grace period": "충족됨, 유예 시간 중",
    "Met": "충족됨",
    "Not met": "충족되지 않음",
    "Copied!": "복사됨!",
    "Copy command": "명령 복사",
    "OK": "정상",
    "Needs attention": "조치 필요",
    "Tip": "팁",
    "Unknown": "알 수 없음",
    "Checking the helper": "도우미 확인 중",
    "One approval needed": "승인 한 번 필요",
    "The helper needs a reinstall": "도우미를 다시 설치해야 합니다",
    "All set": "모두 준비됨",
    "Making sure Keepresso's helper is awake and answering.": "Keepresso의 도우미가 작동 중이며 응답하는지 확인하는 중입니다.",
    "macOS turned the helper's background switch off, so it needs your approval again: in System Settings, under Login Items & Extensions, find Keepresso in App Background Activity and turn it on. Everything is password-free again right after.": "macOS가 도우미의 백그라운드 스위치를 껐으므로 다시 승인이 필요합니다. 시스템 설정의 로그인 항목 및 확장 프로그램에서 앱 백그라운드 활동의 Keepresso를 찾아 켜십시오. 그 직후 모든 것이 다시 암호 없이 작동합니다.",
    "Keepresso repaired the helper's registration, but macOS keeps disabling it. An old copy of Keepresso in the Trash is the usual cause: empty the Trash, then reinstall the helper below. Nothing else about your setup changes.": "Keepresso가 도우미 등록을 복구했지만 macOS가 계속 비활성화합니다. 보통 휴지통에 있는 오래된 Keepresso 사본이 원인입니다. 휴지통을 비운 다음 아래에서 도우미를 다시 설치하십시오. 설정의 다른 부분은 변경되지 않습니다.",
    "The helper is back. Closed-display mode and AWDL pausing work without password prompts again.": "도우미가 복구되었습니다. 디스플레이 닫힘 모드와 AWDL 일시 정지가 다시 암호 요청 없이 작동합니다.",
    "Waiting for the switch in System Settings; this updates by itself.": "시스템 설정의 스위치를 기다리는 중입니다. 이 항목은 자동으로 업데이트됩니다.",
    "Record": "기록",
    "Press keys…": "키를 누르십시오…",
    "Other process, e.g. rsync": "다른 프로세스, 예: rsync",
    "Export Keepresso Settings": "Keepresso 설정 내보내기",
    "Import Keepresso Settings": "Keepresso 설정 가져오기",
    "Exported to %@.": "%@(으)로 내보냈습니다.",
    "Settings imported.": "설정을 가져왔습니다.",
    "Couldn't export settings: %@": "설정을 내보낼 수 없습니다: %@",
    "Couldn't read the file: %@": "파일을 읽을 수 없습니다: %@",
    "That file isn't a Keepresso settings export.": "이 파일은 Keepresso 설정 내보내기 파일이 아닙니다.",
    "That export was made by a newer version of Keepresso.": "이 내보내기 파일은 더 새로운 버전의 Keepresso에서 생성되었습니다.",
    "Save current rules as…": "현재 규칙을 다른 이름으로 저장…",
    "A recurring notification every interval while a session runs, so a Mac left awake keeps reminding you.": "세션이 실행되는 동안 일정 간격마다 반복되는 알림으로, 깨어 있는 채로 둔 Mac이 계속 상기시켜 줍니다.",
    "A one-time notification once a session has run this long, in case you forget the Mac is awake.": "세션이 이만큼 실행된 뒤 한 번 표시되는 알림으로, Mac이 깨어 있다는 것을 잊었을 경우를 대비합니다.",
    "Watch": "감시",
    "Keep awake while downloads are in progress in this folder.": "이 폴더에서 다운로드가 진행되는 동안 깨어 있게 유지합니다.",
    "Keep Awake": "깨어 있게 유지",
    "Choose a folder on the disk you want to keep spun up.": "계속 회전시키려는 디스크의 폴더를 선택하십시오.",
    "Keepresso needs a new approval": "Keepresso에 새 승인이 필요합니다",
    "macOS turned Keepresso's background switch off. Turn it back on under Login Items & Extensions in System Settings to keep the password-free helper.": "macOS가 Keepresso의 백그라운드 스위치를 껐습니다. 암호 없는 도우미를 유지하려면 시스템 설정의 로그인 항목 및 확장 프로그램에서 다시 켜십시오.",
    "Keepresso needs your password": "Keepresso에 암호가 필요합니다",
    "Enter your administrator password to switch closed-display mode on for this session.": "이 세션에 대해 디스플레이 닫힘 모드를 켜려면 관리자 암호를 입력하십시오.",
    "Enter your administrator password to pause AWDL for this game.": "이 게임을 위해 AWDL을 일시 정지하려면 관리자 암호를 입력하십시오.",
    "Game detected": "게임 감지됨",
    "Pausing AWDL to steady your connection.": "연결을 안정시키기 위해 AWDL을 일시 정지합니다.",
    "AWDL resumed": "AWDL 재개됨",
    "The game closed; AirDrop, Handoff and Continuity are back.": "게임이 종료되었습니다. AirDrop, Handoff, 연속성이 복구되었습니다.",
    "This copy of Keepresso isn't in the Applications folder, so it leaves the helper alone. Install from /Applications.": "이 Keepresso 사본은 응용 프로그램 폴더에 없으므로 도우미를 건드리지 않습니다. /Applications에서 설치하십시오.",
    "The helper wasn't found inside the app. Reinstall Keepresso and try again.": "앱 내부에서 도우미를 찾을 수 없습니다. Keepresso를 다시 설치하고 다시 시도하십시오.",
    "The helper couldn't be registered.": "도우미를 등록할 수 없습니다.",
    "The helper couldn't be removed: %@": "도우미를 제거할 수 없습니다: %@",
    "macOS still reports the helper as registered. Try again, or restart the Mac.": "macOS가 여전히 도우미를 등록됨으로 보고합니다. 다시 시도하거나 Mac을 재시동하십시오.",
    "Removed. System Settings may keep showing Keepresso under App Background Activity until macOS refreshes its list; restarting the Mac clears the leftover row.": "제거되었습니다. macOS가 목록을 새로 고칠 때까지 시스템 설정의 앱 백그라운드 활동에 Keepresso가 계속 표시될 수 있습니다. Mac을 재시동하면 남은 항목이 지워집니다.",
    "macOS is refusing the helper's registration outright. Reinstall the helper; if that doesn't take, restart the Mac and try once more.": "macOS가 도우미 등록을 완전히 거부하고 있습니다. 도우미를 다시 설치하고, 그래도 적용되지 않으면 Mac을 재시동한 후 한 번 더 시도하십시오.",
    "The helper isn't responding. If an old copy of Keepresso is in the Trash, empty the Trash first: macOS keeps disabling the helper while one is there. Then reinstall the helper.": "도우미가 응답하지 않습니다. 휴지통에 오래된 Keepresso 사본이 있다면 먼저 휴지통을 비우십시오. 사본이 있는 동안에는 macOS가 도우미를 계속 비활성화합니다. 그런 다음 도우미를 다시 설치하십시오.",
    "Old copy stuck in the Trash": "휴지통에 걸린 오래된 사본",
    "An old copy of Keepresso in the Trash keeps the background helper from working. Please delete it from the Trash, or empty the Trash.": "휴지통에 있는 오래된 Keepresso 사본이 백그라운드 도우미의 작동을 막고 있습니다. 휴지통에서 삭제하거나 휴지통을 비우십시오.",
    "Language": "언어",
    "App language": "앱 언어",
    "Follow System": "시스템 설정 따르기",
    "%d h %d min": "%d시간 %d분",
    "%d h": "%d시간",
    "%d min": "%d분",
    "%d:%02d": "%d:%02d",
    "%ds": "%d초",
    "%d:%02d:%02d": "%d:%02d:%02d",
    "Keepresso: paused, battery low": "Keepresso: 일시 정지됨, 배터리 부족",
    "Keepresso: brewing": "Keepresso: 실행 중",
    "Keepresso: idle": "Keepresso: 유휴",
    "1920 × 1080": "1920 × 1080",
    "2560 × 1440": "2560 × 1440",
    "2880 × 1620": "2880 × 1620",
    "3840 × 2160 (4K)": "3840 × 2160 (4K)",
    "Stop in": "중지 예약",
    "Quick stop shortcuts": "빠른 중지 단축 버튼",
    "Add Shortcut": "단축 버튼 추가",
    "Shortcut %d": "단축 버튼 %d",
    "Remove shortcut": "단축 버튼 제거",
    "Warn before a timed session ends": "시간 지정 세션이 끝나기 전에 알림",
    "Warn": "알림",
    "1 minute before": "1분 전",
    "2 minutes before": "2분 전",
    "5 minutes before": "5분 전",
    "10 minutes before": "10분 전",
    "AI agents": "AI 에이전트",
    "AI agent is working": "AI 에이전트가 작업 중",
    "Keeps the Mac awake while a coding-agent session (claude, codex, gemini, aider, and the like) is actively working, judged by its CPU use, and lets it sleep once every session has gone idle for the grace period. The menu lists each detected session. A freshly started session can take a few seconds to read as working.": "코딩 에이전트 세션(claude, codex, gemini, aider 등)이 CPU 사용량 기준으로 실제 작업 중인 동안 Mac을 깨어 있게 유지하고, 모든 세션이 유예 기간 동안 유휴 상태가 되면 잠들 수 있게 합니다. 메뉴에 감지된 각 세션이 표시됩니다. 방금 시작한 세션은 작업 중으로 표시되기까지 몇 초가 걸릴 수 있습니다.",
    "Idle grace period": "유휴 유예 기간",
    "Instantly": "즉시",
    "10 minutes": "10분",
    "working": "작업 중",
    "idle": "유휴",
    "+%d more": "외 %d개",
    'Two independent switches. Preventing system sleep keeps the Mac itself running: work finishes, downloads complete, and it stays reachable over the network, while the screen is still free to turn off. Preventing display sleep also keeps the screen lit, which is what you want for a dashboard or a video, and what drains a battery fastest. Most setups want system sleep prevented and display sleep left alone.': '서로 독립적인 두 개의 스위치입니다. 시스템 잠자기 방지는 Mac 자체를 계속 실행 상태로 유지합니다. 작업이 끝나고, 다운로드가 완료되며, 네트워크를 통해 계속 연결할 수 있는 동안에도 화면은 자유롭게 꺼질 수 있습니다. 디스플레이 잠자기 방지는 화면도 계속 켜진 상태로 유지하는데, 이는 대시보드나 동영상에 적합하지만 배터리를 가장 빨리 소모시킵니다. 대부분의 환경에서는 시스템 잠자기만 방지하고 디스플레이 잠자기는 그대로 두는 것이 좋습니다.',
    "“Launch at login” starts Keepresso itself when you log in, so the cup is always in the menu bar. “Start keep-awake on launch” goes further and begins a session right away, using the default duration, for an always-on Mac that shouldn't need a rule to stay up. It's ignored while triggers are controlling activation, since your conditions decide then.": '“로그인 시 실행”은 로그인할 때 Keepresso 자체를 실행하여 컵이 항상 메뉴 막대에 있도록 합니다. “실행 시 깨어 있게 유지 시작”은 한 걸음 더 나아가 기본 지속 시간으로 즉시 세션을 시작하며, 계속 켜져 있어야 하는 Mac에 규칙 없이도 깨어 있게 해 줍니다. 트리거가 활성화를 제어하는 동안에는 무시되는데, 그때는 사용자의 조건이 대신 결정하기 때문입니다.',
    'Starts a session as soon as Keepresso launches.': 'Keepresso가 실행되는 즉시 세션을 시작합니다.',
    "System-wide, so it starts or stops keep-awake whatever app you're in. It needs at least one modifier key (Command, Option, Control, or Shift) so it can't fire while you're typing. Recording it asks for no Accessibility or Input Monitoring permission.": '시스템 전역에서 작동하므로 어떤 앱에 있든 깨어 있게 유지를 시작하거나 중지합니다. 입력 중에 실수로 작동하지 않도록 하나 이상의 조합 키(Command, Option, Control, Shift 중 하나)가 필요합니다. 단축키를 기록해도 손쉬운 사용이나 입력 모니터링 권한을 요청하지 않습니다.',
    'Starts or stops keep-awake from any app.': '어떤 앱에서든 깨어 있게 유지를 시작하거나 중지합니다.',
    "Fifteen languages are available. Changing this relaunches Keepresso, so the menu, every window, and notifications all switch together instead of drifting apart. Set it back to “Follow System” to follow your Mac's language again.": '15개 언어를 사용할 수 있습니다. 이 설정을 변경하면 Keepresso가 다시 실행되어 메뉴, 모든 창, 알림이 따로따로가 아니라 한꺼번에 전환됩니다. 다시 “시스템 설정 따르기”로 설정하면 Mac의 언어를 다시 따릅니다.',
    'Keepresso follows your system language by default.': 'Keepresso는 기본적으로 시스템 언어를 따릅니다.',
    'A small system service for the two switches that need administrator rights: closed-display mode below, and AWDL pausing in Gaming & Streaming. Without it, macOS asks for your password once per app run. With it, both are instant and silent: macOS asks once, when you approve the helper under Login Items, and the approval survives restarts and updates. It can only flip those specific switches, everything it changes is restored if Keepresso quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list; the status shown here is the real one.': '관리자 권한이 필요한 두 스위치, 즉 아래의 디스플레이 닫힘 모드와 게임 및 스트리밍의 AWDL 일시 정지를 위한 작은 시스템 서비스입니다. 이 서비스가 없으면 macOS는 앱을 실행할 때마다 암호를 요청합니다. 이 서비스가 있으면 두 기능 모두 즉시, 조용히 작동합니다. 로그인 항목에서 도우미를 승인할 때 macOS가 한 번 묻고, 그 승인은 재시동과 업데이트 후에도 유지됩니다. 이 서비스는 그 특정 스위치만 전환할 수 있고, 변경하는 모든 것은 Keepresso가 종료되거나 충돌하면 복원되며, 여기서 언제든지 제거할 수 있습니다. 또한 keepresso 명령행 도구를 PATH에 추가합니다(Homebrew 설치본에는 이미 있습니다). 제거 후에는 macOS가 목록을 새로 고칠 때까지 시스템 설정이 오래된 로그인 항목 행을 계속 표시할 수 있습니다. 여기 표시된 상태가 실제 상태입니다.',
    'Handles the privileged switches for Keepresso, with no password prompts.': '암호 요청 없이 Keepresso의 권한이 필요한 스위치를 처리합니다.',
    "Keeping the Mac awake stops it sleeping, but it doesn't reset app-level or enterprise idle detection: remote-desktop and VDI sessions, meeting presence (Teams, Slack), and corporate idle-logout can still mark you away or log you out. This tells macOS you're active as well, which those do notice. It only steps in once you've been idle a few seconds, so it never nudges the pointer while you're using the Mac or gaming. Off by default, and some managed Macs flag simulated activity, so check your policy first.": 'Mac을 깨어 있게 유지하면 잠들지 않지만, 앱 수준이나 기업 수준의 유휴 감지는 재설정되지 않습니다. 원격 데스크탑 및 VDI 세션, 회의 참석 상태(Teams, Slack), 회사의 유휴 자동 로그아웃은 여전히 사용자를 자리 비움으로 표시하거나 로그아웃시킬 수 있습니다. 이 옵션은 macOS에도 사용자가 활성 상태임을 알리며, 이러한 시스템은 이를 실제로 감지합니다. 몇 초 동안 유휴 상태였을 때만 개입하므로, Mac을 사용하거나 게임하는 동안에는 포인터를 절대 건드리지 않습니다. 기본적으로 꺼져 있으며, 일부 관리되는 Mac은 시뮬레이션된 활동을 표시하므로 먼저 정책을 확인하십시오.',
    "Also tells macOS you're active, so you aren't marked away.": 'macOS에도 활성 상태임을 알려, 자리 비움으로 표시되지 않도록 합니다.',
    'While a session runs, the menu shows these as one-click “Stop in” buttons. Clicking one converts the running session to end that much later, so the Mac goes back to sleeping on its own without you remembering to switch it off. It continues the session rather than restarting it, and clicking another button simply replaces the countdown. Up to four, and the list stays sorted.': '세션이 실행되는 동안 메뉴는 이를 원클릭 “중지 예약” 버튼으로 표시합니다. 하나를 클릭하면 실행 중인 세션이 그만큼 나중에 끝나도록 바뀌므로, 직접 꺼야 한다는 것을 기억하지 않아도 Mac이 스스로 다시 잠들 수 있습니다. 세션을 다시 시작하는 대신 이어서 진행하며, 다른 버튼을 클릭하면 카운트다운만 교체됩니다. 최대 4개이며 목록은 정렬된 상태로 유지됩니다.',
    'One-click “Stop in” buttons shown in the menu while a session runs.': '세션이 실행되는 동안 메뉴에 표시되는 원클릭 “중지 예약” 버튼입니다.',
    'A safety net for a session you forget about. If the charge falls this low, Keepresso pauses the session and lets the Mac sleep, even mid-session, and tells you why in a notification. The menu-bar cup shows the pause as a last sip of low-power yellow. Plugging in resumes it on its own. This is the same slider as the one in the menu, so the two always agree.': '잊고 지나칠 수 있는 세션을 위한 안전장치입니다. 충전량이 이 수준까지 떨어지면 Keepresso는 세션 도중이라도 세션을 일시 정지하고 Mac이 잠들게 하며, 알림으로 그 이유를 알려줍니다. 메뉴 막대의 컵은 이 일시 정지를 저전력을 나타내는 노란색의 마지막 한 모금으로 표시합니다. 전원에 연결하면 저절로 다시 시작됩니다. 이는 메뉴에 있는 것과 동일한 슬라이더이므로 둘은 항상 일치합니다.',
    'Lets the Mac sleep once charge drops below this level.': '충전량이 이 수준 아래로 떨어지면 Mac이 잠들게 합니다.',
    "Writes everything you've configured (settings, trigger rules, and presets) to a JSON file, to keep as a backup or to carry to another Mac. The file is version-stamped and checked on import, so a file from a newer Keepresso is refused rather than half-read. Importing replaces your current configuration and ends any running session.": '구성한 모든 항목(설정, 트리거 규칙, 프리셋)을 JSON 파일로 기록하여 백업으로 보관하거나 다른 Mac으로 옮길 수 있습니다. 이 파일에는 버전 표시가 있으며 가져올 때 확인되므로, 더 새로운 Keepresso에서 만든 파일은 일부만 읽히는 대신 거부됩니다. 가져오면 현재 구성이 대체되고 실행 중인 세션이 종료됩니다.',
    'Save your settings, triggers, and presets to a JSON file.': '설정, 트리거, 프리셋을 JSON 파일에 저장합니다.',
    "Normally a MacBook sleeps the moment you shut the lid unless a display is attached. This keeps it running with the lid shut and nothing plugged in, on power or battery. The screen itself still turns off when the lid closes (unless an external display is attached), so it isn't lighting up uselessly inside the closed lid. It works by flipping a system setting (pmset disablesleep), so it stays in effect until you turn it off: closed and on battery, the Mac can still drain over time, so don't leave it on in a bag. “Only while brewing” ties it to the session instead, on when a keep-awake session starts, off when it ends or Keepresso quits (even after a crash). Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password, once per app run for “Only while brewing”.": '일반적으로 MacBook은 디스플레이가 연결되어 있지 않으면 덮개를 닫는 순간 잠듭니다. 이 기능은 덮개를 닫고 아무것도 연결하지 않은 상태에서도 전원이든 배터리든 계속 실행되도록 유지합니다. 덮개를 닫으면 디스플레이 자체는 여전히 꺼지므로(외부 디스플레이가 연결된 경우 제외) 닫힌 덮개 안에서 쓸데없이 켜져 있지 않습니다. 시스템 설정(pmset disablesleep)을 전환하는 방식으로 작동하므로, 끌 때까지 계속 적용됩니다. 덮개를 닫고 배터리를 사용 중이면 시간이 지나면서 여전히 배터리가 소모될 수 있으니 가방 안에서는 켜 두지 마십시오. “실행 중일 때만”은 대신 이를 세션에 연결하여, 깨어 있게 유지 세션이 시작될 때 켜지고 세션이 끝나거나 (충돌 후에도) Keepresso가 종료될 때 꺼집니다. 둘 다 관리자 권한이 필요합니다. 관리자 도우미가 설치되어 있으면 조용히 처리되고(이 탭 상단 참조), 그렇지 않으면 macOS가 암호를 요청하며, “실행 중일 때만”의 경우 앱 실행당 한 번입니다.',
    'Keeps running with the lid shut and no external display.': '덮개를 닫고 외부 디스플레이가 없어도 계속 실행됩니다.',
    "A trigger is a condition Keepresso watches, checked once a second. With triggers on, they take over: Keepresso starts brewing the moment your conditions are met and stops when they aren't, so you never leave the Mac awake by accident. The manual switch in the menu steps aside while they're active. “Pause Triggers” in the menu bar stops them temporarily without touching your rules.": '트리거는 Keepresso가 감시하는 조건으로, 1초에 한 번씩 확인됩니다. 트리거를 켜면 트리거가 제어권을 가져갑니다. 조건이 충족되는 순간 Keepresso가 작동을 시작하고 조건이 더 이상 충족되지 않으면 중지되므로, 실수로 Mac을 켜진 상태로 방치하는 일이 없습니다. 메뉴의 수동 스위치는 트리거가 활성 상태인 동안 물러납니다. 메뉴 막대의 “트리거 일시 정지”를 사용하면 규칙을 건드리지 않고 일시적으로 트리거를 중지할 수 있습니다.',
    'The listed conditions control the session instead of the manual switch.': '나열된 조건이 수동 스위치 대신 세션을 제어합니다.',
    'A preset is a named bundle of trigger rules you apply in one click. The built-ins cover common setups (AI Agent, Meetings, Cloud Gaming, Remote Control, and more), and applying one replaces your current rules. Save your own rules under a name to reuse them or move between setups. Renaming a built-in makes it yours, and Keepresso stops updating it. “Restore default presets” brings back any built-in you removed.': '프리셋은 한 번의 클릭으로 적용할 수 있도록 이름이 지정된 트리거 규칙 묶음입니다. 기본 제공 프리셋은 일반적인 구성(AI 에이전트, 회의, 클라우드 게임, 원격 제어 등)을 다루며, 하나를 적용하면 현재 규칙이 대체됩니다. 자신만의 규칙을 이름을 붙여 저장하면 재사용하거나 구성 간에 전환할 수 있습니다. 기본 제공 프리셋의 이름을 바꾸면 사용자 소유가 되며, Keepresso는 더 이상 이를 업데이트하지 않습니다. “기본 프리셋 복원”을 사용하면 제거한 기본 제공 프리셋을 되돌릴 수 있습니다.',
    '“any” keeps the Mac awake while at least one condition holds, so the rules pile up: add three and any of them is enough. “all” needs every one true at once, which narrows things down (on AC power and an external display connected means only while docked). Conditions are checked once a second, and Keepresso stops brewing as soon as they stop being met.': '“임의”는 조건이 하나 이상 성립하는 동안 Mac을 깨어 있는 상태로 유지하므로 규칙이 쌓입니다. 세 개를 추가하면 그중 하나만 성립해도 충분합니다. “전체”는 모든 조건이 동시에 성립해야 하므로 범위가 좁아집니다(전원 연결 시이면서 외부 디스플레이가 연결됨은 도킹된 동안에만을 의미합니다). 조건은 1초에 한 번씩 확인되며, 조건이 더 이상 충족되지 않으면 Keepresso는 즉시 작동을 멈춥니다.',
    "Conditions Keepresso reads straight from the hardware, with no permission needed: whether you're on AC power, on battery, or charging, and whether an external display is connected. Good for a Mac that should only stay awake while it's docked or plugged in, especially combined with “all” to mean exactly that.": 'Keepresso가 권한 없이 하드웨어에서 직접 읽는 조건입니다. 전원 연결 시인지, 배터리 사용 시인지, 충전 중인지, 그리고 외부 디스플레이가 연결되어 있는지 여부입니다. 도킹되어 있거나 전원에 연결되어 있을 때만 깨어 있어야 하는 Mac에 적합하며, 특히 “전체”와 결합하면 정확히 그런 의미가 됩니다.',
    'Conditions about what the Mac is connected to or busy with: a chosen Wi-Fi network, a VPN, a Bluetooth device such as headphones or a controller, a mounted volume, or sustained network throughput for a large download, upload, or sync. Reading Wi-Fi names needs Location permission and Bluetooth needs its own, both requested from this menu; the rest ask for nothing.': 'Mac이 무엇에 연결되어 있거나 무엇으로 바쁜지에 관한 조건입니다. 선택한 Wi-Fi 네트워크, VPN, 헤드폰이나 컨트롤러 같은 Bluetooth 기기, 마운트된 볼륨, 또는 대용량 다운로드, 업로드, 동기화로 인한 지속적인 네트워크 처리량입니다. Wi-Fi 이름을 읽으려면 위치 권한이 필요하고 Bluetooth는 자체 권한이 필요하며, 둘 다 이 메뉴에서 요청됩니다. 나머지는 아무런 권한도 요청하지 않습니다.',
    "Conditions about what you're actually doing: an app running or frontmost, the camera or microphone in use, audio playing, a game in front, an AI agent working, a process by name, a download finishing in a folder you watch, CPU load above a threshold, a time window, or a calendar event in progress. The camera and microphone conditions read only the device's in-use signal (the green dot), never the stream, so neither asks for permission.": '사용자가 실제로 무엇을 하고 있는지에 관한 조건입니다. 앱이 실행 중이거나 맨 앞에 있음, 카메라나 마이크 사용 중, 오디오 재생 중, 게임이 맨 앞에 있음, AI 에이전트가 작업 중, 이름으로 지정한 프로세스, 감시 중인 폴더에서 다운로드 완료, 임계값을 초과한 CPU 부하, 특정 시간대, 또는 진행 중인 캘린더 이벤트입니다. 카메라와 마이크 조건은 기기의 사용 중 신호(녹색 점)만 읽을 뿐 스트림은 절대 읽지 않으므로 둘 다 권한을 요청하지 않습니다.',
    "A nudge while a session is running, so a Mac left awake doesn't stay awake all night unnoticed. Left off, a one-time reminder tells you once, after the session has run this long. “Repeat” tells you again at every interval until you stop the session. This never stops anything itself, it only reminds you, and the sound is optional. If you'd rather the session end on its own, use a timed session or a quick-stop button instead.": '세션이 실행되는 동안 알려 주는 기능으로, 깨어 있는 상태로 방치된 Mac이 밤새 알아채지 못한 채 계속 깨어 있지 않도록 합니다. 꺼져 있으면 세션이 이만큼 실행된 후 일회성 알림이 한 번만 알려 줍니다. “반복”을 켜면 세션을 중지할 때까지 매 간격마다 다시 알려 줍니다. 이 기능은 그 자체로 아무것도 중지하지 않고 단지 알려 줄 뿐이며, 소리는 선택 사항입니다. 세션이 스스로 끝나기를 원한다면 대신 시간 지정 세션이나 빠른 중지 버튼을 사용하십시오.',
    "These cover the times a session ends without you: a timer expiring, trigger conditions dropping, or a low-battery pause. Stopping it yourself stays silent, since you already know. The warning is a heads-up a few minutes before a timed session runs out, so you can extend it before the Mac drops off. The action runs when the session ends: sleep the display or start the screen saver, handy for a Mac you walk away from. It's off by default so a timed session never surprises you.": '이는 세션이 사용자 모르게 끝나는 경우를 다룹니다. 타이머 만료, 트리거 조건 해제, 또는 배터리 부족 일시 정지입니다. 직접 중지하면 이미 알고 있으므로 알림이 표시되지 않습니다. 경고는 시간 지정 세션이 끝나기 몇 분 전에 미리 알려 주는 것으로, Mac이 꺼지기 전에 세션을 연장할 수 있게 해 줍니다. 이 작업은 세션이 끝날 때 실행됩니다. 디스플레이 잠자기 또는 화면 보호기 시작으로, 자리를 비우는 Mac에 유용합니다. 시간 지정 세션이 예상치 못하게 동작하지 않도록 기본적으로 꺼져 있습니다.',
    'Fires when a session ends on its own, not when you stop it yourself.': '세션이 스스로 끝날 때 실행되며, 직접 중지할 때는 실행되지 않습니다.',
    'A Mac with no monitor attached falls back to a fuzzy 1920 × 1080, which is what makes Screen Sharing and VNC look soft. This creates a higher-resolution HiDPI display in software, so the remote picture is crisp without plugging anything in. It uses a private macOS API, so treat it as experimental and expect it may break on a macOS update. A hardware HDMI or DisplayPort dummy plug does the same job with no software at all.': '모니터가 연결되어 있지 않은 Mac은 흐릿한 1920 × 1080 해상도로 대체되며, 이 때문에 화면 공유와 VNC가 흐리게 보입니다. 이 기능은 소프트웨어로 더 높은 해상도의 HiDPI 디스플레이를 만들어, 아무것도 연결하지 않아도 원격 화면이 선명해지도록 합니다. macOS 비공개 API를 사용하므로 실험적 기능으로 간주하고 macOS 업데이트 시 작동하지 않을 수 있음을 감안하십시오. 하드웨어 HDMI 또는 DisplayPort 더미 플러그는 소프트웨어 없이도 동일한 효과를 냅니다.',
    'For a Mac with no monitor: a sharper picture over Screen Sharing and VNC.': '모니터가 없는 Mac용: 화면 공유와 VNC에서 더 선명한 화면을 제공합니다.',
    "Many external drives and NAS volumes park or disconnect after a few minutes idle, and the next thing that touches them stalls while they spin back up. Keepresso rewrites a tiny hidden marker file in the folder you choose, just enough activity to keep the volume awake. Pick an interval shorter than the drive's own idle timeout. This runs whenever Keepresso is running, with or without a keep-awake session, so a drive stays ready even when the Mac is free to sleep.": '많은 외장 드라이브와 NAS 볼륨은 몇 분간 유휴 상태가 지나면 정지하거나 연결이 끊기며, 그다음에 접근하는 작업은 다시 회전을 시작할 때까지 멈춰 있게 됩니다. Keepresso는 사용자가 선택한 폴더에 있는 작은 숨김 표시 파일을 다시 기록하여, 볼륨을 깨어 있게 유지할 만큼의 활동만 만들어 냅니다. 드라이브 자체의 유휴 시간 제한보다 짧은 간격을 선택하십시오. 이 작업은 깨어 있게 유지 세션 유무와 관계없이 Keepresso가 실행되는 동안 항상 실행되므로, Mac이 자유롭게 잠들 수 있는 상태에서도 드라이브는 계속 준비된 상태를 유지합니다.',
    'Stops an external drive or NAS from spinning down.': '외장 드라이브나 NAS가 회전을 멈추지 않도록 합니다.',
    '3 minutes': '3분',
}


# --- Agent hooks (Claude Code connection) ---
APP.update({
    "Claude Code connected: sessions report working and waiting exactly.": "Claude Code 연결됨: 세션이 작업과 대기를 정확하게 보고합니다.",
    "Connect Claude Code for exact session tracking (adds hooks to its settings).": "정확한 세션 추적을 위해 Claude Code를 연결하세요(설정에 후크를 추가합니다).",
    "Connect Claude Code": "Claude Code 연결",
    "Claude Code's settings file couldn't be read, so it was left untouched.": "Claude Code 설정 파일을 읽을 수 없어 그대로 두었습니다.",
    "Couldn't update Claude Code's settings file.": "Claude Code 설정 파일을 업데이트할 수 없습니다.",
})
