# -*- coding: utf-8 -*-
# Korean overlay for catalog_core.py: English source -> Korean.
CORE = {
    "On AC power": "전원 연결 시",
    "On battery": "배터리 사용 시",
    "Charging": "충전 중",
    "External display connected": "외부 디스플레이 연결됨",
    "is running": "실행 중",
    "is frontmost": "맨 앞에 있음",
    "Audio playing": "오디오 재생 중",
    "VPN connected": "VPN 연결됨",
    "Calendar event in progress": "캘린더 이벤트 진행 중",
    "Playing a game": "게임 플레이 중",
    "Camera in use": "카메라 사용 중",
    "Microphone in use": "마이크 사용 중",
    "On Wi-Fi “%@”": "Wi-Fi “%@”에 연결됨",
    "Process “%@” running": "프로세스 “%@” 실행 중",
    "Volume “%@” mounted": "볼륨 “%@” 마운트됨",
    "Bluetooth “%@” connected": "Bluetooth “%@” 연결됨",
    "Downloading in “%@”": "“%@”에서 다운로드 중",
    "CPU above %d%%": "CPU %d%% 초과",
    "Network above %@": "네트워크 %@ 초과",
    "App %@": "앱 %@",
    "Every day": "매일",
    "Weekdays": "평일",
    "Weekends": "주말",
    "Do nothing": "아무 작업 안 함",
    "Sleep the display": "디스플레이 잠자기",
    "Start the screen saver": "화면 보호기 시작",
    "AI Agent": "AI 에이전트",
    "On AC Power": "전원 연결",
    "External Display Connected": "외부 디스플레이 연결됨",
    "Remote Session (SSH)": "원격 세션 (SSH)",
    "Backup Running": "백업 실행 중",
    "Media Render": "미디어 렌더링",
    "Meetings": "회의",
    "Cloud Gaming": "클라우드 게임",
    "Remote Control": "원격 제어",
    "Remote Login (SSH)": "원격 로그인 (SSH)",
    "Remote Login is on, so you can reach this Mac over SSH.": "원격 로그인이 켜져 있어 SSH로 이 Mac에 접속할 수 있습니다.",
    "Remote Login is off. You might want to enable it for SSH access to a headless Mac.": "원격 로그인이 꺼져 있습니다. 헤드리스 Mac에 SSH로 접속하려면 켜는 것이 좋습니다.",
    "Couldn't confirm Remote Login. If you want SSH access, enable it in System Settings.": "원격 로그인을 확인할 수 없습니다. SSH 접근을 원하면 시스템 설정에서 켜십시오.",
    "Screen Sharing": "화면 공유",
    "Screen Sharing is on, so you can connect with the Screen Sharing app or VNC.": "화면 공유가 켜져 있어 화면 공유 앱이나 VNC로 연결할 수 있습니다.",
    "Screen Sharing is off. You might want to enable it to view a headless Mac's screen.": "화면 공유가 꺼져 있습니다. 헤드리스 Mac의 화면을 보려면 켜는 것이 좋습니다.",
    "Couldn't confirm Screen Sharing. If you want remote viewing, enable it in System Settings.": "화면 공유를 확인할 수 없습니다. 원격 보기를 원하면 시스템 설정에서 켜십시오.",
    "Enable it in System Settings ▸ General ▸ Sharing.": "시스템 설정 ▸ 일반 ▸ 공유에서 켜십시오.",
    "Run AI agents on this Mac with MyAgens": "MyAgens로 이 Mac에서 AI 에이전트를 실행하세요",
    "MyAgens lets AI agents operate your Mac and help with your work, which is handy on an always-on machine you mostly reach remotely.": "MyAgens를 사용하면 AI 에이전트가 Mac을 조작하고 작업을 도울 수 있어, 주로 원격으로 접속하는 상시 가동 기기에서 유용합니다.",
    "Learn more about MyAgens:": "MyAgens에 대해 더 알아보기:",
    "GitHub": "GitHub",
    "Read more": "자세히 보기",
    "Wake for network access": "네트워크 접근 시 깨우기",
    "The Mac wakes when accessed over the network.": "네트워크를 통해 접근하면 Mac이 깨어납니다.",
    "The Mac won't wake for network access, so remote logins may fail.": "Mac이 네트워크 접근 시 깨어나지 않아 원격 로그인이 실패할 수 있습니다.",
    "Couldn't read the power settings.": "전원 설정을 읽을 수 없습니다.",
    "Enable “Wake for network access”.": "“네트워크 접근 시 깨우기”를 켜십시오.",
    "Restart after power failure": "정전 후 재시동",
    "The Mac restarts automatically after a power failure.": "정전 후 Mac이 자동으로 재시동됩니다.",
    "The Mac stays off after a power cut, so it won't come back headless.": "정전 후 Mac이 꺼진 상태로 유지되어 헤드리스 상태에서는 스스로 복귀하지 않습니다.",
    "Enable automatic restart after a power failure.": "정전 후 자동 재시동을 켜십시오.",
    "System sleep disabled": "시스템 잠자기 비활성화됨",
    "Idle system sleep is disabled, so the Mac stays reachable.": "유휴 시스템 잠자기가 비활성화되어 Mac에 계속 접근할 수 있습니다.",
    "The Mac sleeps when idle; Keepresso prevents this while a session runs, but a global setting is safer headless.": "Mac은 유휴 상태에서 잠듭니다. Keepresso가 세션 중에는 이를 방지하지만, 헤드리스 환경에서는 전역 설정이 더 안전합니다.",
    "Disable idle system sleep.": "유휴 시스템 잠자기를 비활성화하십시오.",
    "FileVault disabled": "FileVault 비활성화됨",
    "FileVault is off, so the Mac can reboot unattended to the login window.": "FileVault가 꺼져 있어 Mac이 무인으로 로그인 창까지 재시동할 수 있습니다.",
    "FileVault is on, so a reboot blocks at the disk-unlock screen until someone types the password, defeating headless restart.": "FileVault가 켜져 있어 재시동 시 누군가 암호를 입력할 때까지 디스크 잠금 해제 화면에서 멈추므로 헤드리스 재시동이 불가능해집니다.",
    "Couldn't determine the FileVault status.": "FileVault 상태를 확인할 수 없습니다.",
    "For an unattended Mac, consider turning FileVault off (weigh the security trade-off).": "무인 Mac의 경우 FileVault를 끄는 것을 고려하십시오(보안상의 절충을 감안하십시오).",
    "Automatic login": "자동 로그인",
    "Automatic login is on (%@), so the Mac reaches the desktop after a reboot without a keyboard.": "자동 로그인이 켜져 있어(%@) 재시동 후 키보드 없이도 Mac이 데스크탑까지 도달합니다.",
    "Automatic login is off. After a reboot the Mac waits at the login window for a password.": "자동 로그인이 꺼져 있습니다. 재시동 후 Mac은 로그인 창에서 암호를 기다립니다.",
    "Turn on automatic login for this account.": "이 계정에 대해 자동 로그인을 켜십시오.",
    "Keepresso stopped": "Keepresso가 중지됨",
    "Your keep-awake session has ended.": "깨어 있게 유지 세션이 종료되었습니다.",
    "Paused on low battery": "배터리 부족으로 일시 정지됨",
    "Battery is at %d%%. Keepresso is letting the Mac sleep until you plug in to charge.": "배터리가 %d%%입니다. 충전기를 연결할 때까지 Keepresso가 Mac을 잠들도록 둡니다.",
    "Keepresso is still brewing": "Keepresso가 아직 실행 중입니다",
    "Your Mac is still awake. It's been %@.": "Mac이 아직 깨어 있습니다. %@ 경과했습니다.",
    "Your Mac has been kept awake for %@.": "Mac이 %@ 동안 깨어 있게 유지되었습니다.",
    "Started manually": "수동으로 시작됨",
    "Restarted manually": "수동으로 다시 시작됨",
    "Started by a command": "명령으로 시작됨",
    "Restarted by a command": "명령으로 다시 시작됨",
    "Timed session ended": "시간 제한 세션 종료됨",
    "Paused, battery below %d%%": "일시 정지됨, 배터리 %d%% 미만",
    "Not started, battery below %d%%": "시작되지 않음, 배터리 %d%% 미만",
    "Stopped manually": "수동으로 중지됨",
    "Stopped by a command": "명령으로 중지됨",
    "Trigger conditions met": "트리거 조건 충족됨",
    "Trigger conditions ended": "트리거 조건 종료됨",
    "Triggers: %@": "트리거: %@",
    "%@ (+%ds)": "%@ (+%d초)",
    "Couldn't create the watchdog flag file.": "워치독 플래그 파일을 생성할 수 없습니다.",
    "Couldn't run the watchdog command.": "워치독 명령을 실행할 수 없습니다.",
    "The watchdog couldn't be started.": "워치독을 시작할 수 없습니다.",
    "Couldn't create the sleep watchdog flag file.": "잠자기 워치독 플래그 파일을 생성할 수 없습니다.",
    "Couldn't run the sleep watchdog command.": "잠자기 워치독 명령을 실행할 수 없습니다.",
    "The sleep watchdog couldn't be started.": "잠자기 워치독을 시작할 수 없습니다.",
    "Couldn't run the sleep setting command.": "잠자기 설정 명령을 실행할 수 없습니다.",
    "The sleep setting couldn't be changed.": "잠자기 설정을 변경할 수 없습니다.",
    "The Keepresso helper isn't responding.": "Keepresso 도우미가 응답하지 않습니다.",
    "The Keepresso helper couldn't change the setting.": "Keepresso 도우미가 설정을 변경할 수 없습니다.",
    "Virtual displays aren't available on this macOS version.": "이 macOS 버전에서는 가상 디스플레이를 사용할 수 없습니다.",
    "Couldn't create the virtual display.": "가상 디스플레이를 생성할 수 없습니다.",
    "Preventing system sleep": "시스템 잠자기 방지 중",
    "Preventing display sleep": "디스플레이 잠자기 방지 중",
    "Keeping disks awake": "디스크를 깨어 있게 유지 중",
    "Declaring the user active": "사용자를 활성으로 선언 중",
    "Holding off idle sleep for a background task": "백그라운드 작업을 위해 유휴 잠자기 지연 중",
    "Not enough replies to measure.": "측정하기에 응답이 충분하지 않습니다.",
    "Baseline %d ms": "기준선 %d ms",
    "%d spike up to %d ms": "%d회 스파이크, 최대 %d ms",
    "%d spikes up to %d ms": "%d회 스파이크, 최대 %d ms",
    "max %d ms": "최대 %d ms",
    "%d lost": "%d개 손실",
    "Wired network": "유선 네트워크",
    "Couldn't read the network interfaces.": "네트워크 인터페이스를 읽을 수 없습니다.",
    "Ethernet is connected (%@). A wired link sidesteps Wi-Fi jitter entirely, the most reliable fix.": "Ethernet이 연결되어 있습니다 (%@). 유선 연결은 Wi-Fi 지터를 완전히 우회하는 가장 신뢰할 수 있는 해결책입니다.",
    "An Ethernet adapter is available but no cable is connected.": "Ethernet 어댑터를 사용할 수 있지만 케이블이 연결되어 있지 않습니다.",
    "For gaming or streaming, a wired connection beats any Wi-Fi tuning.": "게임이나 스트리밍에는 유선 연결이 어떤 Wi-Fi 조정보다 낫습니다.",
    "No wired network adapter found.": "유선 네트워크 어댑터를 찾을 수 없습니다.",
    "A USB-C or Thunderbolt Ethernet adapter sidesteps Wi-Fi jitter entirely.": "USB-C 또는 Thunderbolt Ethernet 어댑터는 Wi-Fi 지터를 완전히 우회합니다.",
    "Wi-Fi channel": "Wi-Fi 채널",
    "Not connected to Wi-Fi, or its details are unreadable.": "Wi-Fi에 연결되어 있지 않거나 세부 정보를 읽을 수 없습니다.",
    "If you game or stream over Wi-Fi, re-check while connected.": "Wi-Fi로 게임하거나 스트리밍한다면 연결된 상태에서 다시 확인하십시오.",
    "channel %d at %d MHz": "%d 채널, %d MHz",
    "channel %d": "%d 채널",
    "On 2.4 GHz (%@), the slowest band, where every AWDL hop costs the most.": "가장 느린 대역인 2.4 GHz(%@)에서는 모든 AWDL 홉의 대가가 가장 큽니다.",
    "Prefer a 5 GHz network on %@ at 80 MHz. If 2.4 GHz is unavoidable, set the router to channel 6, AWDL's 2.4 GHz social channel.": "%@의 80 MHz 5 GHz 네트워크를 선택하십시오. 2.4 GHz를 피할 수 없다면 라우터를 AWDL의 2.4 GHz 소셜 채널인 6 채널로 설정하십시오.",
    "On 6 GHz (%@). AWDL's social channels live on 2.4 and 5 GHz, so there's nothing to align here. If stutter persists, a 5 GHz network on %@ keeps AWDL's hops on-channel.": "6 GHz(%@)에서. AWDL의 소셜 채널은 2.4 및 5 GHz에 있으므로 여기서는 맞출 것이 없습니다. 끊김이 계속되면 %@의 5 GHz 네트워크가 AWDL의 홉을 채널에 유지합니다.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel.": "%@에서 AWDL의 5 GHz 소셜 채널과 맞아 홉이 채널에 유지됩니다.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel. Raising the router to 80 MHz width completes the alignment.": "%@에서 AWDL의 5 GHz 소셜 채널과 맞아 홉이 채널에 유지됩니다. 라우터를 80 MHz 폭으로 높이면 정렬이 완성됩니다.",
    "On 5 GHz %@. AWDL's off-channel hops leave this channel roughly every second.": "5 GHz %@에서. AWDL의 채널 밖 홉이 약 1초마다 이 채널을 벗어납니다.",
    "Set the router to %@ at 80 MHz so AWDL's hops stay on-channel.": "AWDL의 홉이 채널에 유지되도록 라우터를 %@의 80 MHz로 설정하십시오.",
    "channel 44 (the EU social channel) or 149 (the US and Canada social channel), whichever your region allows": "지역에서 허용하는 것에 따라 44 채널(EU 소셜 채널) 또는 149 채널(미국 및 캐나다 소셜 채널)",
    "channel 44, AWDL's 5 GHz social channel in the EU": "EU에서 AWDL의 5 GHz 소셜 채널인 44 채널",
    "channel 149, AWDL's 5 GHz social channel where UNII-3 is allowed (the US, Canada, and most of the world)": "UNII-3가 허용되는 지역(미국, 캐나다 및 세계 대부분)에서 AWDL의 5 GHz 소셜 채널인 149 채널",
    "Bluetooth during play": "플레이 중 Bluetooth",
    "Bluetooth is on. It shares the radio chip with Wi-Fi, so heavy Bluetooth traffic (audio, controllers) can add its own blips.": "Bluetooth가 켜져 있습니다. Wi-Fi와 무선 칩을 공유하므로 무거운 Bluetooth 트래픽(오디오, 컨트롤러)이 자체적인 순간 끊김을 더할 수 있습니다.",
    "Nothing to fix: just a variable to know about if stutter persists on a clean channel.": "고칠 것은 없습니다. 깨끗한 채널에서도 끊김이 계속될 경우 알아 둘 변수일 뿐입니다.",
    "Bluetooth is off, so it isn't competing with Wi-Fi for the radio.": "Bluetooth가 꺼져 있어 무선을 두고 Wi-Fi와 경쟁하지 않습니다.",
    "Couldn't read the Bluetooth radio state.": "Bluetooth 무선 상태를 읽을 수 없습니다.",
    "Game Mode": "게임 모드",
    "macOS turns on Game Mode by itself when a game runs full screen: the game gets CPU and GPU priority, and Bluetooth controllers and audio get faster sampling. If the game-controller icon doesn't appear in the menu bar while playing, put the game into full screen.": "게임이 전체 화면으로 실행되면 macOS가 스스로 게임 모드를 켭니다. 게임이 CPU와 GPU 우선순위를 얻고, Bluetooth 컨트롤러와 오디오가 더 빠른 샘플링을 받습니다. 플레이 중 메뉴 막대에 게임 컨트롤러 아이콘이 나타나지 않으면 게임을 전체 화면으로 전환하십시오.",
    "How Game Mode works:": "게임 모드 작동 방식:",
    "Learn more": "더 알아보기",
    "Cloud gaming in the browser": "브라우저에서의 클라우드 게임",
    "Xbox Cloud Gaming and the web versions of GeForce NOW run in a browser tab, so there's no app for the gaming condition to spot. The “Audio playing” condition covers them: game sound keeps the session brewing.": "Xbox Cloud Gaming과 GeForce NOW의 웹 버전은 브라우저 탭에서 실행되므로 게임 조건이 감지할 앱이 없습니다. “오디오 재생 중” 조건이 이를 대신합니다. 게임 소리가 세션을 계속 실행되게 유지합니다.",
    "Add it under Preferences ▸ Triggers ▸ Add ▸ Apps & Activity ▸ Media.": "환경설정 ▸ 트리거 ▸ 추가 ▸ 앱 및 활동 ▸ 미디어에서 추가하십시오.",
    "Location Services and Wi-Fi scans": "위치 서비스와 Wi-Fi 스캔",
    "Location Services triggers independent Wi-Fi scans, another source of occasional blips. Keepresso itself uses Location to read Wi-Fi network names for triggers, so weigh that before turning anything off.": "위치 서비스는 독립적인 Wi-Fi 스캔을 유발하는데, 이는 간헐적 순간 끊김의 또 다른 원인입니다. Keepresso 자체도 트리거를 위해 Wi-Fi 네트워크 이름을 읽는 데 위치를 사용하므로, 무언가를 끄기 전에 이를 감안하십시오.",
    "Review which apps use Location:": "위치를 사용하는 앱 검토:",
    "Why streams stutter once a second": "스트림이 1초에 한 번씩 끊기는 이유",
    "The Wi-Fi radio hops off-channel for AWDL (AirDrop, Handoff, Sidecar, Continuity) roughly every second, which shows up as 50-100 ms ping spikes. The jitter test reproduces the diagnosis; the AWDL watchdog is the session-scoped fix.": "Wi-Fi 무선은 약 1초마다 AWDL(AirDrop, Handoff, Sidecar, 연속성)을 위해 채널 밖으로 홉하며, 이는 50-100 ms의 ping 스파이크로 나타납니다. 지터 테스트로 진단을 재현하고, AWDL 워치독이 세션 범위의 해결책입니다.",
    "The full story:": "전체 이야기:",
}

# Korean overlay for catalog_widget.py: English source -> Korean.
WIDGET = {
    "Keep Awake": "깨어 있게 유지",
    "See and control whether Keepresso is keeping the Mac awake.": "Keepresso가 Mac을 깨어 있게 유지하고 있는지 확인하고 제어합니다.",
    "Start or stop keeping the Mac awake.": "Mac을 깨어 있게 유지하기를 시작하거나 중지합니다.",
    "Keepresso": "Keepresso",
    "Brewing": "실행 중",
    "Off": "꺼짐",
    "Keeping the Mac awake": "Mac을 깨어 있게 유지 중",
    "The Mac can sleep": "Mac이 잠들 수 있음",
    "Stop": "중지",
    "Start": "시작",
    "Resume Triggers": "트리거 재개",
    "Pause Triggers": "트리거 일시 정지",
}
