# -*- coding: utf-8 -*-
# Polish overlay for catalog_app.py: English source -> Polish.
APP = {
    'Add': 'Dodaj',
    'Add:': 'Dodaj:',
    'Clear': 'Wyczyść',
    'Close': 'Zamknij',
    'Done': 'Gotowe',
    'Save': 'Zapisz',
    'Enable': 'Włącz',
    'Enabled': 'Włączone',
    'Installed': 'Zainstalowano',
    'Remove': 'Usuń',
    'Remove condition': 'Usuń warunek',
    'Resume': 'Wznów',
    'Later': 'Później',
    'Learn more': 'Dowiedz się więcej',
    'Re-check': 'Sprawdź ponownie',
    'Run Test': 'Uruchom test',
    'Match': 'Dopasowanie',
    'Threshold': 'Próg',
    'Battery threshold': 'Próg baterii',
    'Presence': 'Obecność',
    'Menu bar': 'Pasek menu',
    'Battery': 'Bateria',
    'Welcome': 'Powitanie',
    "Keeps the Mac running with the lid shut and no external display. This flips a system setting that needs administrator rights: silent with the administrator helper installed (Preferences ▸ General), otherwise macOS asks for your password.": "Utrzymuje działanie Maca przy zamkniętej pokrywie i bez zewnętrznego wyświetlacza. Zmienia to ustawienie systemowe wymagające uprawnień administratora: bezgłośnie z zainstalowanym pomocnikiem administratora (Ustawienia ▸ Ogólne), w przeciwnym razie macOS poprosi o hasło.",
    "Turns closed-display mode on when a keep-awake session starts and off when it ends or Keepresso quits.": "Włącza tryb zamkniętej pokrywy, gdy rozpoczyna się sesja czuwania, i wyłącza go, gdy się kończy lub Keepresso zostaje zamknięte.",
    'Grace period': 'Okres karencji',
    'Section': 'Sekcja',
    'Schedule': 'Harmonogram',
    'Set Duration': 'Ustaw czas trwania',
    'For': 'Przez',
    'From': 'Od',
    'To': 'Do',
    'Until': 'Do',
    'When': 'Kiedy',
    'Below': 'Poniżej',
    'Power': 'Zasilanie',
    'Display': 'Wyświetlacz',
    'Network': 'Sieć',
    'Media': 'Multimedia',
    'Backup': 'Kopia zapasowa',
    'Folder': 'Folder',
    'Downloads': 'Pobrane',
    'Touch': 'Odśwież',
    'Resolution': 'Rozdzielczość',
    'Startup': 'Uruchamianie',
    'Gaming': 'Gry',
    'None': 'Brak',
    'any': 'dowolny',
    'all': 'wszystkie',
    'of these are true:': 'z poniższych jest spełnionych:',
    '1 minute': '1 minuta',
    '2 minutes': '2 minuty',
    '5 minutes': '5 minut',
    '10 seconds': '10 sekund',
    '30 seconds': '30 sekund',
    '15 minutes': '15 minut',
    '30 minutes': '30 minut',
    '1 hour': '1 godzina',
    '2 hours': '2 godziny',
    '4 hours': '4 godziny',
    '8 hours': '8 godzin',
    'No grace': 'Bez karencji',
    'Every 1 minute': 'Co minutę',
    'Every 5 minutes': 'Co 5 minut',
    'Every 10 minutes': 'Co 10 minut',
    'Every 30 minutes': 'Co 30 minut',
    'Every': 'Co',
    'After': 'Po',
    'Keepresso': 'Keepresso',
    'About Keepresso': 'O Keepresso',
    'Welcome to Keepresso': 'Witamy w Keepresso',
    'Keepresso Setup': 'Konfiguracja Keepresso',
    'Keepresso Helper': 'Pomocnik Keepresso',
    'Preferences': 'Ustawienia',
    'Preferences…': 'Ustawienia…',
    'A menu-bar app that keeps your Mac awake on your terms.': 'Aplikacja paska menu, która zgodnie z twoimi zasadami nie pozwala Makowi zasnąć.',
    'AWDL watchdog': 'Strażnik AWDL',
    'Activate by triggers': 'Aktywuj wyzwalaczami',
    'Administrator helper': 'Pomocnik administratora',
    'Allow Bluetooth access…': 'Zezwól na dostęp do Bluetooth…',
    'Allow Wi-Fi access…': 'Zezwól na dostęp do Wi-Fi…',
    'Allow calendar access…': 'Zezwól na dostęp do kalendarza…',
    'App is frontmost': 'Aplikacja jest na pierwszym planie',
    'App is running': 'Aplikacja działa',
    'App match & grace period': 'Dopasowanie aplikacji i okres karencji',
    'Apply or remove': 'Zastosuj lub usuń',
    'Approve…': 'Zatwierdź…',
    'Apps & Activity': 'Aplikacje i aktywność',
    'Bluetooth device connected': 'Podłączono urządzenie Bluetooth',
    'Bluetooth rules need Bluetooth access (System Settings ▸ Privacy)': 'Reguły Bluetooth wymagają dostępu do Bluetooth (Ustawienia systemowe ▸ Prywatność i bezpieczeństwo)',
    'CPU load': 'Obciążenie procesora',
    'CPU threshold': 'Próg procesora',
    'Camera in use': 'Kamera w użyciu',
    'Change…': 'Zmień…',
    'Charging': 'Ładowanie',
    'Check for Updates…': 'Sprawdź uaktualnienia…',
    'Closed-display mode': 'Tryb zamkniętej pokrywy',
    'Contacting the helper…': 'Łączenie z pomocnikiem…',
    'Create a virtual display': 'Utwórz wirtualny wyświetlacz',
    'Currently paused from the menu bar.': 'Obecnie wstrzymano z paska menu.',
    'Custom Duration…': 'Niestandardowy czas trwania…',
    'During calendar events': 'Podczas wydarzeń w kalendarzu',
    'Export Settings…': 'Eksportuj ustawienia…',
    'Import Settings…': 'Importuj ustawienia…',
    'External display connected': 'Podłączono zewnętrzny wyświetlacz',
    'Fix…': 'Napraw…',
    'GNU GPL v3.0': 'GNU GPL v3.0',
    'Gaming & Streaming': 'Gry i streaming',
    'Gaming & Streaming…': 'Gry i streaming…',
    'Get Started': 'Rozpocznij',
    'Global shortcut': 'Globalny skrót',
    'Headless Setup': 'Konfiguracja bez monitora',
    'Headless Setup…': 'Konfiguracja bez monitora…',
    'Headless virtual display (experimental)': 'Wirtualny wyświetlacz bez monitora (eksperymentalne)',
    'Helper installed and responding': 'Pomocnik zainstalowany i odpowiada',
    'HiDPI (Retina)': 'HiDPI (Retina)',
    'How do you use your Mac?': 'Jak używasz swojego Maca?',
    'Install Helper…': 'Zainstaluj pomocnika…',
    'Install…': 'Zainstaluj…',
    'Jitter test': 'Test jittera',
    'Keep a disk spinning': 'Utrzymuj obracanie dysku',
    'Keep awake with lid closed': 'Nie pozwalaj zasnąć przy zamkniętej pokrywie',
    'Keep awake with the lid closed': 'Nie pozwalaj zasnąć przy zamkniętej pokrywie',
    'Keep awake': 'Nie pozwalaj zasnąć',
    'Keep me active': 'Oznaczaj mnie jako aktywnego',
    'Keeping the Mac awake now': 'Teraz Mac nie zasypia',
    'Keepresso decisions': 'Decyzje Keepresso',
    'Measuring, about 10 seconds…': 'Pomiar, około 10 sekund…',
    'Microphone in use': 'Mikrofon w użyciu',
    'Network & Devices': 'Sieć i urządzenia',
    'Network activity': 'Aktywność sieciowa',
    'Network threshold': 'Próg sieci',
    'No Wi-Fi network joined': 'Nie połączono z siecią Wi-Fi',
    'No apps running': 'Brak działających aplikacji',
    'No conditions yet, so the Mac can sleep.': 'Nie ma jeszcze żadnych warunków, więc Mac może zasnąć.',
    'No conditions yet. Add some in Preferences ▸ Triggers.': 'Nie ma jeszcze żadnych warunków. Dodaj je w Ustawieniach ▸ Wyzwalacze.',
    'No days selected means every day.': 'Brak zaznaczonych dni oznacza każdy dzień.',
    'No paired devices': 'Brak sparowanych urządzeń',
    'No session activity yet.': 'Nie ma jeszcze żadnej aktywności sesji.',
    'No volumes mounted': 'Brak zamontowanych wolumenów',
    'Not available on this macOS version.': 'Niedostępne w tej wersji macOS.',
    'Nothing is holding the Mac awake right now.': 'Obecnie nic nie utrzymuje Maca w stanie czuwania.',
    'Notify when a session ends': 'Powiadamiaj o zakończeniu sesji',
    'Notify when auto-pausing and resuming': 'Powiadamiaj o automatycznym wstrzymywaniu i wznawianiu',
    'On AC power': 'Przy zasilaniu sieciowym',
    'On battery': 'Na baterii',
    'On session end': 'Po zakończeniu sesji',
    'Only while brewing': 'Tylko podczas parzenia',
    'Open Login Items': 'Otwórz Elementy logowania',
    'Open Settings': 'Otwórz Ustawienia',
    'Overnight (22:00-6:00)': 'Noc (22:00-6:00)',
    'Pause AWDL automatically while gaming': 'Automatycznie wstrzymuj AWDL podczas gry',
    'Pause AWDL now': 'Wstrzymaj AWDL teraz',
    'Pause Triggers': 'Wstrzymaj wyzwalacze',
    'Pause on low battery': 'Wstrzymaj przy niskim poziomie baterii',
    'Play a sound': 'Odtwórz dźwięk',
    'Playing a game': 'Gra w toku',
    'Power & Display': 'Zasilanie i wyświetlacz',
    'Presets': 'Ustawienia wstępne',
    'Prevent display sleep': 'Zapobiegaj usypianiu wyświetlacza',
    'Prevent system sleep': 'Zapobiegaj usypianiu systemu',
    'Process is running': 'Proces działa',
    'Quit Keepresso': 'Zakończ Keepresso',
    'Reduce lag and jitter': 'Ogranicz opóźnienia i jitter',
    'Reinstall Helper': 'Zainstaluj pomocnika ponownie',
    "Remind me it's still on": 'Przypomnij, że to nadal włączone',
    'Repeat the reminder': 'Powtarzaj przypomnienie',
    'Restore default presets': 'Przywróć domyślne ustawienia wstępne',
    'Resume AWDL after leaving the game': 'Wznów AWDL po opuszczeniu gry',
    'Resume Triggers': 'Wznów wyzwalacze',
    'Session end': 'Koniec sesji',
    'Set Up…': 'Skonfiguruj…',
    'Show Welcome Screen…': 'Pokaż ekran powitalny…',
    'Show countdown in menu bar': 'Pokazuj odliczanie na pasku menu',
    'Start keep-awake on launch': 'Uruchamiaj tryb czuwania przy starcie',
    'The helper needs attention': 'Pomocnik wymaga uwagi',
    "The test couldn't run. Check that you're online and try again.": 'Nie udało się uruchomić testu. Sprawdź połączenie z internetem i spróbuj ponownie.',
    'The watchdog below should smooth this out; re-run the test with it on to confirm.': 'Poniższy strażnik powinien to wygładzić; uruchom test ponownie z włączonym strażnikiem, aby to potwierdzić.',
    'Times & days': 'Godziny i dni',
    'Toggle shortcut': 'Skrót przełączający',
    'Triggers paused. Controlling manually for now.': 'Wyzwalacze wstrzymane. Obecnie sterowanie ręczne.',
    'Until a Time…': 'Do godziny…',
    'VPN connected': 'Połączono z VPN',
    'View on GitHub': 'Pokaż na GitHub',
    'Volume is mounted': 'Wolumen jest zamontowany',
    'Watch a folder for downloads…': 'Obserwuj folder pobierania…',
    'While frontmost': 'Gdy na pierwszym planie',
    'While running': 'Gdy działa',
    'Work hours (weekdays 9:00-18:00)': 'Godziny pracy (dni robocze 9:00-18:00)',
    'Audio playing': 'Odtwarzanie dźwięku',
    'Paused': 'Wstrzymano',
    'Brewing': 'Parzenie',
    'Idle': 'Bezczynność',
    'System can sleep': 'System może zasnąć',
    'No conditions yet': 'Brak warunków',
    'Battery below %d%%, letting the Mac sleep': 'Bateria poniżej %d%%, Mac może zasnąć',
    'Stops in %@': 'Zatrzyma się za %@',
    'Awake for %@': 'Czuwa od %@',
    'Active': 'Aktywne',
    'Held by %@': 'Utrzymywane przez %@',
    'Waiting for any condition': 'Oczekiwanie na dowolny warunek',
    'Waiting on %@': 'Oczekiwanie na %@',
    '%d condition': '%d warunek',
    '%d conditions': '%d warunki',
    'Approve Keepresso again in System Settings.': 'Zatwierdź Keepresso ponownie w Ustawieniach systemowych.',
    "The helper isn't responding; reinstall it.": 'Pomocnik nie odpowiada; zainstaluj go ponownie.',
    'Waiting for a game to come to the front': 'Oczekiwanie, aż gra znajdzie się na pierwszym planie',
    'AWDL paused': 'AWDL wstrzymany',
    'AWDL paused for gaming': 'AWDL wstrzymany na czas gry',
    'Game closed, AWDL back in %ds': 'Gra zamknięta, AWDL wróci za %ds',
    'Latency looks clean.': 'Opóźnienie wygląda czysto.',
    'Once-a-second spikes: this looks like AWDL.': 'Skoki raz na sekundę: to wygląda na AWDL.',
    "Spiky, but not on AWDL's cadence (congestion or a weak signal).": 'Nierówne, ale nie w rytmie AWDL (przeciążenie lub słaby sygnał).',
    'Not enough replies to judge.': 'Za mało odpowiedzi, aby ocenić.',
    'AWDL is on right now': 'AWDL jest teraz włączony',
    'AWDL is off right now': 'AWDL jest teraz wyłączony',
    'AWDL state unknown': 'Stan AWDL nieznany',
    'Agentic coding': 'Kodowanie agentowe',
    'Stay awake while Claude, Codex, or Grok is running.': 'Nie pozwalaj zasnąć, gdy działa Claude, Codex lub Grok.',
    'Gaming & streaming': 'Gry i streaming',
    'Stay awake while a game or cloud-gaming app is in front.': 'Nie pozwalaj zasnąć, gdy gra lub aplikacja do gier w chmurze jest na pierwszym planie.',
    'Meetings & calls': 'Spotkania i rozmowy',
    'Stay awake whenever the camera or microphone is in use.': 'Nie pozwalaj zasnąć, gdy kamera lub mikrofon są w użyciu.',
    'Remote access': 'Dostęp zdalny',
    'Stay awake while someone is connected over SSH.': 'Nie pozwalaj zasnąć, gdy ktoś jest połączony przez SSH.',
    'Keep it manual for now': 'Na razie pozostaw ręcznie',
    'Just toggle keep-awake yourself, and set up your own triggers later in Preferences.': 'Po prostu przełączaj tryb czuwania samodzielnie, a własne wyzwalacze skonfigurujesz później w Ustawieniach.',
    'Launch at login': 'Uruchamiaj przy logowaniu',
    'Start Keepresso automatically when you log in.': 'Uruchamiaj Keepresso automatycznie po zalogowaniu.',
    'Notifications': 'Powiadomienia',
    'Let Keepresso remind you when a long session is still keeping the Mac awake.': 'Pozwól Keepresso przypominać, gdy długa sesja wciąż utrzymuje Maca w stanie czuwania.',
    'Approve a small helper once and the privileged extras (lid-closed mode, AWDL pausing) never ask for your password again. Set and forget; removable in Preferences.': 'Zatwierdź raz mały pomocnik, a uprzywilejowane dodatki (tryb zamkniętej pokrywy, wstrzymywanie AWDL) nigdy więcej nie poproszą o hasło. Ustaw i zapomnij; można go usunąć w Ustawieniach.',
    'Location access (Wi-Fi rules)': 'Dostęp do lokalizacji (reguły Wi-Fi)',
    'Bluetooth access (device rules)': 'Dostęp do Bluetooth (reguły urządzeń)',
    'Calendar access (event rule)': 'Dostęp do kalendarza (reguła wydarzenia)',
    'Keepresso launches at login, so it returns after a reboot.': 'Keepresso uruchamia się przy logowaniu, więc wraca po ponownym uruchomieniu.',
    "Keepresso isn't set to launch at login, so it won't run after an unattended reboot.": 'Keepresso nie jest ustawione na uruchamianie przy logowaniu, więc nie uruchomi się po nienadzorowanym ponownym uruchomieniu.',
    "Turn on “Launch at login” in Keepresso's settings.": 'Włącz „Uruchamiaj przy logowaniu” w ustawieniach Keepresso.',
    'Keepresso can read the current Wi-Fi network name for your Wi-Fi triggers.': 'Keepresso może odczytać nazwę bieżącej sieci Wi-Fi na potrzeby twoich wyzwalaczy Wi-Fi.',
    "Without Location access Keepresso can't read the Wi-Fi network name, so Wi-Fi triggers won't match.": 'Bez dostępu do lokalizacji Keepresso nie może odczytać nazwy sieci Wi-Fi, więc wyzwalacze Wi-Fi nie zadziałają.',
    'Allow Location access for Keepresso.': 'Zezwól Keepresso na dostęp do lokalizacji.',
    'Keepresso can see which paired devices are connected for your Bluetooth triggers.': 'Keepresso może sprawdzić, które sparowane urządzenia są połączone, na potrzeby twoich wyzwalaczy Bluetooth.',
    "Without Bluetooth access Keepresso can't see paired devices, so Bluetooth triggers won't match.": 'Bez dostępu do Bluetooth Keepresso nie widzi sparowanych urządzeń, więc wyzwalacze Bluetooth nie zadziałają.',
    'Allow Bluetooth access for Keepresso.': 'Zezwól Keepresso na dostęp do Bluetooth.',
    'Keepresso can see when a calendar event is in progress for your calendar trigger.': 'Keepresso może sprawdzić, czy trwa wydarzenie w kalendarzu, na potrzeby wyzwalacza kalendarza.',
    "Without full calendar access Keepresso can't see events, so the calendar trigger won't match.": 'Bez pełnego dostępu do kalendarza Keepresso nie widzi wydarzeń, więc wyzwalacz kalendarza nie zadziała.',
    'Allow full calendar access for Keepresso.': 'Zezwól Keepresso na pełny dostęp do kalendarza.',
    'Keepresso can post the “still brewing” reminder.': 'Keepresso może wysłać przypomnienie „wciąż parzy”.',
    "Notifications are off, so the “still brewing” reminder can't appear.": 'Powiadomienia są wyłączone, więc przypomnienie „wciąż parzy” nie może się pojawić.',
    'Allow notifications for Keepresso.': 'Zezwól Keepresso na powiadomienia.',
    'Above %d%%': 'Powyżej %d%%',
    'Above %@': 'Powyżej %@',
    'Version %@': 'Wersja %@',
    'Remove “%@”': 'Usuń „%@”',
    'On current Wi-Fi (%@)': 'W bieżącej sieci Wi-Fi (%@)',
    'keep the Mac awake with the lid closed': 'nie pozwolić Makowi zasnąć przy zamkniętej pokrywie',
    'switch closed-display mode with the session': 'przełączać tryb zamkniętej pokrywy razem z sesją',
    'pause AWDL (turn off the Wi-Fi AirDrop/Handoff radio hops)': 'wstrzymać AWDL (wyłączyć skoki radiowe Wi-Fi używane przez AirDrop/Handoff)',
    "macOS is asking for your administrator password to %@. The dialog may be titled “osascript”: that's Keepresso running the command, and nothing else is changed. To stop these prompts for good, install the administrator helper (Preferences ▸ General).": 'macOS prosi o hasło administratora, aby %@. Okno dialogowe może mieć tytuł „osascript”: to Keepresso uruchamia to polecenie, nic innego nie ulega zmianie. Aby na stałe zatrzymać te monity, zainstaluj pomocnika administratora (Ustawienia ▸ Ogólne).',
    'Keepresso keeps your Mac awake on your terms. It lives in the menu bar near the clock, with no Dock icon. Click its cup any time to start or stop.': 'Keepresso utrzymuje Maca w stanie czuwania na twoich warunkach. Działa w pasku menu obok zegara, bez ikony w Docku. Kliknij jego filiżankę w dowolnej chwili, aby rozpocząć lub zatrzymać.',
    'Pick one to set up matching triggers, or keep it manual and add your own later. You can change this any time in Preferences.': 'Wybierz jedną opcję, aby skonfigurować odpowiednie wyzwalacze, albo pozostaw sterowanie ręczne i dodaj własne później. Możesz to zmienić w dowolnej chwili w Ustawieniach.',
    'When on, the listed conditions control the session instead of the manual switch.': 'Gdy włączone, wymienione warunki sterują sesją zamiast ręcznego przełącznika.',
    'Activation is controlled by triggers.\nEdit them in Preferences.': 'Aktywacją sterują wyzwalacze.\nEdytuj je w Ustawieniach.',
    'Why each session started or stopped, newest first. Kept in memory; clears on relaunch.': 'Dlaczego każda sesja się rozpoczęła lub zakończyła, od najnowszej. Przechowywane w pamięci; czyszczone przy ponownym uruchomieniu.',
    "Every app's live power assertions, not just Keepresso's, the same data pmset -g assertions prints.": 'Aktywne asercje zasilania wszystkich aplikacji, nie tylko Keepresso, te same dane, które wyświetla polecenie pmset -g assertions.',
    'A system-wide keyboard shortcut that starts or stops keep-awake from any app. Needs at least one modifier key.': 'Ogólnosystemowy skrót klawiszowy, który rozpoczyna lub zatrzymuje tryb czuwania z dowolnej aplikacji. Wymaga co najmniej jednego klawisza modyfikującego.',
    "Lets the Mac sleep once battery charge drops below this level, even mid-session, so it doesn't run flat.": 'Pozwala Makowi zasnąć, gdy poziom naładowania baterii spadnie poniżej tej wartości, nawet w trakcie sesji, aby bateria się nie wyczerpała.',
    'Shows the remaining time next to the menu-bar icon during a timed session.': 'Pokazuje pozostały czas obok ikony na pasku menu podczas sesji z limitem czasu.',
    'Starts a session as soon as Keepresso launches, using the default duration. Ignored while triggers are controlling activation.': 'Rozpoczyna sesję zaraz po uruchomieniu Keepresso, z użyciem domyślnego czasu trwania. Ignorowane, gdy aktywacją sterują wyzwalacze.',
    'Reopen the first-run welcome, with quick one-click setup for how you use your Mac.': 'Otwórz ponownie powitanie z pierwszego uruchomienia, z szybką konfiguracją jednym kliknięciem dopasowaną do sposobu korzystania z Maca.',
    'Fires when a timed session expires, trigger conditions drop, or a low-battery pause kicks in, not when you stop it yourself. The action is off by default so a timed session never surprises you.': 'Uruchamia się, gdy sesja z limitem czasu wygaśnie, warunki wyzwalaczy przestaną być spełnione lub zadziała wstrzymanie przy niskim poziomie baterii, a nie wtedy, gdy zatrzymasz ją samodzielnie. Ta czynność jest domyślnie wyłączona, aby sesja z limitem czasu nigdy cię nie zaskoczyła.',
    'If that time already passed today, it means tomorrow.': 'Jeśli ta godzina już dziś minęła, oznacza to jutro.',
    'Runs past midnight into the next day.': 'Trwa po północy, aż do następnego dnia.',
    'Save your settings, triggers, and presets to a JSON file to back them up or move them to another Mac. Importing replaces your current configuration and ends any running session.': 'Zapisz swoje ustawienia, wyzwalacze i zestawy ustawień wstępnych do pliku JSON, aby je zabezpieczyć lub przenieść na innego Maca. Import zastępuje bieżącą konfigurację i kończy każdą trwającą sesję.',
    'Keeps the Mac awake while a partial-download file (.crdownload, .download, .part, and the like) exists in the chosen folder, then lets it sleep once the download finishes. Holds for 30 seconds between files in a batch.': 'Utrzymuje Maca w stanie czuwania, dopóki w wybranym folderze istnieje częściowo pobrany plik (.crdownload, .download, .part i podobne), a następnie pozwala mu zasnąć po zakończeniu pobierania. Utrzymuje aktywność przez 30 sekund między plikami w tej samej partii.',
    'Writes a tiny marker file on the chosen volume periodically to stop an external drive or NAS from spinning down.': 'Okresowo zapisuje niewielki plik znacznika na wybranym wolumenie, aby zapobiec zatrzymaniu zewnętrznego dysku lub NAS.',
    'For a Mac with no monitor: creates a higher-resolution display so Screen Sharing and VNC look crisp instead of a fuzzy 1920 × 1080. It uses a private macOS API, so treat it as experimental and expect it may break on a macOS update. A hardware HDMI or DisplayPort dummy plug is a no-software alternative.': 'Dla Maca bez monitora: tworzy wyświetlacz o wyższej rozdzielczości, dzięki czemu Udostępnianie ekranu i VNC wyglądają ostro zamiast rozmytego 1920 × 1080. Wykorzystuje prywatne API macOS, więc traktuj to jako funkcję eksperymentalną i licz się z tym, że aktualizacja macOS może ją przestać działać. Sprzętowa zaślepka HDMI lub DisplayPort to alternatywa niewymagająca oprogramowania.',
    'Stays awake on battery too; the display turns off when the lid closes. Turn it off before putting it in a bag.': 'Pozostaje aktywny również na baterii; wyświetlacz wyłącza się po zamknięciu pokrywy. Wyłącz tę funkcję przed schowaniem Maca do torby.',
    'The calendar rule needs Calendar access (System Settings ▸ Privacy)': 'Reguła kalendarza wymaga dostępu do kalendarza (Ustawienia systemowe ▸ Prywatność i bezpieczeństwo)',
    'Wi-Fi rules need Location access (System Settings ▸ Privacy)': 'Reguły Wi-Fi wymagają dostępu do lokalizacji (Ustawienia systemowe ▸ Prywatność i bezpieczeństwo)',
    "Checks an always-on Mac (e.g. a headless Mac mini) needs. Keepresso can read these but can't change the system ones, so use the links and commands below.": 'Kontrole potrzebne stale włączonemu Makowi (np. Mac mini bez monitora). Keepresso może je odczytać, ale nie może zmienić ustawień systemowych, dlatego skorzystaj z poniższych odnośników i poleceń.',
    "macOS hops the Wi-Fi radio off-channel for AWDL about once a second, which shows up as ping spikes mid-game or mid-stream. Diagnose it here, and pause AWDL for the session if it's the culprit.": 'macOS co około sekundę przełącza radio Wi-Fi poza kanał na potrzeby AWDL, co objawia się skokami pingu w trakcie gry lub streamingu. Zdiagnozuj to tutaj i wstrzymaj AWDL na czas sesji, jeśli to on jest winowajcą.',
    "Pings 1.1.1.1 five times a second for 10 seconds and checks whether latency spikes on AWDL's once-a-second cadence.": 'Wysyła ping do 1.1.1.1 pięć razy na sekundę przez 10 sekund i sprawdza, czy opóźnienie skacze w rytmie AWDL, czyli raz na sekundę.',
    'Counts only while a game (or a cloud-gaming app) is the active window, not just running in the background. Keeps holding for 5 minutes after you switch away.': 'Liczy się tylko wtedy, gdy gra (lub aplikacja do gier w chmurze) jest aktywnym oknem, a nie tylko działa w tle. Utrzymuje aktywność jeszcze przez 5 minut po przełączeniu się na coś innego.',
    "How long the pause lingers after the game stops being the active window, so a quick alt-tab doesn't flap the radios. Shorter brings AirDrop and Handoff back faster; longer rides out launchers and loading screens.": 'Jak długo utrzymuje się wstrzymanie po tym, jak gra przestaje być aktywnym oknem, aby szybkie alt-tab nie przełączało radia w kółko. Krótszy czas przywraca AirDrop i Handoff szybciej; dłuższy pozwala przetrwać launchery i ekrany wczytywania.',
    'Posts a notification when a game is detected and AWDL pauses, and again when it resumes. A notice that your administrator password is needed is always sent (even behind a fullscreen game), regardless of this switch.': 'Wysyła powiadomienie, gdy zostanie wykryta gra i AWDL zostanie wstrzymany, oraz ponownie, gdy zostanie wznowiony. Informacja o konieczności podania hasła administratora jest zawsze wysyłana (nawet za grą pełnoekranową), niezależnie od tego przełącznika.',
    "Also tells macOS you're active while a session runs, so remote-desktop sessions, meeting presence (Teams, Slack), and corporate idle-logout don't mark you away. A plain keep-awake doesn't reach those. It only steps in once you've been idle a few seconds, so it never nudges the pointer while you're using the Mac or gaming. Off by default; some managed Macs flag simulated activity.": 'Informuje też macOS, że jesteś aktywny podczas trwania sesji, dzięki czemu sesje pulpitu zdalnego, obecność na spotkaniach (Teams, Slack) i firmowe wylogowywanie przy bezczynności nie oznaczają cię jako nieobecnego. Zwykłe utrzymywanie czuwania tego nie zapewnia. Włącza się dopiero po kilku sekundach bezczynności, więc nigdy nie porusza kursorem, gdy korzystasz z Maca lub grasz. Domyślnie wyłączone; niektóre zarządzane Maki oznaczają symulowaną aktywność.',
    'Install a small helper service so closed-display mode and AWDL pausing never ask for your password again. macOS will ask you to allow it in System Settings, once; nothing else changes.': 'Zainstaluj mały pomocniczy proces systemowy, aby tryb zamkniętej pokrywy i wstrzymywanie AWDL nigdy więcej nie prosiły o hasło. macOS poprosi cię o zezwolenie na to w Ustawieniach systemowych, jednorazowo; nic więcej się nie zmienia.',
    "One step left, in System Settings: under General ▸ Login Items & Extensions (“Login Items” on older macOS), find Keepresso in the “Allow in the Background” list and turn its switch ON. macOS asks for your administrator password once; this updates by itself when you're done.": 'Pozostał jeden krok w Ustawieniach systemowych: w Ogólne ▸ Elementy logowania i rozszerzenia („Elementy logowania” w starszym macOS) znajdź Keepresso na liście „Zezwalaj w tle” i włącz jego przełącznik. macOS jednorazowo poprosi o hasło administratora; ten stan zaktualizuje się sam, gdy skończysz.',
    "Keeps running with the lid shut and no external display, on power or battery. The display itself still turns off when the lid closes (unless an external display is attached), so it's not lighting up uselessly inside the closed lid. Changing this flips a system setting (pmset disablesleep), so it stays in effect until you turn it off. On battery and closed it can still drain the battery over time, so don't leave it on in a bag. With “Only while brewing” on, Keepresso instead switches it on when a keep-awake session starts and back off when it ends or the app quits. Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password (once per app run for “Only while brewing”).": 'Działa dalej przy zamkniętej pokrywie i bez zewnętrznego wyświetlacza, na zasilaniu sieciowym lub na baterii. Sam wyświetlacz nadal wyłącza się po zamknięciu pokrywy (chyba że podłączony jest zewnętrzny wyświetlacz), więc nie świeci bezużytecznie wewnątrz zamkniętej obudowy. Zmiana tej opcji przełącza ustawienie systemowe (pmset disablesleep), więc pozostaje ono aktywne, dopóki go nie wyłączysz. Na baterii, przy zamkniętej pokrywie, może z czasem wyczerpać baterię, więc nie zostawiaj tego włączonego w torbie. Przy włączonym „Tylko podczas parzenia” Keepresso włącza tę opcję zamiast tego, gdy rozpoczyna się sesja czuwania, i wyłącza ją z powrotem, gdy sesja się kończy lub aplikacja zostaje zamknięta. Obie opcje wymagają uprawnień administratora: bezgłośnie z zainstalowanym pomocnikiem administratora (patrz góra tej zakładki), w przeciwnym razie macOS poprosi o hasło (raz na uruchomienie aplikacji dla „Tylko podczas parzenia”).',
    "Turns the pause on right now and keeps it on until you turn it off or quit Keepresso (it isn't tied to whether a keep-awake session is brewing). While it's on, AirDrop, Handoff, Sidecar, and Continuity Camera take a break, and the once-a-second lag spikes stop. Everything comes back the moment you turn it off or quit Keepresso; even if the app crashes, macOS is restored automatically. With the administrator helper installed the switch is always instant and silent; without it, macOS asks for your password once per launch (the system dialog may show “osascript”, which is Keepresso running the command).": 'Włącza wstrzymanie od razu i utrzymuje je włączone, dopóki go nie wyłączysz lub nie zamkniesz Keepresso (nie zależy od tego, czy trwa sesja czuwania). Gdy jest włączone, AirDrop, Handoff, Sidecar i Aparat Continuity robią przerwę, a skoki opóźnień raz na sekundę ustają. Wszystko wraca w chwili, gdy je wyłączysz lub zamkniesz Keepresso; nawet jeśli aplikacja ulegnie awarii, macOS zostanie przywrócony automatycznie. Z zainstalowanym pomocnikiem administratora przełącznik działa zawsze natychmiast i bezgłośnie; bez niego macOS prosi o hasło raz na uruchomienie (systemowe okno dialogowe może pokazywać „osascript”, czyli Keepresso uruchamiające to polecenie).',
    'Watches for a game (or a cloud-gaming app like GeForce NOW) as the active window and pauses AWDL on its own, then lifts the pause a little after you switch away (the delay below). It only counts while the game is in front and in use, not just running in the background. Without the administrator helper, turning this on asks for your password once per app run, right now rather than mid-game; with the helper it never asks at all. No trigger setup needed: leave this on and forget it.': 'Obserwuje, czy gra (lub aplikacja do gier w chmurze, np. GeForce NOW) jest aktywnym oknem, i samodzielnie wstrzymuje AWDL, a następnie znosi wstrzymanie chwilę po przełączeniu się na coś innego (opóźnienie poniżej). Liczy się to tylko, gdy gra jest na pierwszym planie i w użyciu, a nie tylko działa w tle. Bez pomocnika administratora włączenie tej opcji prosi o hasło raz na uruchomienie aplikacji, od razu, a nie w trakcie gry; z pomocnikiem nigdy nie pyta. Nie wymaga konfiguracji wyzwalaczy: zostaw włączone i zapomnij o tym.',
    'Helper installed. Closed-display mode and AWDL pausing work without password prompts.': 'Pomocnik zainstalowany. Tryb zamkniętej pokrywy i wstrzymywanie AWDL działają bez próśb o hasło.',
    'Pause AWDL to steady your connection, and test your jitter, in Gaming & Streaming.': 'Wstrzymaj AWDL, aby ustabilizować połączenie, i przetestuj jitter w Gry i streaming.',
    'A small system service that handles the privileged switches (closed-display mode below, AWDL pausing in Gaming & Streaming) for Keepresso, so no password prompts ever again: macOS asks once when you approve it under Login Items, and the approval survives restarts and updates. It can only flip those specific switches, everything it changes is restored if the app quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list; the status shown here is the real one.': 'Mały proces systemowy, który obsługuje uprzywilejowane przełączniki (tryb zamkniętej pokrywy poniżej, wstrzymywanie AWDL w Gry i streaming) dla Keepresso, dzięki czemu monity o hasło znikają na dobre: macOS pyta jednorazowo, gdy zatwierdzisz go w Elementach logowania, a zatwierdzenie przetrwa ponowne uruchomienia i aktualizacje. Może przełączać wyłącznie te konkretne opcje, wszystko, co zmienia, jest przywracane po zamknięciu lub awarii aplikacji, a ty możesz go w każdej chwili usunąć tutaj. Umieszcza też narzędzie wiersza poleceń keepresso w twojej zmiennej PATH (instalacje przez Homebrew już je mają). Po usunięciu Ustawienia systemowe mogą jeszcze przez chwilę pokazywać nieaktualny wiersz w Elementach logowania, dopóki macOS nie odświeży listy; stan pokazany tutaj jest tym prawdziwym.',
    'General': 'Ogólne',
    'Triggers': 'Wyzwalacze',
    'Reminder': 'Przypomnienie',
    'Disk': 'Dysk',
    'Activity': 'Aktywność',
    'Indefinitely': 'Bezterminowo',
    'Update Session': 'Aktualizuj sesję',
    'Start': 'Rozpocznij',
    'Met, in grace period': 'Spełniony, w okresie karencji',
    'Met': 'Spełniony',
    'Not met': 'Niespełniony',
    'Copied!': 'Skopiowano!',
    'Copy command': 'Kopiuj polecenie',
    'OK': 'OK',
    'Needs attention': 'Wymaga uwagi',
    'Tip': 'Wskazówka',
    'Unknown': 'Nieznane',
    'Checking the helper': 'Sprawdzanie pomocnika',
    'One approval needed': 'Wymagane jedno zatwierdzenie',
    'The helper needs a reinstall': 'Pomocnik wymaga ponownej instalacji',
    'All set': 'Wszystko gotowe',
    "Making sure Keepresso's helper is awake and answering.": 'Sprawdzanie, czy pomocnik Keepresso działa i odpowiada.',
    "macOS turned the helper's background switch off, so it needs your approval again: in System Settings, under Login Items & Extensions, find Keepresso in App Background Activity and turn it on. Everything is password-free again right after.": 'macOS wyłączył przełącznik działania pomocnika w tle, więc potrzebne jest ponowne zatwierdzenie: w Ustawieniach systemowych, w Elementach logowania i rozszerzeniach, znajdź Keepresso w Aktywności aplikacji w tle i włącz ją. Zaraz potem wszystko znów będzie działać bez hasła.',
    "Keepresso repaired the helper's registration, but macOS keeps disabling it. An old copy of Keepresso in the Trash is the usual cause: empty the Trash, then reinstall the helper below. Nothing else about your setup changes.": 'Keepresso naprawiło rejestrację pomocnika, ale macOS wciąż ją wyłącza. Zwykle przyczyną jest stara kopia Keepresso w Koszu: opróżnij Kosz, a następnie zainstaluj pomocnika ponownie poniżej. Nic innego w twojej konfiguracji się nie zmienia.',
    'The helper is back. Closed-display mode and AWDL pausing work without password prompts again.': 'Pomocnik znów działa. Tryb zamkniętej pokrywy i wstrzymywanie AWDL ponownie działają bez próśb o hasło.',
    'Waiting for the switch in System Settings; this updates by itself.': 'Oczekiwanie na przełącznik w Ustawieniach systemowych; ten stan aktualizuje się sam.',
    'Record': 'Nagraj',
    'Press keys…': 'Naciśnij klawisze…',
    'Other process, e.g. rsync': 'Inny proces, np. rsync',
    'Export Keepresso Settings': 'Eksportuj ustawienia Keepresso',
    'Import Keepresso Settings': 'Importuj ustawienia Keepresso',
    'Exported to %@.': 'Wyeksportowano do %@.',
    'Settings imported.': 'Zaimportowano ustawienia.',
    "Couldn't export settings: %@": 'Nie udało się wyeksportować ustawień: %@',
    "Couldn't read the file: %@": 'Nie udało się odczytać pliku: %@',
    "That file isn't a Keepresso settings export.": 'Ten plik nie jest eksportem ustawień Keepresso.',
    'That export was made by a newer version of Keepresso.': 'Ten eksport został utworzony przez nowszą wersję Keepresso.',
    'Save current rules as…': 'Zapisz bieżące reguły jako…',
    'A recurring notification every interval while a session runs, so a Mac left awake keeps reminding you.': 'Cykliczne powiadomienie w wybranym odstępie czasu podczas trwania sesji, dzięki czemu pozostawiony w stanie czuwania Mac stale ci o tym przypomina.',
    'A one-time notification once a session has run this long, in case you forget the Mac is awake.': 'Jednorazowe powiadomienie, gdy sesja trwa już tak długo, na wypadek gdybyś zapomniał, że Mac nie śpi.',
    'Watch': 'Obserwuj',
    'Keep awake while downloads are in progress in this folder.': 'Nie pozwalaj zasnąć, gdy w tym folderze trwają pobierania.',
    'Keep Awake': 'Nie pozwalaj zasnąć',
    'Choose a folder on the disk you want to keep spun up.': 'Wybierz folder na dysku, który chcesz utrzymać w ruchu.',
    'Keepresso needs a new approval': 'Keepresso wymaga nowego zatwierdzenia',
    "macOS turned Keepresso's background switch off. Turn it back on under Login Items & Extensions in System Settings to keep the password-free helper.": 'macOS wyłączył przełącznik działania Keepresso w tle. Włącz go ponownie w Elementach logowania i rozszerzeniach w Ustawieniach systemowych, aby zachować pomocnika działającego bez hasła.',
    'Keepresso needs your password': 'Keepresso potrzebuje twojego hasła',
    'Enter your administrator password to switch closed-display mode on for this session.': 'Podaj hasło administratora, aby włączyć tryb zamkniętej pokrywy dla tej sesji.',
    'Enter your administrator password to pause AWDL for this game.': 'Podaj hasło administratora, aby wstrzymać AWDL na czas tej gry.',
    'Game detected': 'Wykryto grę',
    'Pausing AWDL to steady your connection.': 'Wstrzymywanie AWDL w celu ustabilizowania połączenia.',
    'AWDL resumed': 'AWDL wznowiony',
    'The game closed; AirDrop, Handoff and Continuity are back.': 'Gra została zamknięta; AirDrop, Handoff i Continuity znów działają.',
    "This copy of Keepresso isn't in the Applications folder, so it leaves the helper alone. Install from /Applications.": 'Ta kopia Keepresso nie znajduje się w folderze Programy, więc nie ingeruje w pomocnika. Zainstaluj z /Applications.',
    "The helper wasn't found inside the app. Reinstall Keepresso and try again.": 'Nie znaleziono pomocnika wewnątrz aplikacji. Zainstaluj Keepresso ponownie i spróbuj jeszcze raz.',
    "The helper couldn't be registered.": 'Nie udało się zarejestrować pomocnika.',
    "The helper couldn't be removed: %@": 'Nie udało się usunąć pomocnika: %@',
    'macOS still reports the helper as registered. Try again, or restart the Mac.': 'macOS wciąż zgłasza, że pomocnik jest zarejestrowany. Spróbuj ponownie albo uruchom Maca ponownie.',
    'Removed. System Settings may keep showing Keepresso under App Background Activity until macOS refreshes its list; restarting the Mac clears the leftover row.': 'Usunięto. Ustawienia systemowe mogą nadal pokazywać Keepresso w Aktywności aplikacji w tle, dopóki macOS nie odświeży listy; ponowne uruchomienie Maca usuwa pozostały wiersz.',
    "macOS is refusing the helper's registration outright. Reinstall the helper; if that doesn't take, restart the Mac and try once more.": 'macOS całkowicie odmawia rejestracji pomocnika. Zainstaluj pomocnika ponownie; jeśli to nie pomoże, uruchom Maca ponownie i spróbuj jeszcze raz.',
    "The helper isn't responding. If an old copy of Keepresso is in the Trash, empty the Trash first: macOS keeps disabling the helper while one is there. Then reinstall the helper.": 'Pomocnik nie odpowiada. Jeśli w Koszu znajduje się stara kopia Keepresso, najpierw opróżnij Kosz: dopóki tam jest, macOS wciąż wyłącza pomocnika. Następnie zainstaluj pomocnika ponownie.',
    'Old copy stuck in the Trash': 'Stara kopia utknęła w Koszu',
    'An old copy of Keepresso in the Trash keeps the background helper from working. Please delete it from the Trash, or empty the Trash.': 'Stara kopia Keepresso w Koszu uniemożliwia działanie pomocnika w tle. Usuń ją z Kosza albo opróżnij Kosz.',
    'Language': 'Język',
    'App language': 'Język aplikacji',
    'Follow System': 'Zgodnie z systemem',
    'Keepresso follows your system language by default. Changing this relaunches Keepresso so menus, windows, and notifications all switch together.': 'Keepresso domyślnie używa języka systemu. Zmiana tego ustawienia powoduje ponowne uruchomienie Keepresso, dzięki czemu menu, okna i powiadomienia przełączają się razem.',
    '%d h %d min': '%d godz. %d min',
    '%d h': '%d godz.',
    '%d min': '%d min',
    '%d:%02d': '%d:%02d',
    '%ds': '%d s',
    '%d:%02d:%02d': '%d:%02d:%02d',
    'Keepresso: paused, battery low': 'Keepresso: wstrzymano, niski poziom baterii',
    'Keepresso: brewing': 'Keepresso: parzenie',
    'Keepresso: idle': 'Keepresso: bezczynność',
    '1920 × 1080': '1920 × 1080',
    '2560 × 1440': '2560 × 1440',
    '2880 × 1620': '2880 × 1620',
    '3840 × 2160 (4K)': '3840 × 2160 (4K)',
    'Stop in': 'Zatrzymaj za',
    'Quick stop shortcuts': 'Skróty szybkiego zatrzymania',
    'Add Shortcut': 'Dodaj skrót',
    'Shortcut %d': 'Skrót %d',
    'Remove shortcut': 'Usuń skrót',
    'One-click “Stop in” buttons shown in the menu while a session runs, so the Mac goes back to sleeping on its own that much later. Up to four; the list stays sorted.': 'Widoczne w menu podczas sesji przyciski „Zatrzymaj za” jednym kliknięciem, dzięki którym Mac po tym czasie znów zaśnie sam. Maksymalnie cztery; lista pozostaje posortowana.',
    'Warn before a timed session ends': 'Ostrzegaj przed końcem sesji z limitem czasu',
    'Warn': 'Ostrzegaj',
    '1 minute before': '1 minutę przed',
    '2 minutes before': '2 minuty przed',
    '5 minutes before': '5 minut przed',
    '10 minutes before': '10 minut przed',
    'AI agents': 'Agenci AI',
    'AI agent is working': 'Agent AI pracuje',
    'Keeps the Mac awake while a coding-agent session (claude, codex, gemini, aider, and the like) is actively working, judged by its CPU use, and lets it sleep once every session has gone idle for the grace period. The menu lists each detected session. A freshly started session can take a few seconds to read as working.': 'Utrzymuje Maca w stanie czuwania, gdy sesja agenta kodującego (claude, codex, gemini, aider i podobne) faktycznie pracuje, oceniając to po użyciu CPU, i pozwala mu zasnąć, gdy wszystkie sesje pozostaną bezczynne przez okres karencji. Menu wyświetla każdą wykrytą sesję. Świeżo uruchomiona sesja może potrzebować kilku sekund, zanim zostanie uznana za pracującą.',
    'Idle grace period': 'Karencja po bezczynności',
    'Instantly': 'Natychmiast',
    '10 minutes': '10 minut',
    'working': 'pracuje',
    'idle': 'bezczynny',
    '+%d more': '+%d więcej',
}


# --- Agent hooks (Claude Code connection) ---
APP.update({
    "Claude Code connected: sessions report working and waiting exactly.": "Claude Code połączony: sesje dokładnie zgłaszają pracę i oczekiwanie.",
    "Connect Claude Code for exact session tracking (adds hooks to its settings).": "Połącz Claude Code, aby dokładnie śledzić sesje (dodaje hooki do jego ustawień).",
    "Connect Claude Code": "Połącz Claude Code",
    "Claude Code's settings file couldn't be read, so it was left untouched.": "Nie można odczytać pliku ustawień Claude Code, więc pozostawiono go bez zmian.",
    "Couldn't update Claude Code's settings file.": "Nie można zaktualizować pliku ustawień Claude Code.",
})
