# -*- coding: utf-8 -*-
# Brazilian Portuguese overlay for catalog_app.py: English source -> Portuguese (Brazil).
APP = {
    "Add": "Adicionar",
    "Add:": "Adicionar:",
    "Clear": "Limpar",
    "Close": "Fechar",
    "Done": "Concluído",
    "Save": "Salvar",
    "Enable": "Ativar",
    "Enabled": "Ativado",
    "Installed": "Instalado",
    "Remove": "Remover",
    "Remove condition": "Remover condição",
    "Resume": "Retomar",
    "Later": "Mais tarde",
    "Learn more": "Saiba mais",
    "Re-check": "Verificar novamente",
    "Run Test": "Executar teste",
    "Match": "Correspondência",
    "Threshold": "Limite",
    "Battery threshold": "Limite de bateria",
    "Presence": "Presença",
    "Menu bar": "Barra de menus",
    "Battery": "Bateria",
    "Welcome": "Boas-vindas",
    "Keeps the Mac running with the lid shut and no external display. This flips a system setting that needs administrator rights: silent with the administrator helper installed (Preferences ▸ General), otherwise macOS asks for your password.": "Mantém o Mac funcionando com a tampa fechada e sem tela externa. Isso muda um ajuste do sistema que exige privilégios de administrador: silencioso com o assistente de administrador instalado (Preferências ▸ Geral), caso contrário o macOS pede sua senha.",
    "Turns closed-display mode on when a keep-awake session starts and off when it ends or Keepresso quits.": "Ativa o modo com tela fechada quando uma sessão de vigília começa e desativa quando ela termina ou o Keepresso é fechado.",
    "Grace period": "Período de tolerância",
    "Section": "Seção",
    "Schedule": "Programação",
    "Set Duration": "Definir duração",
    "For": "Por",
    "From": "De",
    "To": "Até",
    "Until": "Até",
    "When": "Quando",
    "Below": "Abaixo de",
    "Power": "Energia",
    "Display": "Tela",
    "Network": "Rede",
    "Media": "Mídia",
    "Backup": "Backup",
    "Folder": "Pasta",
    "Downloads": "Downloads",
    "Touch": "Atualizar",
    "Resolution": "Resolução",
    "Startup": "Inicialização",
    "Gaming": "Jogos",
    "None": "Nenhum",
    "any": "qualquer uma",
    "all": "todas",
    "of these are true:": "destas são verdadeiras:",
    "1 minute": "1 minuto",
    "2 minutes": "2 minutos",
    "5 minutes": "5 minutos",
    "10 seconds": "10 segundos",
    "30 seconds": "30 segundos",
    "15 minutes": "15 minutos",
    "30 minutes": "30 minutos",
    "1 hour": "1 hora",
    "2 hours": "2 horas",
    "4 hours": "4 horas",
    "8 hours": "8 horas",
    "No grace": "Sem tolerância",
    "Every 1 minute": "A cada 1 minuto",
    "Every 5 minutes": "A cada 5 minutos",
    "Every 10 minutes": "A cada 10 minutos",
    "Every 30 minutes": "A cada 30 minutos",
    "Every": "A cada",
    "After": "Após",
    "Keepresso": "Keepresso",
    "About Keepresso": "Sobre o Keepresso",
    "Welcome to Keepresso": "Bem-vindo ao Keepresso",
    "Keepresso Setup": "Configuração do Keepresso",
    "Keepresso Helper": "Assistente do Keepresso",
    "Preferences": "Preferências",
    "Preferences…": "Preferências…",
    "A menu-bar app that keeps your Mac awake on your terms.": "Um app de barra de menus que mantém seu Mac acordado do seu jeito.",
    "AWDL watchdog": "Monitoramento de AWDL",
    "Activate by triggers": "Ativar por gatilhos",
    "Administrator helper": "Assistente de administrador",
    "Allow Bluetooth access…": "Permitir acesso ao Bluetooth…",
    "Allow Wi-Fi access…": "Permitir acesso ao Wi-Fi…",
    "Allow calendar access…": "Permitir acesso ao calendário…",
    "App is frontmost": "O app está em primeiro plano",
    "App is running": "O app está em execução",
    "App match & grace period": "Correspondência de app e período de tolerância",
    "Apply or remove": "Aplicar ou remover",
    "Approve…": "Aprovar…",
    "Apps & Activity": "Apps e atividade",
    "Bluetooth device connected": "Dispositivo Bluetooth conectado",
    "Bluetooth rules need Bluetooth access (System Settings ▸ Privacy)": "As regras de Bluetooth precisam de acesso ao Bluetooth (Ajustes do Sistema ▸ Privacidade)",
    "CPU load": "Carga da CPU",
    "CPU threshold": "Limite de CPU",
    "Camera in use": "Câmera em uso",
    "Change…": "Alterar…",
    "Charging": "Carregando",
    "Check for Updates…": "Verificar atualizações…",
    "Closed-display mode": "Modo com tela fechada",
    "Contacting the helper…": "Entrando em contato com o assistente…",
    "Create a virtual display": "Criar uma tela virtual",
    "Currently paused from the menu bar.": "Pausado atualmente pela barra de menus.",
    "Custom Duration…": "Duração personalizada…",
    "During calendar events": "Durante eventos do calendário",
    "Export Settings…": "Exportar ajustes…",
    "Import Settings…": "Importar ajustes…",
    "External display connected": "Tela externa conectada",
    "Fix…": "Corrigir…",
    "GNU GPL v3.0": "GNU GPL v3.0",
    "Gaming & Streaming": "Jogos e streaming",
    "Gaming & Streaming…": "Jogos e streaming…",
    "Get Started": "Começar",
    "Global shortcut": "Atalho global",
    "Headless Setup": "Configuração sem monitor",
    "Headless Setup…": "Configuração sem monitor…",
    "Headless virtual display (experimental)": "Tela virtual sem monitor (experimental)",
    "Helper installed and responding": "Assistente instalado e respondendo",
    "HiDPI (Retina)": "HiDPI (Retina)",
    "How do you use your Mac?": "Como você usa o seu Mac?",
    "Install Helper…": "Instalar assistente…",
    "Install…": "Instalar…",
    "Jitter test": "Teste de jitter",
    "Keep a disk spinning": "Manter um disco girando",
    "Keep awake with lid closed": "Manter acordado com a tampa fechada",
    "Keep awake with the lid closed": "Manter acordado com a tampa fechada",
    "Keep awake": "Manter acordado",
    "Keep me active": "Manter-me ativo",
    "Keeping the Mac awake now": "Mantendo o Mac acordado agora",
    "Keepresso decisions": "Decisões do Keepresso",
    "Measuring, about 10 seconds…": "Medindo, cerca de 10 segundos…",
    "Microphone in use": "Microfone em uso",
    "Network & Devices": "Rede e dispositivos",
    "Network activity": "Atividade de rede",
    "Network threshold": "Limite de rede",
    "No Wi-Fi network joined": "Nenhuma rede Wi-Fi conectada",
    "No apps running": "Nenhum app em execução",
    "No conditions yet, so the Mac can sleep.": "Ainda não há condições, então o Mac pode suspender.",
    "No conditions yet. Add some in Preferences ▸ Triggers.": "Ainda não há condições. Adicione algumas em Preferências ▸ Gatilhos.",
    "No days selected means every day.": "Não selecionar nenhum dia significa todos os dias.",
    "No paired devices": "Nenhum dispositivo pareado",
    "No session activity yet.": "Ainda não há atividade de sessão.",
    "No volumes mounted": "Nenhum volume montado",
    "Not available on this macOS version.": "Não disponível nesta versão do macOS.",
    "Nothing is holding the Mac awake right now.": "No momento, nada está mantendo o Mac acordado.",
    "Notify when a session ends": "Notificar quando uma sessão terminar",
    "Notify when auto-pausing and resuming": "Notificar ao pausar e retomar automaticamente",
    "On AC power": "Na energia elétrica",
    "On battery": "Na bateria",
    "On session end": "Ao terminar a sessão",
    "Only while brewing": "Somente durante o preparo",
    "Open Login Items": "Abrir Itens de Login",
    "Open Settings": "Abrir Ajustes",
    "Overnight (22:00-6:00)": "Durante a noite (22:00-6:00)",
    "Pause AWDL automatically while gaming": "Pausar o AWDL automaticamente ao jogar",
    "Pause AWDL now": "Pausar o AWDL agora",
    "Pause Triggers": "Pausar gatilhos",
    "Pause on low battery": "Pausar com bateria baixa",
    "Play a sound": "Reproduzir um som",
    "Playing a game": "Jogando",
    "Power & Display": "Energia e tela",
    "Presets": "Predefinições",
    "Prevent display sleep": "Impedir a suspensão da tela",
    "Prevent system sleep": "Impedir a suspensão do sistema",
    "Process is running": "O processo está em execução",
    "Quit Keepresso": "Sair do Keepresso",
    "Reduce lag and jitter": "Reduzir lag e jitter",
    "Reinstall Helper": "Reinstalar assistente",
    "Remind me it's still on": "Lembrar que ainda está ativo",
    "Repeat the reminder": "Repetir o lembrete",
    "Restore default presets": "Restaurar predefinições padrão",
    "Resume AWDL after leaving the game": "Retomar o AWDL ao sair do jogo",
    "Resume Triggers": "Retomar gatilhos",
    "Session end": "Fim da sessão",
    "Set Up…": "Configurar…",
    "Show Welcome Screen…": "Mostrar tela de boas-vindas…",
    "Show countdown in menu bar": "Mostrar contagem regressiva na barra de menus",
    "Start keep-awake on launch": "Iniciar a vigília ao abrir",
    "The helper needs attention": "O assistente precisa de atenção",
    "The test couldn't run. Check that you're online and try again.": "Não foi possível executar o teste. Verifique se você está on-line e tente novamente.",
    "The watchdog below should smooth this out; re-run the test with it on to confirm.": "O monitoramento abaixo deve suavizar isso; execute o teste novamente com ele ativado para confirmar.",
    "Times & days": "Horários e dias",
    "Toggle shortcut": "Atalho de alternância",
    "Triggers paused. Controlling manually for now.": "Gatilhos pausados. Controle manual por enquanto.",
    "Until a Time…": "Até um horário…",
    "VPN connected": "VPN conectada",
    "View on GitHub": "Ver no GitHub",
    "Volume is mounted": "O volume está montado",
    "Watch a folder for downloads…": "Monitorar uma pasta para downloads…",
    "While frontmost": "Enquanto em primeiro plano",
    "While running": "Enquanto em execução",
    "Work hours (weekdays 9:00-18:00)": "Horário de trabalho (dias úteis 9:00-18:00)",
    "Audio playing": "Áudio em reprodução",
    "Paused": "Em pausa",
    "Brewing": "Preparando",
    "Idle": "Inativo",
    "System can sleep": "O sistema pode suspender",
    "No conditions yet": "Ainda não há condições",
    "Battery below %d%%, letting the Mac sleep": "Bateria abaixo de %d%%, deixando o Mac suspender",
    "Stops in %@": "Para em %@",
    "Awake for %@": "Acordado há %@",
    "Active": "Ativo",
    "Held by %@": "Mantido por %@",
    "Waiting for any condition": "Aguardando qualquer condição",
    "Waiting on %@": "Aguardando %@",
    "%d condition": "%d condição",
    "%d conditions": "%d condições",
    "Approve Keepresso again in System Settings.": "Aprove o Keepresso novamente em Ajustes do Sistema.",
    "The helper isn't responding; reinstall it.": "O assistente não está respondendo; reinstale-o.",
    "Waiting for a game to come to the front": "Aguardando um jogo passar para o primeiro plano",
    "AWDL paused": "AWDL pausado",
    "AWDL paused for gaming": "AWDL pausado para jogos",
    "Game closed, AWDL back in %ds": "Jogo fechado, o AWDL volta em %d s",
    "Latency looks clean.": "A latência parece limpa.",
    "Once-a-second spikes: this looks like AWDL.": "Picos uma vez por segundo: isso parece ser o AWDL.",
    "Spiky, but not on AWDL's cadence (congestion or a weak signal).": "Com picos, mas não na cadência do AWDL (congestionamento ou sinal fraco).",
    "Not enough replies to judge.": "Respostas insuficientes para avaliar.",
    "AWDL is on right now": "O AWDL está ativado agora",
    "AWDL is off right now": "O AWDL está desativado agora",
    "AWDL state unknown": "Estado do AWDL desconhecido",
    "Agentic coding": "Programação com agentes",
    "Stay awake while Claude, Codex, or Grok is running.": "Continue acordado enquanto o Claude, o Codex ou o Grok estiver em execução.",
    "Gaming & streaming": "Jogos e streaming",
    "Stay awake while a game or cloud-gaming app is in front.": "Continue acordado enquanto um jogo ou app de cloud gaming estiver em primeiro plano.",
    "Meetings & calls": "Reuniões e chamadas",
    "Stay awake whenever the camera or microphone is in use.": "Continue acordado sempre que a câmera ou o microfone estiver em uso.",
    "Remote access": "Acesso remoto",
    "Stay awake while someone is connected over SSH.": "Continue acordado enquanto alguém estiver conectado por SSH.",
    "Keep it manual for now": "Manter manual por enquanto",
    "Just toggle keep-awake yourself, and set up your own triggers later in Preferences.": "Ative e desative a vigília você mesmo, e configure seus próprios gatilhos depois em Preferências.",
    "Launch at login": "Abrir no login",
    "Start Keepresso automatically when you log in.": "Iniciar o Keepresso automaticamente ao fazer login.",
    "Notifications": "Notificações",
    "Let Keepresso remind you when a long session is still keeping the Mac awake.": "Deixe o Keepresso lembrar você quando uma sessão longa ainda estiver mantendo o Mac acordado.",
    "Approve a small helper once and the privileged extras (lid-closed mode, AWDL pausing) never ask for your password again. Set and forget; removable in Preferences.": "Aprove um pequeno assistente uma vez e os recursos com privilégios (modo com tampa fechada, pausa do AWDL) nunca mais pedirão sua senha. Configure e esqueça; removível em Preferências.",
    "Location access (Wi-Fi rules)": "Acesso à localização (regras de Wi-Fi)",
    "Bluetooth access (device rules)": "Acesso ao Bluetooth (regras de dispositivo)",
    "Calendar access (event rule)": "Acesso ao calendário (regra de evento)",
    "Keepresso launches at login, so it returns after a reboot.": "O Keepresso abre no login, então ele volta depois de uma reinicialização.",
    "Keepresso isn't set to launch at login, so it won't run after an unattended reboot.": "O Keepresso não está configurado para abrir no login, então não será executado após uma reinicialização sem supervisão.",
    "Turn on “Launch at login” in Keepresso's settings.": "Ative “Abrir no login” nos ajustes do Keepresso.",
    "Keepresso can read the current Wi-Fi network name for your Wi-Fi triggers.": "O Keepresso pode ler o nome da rede Wi-Fi atual para os seus gatilhos de Wi-Fi.",
    "Without Location access Keepresso can't read the Wi-Fi network name, so Wi-Fi triggers won't match.": "Sem acesso à localização, o Keepresso não consegue ler o nome da rede Wi-Fi, então os gatilhos de Wi-Fi não vão corresponder.",
    "Allow Location access for Keepresso.": "Permita o acesso à localização para o Keepresso.",
    "Keepresso can see which paired devices are connected for your Bluetooth triggers.": "O Keepresso pode ver quais dispositivos pareados estão conectados para os seus gatilhos de Bluetooth.",
    "Without Bluetooth access Keepresso can't see paired devices, so Bluetooth triggers won't match.": "Sem acesso ao Bluetooth, o Keepresso não consegue ver dispositivos pareados, então os gatilhos de Bluetooth não vão corresponder.",
    "Allow Bluetooth access for Keepresso.": "Permita o acesso ao Bluetooth para o Keepresso.",
    "Keepresso can see when a calendar event is in progress for your calendar trigger.": "O Keepresso pode ver quando um evento do calendário está em andamento para o seu gatilho de calendário.",
    "Without full calendar access Keepresso can't see events, so the calendar trigger won't match.": "Sem acesso completo ao calendário, o Keepresso não consegue ver eventos, então o gatilho de calendário não vai corresponder.",
    "Allow full calendar access for Keepresso.": "Permita o acesso completo ao calendário para o Keepresso.",
    "Keepresso can post the “still brewing” reminder.": "O Keepresso pode enviar o lembrete de “ainda preparando”.",
    "Notifications are off, so the “still brewing” reminder can't appear.": "As notificações estão desativadas, então o lembrete de “ainda preparando” não pode aparecer.",
    "Allow notifications for Keepresso.": "Permita as notificações para o Keepresso.",
    "Above %d%%": "Acima de %d%%",
    "Above %@": "Acima de %@",
    "Version %@": "Versão %@",
    "Remove “%@”": "Remover “%@”",
    "On current Wi-Fi (%@)": "Na rede Wi-Fi atual (%@)",
    "keep the Mac awake with the lid closed": "manter o Mac acordado com a tampa fechada",
    "switch closed-display mode with the session": "alternar o modo com tela fechada com a sessão",
    "pause AWDL (turn off the Wi-Fi AirDrop/Handoff radio hops)": "pausar o AWDL (desativar os saltos de rádio Wi-Fi do AirDrop/Handoff)",
    "macOS is asking for your administrator password to %@. The dialog may be titled “osascript”: that's Keepresso running the command, and nothing else is changed. To stop these prompts for good, install the administrator helper (Preferences ▸ General).": "O macOS está pedindo sua senha de administrador para %@. A caixa de diálogo pode se chamar “osascript”: é o Keepresso executando o comando, e nada mais é alterado. Para acabar de vez com esses pedidos, instale o assistente de administrador (Preferências ▸ Geral).",
    "Keepresso keeps your Mac awake on your terms. It lives in the menu bar near the clock, with no Dock icon. Click its cup any time to start or stop.": "O Keepresso mantém o seu Mac acordado do seu jeito. Ele fica na barra de menus perto do relógio, sem ícone no Dock. Clique na xícara a qualquer momento para iniciar ou parar.",
    "Pick one to set up matching triggers, or keep it manual and add your own later. You can change this any time in Preferences.": "Escolha uma opção para configurar os gatilhos correspondentes, ou mantenha manual e adicione os seus depois. Você pode mudar isso a qualquer momento em Preferências.",
    "Activation is controlled by triggers.\nEdit them in Preferences.": "A ativação é controlada por gatilhos.\nEdite-os em Preferências.",
    "Why each session started or stopped, newest first. Kept in memory; clears on relaunch.": "Por que cada sessão começou ou terminou, mais recentes primeiro. Mantido na memória; é apagado ao reabrir o app.",
    "Every app's live power assertions, not just Keepresso's, the same data pmset -g assertions prints.": "As afirmações de energia ativas de todos os apps, não só as do Keepresso, os mesmos dados que o comando pmset -g assertions exibe.",
    "Lets the Mac sleep once battery charge drops below this level, even mid-session, so it doesn't run flat.": "Deixa o Mac suspender quando a carga da bateria cai abaixo desse nível, mesmo no meio de uma sessão, para que ela não se esgote.",
    "Shows the remaining time next to the menu-bar icon during a timed session.": "Mostra o tempo restante ao lado do ícone da barra de menus durante uma sessão com tempo definido.",
    "Reopen the first-run welcome, with quick one-click setup for how you use your Mac.": "Reabre a tela de boas-vindas da primeira execução, com configuração rápida em um clique de acordo com o uso do seu Mac.",
    "If that time already passed today, it means tomorrow.": "Se esse horário já passou hoje, quer dizer amanhã.",
    "Runs past midnight into the next day.": "Continua depois da meia-noite até o dia seguinte.",
    "Keeps the Mac awake while a partial-download file (.crdownload, .download, .part, and the like) exists in the chosen folder, then lets it sleep once the download finishes. Holds for 30 seconds between files in a batch.": "Mantém o Mac acordado enquanto existir um arquivo de download parcial (.crdownload, .download, .part e semelhantes) na pasta escolhida, e depois deixa suspender assim que o download terminar. Mantém-se por 30 segundos entre arquivos de um mesmo lote.",
    "Stays awake on battery too; the display turns off when the lid closes. Turn it off before putting it in a bag.": "Continua acordado também na bateria; a tela se apaga quando a tampa fecha. Desative antes de guardar o Mac em uma bolsa.",
    "The calendar rule needs Calendar access (System Settings ▸ Privacy)": "A regra de calendário precisa de acesso ao Calendário (Ajustes do Sistema ▸ Privacidade)",
    "Wi-Fi rules need Location access (System Settings ▸ Privacy)": "As regras de Wi-Fi precisam de acesso à localização (Ajustes do Sistema ▸ Privacidade)",
    "Checks an always-on Mac (e.g. a headless Mac mini) needs. Keepresso can read these but can't change the system ones, so use the links and commands below.": "Verificações que um Mac sempre ligado (por exemplo, um Mac mini sem monitor) precisa. O Keepresso pode ler esses ajustes, mas não pode alterar os do sistema, então use os links e comandos abaixo.",
    "macOS hops the Wi-Fi radio off-channel for AWDL about once a second, which shows up as ping spikes mid-game or mid-stream. Diagnose it here, and pause AWDL for the session if it's the culprit.": "O macOS tira o rádio Wi-Fi do canal para o AWDL cerca de uma vez por segundo, o que aparece como picos de ping no meio de um jogo ou de uma transmissão. Diagnostique isso aqui e pause o AWDL para a sessão se ele for o culpado.",
    "Pings 1.1.1.1 five times a second for 10 seconds and checks whether latency spikes on AWDL's once-a-second cadence.": "Envia ping para 1.1.1.1 cinco vezes por segundo durante 10 segundos e verifica se a latência tem picos na cadência de uma vez por segundo do AWDL.",
    "Counts only while a game (or a cloud-gaming app) is the active window, not just running in the background. Keeps holding for 5 minutes after you switch away.": "Conta apenas enquanto um jogo (ou um app de cloud gaming) é a janela ativa, não apenas em execução em segundo plano. Continua ativo por 5 minutos depois que você muda de janela.",
    "How long the pause lingers after the game stops being the active window, so a quick alt-tab doesn't flap the radios. Shorter brings AirDrop and Handoff back faster; longer rides out launchers and loading screens.": "Por quanto tempo a pausa continua depois que o jogo deixa de ser a janela ativa, para que um alt-tab rápido não fique ligando e desligando os rádios. Um tempo mais curto traz o AirDrop e o Handoff de volta mais rápido; um tempo mais longo aguenta launchers e telas de carregamento.",
    "Posts a notification when a game is detected and AWDL pauses, and again when it resumes. A notice that your administrator password is needed is always sent (even behind a fullscreen game), regardless of this switch.": "Envia uma notificação quando um jogo é detectado e o AWDL pausa, e outra quando ele retoma. Um aviso de que a sua senha de administrador é necessária é sempre enviado (mesmo atrás de um jogo em tela cheia), independentemente desse controle.",
    "Install a small helper service so closed-display mode and AWDL pausing never ask for your password again. macOS will ask you to allow it in System Settings, once; nothing else changes.": "Instale um pequeno serviço assistente para que o modo com tela fechada e a pausa do AWDL nunca mais peçam sua senha. O macOS vai pedir para você permitir em Ajustes do Sistema, uma única vez; nada mais muda.",
    "One step left, in System Settings: under General ▸ Login Items & Extensions (“Login Items” on older macOS), find Keepresso in the “Allow in the Background” list and turn its switch ON. macOS asks for your administrator password once; this updates by itself when you're done.": "Falta um passo em Ajustes do Sistema: em Geral ▸ Itens de Login e Extensões (“Itens de Login” em versões mais antigas do macOS), encontre o Keepresso na lista “Permitir em Segundo Plano” e ative o controle. O macOS pede sua senha de administrador uma vez; isso se atualiza sozinho quando você terminar.",
    "Turns the pause on right now and keeps it on until you turn it off or quit Keepresso (it isn't tied to whether a keep-awake session is brewing). While it's on, AirDrop, Handoff, Sidecar, and Continuity Camera take a break, and the once-a-second lag spikes stop. Everything comes back the moment you turn it off or quit Keepresso; even if the app crashes, macOS is restored automatically. With the administrator helper installed the switch is always instant and silent; without it, macOS asks for your password once per launch (the system dialog may show “osascript”, which is Keepresso running the command).": "Ativa a pausa agora mesmo e mantém ativada até você desativar ou sair do Keepresso (não depende de haver uma sessão de vigília em preparo). Enquanto estiver ativa, o AirDrop, o Handoff, o Sidecar e a Continuity Camera ficam em pausa, e os picos de lag de uma vez por segundo param. Tudo volta no momento em que você desativa ou sai do Keepresso; mesmo que o app trave, o macOS é restaurado automaticamente. Com o assistente de administrador instalado, o controle é sempre instantâneo e silencioso; sem ele, o macOS pede sua senha uma vez a cada abertura (a caixa de diálogo do sistema pode mostrar “osascript”, que é o Keepresso executando o comando).",
    "Watches for a game (or a cloud-gaming app like GeForce NOW) as the active window and pauses AWDL on its own, then lifts the pause a little after you switch away (the delay below). It only counts while the game is in front and in use, not just running in the background. Without the administrator helper, turning this on asks for your password once per app run, right now rather than mid-game; with the helper it never asks at all. No trigger setup needed: leave this on and forget it.": "Fica de olho em um jogo (ou um app de cloud gaming como o GeForce NOW) como a janela ativa e pausa o AWDL sozinho, depois libera a pausa um pouco depois que você muda de janela (o atraso abaixo). Só conta enquanto o jogo está em primeiro plano e em uso, não apenas em execução em segundo plano. Sem o assistente de administrador, ativar isso pede sua senha uma vez por execução do app, agora mesmo em vez de no meio do jogo; com o assistente, nunca pede. Não precisa configurar gatilhos: deixe ativado e esqueça.",
    "Helper installed. Closed-display mode and AWDL pausing work without password prompts.": "Assistente instalado. O modo com tela fechada e a pausa do AWDL funcionam sem pedidos de senha.",
    "Pause AWDL to steady your connection, and test your jitter, in Gaming & Streaming.": "Pause o AWDL para estabilizar sua conexão e teste o jitter em Jogos e streaming.",
    "General": "Geral",
    "Triggers": "Gatilhos",
    "Reminder": "Lembrete",
    "Disk": "Disco",
    "Activity": "Atividade",
    "Indefinitely": "Indefinidamente",
    "Update Session": "Atualizar sessão",
    "Start": "Iniciar",
    "Met, in grace period": "Atendida, em tolerância",
    "Met": "Atendida",
    "Not met": "Não atendida",
    "Copied!": "Copiado!",
    "Copy command": "Copiar comando",
    "OK": "OK",
    "Needs attention": "Precisa de atenção",
    "Tip": "Dica",
    "Unknown": "Desconhecido",
    "Checking the helper": "Verificando o assistente",
    "One approval needed": "É preciso uma aprovação",
    "The helper needs a reinstall": "O assistente precisa ser reinstalado",
    "All set": "Tudo pronto",
    "Making sure Keepresso's helper is awake and answering.": "Verificando se o assistente do Keepresso está ativo e respondendo.",
    "macOS turned the helper's background switch off, so it needs your approval again: in System Settings, under Login Items & Extensions, find Keepresso in App Background Activity and turn it on. Everything is password-free again right after.": "O macOS desativou o controle de segundo plano do assistente, então ele precisa da sua aprovação de novo: em Ajustes do Sistema, em Itens de Login e Extensões, encontre o Keepresso em Atividade em Segundo Plano dos Apps e ative. Logo depois, tudo volta a funcionar sem senha.",
    "Keepresso repaired the helper's registration, but macOS keeps disabling it. An old copy of Keepresso in the Trash is the usual cause: empty the Trash, then reinstall the helper below. Nothing else about your setup changes.": "O Keepresso reparou o registro do assistente, mas o macOS continua desativando-o. Uma cópia antiga do Keepresso na Lixeira costuma ser a causa: esvazie a Lixeira e depois reinstale o assistente abaixo. Nada mais na sua configuração muda.",
    "The helper is back. Closed-display mode and AWDL pausing work without password prompts again.": "O assistente está de volta. O modo com tela fechada e a pausa do AWDL voltam a funcionar sem pedidos de senha.",
    "Waiting for the switch in System Settings; this updates by itself.": "Aguardando o controle em Ajustes do Sistema; isso se atualiza sozinho.",
    "Record": "Gravar",
    "Press keys…": "Pressione as teclas…",
    "Other process, e.g. rsync": "Outro processo, por exemplo, rsync",
    "Export Keepresso Settings": "Exportar ajustes do Keepresso",
    "Import Keepresso Settings": "Importar ajustes do Keepresso",
    "Exported to %@.": "Exportado para %@.",
    "Settings imported.": "Ajustes importados.",
    "Couldn't export settings: %@": "Não foi possível exportar os ajustes: %@",
    "Couldn't read the file: %@": "Não foi possível ler o arquivo: %@",
    "That file isn't a Keepresso settings export.": "Esse arquivo não é uma exportação de ajustes do Keepresso.",
    "That export was made by a newer version of Keepresso.": "Essa exportação foi feita por uma versão mais recente do Keepresso.",
    "Save current rules as…": "Salvar regras atuais como…",
    "A recurring notification every interval while a session runs, so a Mac left awake keeps reminding you.": "Uma notificação recorrente a cada intervalo enquanto uma sessão está em execução, para que um Mac deixado acordado continue lembrando você.",
    "A one-time notification once a session has run this long, in case you forget the Mac is awake.": "Uma notificação única quando uma sessão atingir essa duração, caso você esqueça que o Mac está acordado.",
    "Watch": "Monitorar",
    "Keep awake while downloads are in progress in this folder.": "Mantém acordado enquanto há downloads em andamento nesta pasta.",
    "Keep Awake": "Manter acordado",
    "Choose a folder on the disk you want to keep spun up.": "Escolha uma pasta no disco que você quer manter girando.",
    "Keepresso needs a new approval": "O Keepresso precisa de uma nova aprovação",
    "macOS turned Keepresso's background switch off. Turn it back on under Login Items & Extensions in System Settings to keep the password-free helper.": "O macOS desativou o controle de segundo plano do Keepresso. Ative-o novamente em Itens de Login e Extensões em Ajustes do Sistema para manter o assistente sem senha.",
    "Keepresso needs your password": "O Keepresso precisa da sua senha",
    "Enter your administrator password to switch closed-display mode on for this session.": "Digite sua senha de administrador para ativar o modo com tela fechada nesta sessão.",
    "Enter your administrator password to pause AWDL for this game.": "Digite sua senha de administrador para pausar o AWDL para este jogo.",
    "Game detected": "Jogo detectado",
    "Pausing AWDL to steady your connection.": "Pausando o AWDL para estabilizar sua conexão.",
    "AWDL resumed": "AWDL retomado",
    "The game closed; AirDrop, Handoff and Continuity are back.": "O jogo foi fechado; o AirDrop, o Handoff e o Continuity estão de volta.",
    "This copy of Keepresso isn't in the Applications folder, so it leaves the helper alone. Install from /Applications.": "Esta cópia do Keepresso não está na pasta Aplicativos, então ela não mexe no assistente. Instale a partir de /Applications.",
    "The helper wasn't found inside the app. Reinstall Keepresso and try again.": "O assistente não foi encontrado dentro do app. Reinstale o Keepresso e tente novamente.",
    "The helper couldn't be registered.": "Não foi possível registrar o assistente.",
    "The helper couldn't be removed: %@": "Não foi possível remover o assistente: %@",
    "macOS still reports the helper as registered. Try again, or restart the Mac.": "O macOS ainda informa o assistente como registrado. Tente novamente ou reinicie o Mac.",
    "Removed. System Settings may keep showing Keepresso under App Background Activity until macOS refreshes its list; restarting the Mac clears the leftover row.": "Removido. Ajustes do Sistema pode continuar mostrando o Keepresso em Atividade em Segundo Plano dos Apps até o macOS atualizar a lista; reiniciar o Mac remove a linha residual.",
    "macOS is refusing the helper's registration outright. Reinstall the helper; if that doesn't take, restart the Mac and try once more.": "O macOS está recusando totalmente o registro do assistente. Reinstale o assistente; se isso não resolver, reinicie o Mac e tente mais uma vez.",
    "The helper isn't responding. If an old copy of Keepresso is in the Trash, empty the Trash first: macOS keeps disabling the helper while one is there. Then reinstall the helper.": "O assistente não está respondendo. Se houver uma cópia antiga do Keepresso na Lixeira, esvazie a Lixeira primeiro: o macOS continua desativando o assistente enquanto ela estiver lá. Depois, reinstale o assistente.",
    "Old copy stuck in the Trash": "Cópia antiga presa na Lixeira",
    "An old copy of Keepresso in the Trash keeps the background helper from working. Please delete it from the Trash, or empty the Trash.": "Uma cópia antiga do Keepresso na Lixeira impede que o assistente em segundo plano funcione. Exclua-a da Lixeira ou esvazie a Lixeira.",
    "Language": "Idioma",
    "App language": "Idioma do app",
    "Follow System": "Seguir o sistema",
    "%d h %d min": "%d h %d min",
    "%d h": "%d h",
    "%d min": "%d min",
    "%d:%02d": "%d:%02d",
    "%ds": "%d s",
    "%d:%02d:%02d": "%d:%02d:%02d",
    "Keepresso: paused, battery low": "Keepresso: em pausa, bateria baixa",
    "Keepresso: brewing": "Keepresso: preparando",
    "Keepresso: idle": "Keepresso: inativo",
    "1920 × 1080": "1920 × 1080",
    "2560 × 1440": "2560 × 1440",
    "2880 × 1620": "2880 × 1620",
    "3840 × 2160 (4K)": "3840 × 2160 (4K)",
    "Stop in": "Parar em",
    "Quick stop shortcuts": "Atalhos de parada rápida",
    "Add Shortcut": "Adicionar atalho",
    "Shortcut %d": "Atalho %d",
    "Remove shortcut": "Remover atalho",
    "Warn before a timed session ends": "Avisar antes de uma sessão temporizada terminar",
    "Warn": "Avisar",
    "1 minute before": "1 minuto antes",
    "2 minutes before": "2 minutos antes",
    "5 minutes before": "5 minutos antes",
    "10 minutes before": "10 minutos antes",
    "AI agents": "Agentes de IA",
    "AI agent is working": "Um agente de IA está trabalhando",
    "Keeps the Mac awake while a coding-agent session (claude, codex, gemini, aider, and the like) is actively working, judged by its CPU use, and lets it sleep once every session has gone idle for the grace period. The menu lists each detected session. A freshly started session can take a few seconds to read as working.": "Mantém o Mac acordado enquanto uma sessão de agente de programação (claude, codex, gemini, aider e afins) está realmente trabalhando, a julgar pelo uso de CPU, e o deixa dormir quando todas as sessões ficaram ociosas pelo período de tolerância. O menu lista cada sessão detectada. Uma sessão recém-iniciada pode levar alguns segundos para aparecer como trabalhando.",
    "Idle grace period": "Tolerância após ociosidade",
    "Instantly": "Imediatamente",
    "10 minutes": "10 minutos",
    "working": "trabalhando",
    "idle": "inativo",
    "+%d more": "+%d mais",
    'Two independent switches. Preventing system sleep keeps the Mac itself running: work finishes, downloads complete, and it stays reachable over the network, while the screen is still free to turn off. Preventing display sleep also keeps the screen lit, which is what you want for a dashboard or a video, and what drains a battery fastest. Most setups want system sleep prevented and display sleep left alone.': 'Dois interruptores independentes. Impedir a suspensão do sistema mantém o próprio Mac funcionando: o trabalho termina, os downloads são concluídos e ele continua acessível pela rede, enquanto a tela ainda pode se apagar livremente. Impedir a suspensão da tela também a mantém acesa, o que é útil para um painel ou um vídeo, e é o que mais consome a bateria. Na maioria dos casos, o ideal é impedir a suspensão do sistema e deixar a da tela como está.',
    "“Launch at login” starts Keepresso itself when you log in, so the cup is always in the menu bar. “Start keep-awake on launch” goes further and begins a session right away, using the default duration, for an always-on Mac that shouldn't need a rule to stay up. It's ignored while triggers are controlling activation, since your conditions decide then.": '“Abrir no login” abre o próprio Keepresso quando você entra na sua conta, para que a xícara esteja sempre na barra de menus. “Iniciar a vigília ao abrir” vai além e começa uma sessão imediatamente, usando a duração padrão, para um Mac sempre ligado que não deveria precisar de uma regra para continuar acordado. Isso é ignorado enquanto os gatilhos estão controlando a ativação, já que nesse caso são suas condições que decidem.',
    'Starts a session as soon as Keepresso launches.': 'Inicia uma sessão assim que o Keepresso é aberto.',
    "System-wide, so it starts or stops keep-awake whatever app you're in. It needs at least one modifier key (Command, Option, Control, or Shift) so it can't fire while you're typing. Recording it asks for no Accessibility or Input Monitoring permission.": 'Funciona em todo o sistema, então inicia ou para a vigília não importa em qual app você esteja. Precisa de pelo menos uma tecla modificadora (Comando, Opção, Control ou Shift) para que não seja acionado enquanto você digita. Gravá-lo não pede permissão de Acessibilidade nem de Monitoramento de Entrada.',
    'Starts or stops keep-awake from any app.': 'Inicia ou para a vigília a partir de qualquer app.',
    "Fifteen languages are available. Changing this relaunches Keepresso, so the menu, every window, and notifications all switch together instead of drifting apart. Set it back to “Follow System” to follow your Mac's language again.": 'Há quinze idiomas disponíveis. Alterar isso reabre o Keepresso para que o menu, todas as janelas e as notificações mudem juntos, em vez de ficarem dessincronizados. Volte para “Seguir o sistema” para acompanhar de novo o idioma do seu Mac.',
    'Keepresso follows your system language by default.': 'Por padrão, o Keepresso segue o idioma do sistema.',
    'A small system service for the two switches that need administrator rights: closed-display mode below, and AWDL pausing in Gaming & Streaming. Without it, macOS asks for your password once per app run. With it, both are instant and silent: macOS asks once, when you approve the helper under Login Items, and the approval survives restarts and updates. It can only flip those specific switches, everything it changes is restored if Keepresso quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list; the status shown here is the real one.': 'Um pequeno serviço do sistema para os dois controles que precisam de privilégios de administrador: o modo com tela fechada abaixo e a pausa do AWDL em Jogos e streaming. Sem ele, o macOS pede sua senha uma vez a cada execução do app. Com ele, os dois são instantâneos e silenciosos: o macOS pede uma vez, quando você aprova o assistente em Itens de Login, e a aprovação sobrevive a reinicializações e atualizações. Ele só pode alternar esses controles específicos, tudo que ele altera é restaurado se o Keepresso for fechado ou travar, e você pode removê-lo aqui a qualquer momento. Ele também coloca a ferramenta de linha de comando keepresso no seu PATH (instalações via Homebrew já a têm). Depois da remoção, Ajustes do Sistema pode continuar mostrando uma linha desatualizada em Itens de Login até o macOS atualizar a lista; o status mostrado aqui é o real.',
    'Handles the privileged switches for Keepresso, with no password prompts.': 'Cuida dos controles com privilégios do Keepresso, sem pedidos de senha.',
    "Keeping the Mac awake stops it sleeping, but it doesn't reset app-level or enterprise idle detection: remote-desktop and VDI sessions, meeting presence (Teams, Slack), and corporate idle-logout can still mark you away or log you out. This tells macOS you're active as well, which those do notice. It only steps in once you've been idle a few seconds, so it never nudges the pointer while you're using the Mac or gaming. Off by default, and some managed Macs flag simulated activity, so check your policy first.": 'Manter o Mac acordado impede que ele durma, mas não redefine a detecção de inatividade em nível de app ou corporativa: sessões de área de trabalho remota e VDI, presença em reuniões (Teams, Slack) e o logout automático corporativo por inatividade ainda podem marcar você como ausente ou encerrar sua sessão. Isso também informa ao macOS que você está ativo, algo que esses sistemas realmente percebem. Só entra em ação depois de alguns segundos de inatividade, então nunca move o ponteiro enquanto você está usando o Mac ou jogando. Desativado por padrão, e alguns Macs gerenciados sinalizam atividade simulada, então verifique sua política primeiro.',
    "Also tells macOS you're active, so you aren't marked away.": 'Também informa ao macOS que você está ativo, para que não seja marcado como ausente.',
    'While a session runs, the menu shows these as one-click “Stop in” buttons. Clicking one converts the running session to end that much later, so the Mac goes back to sleeping on its own without you remembering to switch it off. It continues the session rather than restarting it, and clicking another button simply replaces the countdown. Up to four, and the list stays sorted.': 'Enquanto uma sessão está em execução, o menu mostra isso como botões de um clique “Parar em”. Clicar em um faz a sessão em execução passar a terminar depois desse tempo, para que o Mac volte a dormir sozinho sem que você precise se lembrar de desativá-lo. Isso continua a sessão em vez de reiniciá-la, e clicar em outro botão simplesmente substitui a contagem regressiva. Até quatro, e a lista permanece ordenada.',
    'One-click “Stop in” buttons shown in the menu while a session runs.': 'Botões de um clique “Parar em” exibidos no menu enquanto uma sessão está em execução.',
    'A safety net for a session you forget about. If the charge falls this low, Keepresso pauses the session and lets the Mac sleep, even mid-session, and tells you why in a notification. The menu-bar cup shows the pause as a last sip of low-power yellow. Plugging in resumes it on its own. This is the same slider as the one in the menu, so the two always agree.': 'Uma rede de segurança para uma sessão que você esquece. Se a carga cair abaixo desse nível, o Keepresso pausa a sessão e deixa o Mac dormir, mesmo no meio da sessão, e explica o motivo em uma notificação. A xícara na barra de menus mostra a pausa como um último gole amarelo de bateria fraca. Conectar à energia a retoma sozinha. É o mesmo controle deslizante do menu, então os dois sempre coincidem.',
    'Lets the Mac sleep once charge drops below this level.': 'Deixa o Mac dormir quando a carga cai abaixo desse nível.',
    "Writes everything you've configured (settings, trigger rules, and presets) to a JSON file, to keep as a backup or to carry to another Mac. The file is version-stamped and checked on import, so a file from a newer Keepresso is refused rather than half-read. Importing replaces your current configuration and ends any running session.": 'Grava tudo o que você configurou (ajustes, regras de gatilhos e predefinições) em um arquivo JSON, para manter como backup ou levar para outro Mac. O arquivo tem uma marca de versão e é verificado na importação, então um arquivo de uma versão mais nova do Keepresso é recusado em vez de lido pela metade. A importação substitui a configuração atual e encerra qualquer sessão em execução.',
    'Save your settings, triggers, and presets to a JSON file.': 'Salve seus ajustes, gatilhos e predefinições em um arquivo JSON.',
    "Normally a MacBook sleeps the moment you shut the lid unless a display is attached. This keeps it running with the lid shut and nothing plugged in, on power or battery. The screen itself still turns off when the lid closes (unless an external display is attached), so it isn't lighting up uselessly inside the closed lid. It works by flipping a system setting (pmset disablesleep), so it stays in effect until you turn it off: closed and on battery, the Mac can still drain over time, so don't leave it on in a bag. “Only while brewing” ties it to the session instead, on when a keep-awake session starts, off when it ends or Keepresso quits (even after a crash). Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password, once per app run for “Only while brewing”.": 'Normalmente, um MacBook entra em suspensão assim que você fecha a tampa, a menos que uma tela esteja conectada. Isso o mantém funcionando com a tampa fechada e nada conectado, na energia elétrica ou na bateria. A própria tela ainda se apaga quando a tampa fecha (a menos que haja uma tela externa conectada), então ela não fica acesa à toa dentro da tampa fechada. Funciona alterando um ajuste do sistema (pmset disablesleep), que permanece em vigor até você desativá-lo: com a tampa fechada e na bateria, o Mac ainda pode se descarregar com o tempo, então não deixe ativado dentro de uma bolsa. “Somente durante o preparo” vincula isso à sessão: ativado quando uma sessão de vigília começa, desativado quando ela termina ou o Keepresso é fechado (mesmo após uma falha). Os dois precisam de privilégios de administrador: silencioso com o assistente de administrador instalado (veja o topo desta aba), caso contrário o macOS pede sua senha, uma vez por execução do app para “Somente durante o preparo”.',
    'Keeps running with the lid shut and no external display.': 'Continua funcionando com a tampa fechada e sem tela externa.',
    "A trigger is a condition Keepresso watches, checked once a second. With triggers on, they take over: Keepresso starts brewing the moment your conditions are met and stops when they aren't, so you never leave the Mac awake by accident. The manual switch in the menu steps aside while they're active. “Pause Triggers” in the menu bar stops them temporarily without touching your rules.": 'Um gatilho é uma condição que o Keepresso observa, verificada uma vez por segundo. Com os gatilhos ativados, eles assumem o controle: o Keepresso começa a funcionar no momento em que suas condições são atendidas e para quando deixam de ser, assim você nunca deixa o Mac acordado por acidente. O controle manual no menu dá lugar a eles enquanto estão ativos. “Pausar gatilhos” na barra de menus os interrompe temporariamente sem alterar suas regras.',
    'The listed conditions control the session instead of the manual switch.': 'As condições listadas controlam a sessão em vez do controle manual.',
    'A preset is a named bundle of trigger rules you apply in one click. The built-ins cover common setups (AI Agent, Meetings, Cloud Gaming, Remote Control, and more), and applying one replaces your current rules. Save your own rules under a name to reuse them or move between setups. Renaming a built-in makes it yours, and Keepresso stops updating it. “Restore default presets” brings back any built-in you removed.': 'Uma predefinição é um conjunto nomeado de regras de gatilhos que você aplica com um clique. As predefinições internas cobrem configurações comuns (Agente de IA, Reuniões, Jogos na nuvem, Controle remoto e mais), e aplicar uma substitui suas regras atuais. Salve suas próprias regras com um nome para reutilizá-las ou alternar entre configurações. Renomear uma predefinição interna a torna sua, e o Keepresso para de atualizá-la. “Restaurar predefinições padrão” traz de volta qualquer predefinição interna que você removeu.',
    '“any” keeps the Mac awake while at least one condition holds, so the rules pile up: add three and any of them is enough. “all” needs every one true at once, which narrows things down (on AC power and an external display connected means only while docked). Conditions are checked once a second, and Keepresso stops brewing as soon as they stop being met.': '“qualquer uma” mantém o Mac acordado enquanto pelo menos uma condição for válida, então as regras se acumulam: adicione três e basta que qualquer uma delas seja válida. “todas” exige que todas sejam verdadeiras ao mesmo tempo, o que restringe as coisas (na energia elétrica e com uma tela externa conectada significa apenas enquanto conectado a uma estação de acoplamento). As condições são verificadas uma vez por segundo, e o Keepresso para de funcionar assim que deixam de ser atendidas.',
    "Conditions Keepresso reads straight from the hardware, with no permission needed: whether you're on AC power, on battery, or charging, and whether an external display is connected. Good for a Mac that should only stay awake while it's docked or plugged in, especially combined with “all” to mean exactly that.": 'Condições que o Keepresso lê diretamente do hardware, sem precisar de permissão: se você está na energia elétrica, na bateria ou carregando, e se há uma tela externa conectada. Bom para um Mac que só deve continuar acordado enquanto está em uma estação de acoplamento ou conectado à energia, especialmente combinado com “todas” para significar exatamente isso.',
    'Conditions about what the Mac is connected to or busy with: a chosen Wi-Fi network, a VPN, a Bluetooth device such as headphones or a controller, a mounted volume, or sustained network throughput for a large download, upload, or sync. Reading Wi-Fi names needs Location permission and Bluetooth needs its own, both requested from this menu; the rest ask for nothing.': 'Condições sobre a que o Mac está conectado ou com que está ocupado: uma rede Wi-Fi escolhida, uma VPN, um dispositivo Bluetooth como fones de ouvido ou um controle, um volume montado, ou tráfego de rede sustentado para um grande download, upload ou sincronização. Ler os nomes de Wi-Fi precisa de permissão de localização, e o Bluetooth precisa da sua própria, ambas solicitadas a partir deste menu; o resto não pede nada.',
    "Conditions about what you're actually doing: an app running or frontmost, the camera or microphone in use, audio playing, a game in front, an AI agent working, a process by name, a download finishing in a folder you watch, CPU load above a threshold, a time window, or a calendar event in progress. The camera and microphone conditions read only the device's in-use signal (the green dot), never the stream, so neither asks for permission.": 'Condições sobre o que você está realmente fazendo: um app em execução ou em primeiro plano, a câmera ou o microfone em uso, áudio tocando, um jogo em primeiro plano, um agente de IA trabalhando, um processo por nome, um download terminando em uma pasta que você monitora, carga de CPU acima de um limite, uma janela de tempo, ou um evento de calendário em andamento. As condições de câmera e microfone leem apenas o sinal de uso do dispositivo (o ponto verde), nunca o fluxo, então nenhuma delas pede permissão.',
    "A nudge while a session is running, so a Mac left awake doesn't stay awake all night unnoticed. Left off, a one-time reminder tells you once, after the session has run this long. “Repeat” tells you again at every interval until you stop the session. This never stops anything itself, it only reminds you, and the sound is optional. If you'd rather the session end on its own, use a timed session or a quick-stop button instead.": 'Um lembrete enquanto uma sessão está em execução, para que um Mac deixado acordado não fique acordado a noite toda sem você perceber. Desativado, um lembrete único avisa uma vez, depois que a sessão tiver sido executada por esse tempo. “Repetir” avisa novamente a cada intervalo até você parar a sessão. Isso nunca para nada sozinho, apenas avisa você, e o som é opcional. Se preferir que a sessão termine sozinha, use uma sessão temporizada ou um botão de parada rápida.',
    "These cover the times a session ends without you: a timer expiring, trigger conditions dropping, or a low-battery pause. Stopping it yourself stays silent, since you already know. The warning is a heads-up a few minutes before a timed session runs out, so you can extend it before the Mac drops off. The action runs when the session ends: sleep the display or start the screen saver, handy for a Mac you walk away from. It's off by default so a timed session never surprises you.": 'Isso cobre os momentos em que uma sessão termina sem você: um timer expirando, condições de gatilhos deixando de valer, ou uma pausa por bateria fraca. Parar você mesmo permanece silencioso, já que você já sabe. O aviso é um heads-up alguns minutos antes de uma sessão temporizada terminar, para que você possa estendê-la antes que o Mac se desligue. A ação é executada quando a sessão termina: suspender a tela ou iniciar a proteção de tela, útil para um Mac do qual você se afasta. Ela vem desativada por padrão para que uma sessão temporizada nunca surpreenda você.',
    'Fires when a session ends on its own, not when you stop it yourself.': 'Ocorre quando uma sessão termina sozinha, não quando você mesmo a interrompe.',
    'A Mac with no monitor attached falls back to a fuzzy 1920 × 1080, which is what makes Screen Sharing and VNC look soft. This creates a higher-resolution HiDPI display in software, so the remote picture is crisp without plugging anything in. It uses a private macOS API, so treat it as experimental and expect it may break on a macOS update. A hardware HDMI or DisplayPort dummy plug does the same job with no software at all.': 'Um Mac sem monitor conectado volta para uma resolução borrada de 1920 × 1080, o que faz o Compartilhamento de Tela e o VNC parecerem borrados. Isso cria uma tela HiDPI de resolução mais alta via software, para que a imagem remota fique nítida sem conectar nada. Usa uma API privada do macOS, então trate como experimental e espere que possa parar de funcionar em uma atualização do macOS. Um conector dummy de hardware HDMI ou DisplayPort faz o mesmo trabalho sem nenhum software.',
    'For a Mac with no monitor: a sharper picture over Screen Sharing and VNC.': 'Para um Mac sem monitor: uma imagem mais nítida via Compartilhamento de Tela e VNC.',
    "Many external drives and NAS volumes park or disconnect after a few minutes idle, and the next thing that touches them stalls while they spin back up. Keepresso rewrites a tiny hidden marker file in the folder you choose, just enough activity to keep the volume awake. Pick an interval shorter than the drive's own idle timeout. This runs whenever Keepresso is running, with or without a keep-awake session, so a drive stays ready even when the Mac is free to sleep.": 'Muitos discos externos e volumes NAS entram em repouso ou se desconectam após alguns minutos de inatividade, e a próxima coisa que os acessa trava enquanto eles voltam a girar. O Keepresso reescreve um pequeno arquivo marcador oculto na pasta que você escolher, apenas atividade suficiente para manter o volume acordado. Escolha um intervalo mais curto que o tempo limite de inatividade do próprio disco. Isso é executado sempre que o Keepresso está em execução, com ou sem uma sessão de vigília, então um disco continua pronto mesmo quando o Mac pode dormir livremente.',
    'Stops an external drive or NAS from spinning down.': 'Impede que um disco externo ou NAS pare de girar.',
    '3 minutes': '3 minutos',
}


# --- Agent hooks (Claude Code connection) ---
APP.update({
    "Claude Code connected: sessions report working and waiting exactly.": "Claude Code conectado: as sessões informam com exatidão quando trabalham e quando aguardam.",
    "Connect Claude Code for exact session tracking (adds hooks to its settings).": "Conecte o Claude Code para rastreamento exato das sessões (adiciona hooks às configurações dele).",
    "Connect Claude Code": "Conectar Claude Code",
    "Claude Code's settings file couldn't be read, so it was left untouched.": "Não foi possível ler o arquivo de configurações do Claude Code, então ele foi mantido intacto.",
    "Couldn't update Claude Code's settings file.": "Não foi possível atualizar o arquivo de configurações do Claude Code.",
})
