# -*- coding: utf-8 -*-
# Brazilian Portuguese overlay for catalog_app.py: English source -> Portuguese (Brazil).
APP = {
    "Add": "Adicionar",
    "Add:": "Adicionar:",
    "Clear": "Limpar",
    "Close": "Fechar",
    "Done": "Concluído",
    "Save": "Salvar",
    "Enable": "Ativar",
    "Enabled": "Ativado",
    "Installed": "Instalado",
    "Remove": "Remover",
    "Remove condition": "Remover condição",
    "Resume": "Retomar",
    "Later": "Mais tarde",
    "Learn more": "Saiba mais",
    "Re-check": "Verificar novamente",
    "Run Test": "Executar teste",
    "Match": "Correspondência",
    "Threshold": "Limite",
    "Battery threshold": "Limite de bateria",
    "Presence": "Presença",
    "Menu bar": "Barra de menus",
    "Battery": "Bateria",
    "Welcome": "Boas-vindas",
    "Keeps the Mac running with the lid shut and no external display. This flips a system setting that needs administrator rights: silent with the administrator helper installed (Preferences ▸ General), otherwise macOS asks for your password.": "Mantém o Mac funcionando com a tampa fechada e sem tela externa. Isso muda um ajuste do sistema que exige privilégios de administrador: silencioso com o assistente de administrador instalado (Preferências ▸ Geral), caso contrário o macOS pede sua senha.",
    "Turns closed-display mode on when a keep-awake session starts and off when it ends or Keepresso quits.": "Ativa o modo com tela fechada quando uma sessão de vigília começa e desativa quando ela termina ou o Keepresso é fechado.",
    "Grace period": "Período de tolerância",
    "Section": "Seção",
    "Schedule": "Programação",
    "Set Duration": "Definir duração",
    "For": "Por",
    "From": "De",
    "To": "Até",
    "Until": "Até",
    "When": "Quando",
    "Below": "Abaixo de",
    "Power": "Energia",
    "Display": "Tela",
    "Network": "Rede",
    "Media": "Mídia",
    "Backup": "Backup",
    "Folder": "Pasta",
    "Downloads": "Downloads",
    "Touch": "Atualizar",
    "Resolution": "Resolução",
    "Startup": "Inicialização",
    "Gaming": "Jogos",
    "None": "Nenhum",
    "any": "qualquer uma",
    "all": "todas",
    "of these are true:": "destas são verdadeiras:",
    "1 minute": "1 minuto",
    "2 minutes": "2 minutos",
    "5 minutes": "5 minutos",
    "10 seconds": "10 segundos",
    "30 seconds": "30 segundos",
    "15 minutes": "15 minutos",
    "30 minutes": "30 minutos",
    "1 hour": "1 hora",
    "2 hours": "2 horas",
    "4 hours": "4 horas",
    "8 hours": "8 horas",
    "No grace": "Sem tolerância",
    "Every 1 minute": "A cada 1 minuto",
    "Every 5 minutes": "A cada 5 minutos",
    "Every 10 minutes": "A cada 10 minutos",
    "Every 30 minutes": "A cada 30 minutos",
    "Every": "A cada",
    "After": "Após",
    "Keepresso": "Keepresso",
    "About Keepresso": "Sobre o Keepresso",
    "Welcome to Keepresso": "Bem-vindo ao Keepresso",
    "Keepresso Setup": "Configuração do Keepresso",
    "Keepresso Helper": "Assistente do Keepresso",
    "Preferences": "Preferências",
    "Preferences…": "Preferências…",
    "A menu-bar app that keeps your Mac awake on your terms.": "Um app de barra de menus que mantém seu Mac acordado do seu jeito.",
    "AWDL watchdog": "Monitoramento de AWDL",
    "Activate by triggers": "Ativar por gatilhos",
    "Administrator helper": "Assistente de administrador",
    "Allow Bluetooth access…": "Permitir acesso ao Bluetooth…",
    "Allow Wi-Fi access…": "Permitir acesso ao Wi-Fi…",
    "Allow calendar access…": "Permitir acesso ao calendário…",
    "App is frontmost": "O app está em primeiro plano",
    "App is running": "O app está em execução",
    "App match & grace period": "Correspondência de app e período de tolerância",
    "Apply or remove": "Aplicar ou remover",
    "Approve…": "Aprovar…",
    "Apps & Activity": "Apps e atividade",
    "Bluetooth device connected": "Dispositivo Bluetooth conectado",
    "Bluetooth rules need Bluetooth access (System Settings ▸ Privacy)": "As regras de Bluetooth precisam de acesso ao Bluetooth (Ajustes do Sistema ▸ Privacidade)",
    "CPU load": "Carga da CPU",
    "CPU threshold": "Limite de CPU",
    "Camera in use": "Câmera em uso",
    "Change…": "Alterar…",
    "Charging": "Carregando",
    "Check for Updates…": "Verificar atualizações…",
    "Closed-display mode": "Modo com tela fechada",
    "Contacting the helper…": "Entrando em contato com o assistente…",
    "Create a virtual display": "Criar uma tela virtual",
    "Currently paused from the menu bar.": "Pausado atualmente pela barra de menus.",
    "Custom Duration…": "Duração personalizada…",
    "During calendar events": "Durante eventos do calendário",
    "Export Settings…": "Exportar ajustes…",
    "Import Settings…": "Importar ajustes…",
    "External display connected": "Tela externa conectada",
    "Fix…": "Corrigir…",
    "GNU GPL v3.0": "GNU GPL v3.0",
    "Gaming & Streaming": "Jogos e streaming",
    "Gaming & Streaming…": "Jogos e streaming…",
    "Get Started": "Começar",
    "Global shortcut": "Atalho global",
    "Headless Setup": "Configuração sem monitor",
    "Headless Setup…": "Configuração sem monitor…",
    "Headless virtual display (experimental)": "Tela virtual sem monitor (experimental)",
    "Helper installed and responding": "Assistente instalado e respondendo",
    "HiDPI (Retina)": "HiDPI (Retina)",
    "How do you use your Mac?": "Como você usa o seu Mac?",
    "Install Helper…": "Instalar assistente…",
    "Install…": "Instalar…",
    "Jitter test": "Teste de jitter",
    "Keep a disk spinning": "Manter um disco girando",
    "Keep awake with lid closed": "Manter acordado com a tampa fechada",
    "Keep awake with the lid closed": "Manter acordado com a tampa fechada",
    "Keep awake": "Manter acordado",
    "Keep me active": "Manter-me ativo",
    "Keeping the Mac awake now": "Mantendo o Mac acordado agora",
    "Keepresso decisions": "Decisões do Keepresso",
    "Measuring, about 10 seconds…": "Medindo, cerca de 10 segundos…",
    "Microphone in use": "Microfone em uso",
    "Network & Devices": "Rede e dispositivos",
    "Network activity": "Atividade de rede",
    "Network threshold": "Limite de rede",
    "No Wi-Fi network joined": "Nenhuma rede Wi-Fi conectada",
    "No apps running": "Nenhum app em execução",
    "No conditions yet, so the Mac can sleep.": "Ainda não há condições, então o Mac pode suspender.",
    "No conditions yet. Add some in Preferences ▸ Triggers.": "Ainda não há condições. Adicione algumas em Preferências ▸ Gatilhos.",
    "No days selected means every day.": "Não selecionar nenhum dia significa todos os dias.",
    "No paired devices": "Nenhum dispositivo pareado",
    "No session activity yet.": "Ainda não há atividade de sessão.",
    "No volumes mounted": "Nenhum volume montado",
    "Not available on this macOS version.": "Não disponível nesta versão do macOS.",
    "Nothing is holding the Mac awake right now.": "No momento, nada está mantendo o Mac acordado.",
    "Notify when a session ends": "Notificar quando uma sessão terminar",
    "Notify when auto-pausing and resuming": "Notificar ao pausar e retomar automaticamente",
    "On AC power": "Na energia elétrica",
    "On battery": "Na bateria",
    "On session end": "Ao terminar a sessão",
    "Only while brewing": "Somente durante o preparo",
    "Open Login Items": "Abrir Itens de Login",
    "Open Settings": "Abrir Ajustes",
    "Overnight (22:00-6:00)": "Durante a noite (22:00-6:00)",
    "Pause AWDL automatically while gaming": "Pausar o AWDL automaticamente ao jogar",
    "Pause AWDL now": "Pausar o AWDL agora",
    "Pause Triggers": "Pausar gatilhos",
    "Pause on low battery": "Pausar com bateria baixa",
    "Play a sound": "Reproduzir um som",
    "Playing a game": "Jogando",
    "Power & Display": "Energia e tela",
    "Presets": "Predefinições",
    "Prevent display sleep": "Impedir a suspensão da tela",
    "Prevent system sleep": "Impedir a suspensão do sistema",
    "Process is running": "O processo está em execução",
    "Quit Keepresso": "Sair do Keepresso",
    "Reduce lag and jitter": "Reduzir lag e jitter",
    "Reinstall Helper": "Reinstalar assistente",
    "Remind me it's still on": "Lembrar que ainda está ativo",
    "Repeat the reminder": "Repetir o lembrete",
    "Restore default presets": "Restaurar predefinições padrão",
    "Resume AWDL after leaving the game": "Retomar o AWDL ao sair do jogo",
    "Resume Triggers": "Retomar gatilhos",
    "Session end": "Fim da sessão",
    "Set Up…": "Configurar…",
    "Show Welcome Screen…": "Mostrar tela de boas-vindas…",
    "Show countdown in menu bar": "Mostrar contagem regressiva na barra de menus",
    "Start keep-awake on launch": "Iniciar a vigília ao abrir",
    "The helper needs attention": "O assistente precisa de atenção",
    "The test couldn't run. Check that you're online and try again.": "Não foi possível executar o teste. Verifique se você está on-line e tente novamente.",
    "The watchdog below should smooth this out; re-run the test with it on to confirm.": "O monitoramento abaixo deve suavizar isso; execute o teste novamente com ele ativado para confirmar.",
    "Times & days": "Horários e dias",
    "Toggle shortcut": "Atalho de alternância",
    "Triggers paused. Controlling manually for now.": "Gatilhos pausados. Controle manual por enquanto.",
    "Until a Time…": "Até um horário…",
    "VPN connected": "VPN conectada",
    "View on GitHub": "Ver no GitHub",
    "Volume is mounted": "O volume está montado",
    "Watch a folder for downloads…": "Monitorar uma pasta para downloads…",
    "While frontmost": "Enquanto em primeiro plano",
    "While running": "Enquanto em execução",
    "Work hours (weekdays 9:00-18:00)": "Horário de trabalho (dias úteis 9:00-18:00)",
    "Audio playing": "Áudio em reprodução",
    "Paused": "Em pausa",
    "Brewing": "Preparando",
    "Idle": "Inativo",
    "System can sleep": "O sistema pode suspender",
    "No conditions yet": "Ainda não há condições",
    "Battery below %d%%, letting the Mac sleep": "Bateria abaixo de %d%%, deixando o Mac suspender",
    "Stops in %@": "Para em %@",
    "Awake for %@": "Acordado há %@",
    "Active": "Ativo",
    "Held by %@": "Mantido por %@",
    "Waiting for any condition": "Aguardando qualquer condição",
    "Waiting on %@": "Aguardando %@",
    "%d condition": "%d condição",
    "%d conditions": "%d condições",
    "Approve Keepresso again in System Settings.": "Aprove o Keepresso novamente em Ajustes do Sistema.",
    "The helper isn't responding; reinstall it.": "O assistente não está respondendo; reinstale-o.",
    "Waiting for a game to come to the front": "Aguardando um jogo passar para o primeiro plano",
    "AWDL paused": "AWDL pausado",
    "AWDL paused for gaming": "AWDL pausado para jogos",
    "Game closed, AWDL back in %ds": "Jogo fechado, o AWDL volta em %d s",
    "Latency looks clean.": "A latência parece limpa.",
    "Once-a-second spikes: this looks like AWDL.": "Picos uma vez por segundo: isso parece ser o AWDL.",
    "Spiky, but not on AWDL's cadence (congestion or a weak signal).": "Com picos, mas não na cadência do AWDL (congestionamento ou sinal fraco).",
    "Not enough replies to judge.": "Respostas insuficientes para avaliar.",
    "AWDL is on right now": "O AWDL está ativado agora",
    "AWDL is off right now": "O AWDL está desativado agora",
    "AWDL state unknown": "Estado do AWDL desconhecido",
    "Agentic coding": "Programação com agentes",
    "Stay awake while Claude, Codex, or Grok is running.": "Continue acordado enquanto o Claude, o Codex ou o Grok estiver em execução.",
    "Gaming & streaming": "Jogos e streaming",
    "Stay awake while a game or cloud-gaming app is in front.": "Continue acordado enquanto um jogo ou app de cloud gaming estiver em primeiro plano.",
    "Meetings & calls": "Reuniões e chamadas",
    "Stay awake whenever the camera or microphone is in use.": "Continue acordado sempre que a câmera ou o microfone estiver em uso.",
    "Remote access": "Acesso remoto",
    "Stay awake while someone is connected over SSH.": "Continue acordado enquanto alguém estiver conectado por SSH.",
    "Keep it manual for now": "Manter manual por enquanto",
    "Just toggle keep-awake yourself, and set up your own triggers later in Preferences.": "Ative e desative a vigília você mesmo, e configure seus próprios gatilhos depois em Preferências.",
    "Launch at login": "Abrir no login",
    "Start Keepresso automatically when you log in.": "Iniciar o Keepresso automaticamente ao fazer login.",
    "Notifications": "Notificações",
    "Let Keepresso remind you when a long session is still keeping the Mac awake.": "Deixe o Keepresso lembrar você quando uma sessão longa ainda estiver mantendo o Mac acordado.",
    "Approve a small helper once and the privileged extras (lid-closed mode, AWDL pausing) never ask for your password again. Set and forget; removable in Preferences.": "Aprove um pequeno assistente uma vez e os recursos com privilégios (modo com tampa fechada, pausa do AWDL) nunca mais pedirão sua senha. Configure e esqueça; removível em Preferências.",
    "Location access (Wi-Fi rules)": "Acesso à localização (regras de Wi-Fi)",
    "Bluetooth access (device rules)": "Acesso ao Bluetooth (regras de dispositivo)",
    "Calendar access (event rule)": "Acesso ao calendário (regra de evento)",
    "Keepresso launches at login, so it returns after a reboot.": "O Keepresso abre no login, então ele volta depois de uma reinicialização.",
    "Keepresso isn't set to launch at login, so it won't run after an unattended reboot.": "O Keepresso não está configurado para abrir no login, então não será executado após uma reinicialização sem supervisão.",
    "Turn on “Launch at login” in Keepresso's settings.": "Ative “Abrir no login” nos ajustes do Keepresso.",
    "Keepresso can read the current Wi-Fi network name for your Wi-Fi triggers.": "O Keepresso pode ler o nome da rede Wi-Fi atual para os seus gatilhos de Wi-Fi.",
    "Without Location access Keepresso can't read the Wi-Fi network name, so Wi-Fi triggers won't match.": "Sem acesso à localização, o Keepresso não consegue ler o nome da rede Wi-Fi, então os gatilhos de Wi-Fi não vão corresponder.",
    "Allow Location access for Keepresso.": "Permita o acesso à localização para o Keepresso.",
    "Keepresso can see which paired devices are connected for your Bluetooth triggers.": "O Keepresso pode ver quais dispositivos pareados estão conectados para os seus gatilhos de Bluetooth.",
    "Without Bluetooth access Keepresso can't see paired devices, so Bluetooth triggers won't match.": "Sem acesso ao Bluetooth, o Keepresso não consegue ver dispositivos pareados, então os gatilhos de Bluetooth não vão corresponder.",
    "Allow Bluetooth access for Keepresso.": "Permita o acesso ao Bluetooth para o Keepresso.",
    "Keepresso can see when a calendar event is in progress for your calendar trigger.": "O Keepresso pode ver quando um evento do calendário está em andamento para o seu gatilho de calendário.",
    "Without full calendar access Keepresso can't see events, so the calendar trigger won't match.": "Sem acesso completo ao calendário, o Keepresso não consegue ver eventos, então o gatilho de calendário não vai corresponder.",
    "Allow full calendar access for Keepresso.": "Permita o acesso completo ao calendário para o Keepresso.",
    "Keepresso can post the “still brewing” reminder.": "O Keepresso pode enviar o lembrete de “ainda preparando”.",
    "Notifications are off, so the “still brewing” reminder can't appear.": "As notificações estão desativadas, então o lembrete de “ainda preparando” não pode aparecer.",
    "Allow notifications for Keepresso.": "Permita as notificações para o Keepresso.",
    "Above %d%%": "Acima de %d%%",
    "Above %@": "Acima de %@",
    "Version %@": "Versão %@",
    "Remove “%@”": "Remover “%@”",
    "On current Wi-Fi (%@)": "Na rede Wi-Fi atual (%@)",
    "keep the Mac awake with the lid closed": "manter o Mac acordado com a tampa fechada",
    "switch closed-display mode with the session": "alternar o modo com tela fechada com a sessão",
    "pause AWDL (turn off the Wi-Fi AirDrop/Handoff radio hops)": "pausar o AWDL (desativar os saltos de rádio Wi-Fi do AirDrop/Handoff)",
    "macOS is asking for your administrator password to %@. The dialog may be titled “osascript”: that's Keepresso running the command, and nothing else is changed. To stop these prompts for good, install the administrator helper (Preferences ▸ General).": "O macOS está pedindo sua senha de administrador para %@. A caixa de diálogo pode se chamar “osascript”: é o Keepresso executando o comando, e nada mais é alterado. Para acabar de vez com esses pedidos, instale o assistente de administrador (Preferências ▸ Geral).",
    "Keepresso keeps your Mac awake on your terms. It lives in the menu bar near the clock, with no Dock icon. Click its cup any time to start or stop.": "O Keepresso mantém o seu Mac acordado do seu jeito. Ele fica na barra de menus perto do relógio, sem ícone no Dock. Clique na xícara a qualquer momento para iniciar ou parar.",
    "Pick one to set up matching triggers, or keep it manual and add your own later. You can change this any time in Preferences.": "Escolha uma opção para configurar os gatilhos correspondentes, ou mantenha manual e adicione os seus depois. Você pode mudar isso a qualquer momento em Preferências.",
    "When on, the listed conditions control the session instead of the manual switch.": "Quando ativado, as condições listadas controlam a sessão em vez do controle manual.",
    "Activation is controlled by triggers.\nEdit them in Preferences.": "A ativação é controlada por gatilhos.\nEdite-os em Preferências.",
    "Why each session started or stopped, newest first. Kept in memory; clears on relaunch.": "Por que cada sessão começou ou terminou, mais recentes primeiro. Mantido na memória; é apagado ao reabrir o app.",
    "Every app's live power assertions, not just Keepresso's, the same data pmset -g assertions prints.": "As afirmações de energia ativas de todos os apps, não só as do Keepresso, os mesmos dados que o comando pmset -g assertions exibe.",
    "A system-wide keyboard shortcut that starts or stops keep-awake from any app. Needs at least one modifier key.": "Um atalho de teclado válido em todo o sistema que inicia ou para a vigília a partir de qualquer app. Precisa de pelo menos uma tecla modificadora.",
    "Lets the Mac sleep once battery charge drops below this level, even mid-session, so it doesn't run flat.": "Deixa o Mac suspender quando a carga da bateria cai abaixo desse nível, mesmo no meio de uma sessão, para que ela não se esgote.",
    "Shows the remaining time next to the menu-bar icon during a timed session.": "Mostra o tempo restante ao lado do ícone da barra de menus durante uma sessão com tempo definido.",
    "Starts a session as soon as Keepresso launches, using the default duration. Ignored while triggers are controlling activation.": "Inicia uma sessão assim que o Keepresso é aberto, usando a duração padrão. Ignorado enquanto os gatilhos estiverem controlando a ativação.",
    "Reopen the first-run welcome, with quick one-click setup for how you use your Mac.": "Reabre a tela de boas-vindas da primeira execução, com configuração rápida em um clique de acordo com o uso do seu Mac.",
    "Fires when a timed session expires, trigger conditions drop, or a low-battery pause kicks in, not when you stop it yourself. The action is off by default so a timed session never surprises you.": "Ocorre quando uma sessão com tempo definido expira, as condições dos gatilhos deixam de valer, ou entra em ação uma pausa por bateria baixa, não quando você mesmo a interrompe. A ação vem desativada por padrão para que uma sessão com tempo definido nunca surpreenda você.",
    "If that time already passed today, it means tomorrow.": "Se esse horário já passou hoje, quer dizer amanhã.",
    "Runs past midnight into the next day.": "Continua depois da meia-noite até o dia seguinte.",
    "Save your settings, triggers, and presets to a JSON file to back them up or move them to another Mac. Importing replaces your current configuration and ends any running session.": "Salve seus ajustes, gatilhos e predefinições em um arquivo JSON para fazer backup ou movê-los para outro Mac. A importação substitui a configuração atual e encerra qualquer sessão em execução.",
    "Keeps the Mac awake while a partial-download file (.crdownload, .download, .part, and the like) exists in the chosen folder, then lets it sleep once the download finishes. Holds for 30 seconds between files in a batch.": "Mantém o Mac acordado enquanto existir um arquivo de download parcial (.crdownload, .download, .part e semelhantes) na pasta escolhida, e depois deixa suspender assim que o download terminar. Mantém-se por 30 segundos entre arquivos de um mesmo lote.",
    "Writes a tiny marker file on the chosen volume periodically to stop an external drive or NAS from spinning down.": "Grava periodicamente um pequeno arquivo marcador no volume escolhido para impedir que um disco externo ou NAS pare de girar.",
    "For a Mac with no monitor: creates a higher-resolution display so Screen Sharing and VNC look crisp instead of a fuzzy 1920 × 1080. It uses a private macOS API, so treat it as experimental and expect it may break on a macOS update. A hardware HDMI or DisplayPort dummy plug is a no-software alternative.": "Para um Mac sem monitor: cria uma tela com resolução mais alta para que o Compartilhamento de Tela e o VNC fiquem nítidos em vez de um 1920 × 1080 embaçado. Usa uma API privada do macOS, então trate como experimental e espere que possa parar de funcionar em uma atualização do macOS. Um conector dummy de hardware HDMI ou DisplayPort é uma alternativa sem software.",
    "Stays awake on battery too; the display turns off when the lid closes. Turn it off before putting it in a bag.": "Continua acordado também na bateria; a tela se apaga quando a tampa fecha. Desative antes de guardar o Mac em uma bolsa.",
    "The calendar rule needs Calendar access (System Settings ▸ Privacy)": "A regra de calendário precisa de acesso ao Calendário (Ajustes do Sistema ▸ Privacidade)",
    "Wi-Fi rules need Location access (System Settings ▸ Privacy)": "As regras de Wi-Fi precisam de acesso à localização (Ajustes do Sistema ▸ Privacidade)",
    "Checks an always-on Mac (e.g. a headless Mac mini) needs. Keepresso can read these but can't change the system ones, so use the links and commands below.": "Verificações que um Mac sempre ligado (por exemplo, um Mac mini sem monitor) precisa. O Keepresso pode ler esses ajustes, mas não pode alterar os do sistema, então use os links e comandos abaixo.",
    "macOS hops the Wi-Fi radio off-channel for AWDL about once a second, which shows up as ping spikes mid-game or mid-stream. Diagnose it here, and pause AWDL for the session if it's the culprit.": "O macOS tira o rádio Wi-Fi do canal para o AWDL cerca de uma vez por segundo, o que aparece como picos de ping no meio de um jogo ou de uma transmissão. Diagnostique isso aqui e pause o AWDL para a sessão se ele for o culpado.",
    "Pings 1.1.1.1 five times a second for 10 seconds and checks whether latency spikes on AWDL's once-a-second cadence.": "Envia ping para 1.1.1.1 cinco vezes por segundo durante 10 segundos e verifica se a latência tem picos na cadência de uma vez por segundo do AWDL.",
    "Counts only while a game (or a cloud-gaming app) is the active window, not just running in the background. Keeps holding for 5 minutes after you switch away.": "Conta apenas enquanto um jogo (ou um app de cloud gaming) é a janela ativa, não apenas em execução em segundo plano. Continua ativo por 5 minutos depois que você muda de janela.",
    "How long the pause lingers after the game stops being the active window, so a quick alt-tab doesn't flap the radios. Shorter brings AirDrop and Handoff back faster; longer rides out launchers and loading screens.": "Por quanto tempo a pausa continua depois que o jogo deixa de ser a janela ativa, para que um alt-tab rápido não fique ligando e desligando os rádios. Um tempo mais curto traz o AirDrop e o Handoff de volta mais rápido; um tempo mais longo aguenta launchers e telas de carregamento.",
    "Posts a notification when a game is detected and AWDL pauses, and again when it resumes. A notice that your administrator password is needed is always sent (even behind a fullscreen game), regardless of this switch.": "Envia uma notificação quando um jogo é detectado e o AWDL pausa, e outra quando ele retoma. Um aviso de que a sua senha de administrador é necessária é sempre enviado (mesmo atrás de um jogo em tela cheia), independentemente desse controle.",
    "Also tells macOS you're active while a session runs, so remote-desktop sessions, meeting presence (Teams, Slack), and corporate idle-logout don't mark you away. A plain keep-awake doesn't reach those. It only steps in once you've been idle a few seconds, so it never nudges the pointer while you're using the Mac or gaming. Off by default; some managed Macs flag simulated activity.": "Também informa ao macOS que você está ativo enquanto uma sessão está em execução, para que sessões de área de trabalho remota, presença em reuniões (Teams, Slack) e o logout automático corporativo por inatividade não marquem você como ausente. Uma simples vigília não alcança isso. Só entra em ação depois de alguns segundos de inatividade, então nunca move o ponteiro enquanto você está usando o Mac ou jogando. Desativado por padrão; alguns Macs gerenciados sinalizam atividade simulada.",
    "Install a small helper service so closed-display mode and AWDL pausing never ask for your password again. macOS will ask you to allow it in System Settings, once; nothing else changes.": "Instale um pequeno serviço assistente para que o modo com tela fechada e a pausa do AWDL nunca mais peçam sua senha. O macOS vai pedir para você permitir em Ajustes do Sistema, uma única vez; nada mais muda.",
    "One step left, in System Settings: under General ▸ Login Items & Extensions (“Login Items” on older macOS), find Keepresso in the “Allow in the Background” list and turn its switch ON. macOS asks for your administrator password once; this updates by itself when you're done.": "Falta um passo em Ajustes do Sistema: em Geral ▸ Itens de Login e Extensões (“Itens de Login” em versões mais antigas do macOS), encontre o Keepresso na lista “Permitir em Segundo Plano” e ative o controle. O macOS pede sua senha de administrador uma vez; isso se atualiza sozinho quando você terminar.",
    "Keeps running with the lid shut and no external display, on power or battery. The display itself still turns off when the lid closes (unless an external display is attached), so it's not lighting up uselessly inside the closed lid. Changing this flips a system setting (pmset disablesleep), so it stays in effect until you turn it off. On battery and closed it can still drain the battery over time, so don't leave it on in a bag. With “Only while brewing” on, Keepresso instead switches it on when a keep-awake session starts and back off when it ends or the app quits. Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password (once per app run for “Only while brewing”).": "Continua funcionando com a tampa fechada e sem tela externa, na energia elétrica ou na bateria. A própria tela ainda se apaga quando a tampa fecha (a menos que haja uma tela externa conectada), então ela não fica acesa à toa dentro da tampa fechada. Alterar isso muda um ajuste do sistema (pmset disablesleep), então o efeito permanece até você desativar. Na bateria e com a tampa fechada, ainda pode gastar a bateria com o tempo, então não deixe ativado dentro de uma bolsa. Com “Somente durante o preparo” ativado, o Keepresso ativa isso quando uma sessão de vigília começa e desativa quando ela termina ou o app é fechado. Os dois precisam de privilégios de administrador: silencioso com o assistente de administrador instalado (veja o topo desta aba), caso contrário o macOS pede sua senha (uma vez por execução do app para “Somente durante o preparo”).",
    "Turns the pause on right now and keeps it on until you turn it off or quit Keepresso (it isn't tied to whether a keep-awake session is brewing). While it's on, AirDrop, Handoff, Sidecar, and Continuity Camera take a break, and the once-a-second lag spikes stop. Everything comes back the moment you turn it off or quit Keepresso; even if the app crashes, macOS is restored automatically. With the administrator helper installed the switch is always instant and silent; without it, macOS asks for your password once per launch (the system dialog may show “osascript”, which is Keepresso running the command).": "Ativa a pausa agora mesmo e mantém ativada até você desativar ou sair do Keepresso (não depende de haver uma sessão de vigília em preparo). Enquanto estiver ativa, o AirDrop, o Handoff, o Sidecar e a Continuity Camera ficam em pausa, e os picos de lag de uma vez por segundo param. Tudo volta no momento em que você desativa ou sai do Keepresso; mesmo que o app trave, o macOS é restaurado automaticamente. Com o assistente de administrador instalado, o controle é sempre instantâneo e silencioso; sem ele, o macOS pede sua senha uma vez a cada abertura (a caixa de diálogo do sistema pode mostrar “osascript”, que é o Keepresso executando o comando).",
    "Watches for a game (or a cloud-gaming app like GeForce NOW) as the active window and pauses AWDL on its own, then lifts the pause a little after you switch away (the delay below). It only counts while the game is in front and in use, not just running in the background. Without the administrator helper, turning this on asks for your password once per app run, right now rather than mid-game; with the helper it never asks at all. No trigger setup needed: leave this on and forget it.": "Fica de olho em um jogo (ou um app de cloud gaming como o GeForce NOW) como a janela ativa e pausa o AWDL sozinho, depois libera a pausa um pouco depois que você muda de janela (o atraso abaixo). Só conta enquanto o jogo está em primeiro plano e em uso, não apenas em execução em segundo plano. Sem o assistente de administrador, ativar isso pede sua senha uma vez por execução do app, agora mesmo em vez de no meio do jogo; com o assistente, nunca pede. Não precisa configurar gatilhos: deixe ativado e esqueça.",
    "Helper installed. Closed-display mode and AWDL pausing work without password prompts.": "Assistente instalado. O modo com tela fechada e a pausa do AWDL funcionam sem pedidos de senha.",
    "Pause AWDL to steady your connection, and test your jitter, in Gaming & Streaming.": "Pause o AWDL para estabilizar sua conexão e teste o jitter em Jogos e streaming.",
    "A small system service that handles the privileged switches (closed-display mode below, AWDL pausing in Gaming & Streaming) for Keepresso, so no password prompts ever again: macOS asks once when you approve it under Login Items, and the approval survives restarts and updates. It can only flip those specific switches, everything it changes is restored if the app quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list; the status shown here is the real one.": "Um pequeno serviço do sistema que cuida dos controles com privilégios (o modo com tela fechada abaixo, a pausa do AWDL em Jogos e streaming) para o Keepresso, para que nunca mais haja pedidos de senha: o macOS pede uma vez quando você o aprova em Itens de Login, e a aprovação sobrevive a reinicializações e atualizações. Ele só pode alternar esses controles específicos, tudo que ele altera é restaurado se o app for fechado ou travar, e você pode removê-lo aqui a qualquer momento. Ele também coloca a ferramenta de linha de comando keepresso no seu PATH (instalações via Homebrew já a têm). Depois da remoção, Ajustes do Sistema pode continuar mostrando uma linha desatualizada em Itens de Login até o macOS atualizar a lista; o status mostrado aqui é o real.",
    "General": "Geral",
    "Triggers": "Gatilhos",
    "Reminder": "Lembrete",
    "Disk": "Disco",
    "Activity": "Atividade",
    "Indefinitely": "Indefinidamente",
    "Update Session": "Atualizar sessão",
    "Start": "Iniciar",
    "Met, in grace period": "Atendida, em tolerância",
    "Met": "Atendida",
    "Not met": "Não atendida",
    "Copied!": "Copiado!",
    "Copy command": "Copiar comando",
    "OK": "OK",
    "Needs attention": "Precisa de atenção",
    "Tip": "Dica",
    "Unknown": "Desconhecido",
    "Checking the helper": "Verificando o assistente",
    "One approval needed": "É preciso uma aprovação",
    "The helper needs a reinstall": "O assistente precisa ser reinstalado",
    "All set": "Tudo pronto",
    "Making sure Keepresso's helper is awake and answering.": "Verificando se o assistente do Keepresso está ativo e respondendo.",
    "macOS turned the helper's background switch off, so it needs your approval again: in System Settings, under Login Items & Extensions, find Keepresso in App Background Activity and turn it on. Everything is password-free again right after.": "O macOS desativou o controle de segundo plano do assistente, então ele precisa da sua aprovação de novo: em Ajustes do Sistema, em Itens de Login e Extensões, encontre o Keepresso em Atividade em Segundo Plano dos Apps e ative. Logo depois, tudo volta a funcionar sem senha.",
    "Keepresso repaired the helper's registration, but macOS keeps disabling it. An old copy of Keepresso in the Trash is the usual cause: empty the Trash, then reinstall the helper below. Nothing else about your setup changes.": "O Keepresso reparou o registro do assistente, mas o macOS continua desativando-o. Uma cópia antiga do Keepresso na Lixeira costuma ser a causa: esvazie a Lixeira e depois reinstale o assistente abaixo. Nada mais na sua configuração muda.",
    "The helper is back. Closed-display mode and AWDL pausing work without password prompts again.": "O assistente está de volta. O modo com tela fechada e a pausa do AWDL voltam a funcionar sem pedidos de senha.",
    "Waiting for the switch in System Settings; this updates by itself.": "Aguardando o controle em Ajustes do Sistema; isso se atualiza sozinho.",
    "Record": "Gravar",
    "Press keys…": "Pressione as teclas…",
    "Other process, e.g. rsync": "Outro processo, por exemplo, rsync",
    "Export Keepresso Settings": "Exportar ajustes do Keepresso",
    "Import Keepresso Settings": "Importar ajustes do Keepresso",
    "Exported to %@.": "Exportado para %@.",
    "Settings imported.": "Ajustes importados.",
    "Couldn't export settings: %@": "Não foi possível exportar os ajustes: %@",
    "Couldn't read the file: %@": "Não foi possível ler o arquivo: %@",
    "That file isn't a Keepresso settings export.": "Esse arquivo não é uma exportação de ajustes do Keepresso.",
    "That export was made by a newer version of Keepresso.": "Essa exportação foi feita por uma versão mais recente do Keepresso.",
    "Save current rules as…": "Salvar regras atuais como…",
    "A recurring notification every interval while a session runs, so a Mac left awake keeps reminding you.": "Uma notificação recorrente a cada intervalo enquanto uma sessão está em execução, para que um Mac deixado acordado continue lembrando você.",
    "A one-time notification once a session has run this long, in case you forget the Mac is awake.": "Uma notificação única quando uma sessão atingir essa duração, caso você esqueça que o Mac está acordado.",
    "Watch": "Monitorar",
    "Keep awake while downloads are in progress in this folder.": "Mantém acordado enquanto há downloads em andamento nesta pasta.",
    "Keep Awake": "Manter acordado",
    "Choose a folder on the disk you want to keep spun up.": "Escolha uma pasta no disco que você quer manter girando.",
    "Keepresso needs a new approval": "O Keepresso precisa de uma nova aprovação",
    "macOS turned Keepresso's background switch off. Turn it back on under Login Items & Extensions in System Settings to keep the password-free helper.": "O macOS desativou o controle de segundo plano do Keepresso. Ative-o novamente em Itens de Login e Extensões em Ajustes do Sistema para manter o assistente sem senha.",
    "Keepresso needs your password": "O Keepresso precisa da sua senha",
    "Enter your administrator password to switch closed-display mode on for this session.": "Digite sua senha de administrador para ativar o modo com tela fechada nesta sessão.",
    "Enter your administrator password to pause AWDL for this game.": "Digite sua senha de administrador para pausar o AWDL para este jogo.",
    "Game detected": "Jogo detectado",
    "Pausing AWDL to steady your connection.": "Pausando o AWDL para estabilizar sua conexão.",
    "AWDL resumed": "AWDL retomado",
    "The game closed; AirDrop, Handoff and Continuity are back.": "O jogo foi fechado; o AirDrop, o Handoff e o Continuity estão de volta.",
    "This copy of Keepresso isn't in the Applications folder, so it leaves the helper alone. Install from /Applications.": "Esta cópia do Keepresso não está na pasta Aplicativos, então ela não mexe no assistente. Instale a partir de /Applications.",
    "The helper wasn't found inside the app. Reinstall Keepresso and try again.": "O assistente não foi encontrado dentro do app. Reinstale o Keepresso e tente novamente.",
    "The helper couldn't be registered.": "Não foi possível registrar o assistente.",
    "The helper couldn't be removed: %@": "Não foi possível remover o assistente: %@",
    "macOS still reports the helper as registered. Try again, or restart the Mac.": "O macOS ainda informa o assistente como registrado. Tente novamente ou reinicie o Mac.",
    "Removed. System Settings may keep showing Keepresso under App Background Activity until macOS refreshes its list; restarting the Mac clears the leftover row.": "Removido. Ajustes do Sistema pode continuar mostrando o Keepresso em Atividade em Segundo Plano dos Apps até o macOS atualizar a lista; reiniciar o Mac remove a linha residual.",
    "macOS is refusing the helper's registration outright. Reinstall the helper; if that doesn't take, restart the Mac and try once more.": "O macOS está recusando totalmente o registro do assistente. Reinstale o assistente; se isso não resolver, reinicie o Mac e tente mais uma vez.",
    "The helper isn't responding. If an old copy of Keepresso is in the Trash, empty the Trash first: macOS keeps disabling the helper while one is there. Then reinstall the helper.": "O assistente não está respondendo. Se houver uma cópia antiga do Keepresso na Lixeira, esvazie a Lixeira primeiro: o macOS continua desativando o assistente enquanto ela estiver lá. Depois, reinstale o assistente.",
    "Old copy stuck in the Trash": "Cópia antiga presa na Lixeira",
    "An old copy of Keepresso in the Trash keeps the background helper from working. Please delete it from the Trash, or empty the Trash.": "Uma cópia antiga do Keepresso na Lixeira impede que o assistente em segundo plano funcione. Exclua-a da Lixeira ou esvazie a Lixeira.",
    "Language": "Idioma",
    "App language": "Idioma do app",
    "Follow System": "Seguir o sistema",
    "Keepresso follows your system language by default. Changing this relaunches Keepresso so menus, windows, and notifications all switch together.": "Por padrão, o Keepresso segue o idioma do sistema. Alterar isso reabre o Keepresso para que menus, janelas e notificações mudem todos juntos.",
    "%d h %d min": "%d h %d min",
    "%d h": "%d h",
    "%d min": "%d min",
    "%d:%02d": "%d:%02d",
    "%ds": "%d s",
    "%d:%02d:%02d": "%d:%02d:%02d",
    "Keepresso: paused, battery low": "Keepresso: em pausa, bateria baixa",
    "Keepresso: brewing": "Keepresso: preparando",
    "Keepresso: idle": "Keepresso: inativo",
    "1920 × 1080": "1920 × 1080",
    "2560 × 1440": "2560 × 1440",
    "2880 × 1620": "2880 × 1620",
    "3840 × 2160 (4K)": "3840 × 2160 (4K)",
    "Stop in": "Parar em",
    "Quick stop shortcuts": "Atalhos de parada rápida",
    "Add Shortcut": "Adicionar atalho",
    "Shortcut %d": "Atalho %d",
    "Remove shortcut": "Remover atalho",
    "One-click “Stop in” buttons shown in the menu while a session runs, so the Mac goes back to sleeping on its own that much later. Up to four; the list stays sorted.": "Botões de um clique “Parar em” exibidos no menu enquanto uma sessão está em andamento, para que o Mac volte a dormir sozinho depois desse tempo. Até quatro; a lista permanece ordenada.",
    "Warn before a timed session ends": "Avisar antes de uma sessão temporizada terminar",
    "Warn": "Avisar",
    "1 minute before": "1 minuto antes",
    "2 minutes before": "2 minutos antes",
    "5 minutes before": "5 minutos antes",
    "10 minutes before": "10 minutos antes",
    "AI agents": "Agentes de IA",
    "AI agent is working": "Um agente de IA está trabalhando",
    "Keeps the Mac awake while a coding-agent session (claude, codex, gemini, aider, and the like) is actively working, judged by its CPU use, and lets it sleep once every session has gone idle for the grace period. The menu lists each detected session. A freshly started session can take a few seconds to read as working.": "Mantém o Mac acordado enquanto uma sessão de agente de programação (claude, codex, gemini, aider e afins) está realmente trabalhando, a julgar pelo uso de CPU, e o deixa dormir quando todas as sessões ficaram ociosas pelo período de tolerância. O menu lista cada sessão detectada. Uma sessão recém-iniciada pode levar alguns segundos para aparecer como trabalhando.",
    "Idle grace period": "Tolerância após ociosidade",
    "Instantly": "Imediatamente",
    "10 minutes": "10 minutos",
    "working": "trabalhando",
    "idle": "inativo",
    "+%d more": "+%d mais",
}


# --- Agent hooks (Claude Code connection) ---
APP.update({
    "Claude Code connected: sessions report working and waiting exactly.": "Claude Code conectado: as sessões informam com exatidão quando trabalham e quando aguardam.",
    "Connect Claude Code for exact session tracking (adds hooks to its settings).": "Conecte o Claude Code para rastreamento exato das sessões (adiciona hooks às configurações dele).",
    "Connect Claude Code": "Conectar Claude Code",
    "Claude Code's settings file couldn't be read, so it was left untouched.": "Não foi possível ler o arquivo de configurações do Claude Code, então ele foi mantido intacto.",
    "Couldn't update Claude Code's settings file.": "Não foi possível atualizar o arquivo de configurações do Claude Code.",
})
