# -*- coding: utf-8 -*-
# Russian overlay for catalog_app.py: English source -> Russian.
APP = {
    "Add": "Добавить",
    "Add:": "Добавить:",
    "Clear": "Очистить",
    "Close": "Закрыть",
    "Done": "Готово",
    "Save": "Сохранить",
    "Enable": "Включить",
    "Enabled": "Включено",
    "Installed": "Установлено",
    "Remove": "Удалить",
    "Remove condition": "Удалить условие",
    "Resume": "Возобновить",
    "Later": "Позже",
    "Learn more": "Подробнее",
    "Re-check": "Проверить снова",
    "Run Test": "Запустить тест",
    "Match": "Совпадение",
    "Threshold": "Порог",
    "Grace period": "Период ожидания",
    "Section": "Раздел",
    "Schedule": "Расписание",
    "Set Duration": "Задать длительность",
    "For": "На",
    "From": "С",
    "To": "До",
    "Until": "До",
    "When": "Когда",
    "Below": "Ниже",
    "Power": "Питание",
    "Display": "Дисплей",
    "Network": "Сеть",
    "Media": "Медиа",
    "Backup": "Резервное копирование",
    "Folder": "Папка",
    "Downloads": "Загрузки",
    "Touch": "Обновление",
    "Resolution": "Разрешение",
    "Startup": "Запуск",
    "Gaming": "Игры",
    "None": "Нет",
    "any": "любое",
    "all": "все",
    "of these are true:": "из следующих условий:",
    "1 minute": "1 минута",
    "2 minutes": "2 минуты",
    "5 minutes": "5 минут",
    "10 seconds": "10 секунд",
    "30 seconds": "30 секунд",
    "15 minutes": "15 минут",
    "30 minutes": "30 минут",
    "1 hour": "1 час",
    "2 hours": "2 часа",
    "4 hours": "4 часа",
    "8 hours": "8 часов",
    "No grace": "Без ожидания",
    "Every 1 minute": "Каждую минуту",
    "Every 5 minutes": "Каждые 5 минут",
    "Every 10 minutes": "Каждые 10 минут",
    "Every 30 minutes": "Каждые 30 минут",
    "Every": "Каждые",
    "After": "После",
    "Keepresso": "Keepresso",
    "About Keepresso": "О программе Keepresso",
    "Welcome to Keepresso": "Добро пожаловать в Keepresso",
    "Keepresso Setup": "Настройка Keepresso",
    "Keepresso Helper": "Помощник Keepresso",
    "Preferences": "Настройки",
    "Preferences…": "Настройки…",
    "A menu-bar app that keeps your Mac awake on your terms.": "Приложение в строке меню, которое не даёт Mac засыпать на ваших условиях.",
    "AWDL watchdog": "Сторож AWDL",
    "Activate by triggers": "Активировать по триггерам",
    "Administrator helper": "Помощник с правами администратора",
    "Allow Bluetooth access…": "Разрешить доступ к Bluetooth…",
    "Allow Wi-Fi access…": "Разрешить доступ к Wi-Fi…",
    "Allow calendar access…": "Разрешить доступ к календарю…",
    "App is frontmost": "Приложение на переднем плане",
    "App is running": "Приложение запущено",
    "App match & grace period": "Совпадение приложения и период ожидания",
    "Apply or remove": "Применить или удалить",
    "Approve…": "Одобрить…",
    "Apps & Activity": "Приложения и активность",
    "Bluetooth device connected": "Подключено устройство Bluetooth",
    "Bluetooth rules need Bluetooth access (System Settings ▸ Privacy)": "Для правил Bluetooth нужен доступ к Bluetooth (Системные настройки ▸ Конфиденциальность)",
    "CPU load": "Загрузка CPU",
    "CPU threshold": "Порог CPU",
    "Camera in use": "Камера используется",
    "Change…": "Изменить…",
    "Charging": "Зарядка",
    "Check for Updates…": "Проверить наличие обновлений…",
    "Closed-display mode": "Режим закрытой крышки",
    "Contacting the helper…": "Связь с помощником…",
    "Create a virtual display": "Создать виртуальный дисплей",
    "Currently paused from the menu bar.": "Сейчас приостановлено из строки меню.",
    "Custom Duration…": "Своя длительность…",
    "During calendar events": "Во время событий календаря",
    "Export Settings…": "Экспортировать настройки…",
    "Import Settings…": "Импортировать настройки…",
    "External display connected": "Подключён внешний дисплей",
    "Fix…": "Исправить…",
    "GNU GPL v3.0": "GNU GPL v3.0",
    "Gaming & Streaming": "Игры и стриминг",
    "Gaming & Streaming…": "Игры и стриминг…",
    "Get Started": "Начать",
    "Global shortcut": "Глобальное сочетание клавиш",
    "Headless Setup": "Настройка без монитора",
    "Headless Setup…": "Настройка без монитора…",
    "Headless virtual display (experimental)": "Виртуальный дисплей без монитора (экспериментально)",
    "Helper installed and responding": "Помощник установлен и отвечает",
    "HiDPI (Retina)": "HiDPI (Retina)",
    "How do you use your Mac?": "Как вы используете свой Mac?",
    "Install Helper…": "Установить помощник…",
    "Install…": "Установить…",
    "Jitter test": "Тест джиттера",
    "Keep a disk spinning": "Поддерживать вращение диска",
    "Keep awake with lid closed": "Не засыпать с закрытой крышкой",
    "Keep awake with the lid closed": "Не засыпать с закрытой крышкой",
    "Keep awake": "Не засыпать",
    "Keep me active": "Поддерживать мою активность",
    "Keeping the Mac awake now": "Сейчас Mac не засыпает",
    "Keepresso decisions": "Решения Keepresso",
    "Measuring, about 10 seconds…": "Измерение, около 10 секунд…",
    "Microphone in use": "Микрофон используется",
    "Network & Devices": "Сеть и устройства",
    "Network activity": "Сетевая активность",
    "Network threshold": "Сетевой порог",
    "No Wi-Fi network joined": "Нет подключения к сети Wi-Fi",
    "No apps running": "Нет запущенных приложений",
    "No conditions yet, so the Mac can sleep.": "Условий пока нет, поэтому Mac может засыпать.",
    "No conditions yet. Add some in Preferences ▸ Triggers.": "Условий пока нет. Добавьте их в разделе Настройки ▸ Триггеры.",
    "No days selected means every day.": "Если дни не выбраны, это означает каждый день.",
    "No paired devices": "Нет сопряжённых устройств",
    "No session activity yet.": "Активности сеансов пока нет.",
    "No volumes mounted": "Нет подключённых томов",
    "Not available on this macOS version.": "Недоступно в этой версии macOS.",
    "Nothing is holding the Mac awake right now.": "Сейчас ничто не мешает Mac засыпать.",
    "Notify when a session ends": "Уведомлять о завершении сеанса",
    "Notify when auto-pausing and resuming": "Уведомлять об автопаузе и возобновлении",
    "On AC power": "От сети",
    "On battery": "От аккумулятора",
    "On session end": "При завершении сеанса",
    "Only while brewing": "Только во время заваривания",
    "Open Login Items": "Открыть Объекты входа",
    "Open Settings": "Открыть настройки",
    "Overnight (22:00-6:00)": "Ночью (22:00-6:00)",
    "Pause AWDL automatically while gaming": "Автоматически приостанавливать AWDL во время игры",
    "Pause AWDL now": "Приостановить AWDL сейчас",
    "Pause Triggers": "Приостановить триггеры",
    "Pause on low battery": "Приостанавливать при низком заряде",
    "Play a sound": "Воспроизвести звук",
    "Playing a game": "Идёт игра",
    "Power & Display": "Питание и дисплей",
    "Presets": "Предустановки",
    "Prevent display sleep": "Не давать дисплею засыпать",
    "Prevent system sleep": "Не давать системе засыпать",
    "Process is running": "Процесс запущен",
    "Quit Keepresso": "Завершить Keepresso",
    "Reduce lag and jitter": "Уменьшить задержки и джиттер",
    "Reinstall Helper": "Переустановить помощник",
    "Remind me it's still on": "Напоминать, что всё ещё включено",
    "Repeat the reminder": "Повторять напоминание",
    "Restore default presets": "Восстановить стандартные предустановки",
    "Resume AWDL after leaving the game": "Возобновлять AWDL после выхода из игры",
    "Resume Triggers": "Возобновить триггеры",
    "Session end": "Завершение сеанса",
    "Set Up…": "Настроить…",
    "Show Welcome Screen…": "Показать экран приветствия…",
    "Show countdown in menu bar": "Показывать обратный отсчёт в строке меню",
    "Start keep-awake on launch": "Включать поддержание активности при запуске",
    "The helper needs attention": "Помощник требует внимания",
    "The test couldn't run. Check that you're online and try again.": "Не удалось запустить тест. Убедитесь, что вы в сети, и повторите попытку.",
    "The watchdog below should smooth this out; re-run the test with it on to confirm.": "Сторож ниже должен это сгладить. Запустите тест снова с включённым сторожем, чтобы это подтвердить.",
    "Times & days": "Время и дни",
    "Toggle shortcut": "Сочетание для переключения",
    "Triggers paused. Controlling manually for now.": "Триггеры приостановлены. Пока управление вручную.",
    "Until a Time…": "До определённого времени…",
    "VPN connected": "VPN подключён",
    "View on GitHub": "Открыть на GitHub",
    "Volume is mounted": "Том подключён",
    "Watch a folder for downloads…": "Отслеживать папку загрузок…",
    "While frontmost": "Пока на переднем плане",
    "While running": "Пока запущено",
    "Work hours (weekdays 9:00-18:00)": "Рабочее время (будни 9:00-18:00)",
    "Audio playing": "Звук воспроизводится",
    "Paused": "Приостановлено",
    "Brewing": "Заваривание",
    "Idle": "Простой",
    "System can sleep": "Система может засыпать",
    "No conditions yet": "Условий пока нет",
    "Battery below %d%%, letting the Mac sleep": "Батарея ниже %d%%, Mac может заснуть",
    "Stops in %@": "Остановится через %@",
    "Awake for %@": "Не спит уже %@",
    "Active": "Активно",
    "Held by %@": "Держит: %@",
    "Waiting for any condition": "Ожидание любого условия",
    "Waiting on %@": "Ожидание: %@",
    "%d condition": "%d условие",
    "%d conditions": "%d условий",
    "Approve Keepresso again in System Settings.": "Утвердите Keepresso заново в Системных настройках.",
    "The helper isn't responding; reinstall it.": "Помощник не отвечает, переустановите его.",
    "Waiting for a game to come to the front": "Ожидание, когда игра станет активным окном",
    "AWDL paused": "AWDL приостановлен",
    "AWDL paused for gaming": "AWDL приостановлен для игры",
    "Game closed, AWDL back in %ds": "Игра закрыта, AWDL вернётся через %d с",
    "Latency looks clean.": "Задержка выглядит чистой.",
    "Once-a-second spikes: this looks like AWDL.": "Всплески раз в секунду: похоже на AWDL.",
    "Spiky, but not on AWDL's cadence (congestion or a weak signal).": "Скачки есть, но не в ритме AWDL (перегрузка или слабый сигнал).",
    "Not enough replies to judge.": "Недостаточно ответов для оценки.",
    "AWDL is on right now": "AWDL сейчас включён",
    "AWDL is off right now": "AWDL сейчас выключен",
    "AWDL state unknown": "Состояние AWDL неизвестно",
    "Agentic coding": "Агентное программирование",
    "Stay awake while Claude, Codex, or Grok is running.": "Не давайте Mac засыпать, пока запущены Claude, Codex или Grok.",
    "Gaming & streaming": "Игры и стриминг",
    "Stay awake while a game or cloud-gaming app is in front.": "Не давайте Mac засыпать, пока игра или приложение облачного гейминга находится на переднем плане.",
    "Meetings & calls": "Встречи и звонки",
    "Stay awake whenever the camera or microphone is in use.": "Не давайте Mac засыпать, пока используется камера или микрофон.",
    "Remote access": "Удалённый доступ",
    "Stay awake while someone is connected over SSH.": "Не давайте Mac засыпать, пока кто-то подключён по SSH.",
    "Keep it manual for now": "Пока оставить вручную",
    "Just toggle keep-awake yourself, and set up your own triggers later in Preferences.": "Просто переключайте поддержание активности вручную, а свои триггеры настройте позже в Настройках.",
    "Launch at login": "Запуск при входе в систему",
    "Start Keepresso automatically when you log in.": "Автоматически запускать Keepresso при входе в систему.",
    "Notifications": "Уведомления",
    "Let Keepresso remind you when a long session is still keeping the Mac awake.": "Разрешите Keepresso напоминать вам, когда длительный сеанс всё ещё не даёт Mac заснуть.",
    "Approve a small helper once and the privileged extras (lid-closed mode, AWDL pausing) never ask for your password again. Set and forget; removable in Preferences.": "Одобрите небольшого помощника один раз, и привилегированные функции (режим закрытой крышки, приостановка AWDL) больше никогда не запросят ваш пароль. Настройте и забудьте, удалить можно в Настройках.",
    "Location access (Wi-Fi rules)": "Доступ к геопозиции (правила Wi-Fi)",
    "Bluetooth access (device rules)": "Доступ к Bluetooth (правила устройств)",
    "Calendar access (event rule)": "Доступ к календарю (правило события)",
    "Keepresso launches at login, so it returns after a reboot.": "Keepresso запускается при входе в систему, поэтому возвращается после перезагрузки.",
    "Keepresso isn't set to launch at login, so it won't run after an unattended reboot.": "Keepresso не настроен на запуск при входе в систему, поэтому не запустится после перезагрузки без присмотра.",
    "Turn on “Launch at login” in Keepresso's settings.": "Включите «Запуск при входе в систему» в настройках Keepresso.",
    "Keepresso can read the current Wi-Fi network name for your Wi-Fi triggers.": "Keepresso может читать имя текущей сети Wi-Fi для ваших триггеров Wi-Fi.",
    "Without Location access Keepresso can't read the Wi-Fi network name, so Wi-Fi triggers won't match.": "Без доступа к геопозиции Keepresso не может прочитать имя сети Wi-Fi, поэтому триггеры Wi-Fi не будут срабатывать.",
    "Allow Location access for Keepresso.": "Разрешите Keepresso доступ к геопозиции.",
    "Keepresso can see which paired devices are connected for your Bluetooth triggers.": "Keepresso может видеть, какие сопряжённые устройства подключены, для ваших триггеров Bluetooth.",
    "Without Bluetooth access Keepresso can't see paired devices, so Bluetooth triggers won't match.": "Без доступа к Bluetooth Keepresso не видит сопряжённые устройства, поэтому триггеры Bluetooth не будут срабатывать.",
    "Allow Bluetooth access for Keepresso.": "Разрешите Keepresso доступ к Bluetooth.",
    "Keepresso can see when a calendar event is in progress for your calendar trigger.": "Keepresso может видеть, когда идёт событие календаря, для вашего триггера календаря.",
    "Without full calendar access Keepresso can't see events, so the calendar trigger won't match.": "Без полного доступа к календарю Keepresso не видит события, поэтому триггер календаря не будет срабатывать.",
    "Allow full calendar access for Keepresso.": "Разрешите Keepresso полный доступ к календарю.",
    "Keepresso can post the “still brewing” reminder.": "Keepresso может отправлять напоминание «всё ещё заваривается».",
    "Notifications are off, so the “still brewing” reminder can't appear.": "Уведомления выключены, поэтому напоминание «всё ещё заваривается» не появится.",
    "Allow notifications for Keepresso.": "Разрешите Keepresso отправлять уведомления.",
    "Above %d%%": "Выше %d%%",
    "Above %@": "Выше %@",
    "Version %@": "Версия %@",
    "Remove “%@”": "Удалить «%@»",
    "On current Wi-Fi (%@)": "В текущей сети Wi-Fi (%@)",
    "keep the Mac awake with the lid closed": "не давать Mac засыпать с закрытой крышкой",
    "switch closed-display mode with the session": "переключать режим закрытой крышки вместе с сеансом",
    "pause AWDL (turn off the Wi-Fi AirDrop/Handoff radio hops)": "приостановить AWDL (отключить радиопереключения Wi-Fi для AirDrop/Handoff)",
    "macOS is asking for your administrator password to %@. The dialog may be titled “osascript”: that's Keepresso running the command, and nothing else is changed. To stop these prompts for good, install the administrator helper (Preferences ▸ General).": "macOS запрашивает пароль администратора, чтобы %@. Диалоговое окно может называться «osascript»: это Keepresso выполняет команду, больше ничего не меняется. Чтобы навсегда прекратить эти запросы, установите помощника с правами администратора (Настройки ▸ Общие).",
    "Keepresso keeps your Mac awake on your terms. It lives in the menu bar near the clock, with no Dock icon. Click its cup any time to start or stop.": "Keepresso не даёт Mac засыпать на ваших условиях. Приложение живёт в строке меню рядом с часами, без значка в Dock. Нажмите на его чашку в любой момент, чтобы начать или остановить.",
    "Pick one to set up matching triggers, or keep it manual and add your own later. You can change this any time in Preferences.": "Выберите один вариант, чтобы настроить соответствующие триггеры, или оставьте управление вручную и добавьте свои позже. Это можно изменить в любой момент в Настройках.",
    "When on, the listed conditions control the session instead of the manual switch.": "Когда включено, перечисленные условия управляют сеансом вместо ручного переключателя.",
    "Activation is controlled by triggers.\nEdit them in Preferences.": "Активацию контролируют триггеры.\nРедактируйте их в Настройках.",
    "Why each session started or stopped, newest first. Kept in memory; clears on relaunch.": "Почему начался или завершился каждый сеанс, сначала новые. Хранится в памяти, очищается при перезапуске.",
    "Every app's live power assertions, not just Keepresso's, the same data pmset -g assertions prints.": "Текущие запросы энергопотребления всех приложений, а не только Keepresso, те же данные, что выводит pmset -g assertions.",
    "A system-wide keyboard shortcut that starts or stops keep-awake from any app. Needs at least one modifier key.": "Общесистемное сочетание клавиш, которое запускает или останавливает поддержание активности из любого приложения. Требуется хотя бы одна клавиша-модификатор.",
    "Lets the Mac sleep once battery charge drops below this level, even mid-session, so it doesn't run flat.": "Позволяет Mac засыпать, как только заряд батареи опускается ниже этого уровня, даже во время сеанса, чтобы батарея не разрядилась полностью.",
    "Shows the remaining time next to the menu-bar icon during a timed session.": "Показывает оставшееся время рядом со значком в строке меню во время сеанса с таймером.",
    "Starts a session as soon as Keepresso launches, using the default duration. Ignored while triggers are controlling activation.": "Запускает сеанс сразу после запуска Keepresso с длительностью по умолчанию. Игнорируется, пока активацией управляют триггеры.",
    "Reopen the first-run welcome, with quick one-click setup for how you use your Mac.": "Снова открывает экран приветствия первого запуска с быстрой настройкой в один клик под ваш способ использования Mac.",
    "Fires when a timed session expires, trigger conditions drop, or a low-battery pause kicks in, not when you stop it yourself. The action is off by default so a timed session never surprises you.": "Срабатывает, когда истекает сеанс с таймером, перестают выполняться условия триггеров или включается пауза из-за низкого заряда батареи, а не когда вы останавливаете его сами. По умолчанию это действие выключено, чтобы сеанс с таймером никогда не застал вас врасплох.",
    "If that time already passed today, it means tomorrow.": "Если это время сегодня уже прошло, имеется в виду завтра.",
    "Runs past midnight into the next day.": "Продолжается после полуночи до следующего дня.",
    "Save your settings, triggers, and presets to a JSON file to back them up or move them to another Mac. Importing replaces your current configuration and ends any running session.": "Сохраните настройки, триггеры и предустановки в файл JSON для резервного копирования или переноса на другой Mac. Импорт заменяет текущую конфигурацию и завершает любой выполняющийся сеанс.",
    "Keeps the Mac awake while a partial-download file (.crdownload, .download, .part, and the like) exists in the chosen folder, then lets it sleep once the download finishes. Holds for 30 seconds between files in a batch.": "Не даёт Mac засыпать, пока в выбранной папке существует файл незавершённой загрузки (.crdownload, .download, .part и подобные), а затем позволяет ему заснуть после завершения загрузки. Удерживает активность 30 секунд между файлами в пакете.",
    "Writes a tiny marker file on the chosen volume periodically to stop an external drive or NAS from spinning down.": "Периодически записывает крошечный файл-метку на выбранный том, чтобы внешний диск или NAS не переходил в спящий режим.",
    "For a Mac with no monitor: creates a higher-resolution display so Screen Sharing and VNC look crisp instead of a fuzzy 1920 × 1080. It uses a private macOS API, so treat it as experimental and expect it may break on a macOS update. A hardware HDMI or DisplayPort dummy plug is a no-software alternative.": "Для Mac без монитора: создаёт дисплей более высокого разрешения, чтобы «Общий доступ к экрану» и VNC выглядели чётко, а не размыто, как при 1920 × 1080. Используется частный API macOS, поэтому считайте эту функцию экспериментальной: она может перестать работать после обновления macOS. Альтернативой без программного обеспечения служит аппаратная заглушка HDMI или DisplayPort.",
    "Stays awake on battery too; the display turns off when the lid closes. Turn it off before putting it in a bag.": "Остаётся активным и на батарее, дисплей выключается при закрытии крышки. Выключите эту функцию, прежде чем убрать Mac в сумку.",
    "The calendar rule needs Calendar access (System Settings ▸ Privacy)": "Правилу календаря нужен доступ к календарю (Системные настройки ▸ Конфиденциальность)",
    "Wi-Fi rules need Location access (System Settings ▸ Privacy)": "Правилам Wi-Fi нужен доступ к геопозиции (Системные настройки ▸ Конфиденциальность)",
    "Checks an always-on Mac (e.g. a headless Mac mini) needs. Keepresso can read these but can't change the system ones, so use the links and commands below.": "Проверки, необходимые для постоянно включённого Mac (например, Mac mini без монитора). Keepresso может их считывать, но не может изменять системные настройки, поэтому используйте ссылки и команды ниже.",
    "macOS hops the Wi-Fi radio off-channel for AWDL about once a second, which shows up as ping spikes mid-game or mid-stream. Diagnose it here, and pause AWDL for the session if it's the culprit.": "Примерно раз в секунду macOS переключает радиомодуль Wi-Fi на другой канал для AWDL, из-за чего во время игры или стрима появляются всплески пинга. Проверьте это здесь и приостановите AWDL на сеанс, если причина в нём.",
    "Pings 1.1.1.1 five times a second for 10 seconds and checks whether latency spikes on AWDL's once-a-second cadence.": "Отправляет пинг на 1.1.1.1 пять раз в секунду в течение 10 секунд и проверяет, появляются ли всплески задержки в ритме AWDL раз в секунду.",
    "Counts only while a game (or a cloud-gaming app) is the active window, not just running in the background. Keeps holding for 5 minutes after you switch away.": "Учитывается только пока игра (или приложение облачного гейминга) является активным окном, а не просто работает в фоне. Продолжает удерживать активность ещё 5 минут после переключения.",
    "How long the pause lingers after the game stops being the active window, so a quick alt-tab doesn't flap the radios. Shorter brings AirDrop and Handoff back faster; longer rides out launchers and loading screens.": "Как долго сохраняется пауза после того, как игра перестаёт быть активным окном, чтобы быстрое переключение окон не включало и выключало радиомодули без остановки. Меньшее значение быстрее возвращает AirDrop и Handoff, большее позволяет пережить лаунчеры и экраны загрузки.",
    "Posts a notification when a game is detected and AWDL pauses, and again when it resumes. A notice that your administrator password is needed is always sent (even behind a fullscreen game), regardless of this switch.": "Отправляет уведомление, когда обнаружена игра и AWDL приостанавливается, и снова, когда он возобновляется. Уведомление о том, что нужен пароль администратора, отправляется всегда (даже под игрой в полноэкранном режиме), независимо от этого переключателя.",
    "Also tells macOS you're active while a session runs, so remote-desktop sessions, meeting presence (Teams, Slack), and corporate idle-logout don't mark you away. A plain keep-awake doesn't reach those. It only steps in once you've been idle a few seconds, so it never nudges the pointer while you're using the Mac or gaming. Off by default; some managed Macs flag simulated activity.": "Также сообщает macOS, что вы активны, пока выполняется сеанс, поэтому сеансы удалённого рабочего стола, статус присутствия на встречах (Teams, Slack) и корпоративный автоматический выход при бездействии не помечают вас как отсутствующего. Обычное поддержание активности до этого не доходит. Функция включается только после нескольких секунд бездействия, поэтому она никогда не двигает указатель, пока вы используете Mac или играете. По умолчанию выключена: на некоторых управляемых Mac имитация активности может быть замечена.",
    "Install a small helper service so closed-display mode and AWDL pausing never ask for your password again. macOS will ask you to allow it in System Settings, once; nothing else changes.": "Установите небольшую службу-помощник, чтобы режим закрытой крышки и приостановка AWDL больше никогда не запрашивали ваш пароль. macOS один раз попросит вас разрешить это в Системных настройках, больше ничего не изменится.",
    "One step left, in System Settings: under General ▸ Login Items & Extensions (“Login Items” on older macOS), find Keepresso in the “Allow in the Background” list and turn its switch ON. macOS asks for your administrator password once; this updates by itself when you're done.": "Остался один шаг в Системных настройках: в разделе Основные ▸ Элементы входа и расширения («Элементы входа» в более старых версиях macOS) найдите Keepresso в списке «Разрешить в фоновом режиме» и включите переключатель. macOS один раз запросит пароль администратора, после чего этот статус обновится автоматически.",
    "Keeps running with the lid shut and no external display, on power or battery. The display itself still turns off when the lid closes (unless an external display is attached), so it's not lighting up uselessly inside the closed lid. Changing this flips a system setting (pmset disablesleep), so it stays in effect until you turn it off. On battery and closed it can still drain the battery over time, so don't leave it on in a bag. With “Only while brewing” on, Keepresso instead switches it on when a keep-awake session starts and back off when it ends or the app quits. Both need administrator rights: silent with the administrator helper installed (see the top of this tab), otherwise macOS asks for your password (once per app run for “Only while brewing”).": "Продолжает работать с закрытой крышкой и без внешнего дисплея, от сети или от батареи. Сам дисплей всё равно выключается при закрытии крышки (если не подключён внешний дисплей), поэтому он не светится без толку под закрытой крышкой. Изменение этой настройки переключает системный параметр (pmset disablesleep), поэтому она остаётся действующей, пока вы её не выключите. От батареи и с закрытой крышкой она всё же может со временем разрядить аккумулятор, поэтому не оставляйте её включённой в сумке. При включённой опции «Только во время заваривания» Keepresso вместо этого включает настройку при запуске сеанса поддержания активности и выключает её по завершении сеанса или при выходе из приложения. Обе функции требуют прав администратора: бесшумно, если установлен помощник с правами администратора (см. верх этой вкладки), иначе macOS запрашивает пароль (один раз за запуск приложения для «Только во время заваривания»).",
    "Turns the pause on right now and keeps it on until you turn it off or quit Keepresso (it isn't tied to whether a keep-awake session is brewing). While it's on, AirDrop, Handoff, Sidecar, and Continuity Camera take a break, and the once-a-second lag spikes stop. Everything comes back the moment you turn it off or quit Keepresso; even if the app crashes, macOS is restored automatically. With the administrator helper installed the switch is always instant and silent; without it, macOS asks for your password once per launch (the system dialog may show “osascript”, which is Keepresso running the command).": "Немедленно включает паузу и оставляет её включённой, пока вы не выключите её сами или не выйдете из Keepresso (это не зависит от того, идёт ли сеанс поддержания активности). Пока пауза включена, AirDrop, Handoff, Sidecar и камера Continuity временно не работают, а всплески задержки раз в секунду прекращаются. Всё возвращается в момент, когда вы выключаете паузу или выходите из Keepresso: даже если приложение аварийно завершится, macOS восстанавливается автоматически. Если установлен помощник с правами администратора, переключение всегда происходит мгновенно и бесшумно, иначе macOS один раз за запуск запрашивает пароль (в системном диалоге может быть указано «osascript», это Keepresso выполняет команду).",
    "Watches for a game (or a cloud-gaming app like GeForce NOW) as the active window and pauses AWDL on its own, then lifts the pause a little after you switch away (the delay below). It only counts while the game is in front and in use, not just running in the background. Without the administrator helper, turning this on asks for your password once per app run, right now rather than mid-game; with the helper it never asks at all. No trigger setup needed: leave this on and forget it.": "Отслеживает, является ли игра (или приложение облачного гейминга вроде GeForce NOW) активным окном, и самостоятельно приостанавливает AWDL, а затем немного погодя снимает паузу после переключения на другое окно (задержка указана ниже). Учитывается только пока игра находится на переднем плане и используется, а не просто работает в фоне. Без помощника с правами администратора включение этой функции один раз за запуск приложения запрашивает пароль сейчас, а не посреди игры; с помощником пароль не запрашивается вовсе. Настройка триггеров не требуется: включите и забудьте.",
    "Helper installed. Closed-display mode and AWDL pausing work without password prompts.": "Помощник установлен. Режим закрытой крышки и приостановка AWDL работают без запросов пароля.",
    "Pause AWDL to steady your connection, and test your jitter, in Gaming & Streaming.": "Приостановите AWDL, чтобы стабилизировать соединение, и протестируйте джиттер в разделе «Игры и стриминг».",
    "A small system service that handles the privileged switches (closed-display mode below, AWDL pausing in Gaming & Streaming) for Keepresso, so no password prompts ever again: macOS asks once when you approve it under Login Items, and the approval survives restarts and updates. It can only flip those specific switches, everything it changes is restored if the app quits or crashes, and you can remove it here at any time. It also puts the keepresso command-line tool on your PATH (Homebrew installs already have it). After removal, System Settings can keep showing a stale Login Items row until macOS refreshes its list; the status shown here is the real one.": "Небольшая системная служба, которая управляет привилегированными переключателями Keepresso (режим закрытой крышки ниже, приостановка AWDL в разделе «Игры и стриминг»), поэтому запросы пароля больше никогда не понадобятся: macOS спрашивает один раз, когда вы одобряете её в Элементах входа, и это одобрение сохраняется после перезагрузок и обновлений. Она может переключать только эти конкретные параметры, все её изменения восстанавливаются при выходе из приложения или его аварийном завершении, и вы можете удалить её здесь в любой момент. Она также добавляет инструмент командной строки keepresso в PATH (при установке через Homebrew он уже есть). После удаления Системные настройки могут ещё некоторое время показывать устаревшую строку в Элементах входа, пока macOS не обновит список: статус, показанный здесь, всегда актуален.",
    "General": "Общие",
    "Triggers": "Триггеры",
    "Reminder": "Напоминание",
    "Disk": "Диск",
    "Activity": "Активность",
    "Indefinitely": "Бессрочно",
    "Update Session": "Обновить сеанс",
    "Start": "Начать",
    "Met, in grace period": "Выполнено, период ожидания",
    "Met": "Выполнено",
    "Not met": "Не выполнено",
    "Copied!": "Скопировано!",
    "Copy command": "Скопировать команду",
    "OK": "Норма",
    "Needs attention": "Требует внимания",
    "Tip": "Совет",
    "Unknown": "Неизвестно",
    "Checking the helper": "Проверка помощника",
    "One approval needed": "Требуется одно подтверждение",
    "The helper needs a reinstall": "Помощника нужно переустановить",
    "All set": "Всё готово",
    "Making sure Keepresso's helper is awake and answering.": "Проверяем, что помощник Keepresso активен и отвечает.",
    "macOS turned the helper's background switch off, so it needs your approval again: in System Settings, under Login Items & Extensions, find Keepresso in App Background Activity and turn it on. Everything is password-free again right after.": "macOS выключил фоновый переключатель помощника, поэтому требуется ваше повторное подтверждение: в Системных настройках, в разделе «Элементы входа и расширения», найдите Keepresso в списке «Фоновая активность приложений» и включите переключатель. Сразу после этого всё снова будет работать без пароля.",
    "Keepresso repaired the helper's registration, but macOS keeps disabling it. An old copy of Keepresso in the Trash is the usual cause: empty the Trash, then reinstall the helper below. Nothing else about your setup changes.": "Keepresso восстановил регистрацию помощника, но macOS продолжает его отключать. Обычная причина: старая копия Keepresso в Корзине. Очистите Корзину, а затем переустановите помощника ниже. Остальные настройки не изменятся.",
    "The helper is back. Closed-display mode and AWDL pausing work without password prompts again.": "Помощник снова работает. Режим закрытой крышки и приостановка AWDL опять работают без запросов пароля.",
    "Waiting for the switch in System Settings; this updates by itself.": "Ожидание переключения в Системных настройках, статус обновится автоматически.",
    "Record": "Запись",
    "Press keys…": "Нажмите клавиши…",
    "Other process, e.g. rsync": "Другой процесс, например rsync",
    "Export Keepresso Settings": "Экспорт настроек Keepresso",
    "Import Keepresso Settings": "Импорт настроек Keepresso",
    "Exported to %@.": "Экспортировано в %@.",
    "Settings imported.": "Настройки импортированы.",
    "Couldn't export settings: %@": "Не удалось экспортировать настройки: %@",
    "Couldn't read the file: %@": "Не удалось прочитать файл: %@",
    "That file isn't a Keepresso settings export.": "Этот файл не является экспортом настроек Keepresso.",
    "That export was made by a newer version of Keepresso.": "Этот экспорт был создан более новой версией Keepresso.",
    "Save current rules as…": "Сохранить текущие правила как…",
    "A recurring notification every interval while a session runs, so a Mac left awake keeps reminding you.": "Повторяющееся уведомление через равные промежутки времени, пока выполняется сеанс, чтобы Mac, оставленный активным, продолжал напоминать о себе.",
    "A one-time notification once a session has run this long, in case you forget the Mac is awake.": "Однократное уведомление после того, как сеанс длится столько времени, на случай если вы забудете, что Mac не спит.",
    "Watch": "Отслеживать",
    "Keep awake while downloads are in progress in this folder.": "Не давать Mac засыпать, пока в этой папке идёт загрузка.",
    "Keep Awake": "Не засыпать",
    "Choose a folder on the disk you want to keep spun up.": "Выберите папку на диске, который вы хотите держать активным.",
    "Keepresso needs a new approval": "Keepresso требуется новое подтверждение",
    "macOS turned Keepresso's background switch off. Turn it back on under Login Items & Extensions in System Settings to keep the password-free helper.": "macOS выключил фоновый переключатель Keepresso. Включите его снова в разделе «Элементы входа и расширения» Системных настроек, чтобы сохранить помощника без запроса пароля.",
    "Keepresso needs your password": "Keepresso нужен ваш пароль",
    "Enter your administrator password to switch closed-display mode on for this session.": "Введите пароль администратора, чтобы включить режим закрытой крышки для этого сеанса.",
    "Enter your administrator password to pause AWDL for this game.": "Введите пароль администратора, чтобы приостановить AWDL для этой игры.",
    "Game detected": "Обнаружена игра",
    "Pausing AWDL to steady your connection.": "Приостанавливаем AWDL для стабилизации соединения.",
    "AWDL resumed": "AWDL возобновлён",
    "The game closed; AirDrop, Handoff and Continuity are back.": "Игра закрыта, AirDrop, Handoff и Continuity снова доступны.",
    "This copy of Keepresso isn't in the Applications folder, so it leaves the helper alone. Install from /Applications.": "Эта копия Keepresso находится не в папке «Программы», поэтому она не трогает помощника. Установите из /Applications.",
    "The helper wasn't found inside the app. Reinstall Keepresso and try again.": "Помощник не найден внутри приложения. Переустановите Keepresso и попробуйте снова.",
    "The helper couldn't be registered.": "Не удалось зарегистрировать помощника.",
    "The helper couldn't be removed: %@": "Не удалось удалить помощника: %@",
    "macOS still reports the helper as registered. Try again, or restart the Mac.": "macOS по-прежнему сообщает, что помощник зарегистрирован. Попробуйте снова или перезагрузите Mac.",
    "Removed. System Settings may keep showing Keepresso under App Background Activity until macOS refreshes its list; restarting the Mac clears the leftover row.": "Удалено. Системные настройки могут продолжать показывать Keepresso в разделе «Фоновая активность приложений», пока macOS не обновит список; перезагрузка Mac убирает оставшуюся запись.",
    "macOS is refusing the helper's registration outright. Reinstall the helper; if that doesn't take, restart the Mac and try once more.": "macOS полностью отказывается регистрировать помощника. Переустановите помощника; если это не поможет, перезагрузите Mac и попробуйте ещё раз.",
    "The helper isn't responding. If an old copy of Keepresso is in the Trash, empty the Trash first: macOS keeps disabling the helper while one is there. Then reinstall the helper.": "Помощник не отвечает. Если в Корзине есть старая копия Keepresso, сначала очистите Корзину: пока она там, macOS продолжает отключать помощника. Затем переустановите помощника.",
    "Old copy stuck in the Trash": "Старая копия застряла в Корзине",
    "An old copy of Keepresso in the Trash keeps the background helper from working. Please delete it from the Trash, or empty the Trash.": "Старая копия Keepresso в Корзине мешает работе фонового помощника. Удалите её из Корзины или очистите Корзину.",
    "Language": "Язык",
    "App language": "Язык приложения",
    "Follow System": "Как в системе",
    "Keepresso follows your system language by default. Changing this relaunches Keepresso so menus, windows, and notifications all switch together.": "По умолчанию Keepresso использует язык системы. Изменение этого параметра перезапускает Keepresso, чтобы меню, окна и уведомления переключились одновременно.",
    "%d h %d min": "%d ч %d мин",
    "%d h": "%d ч",
    "%d min": "%d мин",
    "%d:%02d": "%d:%02d",
    "%ds": "%d с",
    "%d:%02d:%02d": "%d:%02d:%02d",
    "Keepresso: paused, battery low": "Keepresso: приостановлено, низкий заряд",
    "Keepresso: brewing": "Keepresso: заваривание",
    "Keepresso: idle": "Keepresso: простой",
    "1920 × 1080": "1920 × 1080",
    "2560 × 1440": "2560 × 1440",
    "2880 × 1620": "2880 × 1620",
    "3840 × 2160 (4K)": "3840 × 2160 (4K)",
    "Stop in": "Остановить через",
    "Quick stop shortcuts": "Кнопки быстрой остановки",
    "Add Shortcut": "Добавить кнопку",
    "Shortcut %d": "Кнопка %d",
    "Remove shortcut": "Удалить кнопку",
    "One-click “Stop in” buttons shown in the menu while a session runs, so the Mac goes back to sleeping on its own that much later. Up to four; the list stays sorted.": "Кнопки «Остановить через» в один клик, показываемые в меню во время сеанса, чтобы Mac спустя это время снова засыпал сам. До четырёх; список остаётся отсортированным.",
    "Warn before a timed session ends": "Предупреждать перед завершением сеанса по таймеру",
    "Warn": "Предупреждать",
    "1 minute before": "За 1 минуту",
    "2 minutes before": "За 2 минуты",
    "5 minutes before": "За 5 минут",
    "10 minutes before": "За 10 минут",
    "AI agents": "ИИ-агенты",
    "AI agent is working": "ИИ-агент работает",
    "Keeps the Mac awake while a coding-agent session (claude, codex, gemini, aider, and the like) is actively working, judged by its CPU use, and lets it sleep once every session has gone idle for the grace period. The menu lists each detected session. A freshly started session can take a few seconds to read as working.": "Не даёт Mac уснуть, пока сеанс агента для кодинга (claude, codex, gemini, aider и подобные) действительно работает, судя по использованию CPU, и позволяет уснуть, когда все сеансы простаивали в течение периода ожидания. В меню перечислен каждый обнаруженный сеанс. Только что запущенному сеансу может понадобиться несколько секунд, чтобы отобразиться как работающий.",
    "Idle grace period": "Период ожидания после простоя",
    "Instantly": "Сразу",
    "10 minutes": "10 минут",
    "working": "работает",
    "idle": "простаивает",
    "+%d more": "ещё %d",
}


# --- Agent hooks (Claude Code connection) ---
APP.update({
    "Claude Code connected: sessions report working and waiting exactly.": "Claude Code подключён: сеансы точно сообщают о работе и ожидании.",
    "Connect Claude Code for exact session tracking (adds hooks to its settings).": "Подключите Claude Code для точного отслеживания сеансов (добавляет хуки в его настройки).",
    "Connect Claude Code": "Подключить Claude Code",
    "Claude Code's settings file couldn't be read, so it was left untouched.": "Не удалось прочитать файл настроек Claude Code, поэтому он не был изменён.",
    "Couldn't update Claude Code's settings file.": "Не удалось обновить файл настроек Claude Code.",
})
