# -*- coding: utf-8 -*-
# Russian overlay for catalog_core.py: English source -> Russian.
CORE = {
    "On AC power": "От сети",
    "On battery": "От аккумулятора",
    "Charging": "Зарядка",
    "External display connected": "Подключён внешний дисплей",
    "is running": "выполняется",
    "is frontmost": "на переднем плане",
    "Audio playing": "Звук воспроизводится",
    "VPN connected": "VPN подключён",
    "Calendar event in progress": "Идёт событие календаря",
    "Playing a game": "Идёт игра",
    "Camera in use": "Камера используется",
    "Microphone in use": "Микрофон используется",
    "On Wi-Fi “%@”": "В сети Wi-Fi «%@»",
    "Process “%@” running": "Процесс «%@» запущен",
    "Volume “%@” mounted": "Том «%@» подключён",
    "Bluetooth “%@” connected": "Bluetooth «%@» подключён",
    "Downloading in “%@”": "Загрузка в «%@»",
    "CPU above %d%%": "CPU выше %d%%",
    "Network above %@": "Сеть выше %@",
    "App %@": "Приложение %@",
    "Every day": "Каждый день",
    "Weekdays": "Будни",
    "Weekends": "Выходные",
    "Do nothing": "Ничего не делать",
    "Sleep the display": "Усыпить дисплей",
    "Start the screen saver": "Запустить заставку",
    "AI Agent": "ИИ-агент",
    "On AC Power": "От сети",
    "External Display Connected": "Подключён внешний дисплей",
    "Remote Session (SSH)": "Удалённый сеанс (SSH)",
    "Backup Running": "Резервное копирование выполняется",
    "Media Render": "Рендеринг медиа",
    "Meetings": "Встречи",
    "Cloud Gaming": "Облачный гейминг",
    "Remote Control": "Удалённое управление",
    "Remote Login (SSH)": "Удалённый вход (SSH)",
    "Remote Login is on, so you can reach this Mac over SSH.": "Удалённый вход включён, поэтому вы можете подключиться к этому Mac по SSH.",
    "Remote Login is off. You might want to enable it for SSH access to a headless Mac.": "Удалённый вход выключен. Возможно, стоит включить его для доступа по SSH к Mac без монитора.",
    "Couldn't confirm Remote Login. If you want SSH access, enable it in System Settings.": "Не удалось подтвердить состояние удалённого входа. Если нужен доступ по SSH, включите его в Системных настройках.",
    "Screen Sharing": "Общий доступ к экрану",
    "Screen Sharing is on, so you can connect with the Screen Sharing app or VNC.": "Общий доступ к экрану включён, поэтому вы можете подключиться через приложение «Общий доступ к экрану» или VNC.",
    "Screen Sharing is off. You might want to enable it to view a headless Mac's screen.": "Общий доступ к экрану выключен. Возможно, стоит включить его, чтобы видеть экран Mac без монитора.",
    "Couldn't confirm Screen Sharing. If you want remote viewing, enable it in System Settings.": "Не удалось подтвердить состояние общего доступа к экрану. Если нужен удалённый просмотр, включите его в Системных настройках.",
    "Enable it in System Settings ▸ General ▸ Sharing.": "Включите в Системных настройках ▸ Основные ▸ Общий доступ.",
    "Run AI agents on this Mac with MyAgens": "Запускайте ИИ-агентов на этом Mac с MyAgens",
    "MyAgens lets AI agents operate your Mac and help with your work, which is handy on an always-on machine you mostly reach remotely.": "MyAgens позволяет ИИ-агентам управлять вашим Mac и помогать в работе, что удобно на постоянно включённой машине, к которой вы в основном обращаетесь удалённо.",
    "Learn more about MyAgens:": "Подробнее о MyAgens:",
    "GitHub": "GitHub",
    "Read more": "Читать далее",
    "Wake for network access": "Пробуждение для сетевого доступа",
    "The Mac wakes when accessed over the network.": "Mac просыпается при обращении по сети.",
    "The Mac won't wake for network access, so remote logins may fail.": "Mac не будет просыпаться для сетевого доступа, поэтому удалённый вход может не сработать.",
    "Couldn't read the power settings.": "Не удалось прочитать настройки энергопотребления.",
    "Enable “Wake for network access”.": "Включите «Пробуждение для сетевого доступа».",
    "Restart after power failure": "Перезапуск после сбоя питания",
    "The Mac restarts automatically after a power failure.": "Mac автоматически перезапускается после сбоя питания.",
    "The Mac stays off after a power cut, so it won't come back headless.": "После отключения питания Mac остаётся выключенным, поэтому он не включится сам без монитора.",
    "Enable automatic restart after a power failure.": "Включите автоматический перезапуск после сбоя питания.",
    "System sleep disabled": "Сон системы отключён",
    "Idle system sleep is disabled, so the Mac stays reachable.": "Сон системы при бездействии отключён, поэтому Mac остаётся доступным.",
    "The Mac sleeps when idle; Keepresso prevents this while a session runs, but a global setting is safer headless.": "Mac засыпает при бездействии, Keepresso предотвращает это во время сеанса, но глобальная настройка надёжнее без монитора.",
    "Disable idle system sleep.": "Отключите сон системы при бездействии.",
    "FileVault disabled": "FileVault отключён",
    "FileVault is off, so the Mac can reboot unattended to the login window.": "FileVault выключен, поэтому Mac может перезагрузиться без присмотра до окна входа.",
    "FileVault is on, so a reboot blocks at the disk-unlock screen until someone types the password, defeating headless restart.": "FileVault включён, поэтому перезагрузка останавливается на экране разблокировки диска, пока кто-то не введёт пароль, что делает невозможным перезапуск без монитора.",
    "Couldn't determine the FileVault status.": "Не удалось определить состояние FileVault.",
    "For an unattended Mac, consider turning FileVault off (weigh the security trade-off).": "Для Mac без присмотра рассмотрите возможность отключения FileVault (взвесив компромисс с безопасностью).",
    "Automatic login": "Автоматический вход",
    "Automatic login is on (%@), so the Mac reaches the desktop after a reboot without a keyboard.": "Автоматический вход включён (%@), поэтому Mac попадает на рабочий стол после перезагрузки без клавиатуры.",
    "Automatic login is off. After a reboot the Mac waits at the login window for a password.": "Автоматический вход выключен. После перезагрузки Mac ожидает пароль в окне входа.",
    "Turn on automatic login for this account.": "Включите автоматический вход для этой учётной записи.",
    "Keepresso stopped": "Keepresso остановлен",
    "Your keep-awake session has ended.": "Ваш сеанс поддержания активности завершён.",
    "Paused on low battery": "Приостановлено из-за низкого заряда",
    "Battery is at %d%%. Keepresso is letting the Mac sleep until you plug in to charge.": "Заряд батареи %d%%. Keepresso позволяет Mac заснуть, пока вы не подключите зарядку.",
    "Keepresso is still brewing": "Keepresso всё ещё заваривает",
    "Your Mac is still awake. It's been %@.": "Ваш Mac всё ещё не спит. Прошло %@.",
    "Your Mac has been kept awake for %@.": "Ваш Mac не давали заснуть в течение %@.",
    "Started manually": "Запущено вручную",
    "Restarted manually": "Перезапущено вручную",
    "Started by a command": "Запущено командой",
    "Restarted by a command": "Перезапущено командой",
    "Timed session ended": "Сеанс с таймером завершён",
    "Paused, battery below %d%%": "Приостановлено, заряд ниже %d%%",
    "Not started, battery below %d%%": "Не запущено, заряд ниже %d%%",
    "Stopped manually": "Остановлено вручную",
    "Stopped by a command": "Остановлено командой",
    "Trigger conditions met": "Условия триггера выполнены",
    "Trigger conditions ended": "Условия триггера перестали выполняться",
    "Triggers: %@": "Триггеры: %@",
    "%@ (+%ds)": "%@ (+%d с)",
    "Couldn't create the watchdog flag file.": "Не удалось создать флаг-файл сторожа.",
    "Couldn't run the watchdog command.": "Не удалось выполнить команду сторожа.",
    "The watchdog couldn't be started.": "Не удалось запустить сторож.",
    "Couldn't create the sleep watchdog flag file.": "Не удалось создать флаг-файл сторожа сна.",
    "Couldn't run the sleep watchdog command.": "Не удалось выполнить команду сторожа сна.",
    "The sleep watchdog couldn't be started.": "Не удалось запустить сторож сна.",
    "Couldn't run the sleep setting command.": "Не удалось выполнить команду настройки сна.",
    "The sleep setting couldn't be changed.": "Не удалось изменить настройку сна.",
    "The Keepresso helper isn't responding.": "Помощник Keepresso не отвечает.",
    "The Keepresso helper couldn't change the setting.": "Помощник Keepresso не смог изменить настройку.",
    "Virtual displays aren't available on this macOS version.": "Виртуальные дисплеи недоступны в этой версии macOS.",
    "Couldn't create the virtual display.": "Не удалось создать виртуальный дисплей.",
    "Preventing system sleep": "Предотвращение сна системы",
    "Preventing display sleep": "Предотвращение сна дисплея",
    "Keeping disks awake": "Поддержание дисков активными",
    "Declaring the user active": "Объявление пользователя активным",
    "Holding off idle sleep for a background task": "Отсрочка сна при бездействии для фоновой задачи",
    "Not enough replies to measure.": "Недостаточно ответов для измерения.",
    "Baseline %d ms": "База %d мс",
    "%d spike up to %d ms": "%d всплеск до %d мс",
    "%d spikes up to %d ms": "%d всплесков до %d мс",
    "max %d ms": "макс. %d мс",
    "%d lost": "%d потеряно",
    "Wired network": "Проводная сеть",
    "Couldn't read the network interfaces.": "Не удалось прочитать сетевые интерфейсы.",
    "Ethernet is connected (%@). A wired link sidesteps Wi-Fi jitter entirely, the most reliable fix.": "Ethernet подключён (%@). Проводное соединение полностью исключает джиттер Wi-Fi, это самое надёжное решение.",
    "An Ethernet adapter is available but no cable is connected.": "Адаптер Ethernet доступен, но кабель не подключён.",
    "For gaming or streaming, a wired connection beats any Wi-Fi tuning.": "Для игр или стриминга проводное соединение превосходит любую настройку Wi-Fi.",
    "No wired network adapter found.": "Проводной сетевой адаптер не найден.",
    "A USB-C or Thunderbolt Ethernet adapter sidesteps Wi-Fi jitter entirely.": "Адаптер Ethernet USB-C или Thunderbolt полностью исключает джиттер Wi-Fi.",
    "Wi-Fi channel": "Канал Wi-Fi",
    "Not connected to Wi-Fi, or its details are unreadable.": "Нет подключения к Wi-Fi, либо его данные нельзя прочитать.",
    "If you game or stream over Wi-Fi, re-check while connected.": "Если вы играете или стримите по Wi-Fi, проверьте ещё раз при подключении.",
    "channel %d at %d MHz": "канал %d на %d МГц",
    "channel %d": "канал %d",
    "On 2.4 GHz (%@), the slowest band, where every AWDL hop costs the most.": "На 2,4 ГГц (%@), самом медленном диапазоне, где каждый переход AWDL обходится дороже всего.",
    "Prefer a 5 GHz network on %@ at 80 MHz. If 2.4 GHz is unavoidable, set the router to channel 6, AWDL's 2.4 GHz social channel.": "Предпочтительнее сеть 5 ГГц на %@ с шириной 80 МГц. Если 2,4 ГГц не избежать, настройте роутер на канал 6, социальный канал AWDL на 2,4 ГГц.",
    "On 6 GHz (%@). AWDL's social channels live on 2.4 and 5 GHz, so there's nothing to align here. If stutter persists, a 5 GHz network on %@ keeps AWDL's hops on-channel.": "На 6 ГГц (%@). Социальные каналы AWDL находятся на 2,4 и 5 ГГц, поэтому здесь выравнивать нечего. Если подтормаживания сохраняются, сеть 5 ГГц на %@ удерживает переходы AWDL в пределах канала.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel.": "На %@, что совпадает с социальным каналом AWDL на 5 ГГц, поэтому его переходы остаются в пределах канала.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel. Raising the router to 80 MHz width completes the alignment.": "На %@, что совпадает с социальным каналом AWDL на 5 ГГц, поэтому его переходы остаются в пределах канала. Увеличение ширины канала роутера до 80 МГц завершает выравнивание.",
    "On 5 GHz %@. AWDL's off-channel hops leave this channel roughly every second.": "На 5 ГГц %@. Переходы AWDL за пределы канала покидают этот канал примерно раз в секунду.",
    "Set the router to %@ at 80 MHz so AWDL's hops stay on-channel.": "Настройте роутер на %@ с шириной 80 МГц, чтобы переходы AWDL оставались в пределах канала.",
    "channel 44 (the EU social channel) or 149 (the US and Canada social channel), whichever your region allows": "канал 44 (социальный канал ЕС) или 149 (социальный канал США и Канады), в зависимости от того, что разрешено в вашем регионе",
    "channel 44, AWDL's 5 GHz social channel in the EU": "канал 44, социальный канал AWDL на 5 ГГц в ЕС",
    "channel 149, AWDL's 5 GHz social channel where UNII-3 is allowed (the US, Canada, and most of the world)": "канал 149, социальный канал AWDL на 5 ГГц там, где разрешён UNII-3 (США, Канада и большая часть мира)",
    "Bluetooth during play": "Bluetooth во время игры",
    "Bluetooth is on. It shares the radio chip with Wi-Fi, so heavy Bluetooth traffic (audio, controllers) can add its own blips.": "Bluetooth включён. Он использует тот же радиочип, что и Wi-Fi, поэтому интенсивный трафик Bluetooth (звук, контроллеры) может добавлять собственные помехи.",
    "Nothing to fix: just a variable to know about if stutter persists on a clean channel.": "Исправлять нечего: просто фактор, о котором стоит знать, если подтормаживания сохраняются на чистом канале.",
    "Bluetooth is off, so it isn't competing with Wi-Fi for the radio.": "Bluetooth выключен, поэтому не конкурирует с Wi-Fi за радиомодуль.",
    "Couldn't read the Bluetooth radio state.": "Не удалось прочитать состояние радиомодуля Bluetooth.",
    "Game Mode": "Игровой режим",
    "macOS turns on Game Mode by itself when a game runs full screen: the game gets CPU and GPU priority, and Bluetooth controllers and audio get faster sampling. If the game-controller icon doesn't appear in the menu bar while playing, put the game into full screen.": "macOS сам включает игровой режим, когда игра запущена в полноэкранном режиме: игра получает приоритет CPU и GPU, а Bluetooth-контроллеры и звук получают более быструю дискретизацию. Если значок игрового контроллера не появляется в строке меню во время игры, переключите игру в полноэкранный режим.",
    "How Game Mode works:": "Как работает игровой режим:",
    "Learn more": "Подробнее",
    "Cloud gaming in the browser": "Облачный гейминг в браузере",
    "Xbox Cloud Gaming and the web versions of GeForce NOW run in a browser tab, so there's no app for the gaming condition to spot. The “Audio playing” condition covers them: game sound keeps the session brewing.": "Xbox Cloud Gaming и веб-версии GeForce NOW работают во вкладке браузера, поэтому нет отдельного приложения, которое могло бы обнаружить условие игры. Их покрывает условие «Звук воспроизводится»: звук игры поддерживает сеанс активным.",
    "Add it under Preferences ▸ Triggers ▸ Add ▸ Apps & Activity ▸ Media.": "Добавьте его в Настройки ▸ Триггеры ▸ Добавить ▸ Приложения и активность ▸ Медиа.",
    "Location Services and Wi-Fi scans": "Службы геопозиции и сканирование Wi-Fi",
    "Location Services triggers independent Wi-Fi scans, another source of occasional blips. Keepresso itself uses Location to read Wi-Fi network names for triggers, so weigh that before turning anything off.": "Службы геопозиции запускают независимые сканирования Wi-Fi, ещё один источник случайных помех. Сам Keepresso использует геопозицию, чтобы читать имена сетей Wi-Fi для триггеров, поэтому взвесьте это, прежде чем что-либо отключать.",
    "Review which apps use Location:": "Проверьте, какие приложения используют геопозицию:",
    "Why streams stutter once a second": "Почему трансляции подтормаживают раз в секунду",
    "The Wi-Fi radio hops off-channel for AWDL (AirDrop, Handoff, Sidecar, Continuity) roughly every second, which shows up as 50-100 ms ping spikes. The jitter test reproduces the diagnosis; the AWDL watchdog is the session-scoped fix.": "Радиомодуль Wi-Fi переключается на другой канал для AWDL (AirDrop, Handoff, Sidecar, Continuity) примерно раз в секунду, что проявляется как всплески пинга на 50-100 мс. Тест джиттера воспроизводит эту диагностику, сторож AWDL является решением в рамках сеанса.",
    "The full story:": "Подробное объяснение:",
    "Keepresso stops soon": "Keepresso скоро остановится",
    "Your keep-awake session ends in about %@.": "Ваш сеанс поддержания активности завершится примерно через %@.",
    "AI agent working": "ИИ-агент работает",
}

WIDGET = {
    "Keep Awake": "Не засыпать",
    "See and control whether Keepresso is keeping the Mac awake.": "Посмотрите и управляйте тем, поддерживает ли Keepresso активность Mac.",
    "Start or stop keeping the Mac awake.": "Начните или остановите поддержание активности Mac.",
    "Keepresso": "Keepresso",
    "Brewing": "Заваривание",
    "Off": "Выкл",
    "Keeping the Mac awake": "Mac не засыпает",
    "The Mac can sleep": "Mac может заснуть",
    "Stop": "Остановить",
    "Start": "Начать",
    "Resume Triggers": "Возобновить триггеры",
    "Pause Triggers": "Приостановить триггеры",
}


# --- Agent hooks (Claude Code connection) ---
CORE.update({
    "running command": "выполняет команду",
    "editing": "редактирует",
    "reading": "читает",
    "searching": "ищет",
    "running subagent": "выполняет субагента",
    "browsing": "просматривает веб",
    "using %@": "использует %@",
    "waiting for approval": "ожидает подтверждения",
    "waiting": "ожидает",
    "terminal": "терминал",
    "Claude app": "приложение Claude",
    "IDE": "IDE",
})


# v1.15 thermal safety net: pressure levels and heat-pause lines.
CORE.update({
    "Critical": "Критическое",
    "Fair": "Умеренное",
    "Keepresso stopped the keep-awake session so the Mac can cool down. It resumes when temperatures recover.": "Keepresso остановил сеанс поддержания активности, чтобы Mac мог остыть. Сеанс возобновится, когда температура придёт в норму.",
    "Nominal": "Номинальное",
    "Not started, the Mac is running hot": "Не запущено, Mac разогрелся",
    "Paused on high temperature": "Приостановлено из-за высокой температуры",
    "Paused, the Mac is running hot": "Приостановлено, Mac разогрелся",
    "Serious": "Серьёзное",
    # 1.16.0 fill (16)
    'Lock the screen': 'Заблокировать экран',
    'Sleep the Mac': 'Усыпить Mac',
    'Session started': 'Сеанс начат',
    'Session ended': 'Сеанс завершён',
    'Trigger fired': 'Условие сработало',
    'Trigger released': 'Условие снято',
    'Battery pause': 'Пауза по батарее',
    'Thermal pause': 'Термическая пауза',
    'Thermal stage changed': 'Термическая стадия изменилась',
    'Agent went idle': 'Агент простаивает',
    'Shortcut: %@': 'Команда: %@',
    'Webhook: %@': 'Вебхук: %@',
    'Command: %@': 'Команда: %@',
    '+%ds': '+%d с',
    'waiting counts': 'ожидание считается',
    '%@ (%@)': '%@ (%@)',

    # 1.17.0 automation leases
    "Automation lease: %@": "Аренда автоматизации: %@",
    "Automation lease acquired": "Аренда автоматизации получена",
    "Automation lease ended": "Аренда автоматизации завершена",

    # 1.17.0 controller trigger, second batch
    "Game controller connected": "Подключён игровой контроллер",
    "Steam is downloading": "Steam выполняет загрузку",

})

# 1.18 strings
CORE.update({
    "Microphone in use by %@": "Микрофон используется приложением %@",
    "Microphone in use by app": "Микрофон используется приложением",
})
