# -*- coding: utf-8 -*-
# Turkish overlay for catalog_core.py: English source -> Turkish.
CORE = {
    "On AC power": "Elektrik gücündeyken",
    "On battery": "Pil gücündeyken",
    "Charging": "Şarj oluyor",
    "External display connected": "Harici ekran bağlı",
    "is running": "çalışıyor",
    "is frontmost": "önde",
    "Audio playing": "Ses çalınıyor",
    "VPN connected": "VPN bağlı",
    "Calendar event in progress": "Takvim etkinliği devam ediyor",
    "Playing a game": "Oyun oynanıyor",
    "Camera in use": "Kamera kullanımda",
    "Microphone in use": "Mikrofon kullanımda",
    "On Wi-Fi “%@”": "“%@” Wi-Fi ağındayken",
    "Process “%@” running": "“%@” işlemi çalışıyor",
    "Volume “%@” mounted": "“%@” birimi bağlı",
    "Bluetooth “%@” connected": "Bluetooth “%@” bağlı",
    "Downloading in “%@”": "“%@” içinde indiriliyor",
    "CPU above %d%%": "İşlemci %d%%'nin üzerinde",
    "Network above %@": "Ağ %@ üzerinde",
    "App %@": "%@ uygulaması",
    "Every day": "Her gün",
    "Weekdays": "Hafta içi",
    "Weekends": "Hafta sonu",
    "Do nothing": "Hiçbir şey yapma",
    "Sleep the display": "Ekranı uyut",
    "Start the screen saver": "Ekran koruyucuyu başlat",
    "AI Agent": "Yapay Zeka Aracısı",
    "On AC Power": "Elektrik Gücündeyken",
    "External Display Connected": "Harici Ekran Bağlı",
    "Remote Session (SSH)": "Uzak Oturum (SSH)",
    "Backup Running": "Yedekleme Çalışıyor",
    "Media Render": "Medya İşleme",
    "Meetings": "Toplantılar",
    "Cloud Gaming": "Bulut Oyun",
    "Remote Control": "Uzaktan Kumanda",
    "Remote Login (SSH)": "Uzaktan Oturum Açma (SSH)",
    "Remote Login is on, so you can reach this Mac over SSH.": "Uzaktan Oturum Açma açık, bu nedenle bu Mac'e SSH üzerinden ulaşabilirsiniz.",
    "Remote Login is off. You might want to enable it for SSH access to a headless Mac.": "Uzaktan Oturum Açma kapalı. Ekransız bir Mac'e SSH erişimi için bunu etkinleştirmek isteyebilirsiniz.",
    "Couldn't confirm Remote Login. If you want SSH access, enable it in System Settings.": "Uzaktan Oturum Açma doğrulanamadı. SSH erişimi istiyorsanız Sistem Ayarları'nda etkinleştirin.",
    "Screen Sharing": "Ekran Paylaşımı",
    "Screen Sharing is on, so you can connect with the Screen Sharing app or VNC.": "Ekran Paylaşımı açık, bu nedenle Ekran Paylaşımı uygulaması veya VNC ile bağlanabilirsiniz.",
    "Screen Sharing is off. You might want to enable it to view a headless Mac's screen.": "Ekran Paylaşımı kapalı. Ekransız bir Mac'in ekranını görüntülemek için bunu etkinleştirmek isteyebilirsiniz.",
    "Couldn't confirm Screen Sharing. If you want remote viewing, enable it in System Settings.": "Ekran Paylaşımı doğrulanamadı. Uzaktan görüntüleme istiyorsanız Sistem Ayarları'nda etkinleştirin.",
    "Enable it in System Settings ▸ General ▸ Sharing.": "Sistem Ayarları ▸ Genel ▸ Paylaşım bölümünden etkinleştirin.",
    "Run AI agents on this Mac with MyAgens": "MyAgens ile bu Mac'te yapay zeka aracıları çalıştırın",
    "MyAgens lets AI agents operate your Mac and help with your work, which is handy on an always-on machine you mostly reach remotely.": "MyAgens, yapay zeka aracılarının Mac'inizi kullanmasına ve işinizde yardımcı olmasına olanak tanır; bu, çoğunlukla uzaktan eriştiğiniz her zaman açık bir makinede kullanışlıdır.",
    "Learn more about MyAgens:": "MyAgens hakkında daha fazla bilgi edinin:",
    "GitHub": "GitHub",
    "Read more": "Devamını oku",
    "Wake for network access": "Ağ erişimi için uyan",
    "The Mac wakes when accessed over the network.": "Mac, ağ üzerinden erişildiğinde uyanır.",
    "The Mac won't wake for network access, so remote logins may fail.": "Mac, ağ erişimi için uyanmaz, bu nedenle uzaktan oturum açmalar başarısız olabilir.",
    "Couldn't read the power settings.": "Güç ayarları okunamadı.",
    "Enable “Wake for network access”.": "“Ağ erişimi için uyan” seçeneğini etkinleştirin.",
    "Restart after power failure": "Elektrik kesintisinden sonra yeniden başlat",
    "The Mac restarts automatically after a power failure.": "Mac, elektrik kesintisinden sonra otomatik olarak yeniden başlar.",
    "The Mac stays off after a power cut, so it won't come back headless.": "Mac, elektrik kesintisinden sonra kapalı kalır, bu nedenle ekransız olarak geri gelmez.",
    "Enable automatic restart after a power failure.": "Elektrik kesintisinden sonra otomatik yeniden başlatmayı etkinleştirin.",
    "System sleep disabled": "Sistem uykusu devre dışı",
    "Idle system sleep is disabled, so the Mac stays reachable.": "Boşta sistem uykusu devre dışı, bu nedenle Mac erişilebilir kalır.",
    "The Mac sleeps when idle; Keepresso prevents this while a session runs, but a global setting is safer headless.": "Mac boştayken uyur; Keepresso bir oturum çalışırken bunu engeller, ancak ekransız kullanımda genel bir ayar daha güvenlidir.",
    "Disable idle system sleep.": "Boşta sistem uykusunu devre dışı bırakın.",
    "FileVault disabled": "FileVault devre dışı",
    "FileVault is off, so the Mac can reboot unattended to the login window.": "FileVault kapalı, bu nedenle Mac gözetimsiz olarak oturum açma ekranına yeniden başlayabilir.",
    "FileVault is on, so a reboot blocks at the disk-unlock screen until someone types the password, defeating headless restart.": "FileVault açık, bu nedenle yeniden başlatma, biri parolayı yazana kadar disk kilidi açma ekranında takılır ve bu da ekransız yeniden başlatmayı engeller.",
    "Couldn't determine the FileVault status.": "FileVault durumu belirlenemedi.",
    "For an unattended Mac, consider turning FileVault off (weigh the security trade-off).": "Gözetimsiz bir Mac için FileVault'u kapatmayı düşünün (güvenlik ödünleşimini göz önünde bulundurun).",
    "Automatic login": "Otomatik oturum açma",
    "Automatic login is on (%@), so the Mac reaches the desktop after a reboot without a keyboard.": "Otomatik oturum açma açık (%@), bu nedenle Mac klavye olmadan yeniden başlatmanın ardından masaüstüne ulaşır.",
    "Automatic login is off. After a reboot the Mac waits at the login window for a password.": "Otomatik oturum açma kapalı. Yeniden başlatmanın ardından Mac, oturum açma ekranında bir parola bekler.",
    "Turn on automatic login for this account.": "Bu hesap için otomatik oturum açmayı etkinleştirin.",
    "Keepresso stopped": "Keepresso durdu",
    "Your keep-awake session has ended.": "Uyanık tutma oturumunuz sona erdi.",
    "Paused on low battery": "Düşük pilde duraklatıldı",
    "Battery is at %d%%. Keepresso is letting the Mac sleep until you plug in to charge.": "Pil %d%%'de. Siz şarja takana kadar Keepresso, Mac'in uyumasına izin veriyor.",
    "Keepresso is still brewing": "Keepresso hâlâ demleniyor",
    "Your Mac is still awake. It's been %@.": "Mac'iniz hâlâ uyanık. %@ oldu.",
    "Your Mac has been kept awake for %@.": "Mac'iniz %@ süredir uyanık tutuluyor.",
    "Started manually": "El ile başlatıldı",
    "Restarted manually": "El ile yeniden başlatıldı",
    "Started by a command": "Bir komutla başlatıldı",
    "Restarted by a command": "Bir komutla yeniden başlatıldı",
    "Timed session ended": "Zamanlanmış oturum sona erdi",
    "Paused, battery below %d%%": "Duraklatıldı, pil %d%%'nin altında",
    "Not started, battery below %d%%": "Başlatılmadı, pil %d%%'nin altında",
    "Stopped manually": "El ile durduruldu",
    "Stopped by a command": "Bir komutla durduruldu",
    "Trigger conditions met": "Tetikleyici koşulları karşılandı",
    "Trigger conditions ended": "Tetikleyici koşulları sona erdi",
    "Triggers: %@": "Tetikleyiciler: %@",
    "%@ (+%ds)": "%@ (+%d sn)",
    "Couldn't create the watchdog flag file.": "Gözcü işaret dosyası oluşturulamadı.",
    "Couldn't run the watchdog command.": "Gözcü komutu çalıştırılamadı.",
    "The watchdog couldn't be started.": "Gözcü başlatılamadı.",
    "Couldn't create the sleep watchdog flag file.": "Uyku gözcüsü işaret dosyası oluşturulamadı.",
    "Couldn't run the sleep watchdog command.": "Uyku gözcüsü komutu çalıştırılamadı.",
    "The sleep watchdog couldn't be started.": "Uyku gözcüsü başlatılamadı.",
    "Couldn't run the sleep setting command.": "Uyku ayarı komutu çalıştırılamadı.",
    "The sleep setting couldn't be changed.": "Uyku ayarı değiştirilemedi.",
    "The Keepresso helper isn't responding.": "Keepresso yardımcısı yanıt vermiyor.",
    "The Keepresso helper couldn't change the setting.": "Keepresso yardımcısı ayarı değiştiremedi.",
    "Virtual displays aren't available on this macOS version.": "Sanal ekranlar bu macOS sürümünde kullanılamıyor.",
    "Couldn't create the virtual display.": "Sanal ekran oluşturulamadı.",
    "Preventing system sleep": "Sistem uykusunu engelliyor",
    "Preventing display sleep": "Ekran uykusunu engelliyor",
    "Keeping disks awake": "Diskleri uyanık tutuyor",
    "Declaring the user active": "Kullanıcıyı etkin olarak bildiriyor",
    "Holding off idle sleep for a background task": "Bir arka plan görevi için boşta uykuyu erteliyor",
    "Not enough replies to measure.": "Ölçmek için yeterli yanıt yok.",
    "Baseline %d ms": "Taban değer %d ms",
    "%d spike up to %d ms": "%d sıçrama, %d ms'e kadar",
    "%d spikes up to %d ms": "%d sıçrama, %d ms'e kadar",
    "max %d ms": "en fazla %d ms",
    "%d lost": "%d kayıp",
    "Wired network": "Kablolu ağ",
    "Couldn't read the network interfaces.": "Ağ arayüzleri okunamadı.",
    "Ethernet is connected (%@). A wired link sidesteps Wi-Fi jitter entirely, the most reliable fix.": "Ethernet bağlı (%@). Kablolu bağlantı, Wi-Fi jitter'ını tamamen ortadan kaldırır; en güvenilir çözüm budur.",
    "An Ethernet adapter is available but no cable is connected.": "Bir Ethernet bağdaştırıcısı mevcut ancak kablo bağlı değil.",
    "For gaming or streaming, a wired connection beats any Wi-Fi tuning.": "Oyun veya yayın için kablolu bağlantı, herhangi bir Wi-Fi ayarlamasından üstündür.",
    "No wired network adapter found.": "Kablolu ağ bağdaştırıcısı bulunamadı.",
    "A USB-C or Thunderbolt Ethernet adapter sidesteps Wi-Fi jitter entirely.": "Bir USB-C veya Thunderbolt Ethernet bağdaştırıcısı, Wi-Fi jitter'ını tamamen ortadan kaldırır.",
    "Wi-Fi channel": "Wi-Fi kanalı",
    "Not connected to Wi-Fi, or its details are unreadable.": "Wi-Fi'ye bağlı değil veya ayrıntıları okunamıyor.",
    "If you game or stream over Wi-Fi, re-check while connected.": "Wi-Fi üzerinden oyun oynuyor veya yayın yapıyorsanız, bağlıyken yeniden kontrol edin.",
    "channel %d at %d MHz": "%d. kanal, %d MHz",
    "channel %d": "%d. kanal",
    "On 2.4 GHz (%@), the slowest band, where every AWDL hop costs the most.": "2.4 GHz'de (%@), her AWDL sıçramasının en pahalıya mal olduğu en yavaş bantta.",
    "Prefer a 5 GHz network on %@ at 80 MHz. If 2.4 GHz is unavoidable, set the router to channel 6, AWDL's 2.4 GHz social channel.": "%@ üzerinde 80 MHz'de bir 5 GHz ağı tercih edin. 2.4 GHz kaçınılmazsa, yönlendiriciyi AWDL'nin 2.4 GHz sosyal kanalı olan 6. kanala ayarlayın.",
    "On 6 GHz (%@). AWDL's social channels live on 2.4 and 5 GHz, so there's nothing to align here. If stutter persists, a 5 GHz network on %@ keeps AWDL's hops on-channel.": "6 GHz'de (%@). AWDL'nin sosyal kanalları 2.4 ve 5 GHz'de bulunur, bu nedenle burada hizalanacak bir şey yok. Takılmalar sürerse, %@ üzerindeki bir 5 GHz ağı AWDL'nin sıçramalarını kanalda tutar.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel.": "%@ üzerinde, AWDL'nin 5 GHz sosyal kanalıyla hizalı, bu nedenle sıçramaları kanalda kalır.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel. Raising the router to 80 MHz width completes the alignment.": "%@ üzerinde, AWDL'nin 5 GHz sosyal kanalıyla hizalı, bu nedenle sıçramaları kanalda kalır. Yönlendiriciyi 80 MHz genişliğe çıkarmak hizalamayı tamamlar.",
    "On 5 GHz %@. AWDL's off-channel hops leave this channel roughly every second.": "5 GHz %@ üzerinde. AWDL'nin kanal dışı sıçramaları bu kanalı yaklaşık her saniye terk eder.",
    "Set the router to %@ at 80 MHz so AWDL's hops stay on-channel.": "AWDL'nin sıçramalarının kanalda kalması için yönlendiriciyi 80 MHz'de %@ olarak ayarlayın.",
    "channel 44 (the EU social channel) or 149 (the US and Canada social channel), whichever your region allows": "44. kanal (AB sosyal kanalı) veya 149. kanal (ABD ve Kanada sosyal kanalı), bölgenizin izin verdiği hangisiyse",
    "channel 44, AWDL's 5 GHz social channel in the EU": "44. kanal, AWDL'nin AB'deki 5 GHz sosyal kanalı",
    "channel 149, AWDL's 5 GHz social channel where UNII-3 is allowed (the US, Canada, and most of the world)": "149. kanal, UNII-3'ün izin verildiği yerlerde (ABD, Kanada ve dünyanın çoğu) AWDL'nin 5 GHz sosyal kanalı",
    "Bluetooth during play": "Oyun sırasında Bluetooth",
    "Bluetooth is on. It shares the radio chip with Wi-Fi, so heavy Bluetooth traffic (audio, controllers) can add its own blips.": "Bluetooth açık. Radyo yongasını Wi-Fi ile paylaşır, bu nedenle yoğun Bluetooth trafiği (ses, denetleyiciler) kendi kesintilerini ekleyebilir.",
    "Nothing to fix: just a variable to know about if stutter persists on a clean channel.": "Düzeltilecek bir şey yok: yalnızca temiz bir kanalda takılma devam ederse bilinmesi gereken bir değişken.",
    "Bluetooth is off, so it isn't competing with Wi-Fi for the radio.": "Bluetooth kapalı, bu nedenle radyo için Wi-Fi ile rekabet etmiyor.",
    "Couldn't read the Bluetooth radio state.": "Bluetooth radyo durumu okunamadı.",
    "Game Mode": "Oyun Modu",
    "macOS turns on Game Mode by itself when a game runs full screen: the game gets CPU and GPU priority, and Bluetooth controllers and audio get faster sampling. If the game-controller icon doesn't appear in the menu bar while playing, put the game into full screen.": "macOS, bir oyun tam ekran çalıştığında Oyun Modu'nu kendiliğinden açar: oyun, işlemci ve grafik işlemcisi önceliği alır, Bluetooth denetleyicileri ve ses ise daha hızlı örnekleme elde eder. Oynarken menü çubuğunda oyun denetleyicisi simgesi görünmüyorsa, oyunu tam ekrana alın.",
    "How Game Mode works:": "Oyun Modu nasıl çalışır:",
    "Learn more": "Daha fazla bilgi edinin",
    "Cloud gaming in the browser": "Tarayıcıda bulut oyun",
    "Xbox Cloud Gaming and the web versions of GeForce NOW run in a browser tab, so there's no app for the gaming condition to spot. The “Audio playing” condition covers them: game sound keeps the session brewing.": "Xbox Cloud Gaming ve GeForce NOW'ın web sürümleri bir tarayıcı sekmesinde çalışır, bu nedenle oyun koşulunun tespit edebileceği bir uygulama yoktur. “Ses çalınıyor” koşulu bunları kapsar: oyun sesi oturumu demlenir durumda tutar.",
    "Add it under Preferences ▸ Triggers ▸ Add ▸ Apps & Activity ▸ Media.": "Tercihler ▸ Tetikleyiciler ▸ Ekle ▸ Uygulamalar ve Etkinlik ▸ Medya altına ekleyin.",
    "Location Services and Wi-Fi scans": "Konum Servisleri ve Wi-Fi taramaları",
    "Location Services triggers independent Wi-Fi scans, another source of occasional blips. Keepresso itself uses Location to read Wi-Fi network names for triggers, so weigh that before turning anything off.": "Konum Servisleri, bağımsız Wi-Fi taramalarını tetikler; bu da ara sıra oluşan kesintilerin bir başka kaynağıdır. Keepresso'nun kendisi de tetikleyiciler için Wi-Fi ağı adlarını okumak amacıyla Konum'u kullanır, bu nedenle herhangi bir şeyi kapatmadan önce bunu göz önünde bulundurun.",
    "Review which apps use Location:": "Hangi uygulamaların Konum kullandığını gözden geçirin:",
    "Why streams stutter once a second": "Yayınlar neden saniyede bir takılır",
    "The Wi-Fi radio hops off-channel for AWDL (AirDrop, Handoff, Sidecar, Continuity) roughly every second, which shows up as 50-100 ms ping spikes. The jitter test reproduces the diagnosis; the AWDL watchdog is the session-scoped fix.": "Wi-Fi radyosu, AWDL (AirDrop, Handoff, Sidecar, Continuity) için yaklaşık her saniye kanal dışına sıçrar; bu da 50-100 ms'lik ping sıçramaları olarak ortaya çıkar. Jitter testi bu teşhisi yeniden üretir; AWDL gözcüsü oturuma özgü çözümdür.",
    "The full story:": "Tüm detaylar:",
    "Keepresso stops soon": "Keepresso yakında duracak",
    "Your keep-awake session ends in about %@.": "Uyanık tutma oturumunuz yaklaşık %@ içinde sona erecek.",
    "AI agent working": "Yapay zeka aracısı çalışıyor",
}

WIDGET = {
    "Keep Awake": "Uyanık Tut",
    "See and control whether Keepresso is keeping the Mac awake.": "Keepresso'nun Mac'i uyanık tutup tutmadığını görün ve denetleyin.",
    "Start or stop keeping the Mac awake.": "Mac'i uyanık tutmayı başlatın veya durdurun.",
    "Keepresso": "Keepresso",
    "Brewing": "Demleniyor",
    "Off": "Kapalı",
    "Keeping the Mac awake": "Mac uyanık tutuluyor",
    "The Mac can sleep": "Mac uyuyabilir",
    "Stop": "Durdur",
    "Start": "Başlat",
    "Resume Triggers": "Tetikleyicileri Sürdür",
    "Pause Triggers": "Tetikleyicileri Duraklat",
}


# --- Agent hooks (Claude Code connection) ---
CORE.update({
    "run": "çalıştır",
    "write": "yaz",
    "read": "oku",
    "search": "ara",
    "subagent": "alt ajan",
    "browse": "gez",
    "tool": "araç",
    "permission": "izin",
    "wait": "bekle",
    "terminal": "terminal",
    "Claude app": "Claude uygulaması",
    "IDE": "IDE",
})

# v1.15 thermal safety net: pressure levels and heat-pause lines.
CORE.update({
    "Critical": "Kritik",
    "Fair": "Makul",
    "Keepresso stopped the keep-awake session so the Mac can cool down. It resumes when temperatures recover.": "Keepresso, Mac'in soğuyabilmesi için uyanık tutma oturumunu durdurdu. Sıcaklıklar normale döndüğünde sürdürülür.",
    "Nominal": "Normal",
    "Not started, the Mac is running hot": "Başlatılmadı, Mac aşırı ısınıyor",
    "Paused on high temperature": "Yüksek sıcaklıkta duraklatıldı",
    "Paused, the Mac is running hot": "Duraklatıldı, Mac aşırı ısınıyor",
    "Serious": "Ciddi",
    # 1.16.0 fill (16)
    'Lock the screen': 'Ekranı kilitle',
    'Sleep the Mac': 'Mac’i uyut',
    'Session started': 'Oturum başladı',
    'Session ended': 'Oturum bitti',
    'Trigger fired': 'Tetikleyici ateşlendi',
    'Trigger released': 'Tetikleyici bırakıldı',
    'Battery pause': 'Pil duraklatması',
    'Thermal pause': 'Isı duraklatması',
    'Thermal stage changed': 'Isı aşaması değişti',
    'Agent went idle': 'Ajan boşta',
    'Shortcut: %@': 'Kestirme: %@',
    'Webhook: %@': 'Webhook: %@',
    'Command: %@': 'Komut: %@',
    '+%ds': '+%d sn',
    'waiting counts': 'bekleme sayılır',
    '%@ (%@)': '%@ (%@)',

})

# v1.17 automation leases
CORE.update({
    "Automation lease: %@": "Otomasyon kirası: %@",
    "Automation lease acquired": "Otomasyon kirası alındı",
    "Automation lease ended": "Otomasyon kirası sona erdi",
})

# Controller trigger, new in the 1.17 cycle (second batch).
CORE.update({
    "Game controller connected": "Oyun denetleyicisi bağlı",
    "Steam is downloading": "Steam indiriyor",
})

# 1.18 strings
CORE.update({
    "Microphone in use by %@": "%@ tarafından mikrofon kullanılıyor",
    "Microphone in use by app": "Uygulama tarafından mikrofon kullanılıyor",
})
