# -*- coding: utf-8 -*-
# Ukrainian overlay for catalog_core.py: English source -> Ukrainian.
CORE = {
    "On AC power": "Від мережі",
    "On battery": "Від акумулятора",
    "Charging": "Заряджається",
    "External display connected": "Підключено зовнішній дисплей",
    "is running": "запущено",
    "is frontmost": "на передньому плані",
    "Audio playing": "Відтворюється звук",
    "VPN connected": "VPN підключено",
    "Calendar event in progress": "Триває подія календаря",
    "Playing a game": "Триває гра",
    "Camera in use": "Камера використовується",
    "Microphone in use": "Мікрофон використовується",
    "On Wi-Fi “%@”": "У мережі Wi-Fi «%@»",
    "Process “%@” running": "Процес «%@» запущено",
    "Volume “%@” mounted": "Том «%@» підключено",
    "Bluetooth “%@” connected": "Bluetooth «%@» підключено",
    "Downloading in “%@”": "Завантаження в «%@»",
    "CPU above %d%%": "ЦП вище %d%%",
    "Network above %@": "Мережа вище %@",
    "App %@": "Застосунок %@",
    "Every day": "Щодня",
    "Weekdays": "Будні",
    "Weekends": "Вихідні",
    "Do nothing": "Нічого не робити",
    "Sleep the display": "Приспати дисплей",
    "Start the screen saver": "Запустити заставку",
    "AI Agent": "ШІ-агент",
    "On AC Power": "Від мережі",
    "External Display Connected": "Підключено зовнішній дисплей",
    "Remote Session (SSH)": "Віддалений сеанс (SSH)",
    "Backup Running": "Резервне копіювання триває",
    "Media Render": "Рендеринг медіа",
    "Meetings": "Зустрічі",
    "Cloud Gaming": "Хмарний геймінг",
    "Remote Control": "Віддалене керування",
    "Remote Login (SSH)": "Віддалений вхід (SSH)",
    "Remote Login is on, so you can reach this Mac over SSH.": "Віддалений вхід увімкнено, тому ви можете підключитися до цього Mac через SSH.",
    "Remote Login is off. You might want to enable it for SSH access to a headless Mac.": "Віддалений вхід вимкнено. Можливо, варто його увімкнути для доступу через SSH до Mac без монітора.",
    "Couldn't confirm Remote Login. If you want SSH access, enable it in System Settings.": "Не вдалося підтвердити стан віддаленого входу. Якщо потрібен доступ через SSH, увімкніть його в Системних налаштуваннях.",
    "Screen Sharing": "Спільний доступ до екрана",
    "Screen Sharing is on, so you can connect with the Screen Sharing app or VNC.": "Спільний доступ до екрана увімкнено, тому ви можете підключитися за допомогою застосунку «Спільний доступ до екрана» або VNC.",
    "Screen Sharing is off. You might want to enable it to view a headless Mac's screen.": "Спільний доступ до екрана вимкнено. Можливо, варто його увімкнути, щоб бачити екран Mac без монітора.",
    "Couldn't confirm Screen Sharing. If you want remote viewing, enable it in System Settings.": "Не вдалося підтвердити стан спільного доступу до екрана. Якщо потрібен віддалений перегляд, увімкніть його в Системних налаштуваннях.",
    "Enable it in System Settings ▸ General ▸ Sharing.": "Увімкніть у Системних налаштуваннях ▸ Загальні ▸ Спільний доступ.",
    "Run AI agents on this Mac with MyAgens": "Запускайте ШІ-агентів на цьому Mac за допомогою MyAgens",
    "MyAgens lets AI agents operate your Mac and help with your work, which is handy on an always-on machine you mostly reach remotely.": "MyAgens дозволяє ШІ-агентам керувати вашим Mac і допомагати в роботі, що зручно на постійно ввімкненій машині, до якої ви здебільшого підключаєтеся віддалено.",
    "Learn more about MyAgens:": "Дізнатися більше про MyAgens:",
    "GitHub": "GitHub",
    "Read more": "Читати далі",
    "Wake for network access": "Пробудження для мережевого доступу",
    "The Mac wakes when accessed over the network.": "Mac прокидається, коли до нього звертаються по мережі.",
    "The Mac won't wake for network access, so remote logins may fail.": "Mac не прокинеться для мережевого доступу, тому віддалений вхід може не спрацювати.",
    "Couldn't read the power settings.": "Не вдалося прочитати налаштування живлення.",
    "Enable “Wake for network access”.": "Увімкніть «Пробудження для мережевого доступу».",
    "Restart after power failure": "Перезапуск після збою живлення",
    "The Mac restarts automatically after a power failure.": "Mac автоматично перезапускається після збою живлення.",
    "The Mac stays off after a power cut, so it won't come back headless.": "Після відключення живлення Mac залишається вимкненим, тому він не увімкнеться сам без монітора.",
    "Enable automatic restart after a power failure.": "Увімкніть автоматичний перезапуск після збою живлення.",
    "System sleep disabled": "Сон системи вимкнено",
    "Idle system sleep is disabled, so the Mac stays reachable.": "Сон системи під час бездіяльності вимкнено, тому Mac залишається доступним.",
    "The Mac sleeps when idle; Keepresso prevents this while a session runs, but a global setting is safer headless.": "Mac засинає під час бездіяльності; Keepresso запобігає цьому, поки триває сеанс, але глобальне налаштування надійніше без монітора.",
    "Disable idle system sleep.": "Вимкніть сон системи під час бездіяльності.",
    "FileVault disabled": "FileVault вимкнено",
    "FileVault is off, so the Mac can reboot unattended to the login window.": "FileVault вимкнено, тому Mac може перезавантажитися без нагляду аж до вікна входу.",
    "FileVault is on, so a reboot blocks at the disk-unlock screen until someone types the password, defeating headless restart.": "FileVault увімкнено, тому перезавантаження зупиняється на екрані розблокування диска, доки хтось не введе пароль, що унеможливлює перезапуск без монітора.",
    "Couldn't determine the FileVault status.": "Не вдалося визначити стан FileVault.",
    "For an unattended Mac, consider turning FileVault off (weigh the security trade-off).": "Для Mac без нагляду розгляньте можливість вимкнення FileVault (зважте компроміс щодо безпеки).",
    "Automatic login": "Автоматичний вхід",
    "Automatic login is on (%@), so the Mac reaches the desktop after a reboot without a keyboard.": "Автоматичний вхід увімкнено (%@), тому Mac потрапляє на робочий стіл після перезавантаження без клавіатури.",
    "Automatic login is off. After a reboot the Mac waits at the login window for a password.": "Автоматичний вхід вимкнено. Після перезавантаження Mac очікує пароль у вікні входу.",
    "Turn on automatic login for this account.": "Увімкніть автоматичний вхід для цього облікового запису.",
    "Keepresso stopped": "Keepresso зупинено",
    "Your keep-awake session has ended.": "Ваш сеанс підтримки активності завершився.",
    "Paused on low battery": "Призупинено через низький заряд",
    "Battery is at %d%%. Keepresso sessions and Agent work are paused until you plug in to charge.": "Заряд акумулятора становить %d%%. Сеанси Keepresso та роботу агентів призупинено до підключення живлення.",
    "Keepresso is still brewing": "Keepresso все ще заварює",
    "Your Mac is still awake. It's been %@.": "Ваш Mac усе ще не спить. Минуло %@.",
    "Your Mac has been kept awake for %@.": "Ваш Mac підтримувався неспиним протягом %@.",
    "Started manually": "Запущено вручну",
    "Restarted manually": "Перезапущено вручну",
    "Started by a command": "Запущено командою",
    "Restarted by a command": "Перезапущено командою",
    "Timed session ended": "Сеанс з таймером завершився",
    "Paused, battery below %d%%": "Призупинено, заряд нижче %d%%",
    "Not started, battery below %d%%": "Не запущено, заряд нижче %d%%",
    "Stopped manually": "Зупинено вручну",
    "Stopped by a command": "Зупинено командою",
    "Trigger conditions met": "Умови тригера виконано",
    "Trigger conditions ended": "Умови тригера більше не виконуються",
    "Triggers: %@": "Тригери: %@",
    "%@ (+%ds)": "%@ (+%d с)",
    "Couldn't create the watchdog flag file.": "Не вдалося створити файл-прапорець сторожа.",
    "Couldn't run the watchdog command.": "Не вдалося виконати команду сторожа.",
    "The watchdog couldn't be started.": "Не вдалося запустити сторож.",
    "Couldn't create the sleep watchdog flag file.": "Не вдалося створити файл-прапорець сторожа сну.",
    "Couldn't run the sleep watchdog command.": "Не вдалося виконати команду сторожа сну.",
    "The sleep watchdog couldn't be started.": "Не вдалося запустити сторож сну.",
    "Couldn't run the sleep setting command.": "Не вдалося виконати команду налаштування сну.",
    "The sleep setting couldn't be changed.": "Не вдалося змінити налаштування сну.",
    "The Keepresso helper isn't responding.": "Помічник Keepresso не відповідає.",
    "The Keepresso helper couldn't change the setting.": "Помічник Keepresso не зміг змінити налаштування.",
    "Virtual displays aren't available on this macOS version.": "Віртуальні дисплеї недоступні в цій версії macOS.",
    "Couldn't create the virtual display.": "Не вдалося створити віртуальний дисплей.",
    "Preventing system sleep": "Запобігання сну системи",
    "Preventing display sleep": "Запобігання сну дисплея",
    "Keeping disks awake": "Підтримання дисків активними",
    "Declaring the user active": "Оголошення користувача активним",
    "Holding off idle sleep for a background task": "Відкладення сну через бездіяльність для фонового завдання",
    "Not enough replies to measure.": "Недостатньо відповідей для вимірювання.",
    "Baseline %d ms": "База %d мс",
    "%d spike up to %d ms": "%d стрибок до %d мс",
    "%d spikes up to %d ms": "%d стрибків до %d мс",
    "max %d ms": "макс. %d мс",
    "%d lost": "%d втрачено",
    "Wired network": "Дротова мережа",
    "Couldn't read the network interfaces.": "Не вдалося прочитати мережеві інтерфейси.",
    "Ethernet is connected (%@). A wired link sidesteps Wi-Fi jitter entirely, the most reliable fix.": "Ethernet підключено (%@). Дротове з’єднання повністю обходить джитер Wi-Fi, це найнадійніше рішення.",
    "An Ethernet adapter is available but no cable is connected.": "Адаптер Ethernet доступний, але кабель не підключено.",
    "For gaming or streaming, a wired connection beats any Wi-Fi tuning.": "Для ігор або стримінгу дротове з’єднання переважає будь-яке налаштування Wi-Fi.",
    "No wired network adapter found.": "Дротовий мережевий адаптер не знайдено.",
    "A USB-C or Thunderbolt Ethernet adapter sidesteps Wi-Fi jitter entirely.": "Адаптер Ethernet USB-C або Thunderbolt повністю обходить джитер Wi-Fi.",
    "Wi-Fi channel": "Канал Wi-Fi",
    "Not connected to Wi-Fi, or its details are unreadable.": "Немає підключення до Wi-Fi, або його дані неможливо прочитати.",
    "If you game or stream over Wi-Fi, re-check while connected.": "Якщо ви граєте або стрімите через Wi-Fi, перевірте ще раз під час підключення.",
    "channel %d at %d MHz": "канал %d на %d МГц",
    "channel %d": "канал %d",
    "On 2.4 GHz (%@), the slowest band, where every AWDL hop costs the most.": "На 2,4 ГГц (%@), найповільнішому діапазоні, де кожен перехід AWDL коштує найдорожче.",
    "Prefer a 5 GHz network on %@ at 80 MHz. If 2.4 GHz is unavoidable, set the router to channel 6, AWDL's 2.4 GHz social channel.": "Надавайте перевагу мережі 5 ГГц на %@ із шириною 80 МГц. Якщо 2,4 ГГц не уникнути, налаштуйте роутер на канал 6, соціальний канал AWDL на 2,4 ГГц.",
    "On 6 GHz (%@). AWDL's social channels live on 2.4 and 5 GHz, so there's nothing to align here. If stutter persists, a 5 GHz network on %@ keeps AWDL's hops on-channel.": "На 6 ГГц (%@). Соціальні канали AWDL перебувають на 2,4 та 5 ГГц, тому тут нічого узгоджувати. Якщо заїкання не зникає, мережа 5 ГГц на %@ утримує переходи AWDL в межах одного каналу.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel.": "На %@, що збігається із соціальним каналом AWDL на 5 ГГц, тому його переходи залишаються в межах каналу.",
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel. Raising the router to 80 MHz width completes the alignment.": "На %@, що збігається із соціальним каналом AWDL на 5 ГГц, тому його переходи залишаються в межах каналу. Підвищення ширини каналу роутера до 80 МГц завершує узгодження.",
    "On 5 GHz %@. AWDL's off-channel hops leave this channel roughly every second.": "На 5 ГГц %@. Позаканальні переходи AWDL залишають цей канал приблизно раз на секунду.",
    "Set the router to %@ at 80 MHz so AWDL's hops stay on-channel.": "Налаштуйте роутер на %@ із шириною 80 МГц, щоб переходи AWDL залишалися в межах каналу.",
    "channel 44 (the EU social channel) or 149 (the US and Canada social channel), whichever your region allows": "канал 44 (соціальний канал ЄС) або 149 (соціальний канал США та Канади), залежно від того, що дозволено у вашому регіоні",
    "channel 44, AWDL's 5 GHz social channel in the EU": "канал 44, соціальний канал AWDL на 5 ГГц у ЄС",
    "channel 149, AWDL's 5 GHz social channel where UNII-3 is allowed (the US, Canada, and most of the world)": "канал 149, соціальний канал AWDL на 5 ГГц там, де дозволено UNII-3 (США, Канада та більшість країн світу)",
    "Bluetooth during play": "Bluetooth під час гри",
    "Bluetooth is on. It shares the radio chip with Wi-Fi, so heavy Bluetooth traffic (audio, controllers) can add its own blips.": "Bluetooth увімкнено. Він використовує той самий радіочип, що й Wi-Fi, тому значний трафік Bluetooth (звук, контролери) може додавати власні короткі збої.",
    "Nothing to fix: just a variable to know about if stutter persists on a clean channel.": "Нічого виправляти: це просто фактор, про який варто знати, якщо заїкання зберігається навіть на чистому каналі.",
    "Bluetooth is off, so it isn't competing with Wi-Fi for the radio.": "Bluetooth вимкнено, тому він не конкурує з Wi-Fi за радіомодуль.",
    "Couldn't read the Bluetooth radio state.": "Не вдалося прочитати стан радіомодуля Bluetooth.",
    "Game Mode": "Ігровий режим",
    "macOS turns on Game Mode by itself when a game runs full screen: the game gets CPU and GPU priority, and Bluetooth controllers and audio get faster sampling. If the game-controller icon doesn't appear in the menu bar while playing, put the game into full screen.": "macOS сам вмикає Ігровий режим, коли гра запущена на весь екран: гра отримує пріоритет ЦП і ГП, а Bluetooth-контролери та звук отримують швидшу дискретизацію. Якщо значок ігрового контролера не з’являється в рядку меню під час гри, переведіть гру в повноекранний режим.",
    "How Game Mode works:": "Як працює Ігровий режим:",
    "Learn more": "Дізнатися більше",
    "Cloud gaming in the browser": "Хмарний геймінг у браузері",
    "Xbox Cloud Gaming and the web versions of GeForce NOW run in a browser tab, so there's no app for the gaming condition to spot. The “Audio playing” condition covers them: game sound keeps the session brewing.": "Xbox Cloud Gaming і веб-версії GeForce NOW працюють у вкладці браузера, тому немає окремого застосунку, який могла б виявити умова гри. Умова «Відтворюється звук» охоплює їх: звук гри підтримує сеанс активним.",
    "Add it under Preferences ▸ Triggers ▸ Add ▸ Apps & Activity ▸ Media.": "Додайте її в Налаштування ▸ Тригери ▸ Додати ▸ Застосунки та активність ▸ Медіа.",
    "Location Services and Wi-Fi scans": "Служби геопозиції та сканування Wi-Fi",
    "Location Services triggers independent Wi-Fi scans, another source of occasional blips. Keepresso itself uses Location to read Wi-Fi network names for triggers, so weigh that before turning anything off.": "Служби геопозиції запускають незалежні сканування Wi-Fi, ще одне джерело випадкових коротких збоїв. Сам Keepresso використовує геопозицію, щоб зчитувати назви мереж Wi-Fi для тригерів, тому зважте це, перш ніж щось вимикати.",
    "Review which apps use Location:": "Перевірте, які застосунки використовують геопозицію:",
    "Why streams stutter once a second": "Чому стріми заїкаються раз на секунду",
    "The Wi-Fi radio hops off-channel for AWDL (AirDrop, Handoff, Sidecar, Continuity) roughly every second, which shows up as 50-100 ms ping spikes. The jitter test reproduces the diagnosis; the AWDL watchdog is the session-scoped fix.": "Радіомодуль Wi-Fi приблизно раз на секунду переходить на інший канал заради AWDL (AirDrop, Handoff, Sidecar, Continuity), що проявляється як стрибки пінгу на 50–100 мс. Тест джитера відтворює цю діагностику; сторож AWDL є рішенням у межах одного сеансу.",
    "The full story:": "Повна історія:",
    "Keepresso stops soon": "Keepresso скоро зупиниться",
    "Your keep-awake session ends in about %@.": "Ваш сеанс підтримки активності завершиться приблизно через %@.",
    "AI agent working": "ШІ-агент працює",
}

WIDGET = {
    "Keep Awake": "Не дати заснути",
    "See and control whether Keepresso is keeping the Mac awake.": "Перегляньте та керуйте тим, чи Keepresso не дає Mac заснути.",
    "Start or stop keeping the Mac awake.": "Почніть або зупиніть підтримку активності Mac.",
    "Keepresso": "Keepresso",
    "Brewing": "Заварюється",
    "Off": "Вимкнено",
    "Keeping the Mac awake": "Mac не спить",
    "The Mac can sleep": "Mac може заснути",
    "Stop": "Зупинити",
    "Start": "Почати",
    "Resume Triggers": "Відновити тригери",
    "Pause Triggers": "Призупинити тригери",
}


# --- Agent hooks (Claude Code connection) ---
CORE.update({
    "running command": "виконує команду",
    "editing": "редагує",
    "reading": "читає",
    "searching": "шукає",
    "running subagent": "виконує субагента",
    "browsing": "переглядає веб",
    "using %@": "використовує %@",
    "waiting for approval": "очікує на підтвердження",
    "waiting": "очікує",
    "terminal": "термінал",
    "Claude app": "застосунок Claude",
    "IDE": "IDE",
})


# v1.15 thermal safety net: pressure levels and heat-pause lines.
CORE.update({
    "Critical": "Критичний",
    "Fair": "Помірний",
    "Keepresso stopped the keep-awake session so the Mac can cool down. It resumes when temperatures recover.": "Keepresso зупинив сеанс підтримки активності, щоб Mac міг охолонути. Він відновлюється, коли температура нормалізується.",
    "Nominal": "Номінальний",
    "Not started, the Mac is running hot": "Не запущено, Mac перегрівається",
    "Paused on high temperature": "Призупинено через високу температуру",
    "Paused, the Mac is running hot": "Призупинено, Mac перегрівається",
    "Serious": "Серйозний",
    # 1.16.0 fill (16)
    'Lock the screen': 'Заблокувати екран',
    'Sleep the Mac': 'Приспати Mac',
    'Session started': 'Сеанс розпочато',
    'Session ended': 'Сеанс завершено',
    'Trigger fired': 'Умова спрацювала',
    'Trigger released': 'Умову знято',
    'Battery pause': 'Пауза батареї',
    'Thermal pause': 'Термічна пауза',
    'Thermal stage changed': 'Змінено тепловий етап',
    'Agent went idle': 'Агент у простої',
    'Shortcut: %@': 'Команда: %@',
    'Webhook: %@': 'Вебхук: %@',
    'Command: %@': 'Команда: %@',
    '+%ds': '+%d с',
    'waiting counts': 'очікування рахується',
    '%@ (%@)': '%@ (%@)',

})
