# -*- coding: utf-8 -*-
# Traditional Chinese (Taiwan) overlay for catalog_core.py: English source -> zh-Hant.
CORE = {
    'On AC power': '使用電源時',
    'On battery': '使用電池時',
    'Charging': '充電中',
    'External display connected': '已連接外接螢幕',
    'is running': '執行中',
    'is frontmost': '位於最前',
    'Audio playing': '正在播放音訊',
    'VPN connected': '已連接 VPN',
    'Calendar event in progress': '行事曆事件進行中',
    'Playing a game': '正在玩遊戲',
    'Camera in use': '相機使用中',
    'Microphone in use': '麥克風使用中',
    'On Wi-Fi “%@”': '在 Wi-Fi「%@」上',
    'Process “%@” running': '處理程序「%@」執行中',
    'Volume “%@” mounted': '磁碟區「%@」已裝載',
    'Bluetooth “%@” connected': '已連接藍牙「%@」',
    'Downloading in “%@”': '正在「%@」中下載',
    'CPU above %d%%': 'CPU 高於 %d%%',
    'Network above %@': '網路高於 %@',
    'App %@': 'App %@',
    'Every day': '每天',
    'Weekdays': '平日',
    'Weekends': '週末',
    'Do nothing': '不執行任何動作',
    'Sleep the display': '讓螢幕進入睡眠',
    'Start the screen saver': '啟動螢幕保護程式',
    'AI Agent': 'AI 代理',
    'On AC Power': '使用電源',
    'External Display Connected': '已連接外接螢幕',
    'Remote Session (SSH)': '遠端工作階段（SSH）',
    'Backup Running': '備份進行中',
    'Media Render': '媒體轉譯',
    'Meetings': '會議',
    'Cloud Gaming': '雲端遊戲',
    'Remote Control': '遠端控制',
    'Remote Login (SSH)': '遠端登入（SSH）',
    'Remote Login is on, so you can reach this Mac over SSH.': '遠端登入已開啟，因此您可以透過 SSH 連上這台 Mac。',
    'Remote Login is off. You might want to enable it for SSH access to a headless Mac.': '遠端登入已關閉。若您想透過 SSH 存取無螢幕的 Mac，可考慮開啟此功能。',
    "Couldn't confirm Remote Login. If you want SSH access, enable it in System Settings.": '無法確認遠端登入狀態。若您需要 SSH 存取，請在系統設定中開啟。',
    'Screen Sharing': '螢幕共享',
    'Screen Sharing is on, so you can connect with the Screen Sharing app or VNC.': '螢幕共享已開啟，因此您可以使用「螢幕共享」App 或 VNC 連線。',
    "Screen Sharing is off. You might want to enable it to view a headless Mac's screen.": '螢幕共享已關閉。若您想檢視無螢幕 Mac 的畫面，可考慮開啟此功能。',
    "Couldn't confirm Screen Sharing. If you want remote viewing, enable it in System Settings.": '無法確認螢幕共享狀態。若您需要遠端檢視，請在系統設定中開啟。',
    'Enable it in System Settings ▸ General ▸ Sharing.': '請在「系統設定 ▸ 一般 ▸ 共享」中開啟。',
    'Run AI agents on this Mac with MyAgens': '使用 MyAgens 在這台 Mac 上執行 AI 代理',
    'MyAgens lets AI agents operate your Mac and help with your work, which is handy on an always-on machine you mostly reach remotely.': 'MyAgens 可讓 AI 代理操作您的 Mac 並協助您的工作，對於主要以遠端方式使用的常保開機機器相當實用。',
    'Learn more about MyAgens:': '深入了解 MyAgens：',
    'GitHub': 'GitHub',
    'Read more': '閱讀更多',
    'Wake for network access': '網路存取時喚醒',
    'The Mac wakes when accessed over the network.': '透過網路存取時，Mac 會喚醒。',
    "The Mac won't wake for network access, so remote logins may fail.": 'Mac 不會因網路存取而喚醒，因此遠端登入可能會失敗。',
    "Couldn't read the power settings.": '無法讀取電源設定。',
    'Enable “Wake for network access”.': '請開啟「網路存取時喚醒」。',
    'Restart after power failure': '停電後自動重新開機',
    'The Mac restarts automatically after a power failure.': '停電後 Mac 會自動重新開機。',
    "The Mac stays off after a power cut, so it won't come back headless.": '停電後 Mac 會保持關機狀態，因此在無人操作螢幕的情況下不會自行恢復。',
    'Enable automatic restart after a power failure.': '請開啟停電後自動重新開機。',
    'System sleep disabled': '已停用系統睡眠',
    'Idle system sleep is disabled, so the Mac stays reachable.': '已停用閒置系統睡眠，因此 Mac 會保持可連線狀態。',
    'The Mac sleeps when idle; Keepresso prevents this while a session runs, but a global setting is safer headless.': 'Mac 閒置時會進入睡眠；Keepresso 會在工作階段進行時防止這一點，但在無螢幕環境下，使用全域設定較為保險。',
    'Disable idle system sleep.': '請停用閒置系統睡眠。',
    'FileVault disabled': '已停用 FileVault',
    'FileVault is off, so the Mac can reboot unattended to the login window.': 'FileVault 已關閉，因此 Mac 可在無人操作下重新開機至登入畫面。',
    'FileVault is on, so a reboot blocks at the disk-unlock screen until someone types the password, defeating headless restart.': 'FileVault 已開啟，因此重新開機時會卡在磁碟解鎖畫面，直到有人輸入密碼為止，導致無螢幕重新開機失效。',
    "Couldn't determine the FileVault status.": '無法判斷 FileVault 狀態。',
    'For an unattended Mac, consider turning FileVault off (weigh the security trade-off).': '若 Mac 為無人看管使用，可考慮關閉 FileVault（請自行衡量安全性的取捨）。',
    'Automatic login': '自動登入',
    'Automatic login is on (%@), so the Mac reaches the desktop after a reboot without a keyboard.': '自動登入已開啟（%@），因此 Mac 重新開機後無需鍵盤即可進入桌面。',
    'Automatic login is off. After a reboot the Mac waits at the login window for a password.': '自動登入已關閉。重新開機後，Mac 會停在登入畫面等待輸入密碼。',
    'Turn on automatic login for this account.': '請為此帳號開啟自動登入。',
    'Keepresso stopped': 'Keepresso 已停止',
    'Your keep-awake session has ended.': '您的保持喚醒工作階段已結束。',
    'Paused on low battery': '因電量低而暫停',
    'Battery is at %d%%. Keepresso is letting the Mac sleep until you plug in to charge.': '電量為 %d%%。Keepresso 將讓 Mac 進入睡眠，直到您接上電源充電為止。',
    'Keepresso is still brewing': 'Keepresso 仍在運作中',
    "Your Mac is still awake. It's been %@.": '您的 Mac 仍處於喚醒狀態，已經過 %@。',
    'Your Mac has been kept awake for %@.': '您的 Mac 已保持喚醒 %@。',
    'Started manually': '手動啟動',
    'Restarted manually': '手動重新啟動',
    'Started by a command': '由指令啟動',
    'Restarted by a command': '由指令重新啟動',
    'Timed session ended': '定時工作階段已結束',
    'Paused, battery below %d%%': '已暫停，電量低於 %d%%',
    'Not started, battery below %d%%': '未啟動，電量低於 %d%%',
    'Stopped manually': '手動停止',
    'Stopped by a command': '由指令停止',
    'Trigger conditions met': '觸發條件已符合',
    'Trigger conditions ended': '觸發條件已結束',
    'Triggers: %@': '觸發條件：%@',
    '%@ (+%ds)': '%@（+%d 秒）',
    "Couldn't create the watchdog flag file.": '無法建立看門狗旗標檔案。',
    "Couldn't run the watchdog command.": '無法執行看門狗指令。',
    "The watchdog couldn't be started.": '無法啟動看門狗。',
    "Couldn't create the sleep watchdog flag file.": '無法建立睡眠看門狗旗標檔案。',
    "Couldn't run the sleep watchdog command.": '無法執行睡眠看門狗指令。',
    "The sleep watchdog couldn't be started.": '無法啟動睡眠看門狗。',
    "Couldn't run the sleep setting command.": '無法執行睡眠設定指令。',
    "The sleep setting couldn't be changed.": '無法變更睡眠設定。',
    "The Keepresso helper isn't responding.": 'Keepresso 輔助程式無回應。',
    "The Keepresso helper couldn't change the setting.": 'Keepresso 輔助程式無法變更設定。',
    "Virtual displays aren't available on this macOS version.": '此 macOS 版本不支援虛擬螢幕。',
    "Couldn't create the virtual display.": '無法建立虛擬螢幕。',
    'Preventing system sleep': '正在防止系統睡眠',
    'Preventing display sleep': '正在防止螢幕睡眠',
    'Keeping disks awake': '正在讓磁碟保持喚醒',
    'Declaring the user active': '正在將使用者宣告為使用中',
    'Holding off idle sleep for a background task': '正在為背景工作延後閒置睡眠',
    'Not enough replies to measure.': '回覆數不足，無法測量。',
    'Baseline %d ms': '基準 %d 毫秒',
    '%d spike up to %d ms': '%d 次尖峰，最高 %d 毫秒',
    '%d spikes up to %d ms': '%d 次尖峰，最高 %d 毫秒',
    'max %d ms': '最高 %d 毫秒',
    '%d lost': '遺失 %d 個',
    'Wired network': '有線網路',
    "Couldn't read the network interfaces.": '無法讀取網路介面。',
    'Ethernet is connected (%@). A wired link sidesteps Wi-Fi jitter entirely, the most reliable fix.': '乙太網路已連接（%@）。有線連線可完全避開 Wi-Fi 抖動，是最可靠的解決方式。',
    'An Ethernet adapter is available but no cable is connected.': '偵測到乙太網路轉接器，但未接上網路線。',
    'For gaming or streaming, a wired connection beats any Wi-Fi tuning.': '無論遊戲或串流，有線連線都勝過任何 Wi-Fi 調校。',
    'No wired network adapter found.': '找不到有線網路轉接器。',
    'A USB-C or Thunderbolt Ethernet adapter sidesteps Wi-Fi jitter entirely.': 'USB-C 或 Thunderbolt 乙太網路轉接器可完全避開 Wi-Fi 抖動。',
    'Wi-Fi channel': 'Wi-Fi 頻道',
    'Not connected to Wi-Fi, or its details are unreadable.': '未連接 Wi-Fi，或無法讀取其詳細資訊。',
    'If you game or stream over Wi-Fi, re-check while connected.': '若您透過 Wi-Fi 遊戲或串流，請於連線時重新檢查。',
    'channel %d at %d MHz': '頻道 %d，%d MHz',
    'channel %d': '頻道 %d',
    'On 2.4 GHz (%@), the slowest band, where every AWDL hop costs the most.': '位於 2.4 GHz（%@），這是最慢的頻段，每次 AWDL 跳頻的代價都最高。',
    "Prefer a 5 GHz network on %@ at 80 MHz. If 2.4 GHz is unavoidable, set the router to channel 6, AWDL's 2.4 GHz social channel.": '建議優先使用 %@ 上頻寬 80 MHz 的 5 GHz 網路。若無法避免使用 2.4 GHz，請將路由器設為頻道 6，即 AWDL 在 2.4 GHz 的社交頻道。',
    "On 6 GHz (%@). AWDL's social channels live on 2.4 and 5 GHz, so there's nothing to align here. If stutter persists, a 5 GHz network on %@ keeps AWDL's hops on-channel.": '位於 6 GHz（%@）。AWDL 的社交頻道位於 2.4 與 5 GHz，因此這裡沒有需要對齊的項目。若頓卡情形持續，改用 %@ 上的 5 GHz 網路可讓 AWDL 的跳頻維持在同一頻道。',
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel.": '%@ 與 AWDL 的 5 GHz 社交頻道對齊，因此其跳頻會維持在同一頻道。',
    "On %@, aligned with AWDL's 5 GHz social channel, so its hops stay on-channel. Raising the router to 80 MHz width completes the alignment.": '%@ 與 AWDL 的 5 GHz 社交頻道對齊，因此其跳頻會維持在同一頻道。將路由器頻寬提高至 80 MHz 即可完成對齊。',
    "On 5 GHz %@. AWDL's off-channel hops leave this channel roughly every second.": '位於 5 GHz %@。AWDL 的離頻跳頻大約每秒會離開此頻道一次。',
    "Set the router to %@ at 80 MHz so AWDL's hops stay on-channel.": '請將路由器設為頻寬 80 MHz 的 %@，讓 AWDL 的跳頻維持在同一頻道。',
    'channel 44 (the EU social channel) or 149 (the US and Canada social channel), whichever your region allows': '頻道 44（歐盟社交頻道）或頻道 149（美國與加拿大社交頻道），視您所在地區允許的頻道而定',
    "channel 44, AWDL's 5 GHz social channel in the EU": '頻道 44，AWDL 在歐盟的 5 GHz 社交頻道',
    "channel 149, AWDL's 5 GHz social channel where UNII-3 is allowed (the US, Canada, and most of the world)": '頻道 149，AWDL 在允許 UNII-3 的地區（美國、加拿大及全球大部分地區）的 5 GHz 社交頻道',
    'Bluetooth during play': '遊戲時的藍牙',
    'Bluetooth is on. It shares the radio chip with Wi-Fi, so heavy Bluetooth traffic (audio, controllers) can add its own blips.': '藍牙已開啟。它與 Wi-Fi 共用無線電晶片，因此大量藍牙流量（音訊、控制器）可能會造成自己的短暫延遲。',
    'Nothing to fix: just a variable to know about if stutter persists on a clean channel.': '無需修正：只是在乾淨頻道上仍出現頓卡時，值得了解的一項因素。',
    "Bluetooth is off, so it isn't competing with Wi-Fi for the radio.": '藍牙已關閉，因此不會與 Wi-Fi 爭用無線電。',
    "Couldn't read the Bluetooth radio state.": '無法讀取藍牙無線電狀態。',
    'Game Mode': '遊戲模式',
    "macOS turns on Game Mode by itself when a game runs full screen: the game gets CPU and GPU priority, and Bluetooth controllers and audio get faster sampling. If the game-controller icon doesn't appear in the menu bar while playing, put the game into full screen.": '當遊戲以全螢幕執行時，macOS 會自動開啟遊戲模式：遊戲將取得 CPU 與 GPU 優先權，藍牙控制器與音訊也會取得更快的取樣速度。若遊玩時選單列未出現遊戲控制器圖示，請將遊戲切換為全螢幕。',
    'How Game Mode works:': '遊戲模式的運作方式：',
    'Learn more': '深入了解',
    'Cloud gaming in the browser': '瀏覽器中的雲端遊戲',
    "Xbox Cloud Gaming and the web versions of GeForce NOW run in a browser tab, so there's no app for the gaming condition to spot. The “Audio playing” condition covers them: game sound keeps the session brewing.": 'Xbox Cloud Gaming 與網頁版 GeForce NOW 皆在瀏覽器分頁中執行，因此沒有 App 可供遊戲條件偵測。「正在播放音訊」條件可涵蓋這類情況：遊戲音效會讓工作階段持續運作。',
    'Add it under Preferences ▸ Triggers ▸ Add ▸ Apps & Activity ▸ Media.': '請在「偏好設定 ▸ 觸發條件 ▸ 新增 ▸ App 與活動 ▸ 媒體」中新增。',
    'Location Services and Wi-Fi scans': '定位服務與 Wi-Fi 掃描',
    'Location Services triggers independent Wi-Fi scans, another source of occasional blips. Keepresso itself uses Location to read Wi-Fi network names for triggers, so weigh that before turning anything off.': '定位服務會觸發獨立的 Wi-Fi 掃描，這也是偶發短暫延遲的另一個來源。Keepresso 本身也會使用定位服務來讀取 Wi-Fi 網路名稱，供觸發條件使用，因此請在關閉前自行衡量。',
    'Review which apps use Location:': '查看哪些 App 使用定位服務：',
    'Why streams stutter once a second': '為何串流每秒會頓卡一次',
    'The Wi-Fi radio hops off-channel for AWDL (AirDrop, Handoff, Sidecar, Continuity) roughly every second, which shows up as 50-100 ms ping spikes. The jitter test reproduces the diagnosis; the AWDL watchdog is the session-scoped fix.': 'Wi-Fi 無線電大約每秒會為了 AWDL（AirDrop、Handoff、Sidecar、接續互通）而切換到其他頻道，這會表現為 50 至 100 毫秒的 ping 值突增。抖動測試可重現此診斷；AWDL 看門狗則是僅限本次工作階段的修正方式。',
    'The full story:': '完整說明：',
    'Keepresso stops soon': 'Keepresso 即將停止',
    'Your keep-awake session ends in about %@.': '您的保持喚醒工作階段將在約 %@ 後結束。',
    'AI agent working': 'AI 代理工作中',
    'AI Agent Working': 'AI 代理工作中',
}

WIDGET = {
    'Keep Awake': '保持喚醒',
    'See and control whether Keepresso is keeping the Mac awake.': '查看並控制 Keepresso 是否讓 Mac 保持喚醒。',
    'Start or stop keeping the Mac awake.': '開始或停止讓 Mac 保持喚醒。',
    'Keepresso': 'Keepresso',
    'Brewing': '運作中',
    'Off': '關閉',
    'Keeping the Mac awake': '正在讓 Mac 保持喚醒',
    'The Mac can sleep': 'Mac 可以進入睡眠',
    'Stop': '停止',
    'Start': '開始',
    'Resume Triggers': '繼續觸發條件',
    'Pause Triggers': '暫停觸發條件',
}
